// Package typescript parses TypeScript and TSX with a parser generated by PEGO from typescript.pego.
package typescript

import (
	"errors"
	"path"
	"strings"
)

// ParseTSX parses a .tsx file: TypeScript with JSX, where <T>x is not a type assertion. Like ParseAST, it
// returns the source file as typed values with positions in the unit (code points by default).
func ParseTSX(input string, unit ...Unit) (*SourceFile, error) {
	f, err := ParseAST(tsxMarker+input, unit...)
	if f != nil {
		shiftSpans(f)
	}
	return f, shiftError(err)
}

// RecognizeTSX checks that input is a valid .tsx file without building anything, and returns the syntax
// errors ParseTSX would return.
func RecognizeTSX(input string, unit ...Unit) error {
	return shiftError(Recognize(tsxMarker+input, unit...))
}

// ParseFile parses the source of the file name as a .tsx file if the name ends in .tsx (or .jsx) and as a .ts
// file otherwise (.ts, .mts, .cts and .d.ts files).
func ParseFile(name, input string, unit ...Unit) (*SourceFile, error) {
	if IsTSX(name) {
		return ParseTSX(input, unit...)
	}
	return ParseAST(input, unit...)
}

// IsTSX reports whether the file name is that of a file with JSX (.tsx or .jsx).
func IsTSX(name string) bool {
	ext := strings.ToLower(path.Ext(name))
	return ext == ".tsx" || ext == ".jsx"
}

// tsxMarker selects the TSX start of the grammar's main rule. No TypeScript source can start with NUL, so
// the marker never changes the meaning of a .ts file; ParseTSX moves the positions back past it.
const tsxMarker = "\x00"

type spanSetter interface{ tsetSpan(start, end int) }

// shiftSpans moves the range of every node of f one position back, past the TSX marker.
func shiftSpans(f *SourceFile) {
	Inspect(f, func(n ASTNode) bool {
		if n != nil {
			s, e := n.Range()
			n.(spanSetter).tsetSpan(max(s-1, 0), max(e-1, 0))
		}
		return true
	})
}

// shiftError moves the positions of syntax errors one position back, past the TSX marker.
func shiftError(err error) error {
	shift := func(e *SyntaxError) {
		e.Pos = max(e.Pos-1, 0)
		if e.Line == 1 {
			e.Col = max(e.Col-1, 1)
		}
	}
	var se *SyntaxError
	var ses SyntaxErrors
	switch {
	case errors.As(err, &ses):
		for _, e := range ses {
			shift(e)
		}
	case errors.As(err, &se):
		shift(se)
	}
	return err
}
