// Package typescript parses TypeScript 5.9 and TSX, as the parser of the TypeScript 5.9.3 compiler
// (src/compiler/parser.ts) does, with a parser generated by PEGO from typescript.pego. It depends only on the
// standard library.
//
// ParseAST returns the source file of a .ts file as typed values: a SourceFile of Statements, whose types are
// named after the SyntaxKinds of the compiler's nodes (VariableStatement, CallExpression, TypeReference, ...) and
// whose fields are in the order of the compiler's forEachChild, each node with its Span (the range of its tokens,
// without the trivia before it, like the compiler's getStart and getEnd) in the input. ParseTSX parses a .tsx
// file, and ParseFile chooses by the name of the file and reads the top level of a module as the compiler does.
// Kind, ForEachChild and Inspect read the tree by kind, and Parse returns the generic tree of Nodes, and Recognize
// and RecognizeTSX only check the source. The values of literals are decoded by the Value methods.
//
// The grammar follows the compiler's parser function by function, so it accepts what the compiler's parser accepts
// without a syntactic diagnostic and decides the ambiguities the way it does: arrow functions, type arguments in
// expressions, <T>x and JSX, contextual keywords, automatic semicolon insertion. Like the parser, it is lenient:
// most "grammar errors" (a missing constructor body, a modifier that does not apply, an assignment to a literal)
// are reported by the checker and are not syntax errors here. JSDoc comments are trivia, and the JSDoc types the
// compiler's parser accepts in .ts files (?T, !T, function(...)) are types here too.
//
// # Conformance
//
// The tests compare the parser with the TypeScript 5.9.3 compiler on the 14,804 .ts and .tsx files of the
// compiler's own test cases (tests/cases/compiler and tests/cases/conformance): the compiler's parse
// diagnostics decide whether a file is valid, and for the files both accept, the kinds, ranges and number of
// children of every node must agree. 14,799 files agree (756 of them are rejected by both); the five that do not
// are listed in testdata/tsc-known-failures.list:
//
//   - three diagnostics that the compiler reports for triple-slash directives while it processes pragmas, which
//     are not syntax: two amd-module names (amdModuleName2.ts), an invalid reference directive
//     (invalidReferenceSyntax1.ts) and an invalid resolution-mode attribute
//     (nodeModulesTripleSlashReferenceModeOverrideModeError.ts);
//   - a class member named by a string with an escape that spells constructor ("\x63onstructor"() {}), which the
//     compiler takes for the constructor and the parser for a method (quotedConstructors.ts);
//   - a JSX closing tag whose name has white space between its parts (</A . B . C.D>), which the compiler accepts
//     (tsxOpeningClosingNames.tsx).
//
// The same checks on 150,000 sources made by deleting, duplicating, replacing, inserting or swapping one token of
// those test cases find 32 differences, 24 of them the same pragmas, constructors and closing tag; the others
// are rare (an await after the name of a class or a namespace in a module, whose diagnostic the compiler drops in
// its reparse of the top level, and five single cases of type arguments, computed names and escapes). See the
// README for how to run the tests and the results per directory.
//
// The parser makes no semantic checks, and reads no JavaScript files, regular expression bodies or values of
// literals beyond what the Value methods decode.
// Nesting is limited by the depth limit of the generated parser (100,000 rule calls: about 12,000 levels of
// parentheses or arrays, 6,600 of type arguments, 33,000 of blocks); deeper input fails with an error instead of
// exhausting the stack.
package typescript

import (
	"errors"
	"path"
	"strings"
)

// ParseTSX parses a .tsx file: TypeScript with JSX, where <T>x is not a type assertion. Like ParseAST, it
// returns the source file as typed values with positions in the unit (code points by default).
func ParseTSX(input string, unit ...Unit) (*SourceFile, error) {
	return parseWith(tsxMarker, input, unit)
}

// RecognizeTSX checks that input is a valid .tsx file without building anything, and returns the syntax
// errors ParseTSX would return.
func RecognizeTSX(input string, unit ...Unit) error {
	return shiftError(Recognize(tsxMarker+input, unitOptions(unit)...), len(tsxMarker))
}

// ParseFile parses the source of the file name as the TypeScript compiler does (ts.createSourceFile): as a
// .tsx file if the name ends in .tsx (or .jsx) and as a .ts file otherwise (.ts, .mts, .cts, .d.ts). In a
// module, a file with import or export declarations or import.meta, the top level is parsed in the await
// context (await (x) is an await expression, not a call), as the compiler reparses it; not in a declaration
// file (.d.ts).
func ParseFile(name, input string, unit ...Unit) (*SourceFile, error) {
	marker := ""
	if IsTSX(name) {
		marker = tsxMarker
	}
	f, err := parseWith(marker, input, unit)
	if !strings.Contains(input, "await") || isDeclarationFile(name) || f != nil && !IsExternalModule(f) {
		return f, err
	}
	// The top level may hold await expressions: parse it as a module would be.
	mf, merr := parseWith(marker+awaitMarker, input, unit)
	if f == nil && (mf == nil || !IsExternalModule(mf)) {
		return f, err // not a module either way: the error of the script
	}
	return mf, merr
}

// IsTSX reports whether the file name is that of a file with JSX (.tsx or .jsx).
func IsTSX(name string) bool {
	ext := strings.ToLower(path.Ext(name))
	return ext == ".tsx" || ext == ".jsx"
}

// isDeclarationFile reports whether the file name is that of a declaration file (isDeclarationFileName):
// .d.ts, .d.mts, .d.cts, or a .ts file with .d. in its name (such as a.d.json.ts).
func isDeclarationFile(name string) bool {
	base := path.Base(name)
	for _, ext := range []string{".d.ts", ".d.mts", ".d.cts"} {
		if strings.HasSuffix(base, ext) {
			return true
		}
	}
	return strings.HasSuffix(base, ".ts") && strings.Contains(base, ".d.")
}

// IsExternalModule reports whether f is a module, as the TypeScript compiler decides
// (isFileProbablyExternalModule): it has an import or export declaration, an export modifier, an
// import x = require(...), or uses import.meta.
func IsExternalModule(f *SourceFile) bool {
	for _, s := range f.Statements {
		switch s := s.(type) {
		case *ImportDeclaration, *ExportAssignment, *ExportDeclaration:
			return true
		case *ImportEqualsDeclaration:
			if _, ok := s.ModuleReference.(*ExternalModuleReference); ok {
				return true
			}
		}
		if hasExportModifier(s) {
			return true
		}
	}
	found := false
	Inspect(f, func(n ASTNode) bool {
		if m, ok := n.(*MetaProperty); ok && m.KeywordToken == "import" && m.Name.Text == "meta" {
			found = true
		}
		return !found
	})
	return found
}

func hasExportModifier(s Statement) bool {
	var mods []ModifierLike
	switch s := s.(type) {
	case *VariableStatement:
		mods = s.Modifiers
	case *FunctionDeclaration:
		mods = s.Modifiers
	case *ClassDeclaration:
		mods = s.Modifiers
	case *InterfaceDeclaration:
		mods = s.Modifiers
	case *TypeAliasDeclaration:
		mods = s.Modifiers
	case *EnumDeclaration:
		mods = s.Modifiers
	case *ModuleDeclaration:
		mods = s.Modifiers
	case *ImportEqualsDeclaration:
		mods = s.Modifiers
	}
	for _, m := range mods {
		if m, ok := m.(*Modifier); ok && m.Text == "export" {
			return true
		}
	}
	return false
}

// The grammar's main rule reads markers before the source: tsxMarker selects TSX, and awaitMarker parses the
// top level in the await context. No TypeScript source can start with them (they are not whitespace or the
// start of a token), so they never change the meaning of a source; the positions are moved back past them.
const (
	tsxMarker   = "\x00"
	awaitMarker = "\x01"
)

// parseWith parses the input after the markers, and moves the positions back past them.
func parseWith(markers, input string, unit []Unit) (*SourceFile, error) {
	if markers == "" {
		return ParseAST(input, unitOptions(unit)...)
	}
	f, err := ParseAST(markers+input, unitOptions(unit)...)
	if f != nil {
		shiftSpans(f, len(markers))
	}
	return f, shiftError(err, len(markers))
}

type spanSetter interface{ tsetSpan(start, end int) }

// shiftSpans moves the range of every node of f d positions back.
func shiftSpans(f *SourceFile, d int) {
	Inspect(f, func(n ASTNode) bool {
		if n != nil {
			s, e := n.Range()
			n.(spanSetter).tsetSpan(max(s-d, 0), max(e-d, 0))
		}
		return true
	})
}

// shiftError moves the positions of syntax errors d positions back.
func shiftError(err error, d int) error {
	shift := func(e *SyntaxError) {
		e.Pos = max(e.Pos-d, 0)
		if e.Line == 1 {
			e.Col = max(e.Col-d, 1)
		}
	}
	var se *SyntaxError
	var ses SyntaxErrors
	switch {
	case errors.As(err, &ses):
		for _, e := range ses {
			shift(e)
		}
	case errors.As(err, &se):
		shift(se)
	}
	return err
}

// unitOptions preserves the first-unit policy of the handwritten convenience API.
func unitOptions(units []Unit) []ParseOption {
	if len(units) == 0 {
		return nil
	}
	return []ParseOption{WithUnit(units[0])}
}
