"""Generates the combinatorial test scripts cases/gen-*.sql of group D (run: python3 ag-d-gencases.py D)."""
import itertools, sys

D = sys.argv[1]


def write(name, stmts):
    with open(D + '/cases/' + name, 'w') as f:
        f.write('-- generated by ag-d-gencases.py\n')
        for s in stmts:
            f.write(s + ';\n')
    print(name, len(stmts))


# XMLTABLE column options: every sequence of up to 3 options (any order, duplicates are errors)
opts = ["path 'p'", "default 1", "not null", "null", '"path" \'q\'', '"default" 2']
seqs = [()]
for n in (1, 2, 3):
    seqs += list(itertools.product(opts, repeat=n))
write('gen-xmltable-options.sql',
      ["select * from xmltable('/r' passing x columns a int %s)" % ' '.join(s) for s in seqs])

# JSON_QUERY: returning x wrapper x quotes x behaviors
ret = ['', 'returning int', 'returning text format json', 'returning bytea format json encoding utf16']
wrap = ['', 'without wrapper', 'without array wrapper', 'with wrapper', 'with array wrapper', 'with conditional wrapper',
        'with conditional array wrapper', 'with unconditional wrapper', 'with unconditional array wrapper']
quotes = ['', 'keep quotes', 'keep quotes on scalar string', 'omit quotes', 'omit quotes on scalar string']
beh = ['', 'error on empty', 'null on error', 'default 1 on empty', 'empty array on empty empty object on error',
       'true on empty false on error', 'unknown on error', 'empty on empty', 'error on error error on empty']
write('gen-json-query.sql', ["select json_query(a, 'x' passing 1 as v %s %s %s %s)" % c
                             for c in itertools.product(ret, wrap, quotes, beh)])
# the clauses in every order (only the right order is valid)
cl = ['passing 1 as v', 'returning int', 'with wrapper', 'omit quotes', 'null on empty']
write('gen-json-query-order.sql', ["select json_query(a, 'x' %s)" % ' '.join(p) for p in itertools.permutations(cl)])
write('gen-json-value.sql', ["select json_value(a, 'x' %s %s %s %s)" % c
                             for c in itertools.product(['', 'passing 1 as v'], ret[:3], beh, ['', 'with wrapper', 'omit quotes'])])
write('gen-json-exists.sql', ["select json_exists(a, 'x' %s %s)" % c
                              for c in itertools.product(['', 'passing 1 as v'], beh)])

# JSON_OBJECT / JSON_ARRAY / JSON_OBJECTAGG / JSON_ARRAYAGG: the clauses in every order
nul = ['', 'null on null', 'absent on null']
uni = ['', 'with unique', 'with unique keys', 'without unique', 'without unique keys']
rets = ['', 'returning jsonb', 'returning text format json encoding utf8']
st = []
for fn, arg in (('json_object', "'a' : 1"), ('json_object', 'a value b'), ('json_objectagg', 'k : v'), ('json_objectagg', 'k value v')):
    for c in itertools.product(nul, uni, rets):
        st.append('select %s(%s %s)' % (fn, arg, ' '.join(c)))
    for p in itertools.permutations(['null on null', 'with unique keys', 'returning json']):
        st.append('select %s(%s %s)' % (fn, arg, ' '.join(p)))
for fn, arg in (('json_array', '1, 2'), ('json_array', "1 format json"), ('json_arrayagg', 'v'), ('json_arrayagg', 'v order by k')):
    for c in itertools.product(nul, rets):
        st.append('select %s(%s %s)' % (fn, arg, ' '.join(c)))
    for c in itertools.product(['', 'with unique keys'], nul):
        st.append('select %s(%s %s)' % (fn, arg, ' '.join(c)))
    for p in itertools.permutations(['null on null', 'returning json']):
        st.append('select %s(%s %s)' % (fn, arg, ' '.join(p)))
write('gen-json-constructors.sql', st)

# IS JSON: the type and the uniqueness, with and without NOT, followed by other operators
st = []
for n, t, u in itertools.product(['', 'not'], ['', 'value', 'array', 'object', 'scalar'], uni):
    st.append('select a is %s json %s %s' % (n, t, u))
    st.append('select a is %s json %s %s is null' % (n, t, u))
    st.append('select a is %s json %s %s and b' % (n, t, u))
write('gen-is-json.sql', st)

# JSON_TABLE columns: the forms with their clauses
fmt = ['', 'format json', 'format json encoding utf8']
path = ['', "path '$.a'"]
st = []
for t, f, p, w, q, b in itertools.product(['int', 'text'], fmt, path, wrap[:4], quotes[:3], beh[:5]):
    st.append("select * from json_table(x, '$' columns (a %s %s %s %s %s %s))" % (t, f, p, w, q, b))
for t, p, b in itertools.product(['int'], path, ['', 'error on error', 'true on error', 'default 1 on error', 'error on empty',
                                                'null on empty error on error']):
    st.append("select * from json_table(x, '$' columns (a %s exists %s %s))" % (t, p, b))
for f, w, q, b in itertools.product(['', 'format json'], wrap[:3], quotes[:2], ['', 'error on error']):
    st.append("select * from json_table(x, '$' columns (a int exists %s %s %s %s))" % (f, w, q, b))
for p, n in itertools.product(['', 'path'], ['', "as nm"]):
    st.append("select * from json_table(x, '$' columns (nested %s '$.n' %s columns (a int)))" % (p, n))
write('gen-json-table.sql', st)

# JSON_TABLE: the clauses around the columns
st = []
for c in itertools.product(['', 'format json'], ['', "as p"], ['', 'passing 1 as v, 2 as w'], ['', 'error on error', 'default 1 on error',
                                                                                         'error on empty'], ['', 'as t', 't(a)']):
    st.append("select * from json_table(x %s, '$' %s %s columns (a int) %s) %s" % c)
write('gen-json-table-clauses.sql', st)

# XMLTABLE: the namespaces, the passing mechanisms, the alias
st = []
for ns, pm1, pm2, al in itertools.product(['', "xmlnamespaces('u' as a),", "xmlnamespaces(default 'd'),", "xmlnamespaces('u' as a, default 'd'),"],
                                          ['', 'by ref', 'by value'], ['', 'by ref', 'by value'], ['', 'as t', 't(a)', 'lateral']):
    if al == 'lateral':
        st.append("select * from lateral xmltable(%s '/r' passing %s x %s columns a int)" % (ns, pm1, pm2))
    else:
        st.append("select * from xmltable(%s '/r' passing %s x %s columns a int) %s" % (ns, pm1, pm2, al))
write('gen-xmltable-clauses.sql', st)

# the XML functions: the optional parts
st = []
for d, ws in itertools.product(['document', 'content'], ['', 'preserve whitespace', 'strip whitespace', 'preserve', 'whitespace']):
    st.append('select xmlparse(%s x %s)' % (d, ws))
for d, ind, ty in itertools.product(['document', 'content'], ['', 'indent', 'no indent', 'no'], ['text', 'varchar(3)', 'text[]', 'text array']):
    st.append('select xmlserialize(%s x as %s %s)' % (d, ty, ind))
for v, s in itertools.product(['version 1', "version '1.0'", 'version no value', 'version no', 'version'],
                              ['', ', standalone yes', ', standalone no', ', standalone no value', ', standalone', ', standalone value', ', yes']):
    st.append('select xmlroot(x, %s %s)' % (v, s))
for a, l in itertools.product(['', ', xmlattributes(a)', ', xmlattributes(a as b, c)', ', xmlattributes()'], ['', ', x', ', x, y']):
    st.append('select xmlelement(name foo %s %s)' % (a, l))
    st.append('select xmlelement(name foo %s %s %s)' % (l, a, ''))
write('gen-xml-functions.sql', st)
