#!/usr/bin/env python3
"""Writes rawschema.go: the fields of the nodes of the raw parse tree, from pglast's definitions.

    python3 rawschema.py > ../../rawschema.go        (with the interpreter that has pglast installed)

For every node type: the name of each field in the JSON of libpg_query, the name of the Go field that
carries it in this package (the name with each underscore-separated part capitalized: sortby_dir is
SortbyDir), whether its value is an enumeration (and the first enumerator, which libpg_query prints for
an unset field) and whether it is a node of one concrete type, which the JSON prints without the wrapper
that a generic Node pointer has (the alias of a RangeVar, the typeName of a TypeCast...).
"""
import os
import re
import sys

import pglast
import pglast.enums as E

pyi = os.path.join(os.path.dirname(pglast.__file__), 'ast.pyi')
schema = {}
cur = None
for line in open(pyi):
    m = re.match(r'class (\w+)\((\w+)\):', line)
    if m:
        cur = m.group(1)
        schema[cur] = []
        continue
    m = re.match(r'    (\w+): (.*)$', line)
    if m and cur and not m.group(1).startswith('_') and m.group(1) != 'ancestors':
        schema[cur].append((m.group(1), m.group(2).replace(' | None', '').replace('enums.', '')))


def goname(raw):
    raw = raw.rstrip('_')
    return ''.join(p[:1].upper() + p[1:] for p in raw.split('_'))


def enum_first(typ):
    for modname in ('parsenodes', 'primnodes', 'nodes', 'lockoptions', 'xml', 'cmptype'):
        mod = getattr(E, modname, None)
        if mod and hasattr(mod, typ) and isinstance(getattr(mod, typ), type):
            try:
                return list(getattr(mod, typ))[0].name
            except Exception:
                return None
    return None


IGNORED = {'location', 'rexpr_list_start', 'rexpr_list_end', 'list_start', 'list_end', 'stmt_len', 'stmt_location',
           'conninfo_location', 'name_location', 'arg_location', 'payload_location'}

print('// Code generated by internal/refgen/rawschema.py. DO NOT EDIT.')
print()
print('package postgresql')
print()
print('// rawField describes a field of a node of the raw parse tree: its JSON name, the Go name of the field')
print('// that carries it, the first enumerator when it is an enumeration, and whether its value is a node of')
print('// one concrete type (printed without the wrapper of a generic node).')
print('type rawField struct {')
print('\tjson, goName, enum string')
print('\tconcrete           bool')
print('}')
print()
print('// rawNodes lists the fields of every node type of the raw parse tree.')
print('var rawNodes = map[string][]rawField{')
for t in sorted(schema):
    fields = []
    for f, typ in schema[t]:
        if f in IGNORED:
            continue
        en = enum_first(typ) or ''
        concrete = typ in schema and typ not in ('Node', 'Expr') and not en
        fields.append('{%s, %s, %s, %s}' % ('"' + f.rstrip('_') + '"', '"' + goname(f) + '"', '"' + en + '"', 'true' if concrete else 'false'))
    print('\t"%s": {%s},' % (t, ', '.join(fields)))
print('}')
