-- AlterObjectDependsStmt: every production of gram.y
ALTER FUNCTION f DEPENDS ON EXTENSION e;
ALTER FUNCTION f NO DEPENDS ON EXTENSION e;
ALTER FUNCTION f(int) DEPENDS ON EXTENSION e;
ALTER FUNCTION s.f(int, out text, variadic int[]) NO DEPENDS ON EXTENSION e;
ALTER PROCEDURE p DEPENDS ON EXTENSION e;
ALTER PROCEDURE p(int) NO DEPENDS ON EXTENSION e;
ALTER ROUTINE r DEPENDS ON EXTENSION e;
ALTER ROUTINE s.r(int) NO DEPENDS ON EXTENSION e;
ALTER TRIGGER t ON u DEPENDS ON EXTENSION e;
ALTER TRIGGER t ON s.u NO DEPENDS ON EXTENSION e;
ALTER MATERIALIZED VIEW v DEPENDS ON EXTENSION e;
ALTER MATERIALIZED VIEW s.v NO DEPENDS ON EXTENSION e;
ALTER INDEX i DEPENDS ON EXTENSION e;
ALTER INDEX s.i NO DEPENDS ON EXTENSION e;
-- names that are keywords
ALTER FUNCTION no DEPENDS ON EXTENSION e;
ALTER FUNCTION f NO DEPENDS ON EXTENSION no;
ALTER FUNCTION depends DEPENDS ON EXTENSION depends;
ALTER TRIGGER no ON no DEPENDS ON EXTENSION no;
ALTER INDEX no DEPENDS ON EXTENSION e;
ALTER INDEX no NO DEPENDS ON EXTENSION e;
ALTER MATERIALIZED VIEW no NO DEPENDS ON EXTENSION e;
ALTER FUNCTION f DEPENDS ON EXTENSION "E";
ALTER FUNCTION f DEPENDS ON EXTENSION extension;
-- comments and case between the tokens
alter /* a */ function /* b */ f /* c */ no /* d */ depends /* e */ on /* f */ extension /* g */ e /* h */;
AlTeR iNdEx i nO dEpEnDs On ExTeNsIoN e;
alter materialized -- x
view v depends on extension e;
-- invalid
ALTER TABLE t DEPENDS ON EXTENSION e;
ALTER VIEW v DEPENDS ON EXTENSION e;
ALTER SEQUENCE s DEPENDS ON EXTENSION e;
ALTER AGGREGATE a(*) DEPENDS ON EXTENSION e;
ALTER OPERATOR +(int, int) DEPENDS ON EXTENSION e;
ALTER FUNCTION f DEPENDS EXTENSION e;
ALTER FUNCTION f DEPENDS ON e;
ALTER FUNCTION f DEPENDS ON EXTENSION;
ALTER FUNCTION f DEPENDS ON EXTENSION e.f;
ALTER FUNCTION f DEPENDS ON EXTENSION e, f;
ALTER FUNCTION f NO NO DEPENDS ON EXTENSION e;
ALTER FUNCTION f DEPENDS ON ON EXTENSION e;
ALTER FUNCTION IF EXISTS f DEPENDS ON EXTENSION e;
ALTER TRIGGER t DEPENDS ON EXTENSION e;
ALTER TRIGGER ON u DEPENDS ON EXTENSION e;
ALTER TRIGGER IF EXISTS t ON u DEPENDS ON EXTENSION e;
ALTER TRIGGER t ON u, v DEPENDS ON EXTENSION e;
ALTER TRIGGER t ON ONLY u DEPENDS ON EXTENSION e;
ALTER MATERIALIZED VIEW IF EXISTS v DEPENDS ON EXTENSION e;
ALTER MATERIALIZED VIEW ONLY v DEPENDS ON EXTENSION e;
ALTER INDEX IF EXISTS i DEPENDS ON EXTENSION e;
ALTER INDEX ONLY i DEPENDS ON EXTENSION e;
ALTER INDEX a.b.c.d DEPENDS ON EXTENSION e;
ALTER FOREIGN TABLE t DEPENDS ON EXTENSION e;
ALTER MATERIALIZED v DEPENDS ON EXTENSION e;
ALTER EXTENSION e DEPENDS ON EXTENSION f;
ALTER DATABASE d DEPENDS ON EXTENSION e;
ALTER SCHEMA s NO DEPENDS ON EXTENSION e;
