// Package cel parses CEL, the Common Expression Language, with a parser generated by PEGO from cel.pego.
package cel

import (
	"errors"
	"strconv"
	"strings"
	"unicode/utf8"
)

// trivia skips the whitespace and comments at the start of s that the grammar allows between the tokens
// of a literal or a name, and returns the rest.
func trivia(s string) string {
	for {
		s = strings.TrimLeft(s, " \t\r\n\f")
		if !strings.HasPrefix(s, "//") {
			return s
		}
		i := strings.IndexByte(s, '\n')
		if i < 0 {
			return ""
		}
		s = s[i:]
	}
}

// compact removes the whitespace and comments that the grammar allows between the tokens of a name.
func compact(s string) string {
	if !strings.ContainsAny(s, " \t\r\n\f/") {
		return s
	}
	var b strings.Builder
	for len(s) > 0 {
		t := trivia(s)
		if len(t) == 0 {
			break
		}
		s = t
		b.WriteByte(s[0])
		s = s[1:]
	}
	return b.String()
}

// sign splits the text of a numeric literal into its sign ("" or "-") and the rest.
func sign(text string) (string, string) {
	if strings.HasPrefix(text, "-") {
		return "-", trivia(text[1:])
	}
	return "", text
}

// Name returns the identifier without the leading dot, and Rooted tells whether there was one.
func (n *Ident) Name() string {
	s := compact(n.Text)
	if strings.HasPrefix(s, ".") {
		return s[1:]
	}
	return s
}

// Rooted reports whether the identifier starts with a dot, which resolves it in the root scope.
func (n *Ident) Rooted() bool { return strings.HasPrefix(n.Text, ".") }

// Value returns the name of a field or a map key, without the backquotes of an escaped name.
func (n *Name) Value() string {
	if strings.HasPrefix(n.Text, "`") {
		return n.Text[1 : len(n.Text)-1]
	}
	return n.Text
}

// Value returns the integer. A value outside the range of int64 is an error.
func (n *IntLit) Value() (int64, error) {
	sg, t := sign(n.Text)
	base := 10
	if strings.HasPrefix(t, "0x") {
		base, t = 16, t[2:]
	}
	i, err := strconv.ParseInt(sg+t, base, 64)
	if err != nil {
		return 0, errors.New("invalid int literal")
	}
	return i, nil
}

// Value returns the unsigned integer. A value outside the range of uint64 is an error.
func (n *UintLit) Value() (uint64, error) {
	t := n.Text[:len(n.Text)-1]
	base := 10
	if strings.HasPrefix(t, "0x") {
		base, t = 16, t[2:]
	}
	i, err := strconv.ParseUint(t, base, 64)
	if err != nil {
		return 0, errors.New("invalid uint literal")
	}
	return i, nil
}

// Value returns the floating-point number. A value too large for float64 is an error.
func (n *DoubleLit) Value() (float64, error) {
	sg, t := sign(n.Text)
	f, err := strconv.ParseFloat(sg+t, 64)
	if err != nil {
		return 0, errors.New("invalid double literal")
	}
	return f, nil
}

// Value returns the boolean.
func (n *BoolLit) Value() bool { return n.Text == "true" }

// Value returns the string the literal denotes, with its escape sequences decoded.
func (n *StringLit) Value() string {
	s, _ := unquote(n.Text, false)
	return s
}

// Value returns the bytes the literal denotes. The UTF-8 encoding of the characters of the literal and the
// values of its octal and hexadecimal escapes make up the bytes.
func (n *BytesLit) Value() []byte {
	s, _ := unquote(n.Text[1:], true)
	return []byte(s)
}

// unquote decodes a string literal, with its optional r prefix, as cel-go does: line breaks (CRLF and CR)
// become LF, a raw literal keeps its content, and otherwise the escape sequences are decoded. In bytes, octal
// and hexadecimal escapes are single bytes, and \u and \U are errors; in strings, they are code points.
func unquote(lit string, isBytes bool) (string, error) {
	if strings.ContainsRune(lit, '\r') {
		lit = strings.NewReplacer("\r\n", "\n", "\r", "\n").Replace(lit)
	}
	raw := false
	if lit[0] == 'r' || lit[0] == 'R' {
		raw, lit = true, lit[1:]
	}
	q := 1
	if len(lit) >= 6 && lit[1] == lit[0] && lit[2] == lit[0] {
		q = 3
	}
	body := lit[q : len(lit)-q]
	if raw || strings.IndexByte(body, '\\') < 0 {
		return body, nil
	}
	buf := make([]byte, 0, len(body))
	for len(body) > 0 {
		c := body[0]
		if c >= utf8.RuneSelf {
			r, size := utf8.DecodeRuneInString(body)
			buf = utf8.AppendRune(buf, r)
			body = body[size:]
			continue
		}
		if c != '\\' {
			buf = append(buf, c)
			body = body[1:]
			continue
		}
		var err error
		buf, body, err = unescape(buf, body, isBytes)
		if err != nil {
			return "", err
		}
	}
	return string(buf), nil
}

// unescape decodes the escape sequence at the start of s, which begins with a backslash, and appends it to buf.
func unescape(buf []byte, s string, isBytes bool) ([]byte, string, error) {
	if len(s) < 2 {
		return nil, "", errors.New("unable to unescape string, found '\\' as last character")
	}
	c, s := s[1], s[2:]
	switch c {
	case 'a':
		return append(buf, '\a'), s, nil
	case 'b':
		return append(buf, '\b'), s, nil
	case 'f':
		return append(buf, '\f'), s, nil
	case 'n':
		return append(buf, '\n'), s, nil
	case 'r':
		return append(buf, '\r'), s, nil
	case 't':
		return append(buf, '\t'), s, nil
	case 'v':
		return append(buf, '\v'), s, nil
	case '\\', '\'', '"', '`', '?':
		return append(buf, c), s, nil
	case 'x', 'X', 'u', 'U':
		n := 2
		switch c {
		case 'u':
			n = 4
		case 'U':
			n = 8
		}
		if (c == 'u' || c == 'U') && isBytes {
			return nil, "", errors.New("unable to unescape string")
		}
		if len(s) < n {
			return nil, "", errors.New("unable to unescape string")
		}
		v, err := strconv.ParseUint(s[:n], 16, 32)
		if err != nil || s[0] == '+' || s[0] == '-' {
			return nil, "", errors.New("unable to unescape string")
		}
		s = s[n:]
		if isBytes && (c == 'x' || c == 'X') {
			return append(buf, byte(v)), s, nil
		}
		if !utf8.ValidRune(rune(v)) {
			return nil, "", errors.New("invalid unicode code point")
		}
		return utf8.AppendRune(buf, rune(v)), s, nil
	case '0', '1', '2', '3':
		if len(s) < 2 || s[0] < '0' || s[0] > '7' || s[1] < '0' || s[1] > '7' {
			return nil, "", errors.New("unable to unescape octal sequence in string")
		}
		v := int(c-'0')*64 + int(s[0]-'0')*8 + int(s[1]-'0')
		s = s[2:]
		if isBytes {
			return append(buf, byte(v)), s, nil
		}
		return utf8.AppendRune(buf, rune(v)), s, nil
	}
	return nil, "", errors.New("unable to unescape string")
}

// SpanOf returns the range of the input that e covers, or the zero Span for nil or an Error left by recovery.
func SpanOf(e Expr) Span {
	switch e := e.(type) {
	case *Ident:
		return e.Span
	case *IntLit:
		return e.Span
	case *UintLit:
		return e.Span
	case *DoubleLit:
		return e.Span
	case *StringLit:
		return e.Span
	case *BytesLit:
		return e.Span
	case *BoolLit:
		return e.Span
	case *NullLit:
		return e.Span
	case *Paren:
		return e.Span
	case *Select:
		return e.Span
	case *Index:
		return e.Span
	case *Call:
		return e.Span
	case *Unary:
		return e.Span
	case *Binary:
		return e.Span
	case *Conditional:
		return e.Span
	case *ListLit:
		return e.Span
	case *MapLit:
		return e.Span
	case *MessageLit:
		return e.Span
	case *Optional:
		return e.Span
	}
	return Span{}
}

// Children calls f with each direct sub-expression of e, in source order.
func Children(e Expr, f func(Expr)) {
	switch e := e.(type) {
	case *Paren:
		f(e.X)
	case *Select:
		f(e.X)
	case *Index:
		f(e.X)
		f(e.Index)
	case *Call:
		if e.Target != nil {
			f(e.Target)
		}
		for _, a := range e.Args {
			f(a)
		}
	case *Unary:
		f(e.X)
	case *Binary:
		f(e.Left)
		f(e.Right)
	case *Conditional:
		f(e.Cond)
		f(e.Then)
		f(e.Else)
	case *ListLit:
		for _, x := range e.Elems {
			f(x)
		}
	case *MapLit:
		for _, en := range e.Entries {
			f(en.Key)
			f(en.Value)
		}
	case *MessageLit:
		for _, fl := range e.Fields {
			f(fl.Value)
		}
	case *Optional:
		f(e.X)
	}
}

// Inspect traverses the expression in depth-first order: it calls f(e), and if f returns true, inspects the
// children of e.
func Inspect(e Expr, f func(Expr) bool) {
	if e == nil || !f(e) {
		return
	}
	Children(e, func(c Expr) { Inspect(c, f) })
}
