package cel_test

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/ornew/pego/parsers/cel"
)

// refDir is the directory of the reference results of cel-go: testdata/ref, or the directory that the environment
// variable CEL_REF_DIR names, which is where a larger set generated by internal/refgen goes.
func refDir() string {
	if d := os.Getenv("CEL_REF_DIR"); d != "" {
		return d
	}
	return filepath.Join("testdata", "ref")
}

// refCase is a line of testdata/ref/*.tsv: an expression and what cel-go makes of it (see internal/refgen).
type refCase struct {
	src, want string
}

func readRef(t testing.TB, name string) []refCase {
	t.Helper()
	f, err := os.Open(filepath.Join(refDir(), name))
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var cases []refCase
	sc := bufio.NewScanner(f)
	sc.Buffer(nil, 1<<24)
	for sc.Scan() {
		q, want, ok := strings.Cut(sc.Text(), "\t")
		if !ok {
			t.Fatalf("%s: bad line %.60q", name, sc.Text())
		}
		src, err := strconv.Unquote(q)
		if err != nil {
			t.Fatalf("%s: bad line %.60q: %v", name, sc.Text(), err)
		}
		cases = append(cases, refCase{src, want})
	}
	if err := sc.Err(); err != nil {
		t.Fatal(err)
	}
	if len(cases) == 0 {
		t.Fatalf("%s: no cases", name)
	}
	return cases
}

// result parses src as ParseExpr does and returns the canonical form of the expression, or ERR@line:column of
// the error (the columns of cel-go count from 1 as well).
func result(src string) string {
	e, err := cel.ParseExpr(src)
	if err != nil {
		var se *cel.SyntaxError
		var ce *cel.CheckError
		switch {
		case errors.As(err, &se):
			return fmt.Sprintf("ERR@%d:%d", se.Line, se.Col)
		case errors.As(err, &ce):
			return fmt.Sprintf("ERR@%d:%d", ce.Line, ce.Col)
		}
		return "ERR"
	}
	return canonical(src, e)
}

// TestDifferential compares the AST of every expression of testdata/ref/*.tsv with the one cel-go returns for it
// (and the rejected ones with the errors of cel-go): the conformance tests of cel-spec, the cases of cel-go's own
// parser tests, hand-picked edge cases, and random expressions and literals.
func TestDifferential(t *testing.T) {
	files, _ := filepath.Glob(filepath.Join(refDir(), "*.tsv"))
	for _, f := range files {
		name := filepath.Base(f)
		if name == "limits.tsv" {
			continue
		}
		t.Run(strings.TrimSuffix(name, ".tsv"), func(t *testing.T) {
			bad, rejected, samePos := 0, 0, 0
			for _, c := range readRef(t, name) {
				got := result(c.src)
				gotErr, wantErr := strings.HasPrefix(got, "ERR"), strings.HasPrefix(c.want, "ERR")
				if c.want == "OK" && !gotErr { // a file of verdicts: the tree is not compared
					got = "OK"
				}
				switch {
				case gotErr && wantErr: // the position of the error is not required to be the same
					rejected++
					if got == c.want {
						samePos++
					}
				case got != c.want:
					bad++
					if bad <= 12 {
						t.Errorf("%.300q\n got  %.300s\n want %.300s", c.src, got, c.want)
					}
				}
			}
			if bad > 12 {
				t.Errorf("%d differences in all", bad)
			}
			if rejected > 0 {
				t.Logf("%d rejected, the first error at the same position as cel-go's in %d (%.1f%%)", rejected, samePos, 100*float64(samePos)/float64(rejected))
			}
		})
	}
}
