"""Generates the Unicode tables of the parsers/python module from CPython's unicodedata.

Run it with the CPython whose Unicode database the module follows (3.14: Unicode 16.0), from the
module directory:

    python3.14 tools/gentables.py [Name.pl] > /tmp/xid.pego

It writes:

  - tables.go: the code points that str.isprintable rejects (for repr), and the ranges of the
    character names of the form PREFIX-XXXX;
  - unicode.bin (zlib): the character names and name aliases that \\N{...} accepts, and the data of
    NFKC normalization (of identifiers) for the characters that may continue an identifier: their
    compatibility decompositions, the canonical combining classes, and the canonical compositions.

It prints the character classes of identifiers of python.pego (idstart_other, idcont_other).

unicodedata cannot list name aliases, which \\N{...} accepts. Pass a file of candidate names, such as
Perl's lib/unicore/Name.pl (which lists names and aliases, one per line after a line with the code
point); every candidate that unicodedata.lookup resolves to one character and that is not the name
of that character is kept as an alias.
"""

import re
import sys
import unicodedata
import zlib


def ranges(pred, lo=0x80):
    out = []
    start = None
    for cp in range(lo, 0x110000):
        ok = pred(cp)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


# Names of the form PREFIX-HEX, kept as ranges instead of names. CPython resolves CJK UNIFIED
# IDEOGRAPH- with an algorithm (that accepts only upper-case hexadecimal digits) and the others
# from its table of names (without regard to case). Hangul syllables have an algorithm of their own.
HEX_PREFIXES = ["CJK UNIFIED IDEOGRAPH", "CJK COMPATIBILITY IDEOGRAPH", "EGYPTIAN HIEROGLYPH",
                "KHITAN SMALL SCRIPT CHARACTER", "NUSHU CHARACTER"]


def is_hangul_syllable(cp):
    return 0xAC00 <= cp <= 0xD7A3


def main():
    names = {}
    prefixed = {p: [] for p in HEX_PREFIXES}
    for cp in range(0x110000):
        n = unicodedata.name(chr(cp), None)
        if n is None:
            continue
        m = re.fullmatch(r"(.*)-([0-9A-F]{4,6})", n)
        if m and m.group(1) in prefixed and int(m.group(2), 16) == cp:
            prefixed[m.group(1)].append(cp)
            continue
        if n.startswith("HANGUL SYLLABLE "):
            continue
        names[n] = cp
    aliases = {}
    if len(sys.argv) > 1:
        lines = open(sys.argv[1], encoding="utf-8").read().split("\n")
        for line in lines:
            line = line.strip()
            if not line or line.startswith("#") or not re.fullmatch(r"[A-Z0-9 \-]+", line):
                continue
            if re.fullmatch(r"[0-9A-F]{5}( [0-9A-F]{5})*", line) or line in names:
                continue
            try:
                s = unicodedata.lookup(line)
            except KeyError:
                continue
            if len(s) == 1 and unicodedata.name(s, "") != line:
                aliases[line] = ord(s)
    table = dict(names)
    table.update(aliases)
    out = ["N\t%s\t%X" % (n, cp) for n, cp in sorted(table.items())]

    # NFKC of identifiers: the decompositions of the characters that may continue an identifier.
    xid = [cp for cp in range(0x80, 0x110000) if ("a" + chr(cp)).isidentifier()]
    for cp in xid:
        if is_hangul_syllable(cp):
            continue
        d = unicodedata.normalize("NFKD", chr(cp))
        if d != chr(cp):
            out.append("D\t%X\t%s" % (cp, " ".join("%X" % ord(c) for c in d)))
    for cp in range(0x110000):
        c = unicodedata.combining(chr(cp))
        if c:
            out.append("C\t%X\t%d" % (cp, c))
    for cp in range(0x110000):
        if is_hangul_syllable(cp):
            continue
        d = unicodedata.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(x, 16) for x in d.split()]
        if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            out.append("P\t%X %X\t%X" % (parts[0], parts[1], cp))
    data = ("\n".join(out) + "\n").encode()
    with open("unicode.bin", "wb") as f:
        f.write(zlib.compress(data, 9))

    def prefix_ranges(cps):
        out = []
        for cp in cps:
            if out and out[-1][1] == cp - 1:
                out[-1][1] = cp
            else:
                out.append([cp, cp])
        return out

    nonprint = ranges(lambda cp: not chr(cp).isprintable())
    with open("tables.go", "w") as f:
        f.write("// Code generated by tools/gentables.py from the Unicode %s database of CPython. DO NOT EDIT.\n\n"
                % unicodedata.unidata_version)
        f.write("package python\n\n")
        f.write("// unidataVersion is the version of the Unicode database the tables follow.\n")
        f.write("const unidataVersion = \"%s\"\n\n" % unicodedata.unidata_version)
        f.write("// nonPrintable lists the code points from U+0080 on that str.isprintable rejects.\n")
        f.write("var nonPrintable = []runeRange{\n")
        for a, b in nonprint:
            f.write("\t{0x%X, 0x%X},\n" % (a, b))
        f.write("}\n\n")
        f.write("// hexNames lists the names of the form PREFIX-XXXX and the code points they name.\n")
        f.write("var hexNames = []hexName{\n")
        for p in HEX_PREFIXES:
            f.write("\t{\"%s\", []runeRange{" % p)
            f.write(", ".join("{0x%X, 0x%X}" % (a, b) for a, b in prefix_ranges(prefixed[p])))
            f.write("}},\n")
        f.write("}\n")
    start = ranges(lambda cp: chr(cp).isidentifier())
    cont = ranges(lambda cp: ("a" + chr(cp)).isidentifier())

    def cls(rs):
        return "".join("\\u{%X}" % a if a == b else "\\u{%X}-\\u{%X}" % (a, b) for a, b in rs)

    print("def idstart_other = (?" + cls(start) + ")")
    print("def idcont_other = (?" + cls(cont) + ")")
    print("names", len(names), "aliases", len(aliases), "bytes", len(data), file=sys.stderr)


main()
