// Package cue parses CUE (https://cuelang.org/) with a parser generated by PEGO from cue.pego. It reads syntax
// only: it does not evaluate, unify, load packages or format.
//
// The language is that of the specification (doc/ref/spec.md of github.com/cue-lang/cue) as the reference
// implementation, cuelang.org/go/cue/parser of v0.17.1, reads it, which decides where the two differ. ParseFile
// accepts exactly what cue/parser.ParseFile accepts and returns the syntax tree; ParseAST returns the tree as the
// grammar reads it, without the checks that come after the syntax (File.Check: experiments, scopes, import paths,
// the indentation of strings with interpolations, UTF-8); Parse returns it as a tree of Nodes, and Recognize only
// checks the syntax. The types of the tree follow cuelang.org/go/cue/ast, and every node has its Span in the input
// (in code points; Bytes counts bytes). Comments lists the comments of a source. String.Unquote, Int.Value,
// Float.Rat and the other methods decode literals as cuelang.org/go/cue/literal does, and Inspect walks the tree.
//
// # Conformance
//
// The tests compare with the reference results of cue/parser, vendored in testdata (see the README of the module
// for the numbers and the commands): acceptance and the syntax tree for 4,061 CUE sources (the files of
// cue-lang/cue, the CUE of its test archives and of the tests of the parser, and the examples of the
// specification), 32,488 mutations of them, and 15,000 generated strings, numbers and token sequences, and the
// values of 4,126 literals against cuelang.org/go/cue/literal. None differs; larger runs of 609,150 mutants and
// 750,000 generated inputs did not either.
//
// # Deviations from the reference parser
//
//   - Errors: ParseFile returns the first error, with the position and the expected tokens of PEGO's syntax
//     errors, not the reference's list and messages (the messages of Check are the reference's). Only acceptance
//     is the same.
//   - Comments are listed, not attached to nodes; there are no relative positions, no identifier resolution and no
//     BadExpr.
//   - Nesting: the reference rejects expressions nested 10,000 levels deep; this parser stops at the generated
//     parser's limit of 100,000 rule calls, which is 8,331 levels of structs, 14,282 of lists and 19,995 of
//     parentheses.
//   - Only the latest syntax is read, with no @lang selection of older versions.
//   - ParseAST accepts invalid UTF-8 in strings and comments (ParseFile rejects it), and the syntax of all
//     experiments in any file (Check rejects what the file has not enabled).
//
// Unicode letters and digits in identifiers are those of the unicode package of the Go version that made the
// parser (see the README).
package cue

import (
	"unicode/utf8"
)

// ParseFile parses a CUE file as cuelang.org/go/cue/parser.ParseFile does, and returns the first error, if
// any: ParseAST, then Check, and an error for input that is not UTF-8 (which the parser reads as U+FFFD).
func ParseFile(input string, unit ...Unit) (*File, error) {
	if !utf8.ValidString(input) {
		i := 0
		for j, r := range input {
			if r == utf8.RuneError {
				if _, w := utf8.DecodeRuneInString(input[j:]); w == 1 {
					break
				}
			}
			i = j
		}
		return nil, locate(input, &SemanticError{Span: Span{Start: i + 1, End: i + 1}, Msg: "illegal UTF-8 encoding"}, unit)
	}
	f, err := ParseAST(input, unit...)
	if err != nil {
		return nil, err
	}
	if err := f.Check(); err != nil {
		return nil, locate(input, err, unit)
	}
	return f, nil
}

// Valid reports whether input is a CUE file that ParseFile accepts.
func Valid(input string) bool {
	_, err := ParseFile(input)
	return err == nil
}

// locate sets the line and column of a SemanticError, whose position is in the unit of the parse.
func locate(input string, err error, unit []Unit) error {
	e, ok := err.(*SemanticError)
	if !ok {
		return err
	}
	bytes := len(unit) > 0 && unit[0] == Bytes
	e.Line, e.Col = 1, 1
	i := 0
	for j, r := range input {
		if bytes && j >= e.Start || !bytes && i >= e.Start {
			break
		}
		if r == '\n' {
			e.Line, e.Col = e.Line+1, 1
		} else {
			e.Col++
		}
		i++
	}
	return e
}
