// Package csv parses CSV (RFC 4180) with a parser generated by PEGO from csv.pego.
//
// Records returns the records of a file as strings, with the quotes of quoted fields removed and their
// doubled quotes decoded, as encoding/csv's ReadAll does; Table reads a file with a header record.
// ParseAST returns the file as typed values with their positions in the input (a File of Records of
// Fields), Parse returns it as a tree of Nodes, and Recognize and Valid only check it.
//
// # Syntax
//
// The parser accepts the files of RFC 4180's grammar, and in the points where the RFC and practice
// differ it accepts what encoding/csv accepts with its default settings (Comma ',', LazyQuotes and
// TrimLeadingSpace false, no Comment):
//
//   - A record ends with CRLF or with LF (the RFC requires CRLF). A CR elsewhere, outside quotes, is
//     data (the RFC does not allow it in an unquoted field), except at the end of the input, where it
//     ends the last record as encoding/csv does.
//   - A field may contain any character except, unquoted, the comma, the double quote and the line
//     break (the RFC's TEXTDATA allows only printable ASCII). Bytes that are not UTF-8 are data too.
//   - The line break after the last record is optional, and an empty input has no records.
//   - A double quote in an unquoted field, a quoted field followed by anything but a comma or a line
//     break, spaces around a quoted field (` "a"` or `"a" `) and an unterminated quoted field are
//     syntax errors, as in the RFC and in encoding/csv.
//   - A byte order mark (U+FEFF) at the start of the input is skipped. encoding/csv keeps it in the
//     first field.
//
// # Values
//
// ParseAST represents the input as the RFC's grammar does: an empty line is a record with one empty
// field (Record.Blank), and records may have different numbers of fields. Records and Table drop
// blank records, as encoding/csv skips empty lines. Records does not require every record to have the
// same number of fields (the RFC says only that they should; encoding/csv requires it unless
// FieldsPerRecord is -1); Table requires every record to have as many fields as the header.
//
// The value of a quoted field is the text between its quotes with each "" replaced by ". A CRLF inside
// a quoted field is kept as it is; encoding/csv turns it into LF.
package csv

import (
	"errors"
	"fmt"
	"strings"
)

// Valid reports whether input is a CSV file.
func Valid(input string) bool { return Recognize(input, Bytes) == nil }

// Records parses input and returns its records, each a list of the values of its fields (see
// Field.Value). Blank records (empty lines) are left out. Errors are *SyntaxError.
func Records(input string) ([][]string, error) {
	f, err := ParseAST(input, Bytes)
	if err != nil {
		return nil, err
	}
	return f.Strings(), nil
}

// Strings returns the values of the fields of the file's records, leaving out blank records, as Records
// does.
func (f *File) Strings() [][]string {
	out := make([][]string, 0, len(f.Records))
	// One backing array for all the fields, as encoding/csv's ReadAll allocates one per record.
	n := 0
	for _, r := range f.Records {
		n += len(r.Fields)
	}
	vals := make([]string, 0, n)
	for _, r := range f.Records {
		if r.Blank() {
			continue
		}
		start := len(vals)
		for _, fl := range r.Fields {
			vals = append(vals, fl.Value())
		}
		out = append(out, vals[start:len(vals):len(vals)])
	}
	return out
}

// Strings returns the values of the record's fields.
func (r *Record) Strings() []string {
	s := make([]string, len(r.Fields))
	for i, f := range r.Fields {
		s[i] = f.Value()
	}
	return s
}

// Blank reports whether the record is an empty line: a single empty field without quotes. Records and
// Table leave blank records out, as encoding/csv does.
func (r *Record) Blank() bool { return len(r.Fields) == 1 && r.Fields[0].Text == "" }

// Quoted reports whether the field is enclosed in double quotes.
func (f *Field) Quoted() bool { return f.Text != "" && f.Text[0] == '"' }

// Value returns the field's value: the text of an unquoted field, or the text between the quotes of a
// quoted field with each "" replaced by ".
func (f *Field) Value() string {
	t := f.Text
	if t == "" || t[0] != '"' {
		return t
	}
	t = t[1 : len(t)-1]
	if !strings.Contains(t, `""`) {
		return t
	}
	return strings.ReplaceAll(t, `""`, `"`)
}

// ErrNoHeader is returned by Table for an input without records.
var ErrNoHeader = errors.New("csv: no header record")

// FieldCountError is returned by Table for a record whose number of fields differs from the header's.
type FieldCountError struct {
	Line   int // the line on which the record begins, from 1
	Fields int // the number of fields of the record
	Want   int // the number of fields of the header
}

func (e *FieldCountError) Error() string {
	return fmt.Sprintf("csv: line %d: record has %d fields, the header has %d", e.Line, e.Fields, e.Want)
}

// Table parses input as a file whose first record is a header (RFC 4180's header=present) and returns
// the header and the other records. Every record must have as many fields as the header; otherwise the
// error is a *FieldCountError. Blank records are left out, and an input without records is ErrNoHeader.
// Syntax errors are *SyntaxError.
func Table(input string) (header []string, rows [][]string, err error) {
	f, err := ParseAST(input, Bytes)
	if err != nil {
		return nil, nil, err
	}
	want := -1
	for _, r := range f.Records {
		switch {
		case r.Blank():
		case want < 0:
			want = len(r.Fields)
		case len(r.Fields) != want:
			line := 1 + strings.Count(input[:r.Start], "\n")
			return nil, nil, &FieldCountError{Line: line, Fields: len(r.Fields), Want: want}
		}
	}
	if want < 0 {
		return nil, nil, ErrNoHeader
	}
	recs := f.Strings()
	return recs[0], recs[1:], nil
}
