// Package yaml parses YAML 1.2.2 (https://yaml.org/spec/1.2.2/) with a parser generated by PEGO from
// yaml.pego.
//
// ParseAST returns the stream as typed values: a Stream of Documents, whose nodes are Mappings,
// Sequences, Scalars and Aliases, each with its Span in the input and its Properties (tag and anchor).
// Parse returns the same as a tree of Nodes, and Recognize only checks the input. A Scalar keeps its
// source text; Value decodes it according to its style (escapes, line folding, block indentation and
// chomping). Events writes the event stream of the YAML test suite, and Load and LoadAll compose
// documents into Go values with the YAML 1.2 core schema.
//
// The grammar follows the productions of the specification, with the indentation n and the context c
// of the parameterized productions as variables of the grammar (see yaml.pego). The syntax is checked
// by the parser; the rules that are not syntax are checked by Events, Load and LoadAll (and Check):
// a tag shorthand must use a handle that the document declares, a document may have at most one YAML
// directive and one TAG directive per handle, and the major version of a YAML directive must be 1.
//
// Conformance, measured against the yaml-test-suite (data release 2022-01-17, vendored in
// testdata/yaml-test-suite): see the README for the numbers and the known deviations.
package yaml

import (
	"errors"
	"fmt"
	"math"
	"strconv"
	"strings"
	"unicode/utf8"
)

// The styles of a Scalar (Scalar.Style).
const (
	Plain        = 0 // a plain scalar, or an empty node
	SingleQuoted = 1
	DoubleQuoted = 2
	Literal      = 3 // a literal block scalar (|)
	Folded       = 4 // a folded block scalar (>)
)

// Tag returns the tag of the properties, or nil.
func (p *Properties) tag() *Tag {
	if p == nil {
		return nil
	}
	return p.Tag
}

func (p *Properties) anchor() *Anchor {
	if p == nil {
		return nil
	}
	return p.Anchor
}

// Name returns the name of the anchor, without "&".
func (a *Anchor) Name() string { return a.Text[1:] }

// Name returns the name of the anchor the alias refers to, without "*".
func (a *Alias) Name() string { return a.Text[1:] }

// Value returns the content of the scalar: for a plain or quoted scalar, its text with the lines folded
// and, in a double-quoted scalar, the escape sequences decoded; for a block scalar, its lines without
// the indentation, folded in a folded scalar and with the final line breaks chomped as the header says.
// An escape of a surrogate or of a value outside Unicode decodes to U+FFFD.
func (s *Scalar) Value() string {
	switch s.Style {
	case SingleQuoted:
		return foldFlow(s.Text[1:len(s.Text)-1], '\'')
	case DoubleQuoted:
		return foldFlow(s.Text[1:len(s.Text)-1], '"')
	case Literal, Folded:
		return blockValue(s.Text, s.Indent, s.Style == Folded)
	}
	if !strings.ContainsAny(s.Text, "\r\n") {
		return s.Text
	}
	return foldFlow(s.Text, 0)
}

func isWhite(c byte) bool { return c == ' ' || c == '\t' }

// foldFlow decodes the text of a flow scalar (7.3): a line break and the white space around it fold to a
// space, or to a line feed per empty line that follows it; quote is '\'' to decode '' in a single-quoted
// scalar, '"' to decode the escapes of a double-quoted one.
func foldFlow(t string, quote byte) string {
	var b strings.Builder
	b.Grow(len(t))
	pending := 0 // the start of white space not yet written, which a line break discards; -1 if none
	pending = -1
	flush := func(i int) {
		if pending >= 0 {
			b.WriteString(t[pending:i])
			pending = -1
		}
	}
	i := 0
	// skipBreak skips the line break at i, the empty lines after it and the indentation of the next line,
	// and returns the number of empty lines.
	skipBreak := func() int {
		empty := 0
		i = skipNewline(t, i)
		for {
			j := i
			for j < len(t) && isWhite(t[j]) {
				j++
			}
			if j < len(t) && (t[j] == '\n' || t[j] == '\r') {
				empty++
				i = skipNewline(t, j)
				continue
			}
			i = j
			return empty
		}
	}
	for i < len(t) {
		c := t[i]
		switch {
		case isWhite(c):
			if pending < 0 {
				pending = i
			}
			i++
		case c == '\n' || c == '\r':
			pending = -1
			if empty := skipBreak(); empty == 0 {
				b.WriteByte(' ')
			} else {
				b.WriteString(strings.Repeat("\n", empty))
			}
		case c == '\'' && quote == '\'':
			flush(i)
			b.WriteByte('\'')
			i += 2
		case c == '\\' && quote == '"':
			flush(i)
			i++
			if t[i] == '\n' || t[i] == '\r' {
				// An escaped line break: the break and the indentation of the next line are discarded,
				// the empty lines after it are line feeds.
				b.WriteString(strings.Repeat("\n", skipBreak()))
				continue
			}
			i = decodeEscape(&b, t, i)
		default:
			flush(i)
			j := i + 1
			for j < len(t) && !isWhite(t[j]) && t[j] != '\n' && t[j] != '\r' && t[j] != '\\' && t[j] != '\'' {
				j++
			}
			b.WriteString(t[i:j])
			i = j
		}
	}
	flush(len(t))
	return b.String()
}

func skipNewline(t string, i int) int {
	if t[i] == '\r' && i+1 < len(t) && t[i+1] == '\n' {
		return i + 2
	}
	return i + 1
}

// decodeEscape writes the character of the escape sequence whose letter is at t[i] and returns the
// index after the sequence.
func decodeEscape(b *strings.Builder, t string, i int) int {
	c := t[i]
	switch c {
	case '0':
		b.WriteByte(0)
	case 'a':
		b.WriteByte('\a')
	case 'b':
		b.WriteByte('\b')
	case 't', '\t':
		b.WriteByte('\t')
	case 'n':
		b.WriteByte('\n')
	case 'v':
		b.WriteByte('\v')
	case 'f':
		b.WriteByte('\f')
	case 'r':
		b.WriteByte('\r')
	case 'e':
		b.WriteByte(0x1b)
	case 'N':
		b.WriteRune(0x85)
	case '_':
		b.WriteRune(0xa0)
	case 'L':
		b.WriteRune(0x2028)
	case 'P':
		b.WriteRune(0x2029)
	case 'x', 'u', 'U':
		n := map[byte]int{'x': 2, 'u': 4, 'U': 8}[c]
		v, _ := strconv.ParseUint(t[i+1:i+1+n], 16, 32)
		r := rune(v)
		if v > utf8.MaxRune || !utf8.ValidRune(r) {
			r = utf8.RuneError
		}
		b.WriteRune(r)
		return i + 1 + n
	default: // ' ', '"', '/', '\\'
		b.WriteByte(c)
	}
	return i + 1
}

// blockValue decodes a block scalar (8.1) from its text, which starts with the indicator, and the
// indentation of its content.
func blockValue(t string, indent int, folded bool) string {
	// The header: indicators up to white space, a comment or the end of the line.
	chomp := byte(0)
	i := 1
	for ; i < len(t) && !isWhite(t[i]) && t[i] != '#' && t[i] != '\n' && t[i] != '\r'; i++ {
		if t[i] == '-' || t[i] == '+' {
			chomp = t[i]
		}
	}
	for i < len(t) && t[i] != '\n' && t[i] != '\r' {
		i++
	}
	if i < len(t) {
		i = skipNewline(t, i)
	}
	// The lines. A last line without a line break counts as one with a line break, as in the reference
	// parser of the YAML test suite.
	type line struct {
		text    string // without the indentation; "" for an empty line
		content bool   // a content line, rather than an empty one
		more    bool   // a more-indented line: its text starts with white space
	}
	var lines []line
	for i < len(t) {
		j := i
		for j < len(t) && t[j] != '\n' && t[j] != '\r' {
			j++
		}
		var l line
		if raw := t[i:j]; len(raw) > indent {
			l.text, l.content = raw[indent:], true
			l.more = isWhite(l.text[0])
		}
		lines = append(lines, l)
		if j < len(t) {
			j = skipNewline(t, j)
		}
		i = j
	}
	last := -1
	for k, l := range lines {
		if l.content {
			last = k
		}
	}
	var b strings.Builder
	prev := -1 // the last content line written
	for k := 0; k <= last; k++ {
		l := lines[k]
		if !l.content {
			continue
		}
		empty := k - prev - 1
		switch {
		case prev < 0:
			b.WriteString(strings.Repeat("\n", empty))
		case folded && !l.more && !lines[prev].more:
			if empty == 0 {
				b.WriteByte(' ')
			} else {
				b.WriteString(strings.Repeat("\n", empty))
			}
		default:
			b.WriteString(strings.Repeat("\n", empty+1))
		}
		b.WriteString(l.text)
		prev = k
	}
	switch chomp {
	case '-':
	case '+':
		n := len(lines) - last - 1 // the empty lines after the last content line
		if last >= 0 {
			n++ // and the line break of the last content line
		}
		b.WriteString(strings.Repeat("\n", n))
	default:
		if last >= 0 {
			b.WriteByte('\n')
		}
	}
	return b.String()
}

// The tag prefixes of the default handles.
const (
	CoreTagPrefix = "tag:yaml.org,2002:"
)

// tagHandles returns the handles that the directives of the document declare, with the default ones,
// and checks the directives.
func (d *Document) tagHandles() (map[string]string, error) {
	handles := map[string]string{"!": "!", "!!": CoreTagPrefix}
	declared := map[string]bool{}
	yaml := false
	for _, dir := range d.Directives {
		switch dir.Name.Text {
		case "YAML":
			if yaml {
				return nil, errorAt(dir.Span, "more than one YAML directive")
			}
			yaml = true
			if v := dir.Params[0].Text; !strings.HasPrefix(v, "1.") {
				return nil, errorAt(dir.Span, "unsupported YAML version "+v)
			}
		case "TAG":
			h := dir.Params[0].Text
			if declared[h] {
				return nil, errorAt(dir.Span, "more than one TAG directive for the handle "+h)
			}
			declared[h] = true
			handles[h] = dir.Params[1].Text
		}
	}
	return handles, nil
}

// SemanticError is an error found after parsing, at a span of the input: an undeclared tag handle, a repeated
// directive, an undefined alias, a duplicate key, a value that does not match its tag, and so on.
type SemanticError struct {
	Span
	Msg string
}

func (e *SemanticError) Error() string { return fmt.Sprintf("yaml: %d-%d: %s", e.Start, e.End, e.Msg) }

func errorAt(s Span, msg string) error { return &SemanticError{s, msg} }

// resolveTag returns the full name of a tag: the prefix of its handle followed by its suffix with the %
// escapes decoded, the URI of a verbatim tag, or "!" for the non-specific tag.
func resolveTag(t *Tag, handles map[string]string) (string, error) {
	s := t.Text
	if strings.HasPrefix(s, "!<") {
		return s[2 : len(s)-1], nil
	}
	if s == "!" {
		return "!", nil
	}
	h := "!"
	if i := strings.IndexByte(s[1:], '!'); i >= 0 {
		h = s[:i+2]
	}
	prefix, ok := handles[h]
	if !ok {
		return "", errorAt(t.Span, "undeclared tag handle "+h)
	}
	suffix, err := unescapeURI(s[len(h):])
	if err != nil {
		return "", errorAt(t.Span, err.Error())
	}
	return prefix + suffix, nil
}

func unescapeURI(s string) (string, error) {
	if !strings.Contains(s, "%") {
		return s, nil
	}
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '%' {
			v, err := strconv.ParseUint(s[i+1:i+3], 16, 8)
			if err != nil {
				return "", err
			}
			b.WriteByte(byte(v))
			i += 2
			continue
		}
		b.WriteByte(s[i])
	}
	if !utf8.ValidString(b.String()) {
		return "", errors.New("tag escapes are not UTF-8")
	}
	return b.String(), nil
}

// Check reports the errors of the stream that are not syntax errors, which Valid, Events, Load and
// LoadAll report too: a tag shorthand with a handle the document does not declare, more than one YAML
// directive in a document or more than one TAG directive for a handle, a YAML version other than 1.x,
// and an alias of an anchor that no node before it in the document has.
func (s *Stream) Check() error {
	for _, d := range s.Documents {
		handles, err := d.tagHandles()
		if err != nil {
			return err
		}
		c := checker{handles: handles, anchors: map[string]bool{}}
		if err := c.node(d.Root); err != nil {
			return err
		}
	}
	return nil
}

type checker struct {
	handles map[string]string
	anchors map[string]bool
}

// node checks a node and its descendants in the order of the document.
func (c *checker) node(v Value) error {
	var p *Properties
	switch v := v.(type) {
	case *Mapping:
		p = v.Props
	case *Sequence:
		p = v.Props
	case *Scalar:
		p = v.Props
	case *Alias:
		if !c.anchors[v.Name()] {
			return errorAt(v.Span, "undefined alias "+v.Text)
		}
	}
	if a := p.anchor(); a != nil {
		c.anchors[a.Name()] = true
	}
	if t := p.tag(); t != nil {
		if _, err := resolveTag(t, c.handles); err != nil {
			return err
		}
	}
	switch v := v.(type) {
	case *Mapping:
		for _, pr := range v.Pairs {
			if err := c.node(pr.Key); err != nil {
				return err
			}
			if err := c.node(pr.Value); err != nil {
				return err
			}
		}
	case *Sequence:
		for _, it := range v.Items {
			if err := c.node(it); err != nil {
				return err
			}
		}
	}
	return nil
}

// parseChecked parses input and checks the stream (Check), which must be UTF-8.
func parseChecked(input string) (*Stream, error) {
	if !utf8.ValidString(input) {
		i := 0
		for i < len(input) {
			r, n := utf8.DecodeRuneInString(input[i:])
			if r == utf8.RuneError && n == 1 {
				break
			}
			i += n
		}
		return nil, fmt.Errorf("yaml: invalid UTF-8 at byte %d", i)
	}
	s, err := ParseAST(input)
	if err != nil {
		return nil, err
	}
	if err := s.Check(); err != nil {
		return nil, err
	}
	return s, nil
}

// Valid reports whether input is a valid YAML stream: well-formed UTF-8 that ParseAST accepts and Check
// finds no error in.
func Valid(input string) bool {
	_, err := parseChecked(input)
	return err == nil
}

// Events parses input and returns its event stream in the format of the yaml-test-suite (test.event):
// one event per line (+STR, +DOC, +MAP, +SEQ, =VAL, =ALI, -SEQ, -MAP, -DOC, -STR), with the anchors, the
// resolved tags, the style of each scalar and its value with \\, \0, \b, \t, \n and \r escaped.
func Events(input string) (string, error) {
	s, err := parseChecked(input)
	if err != nil {
		return "", err
	}
	return s.Events()
}

// Events returns the event stream of a parsed stream (see the function Events), or the error of Check.
func (s *Stream) Events() (string, error) {
	if err := s.Check(); err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString("+STR\n")
	for _, d := range s.Documents {
		handles, err := d.tagHandles()
		if err != nil {
			return "", err
		}
		b.WriteString("+DOC")
		if d.Start != nil {
			b.WriteString(" ---")
		}
		b.WriteByte('\n')
		if err := writeEvents(&b, d.Root, handles); err != nil {
			return "", err
		}
		b.WriteString("-DOC")
		if d.End != nil {
			b.WriteString(" ...")
		}
		b.WriteByte('\n')
	}
	b.WriteString("-STR\n")
	return b.String(), nil
}

func writeProps(b *strings.Builder, p *Properties, handles map[string]string) error {
	if a := p.anchor(); a != nil {
		b.WriteString(" &")
		b.WriteString(a.Name())
	}
	if t := p.tag(); t != nil {
		tag, err := resolveTag(t, handles)
		if err != nil {
			return err
		}
		b.WriteString(" <")
		b.WriteString(tag)
		b.WriteByte('>')
	}
	return nil
}

func writeEvents(b *strings.Builder, v Value, handles map[string]string) error {
	switch v := v.(type) {
	case *Mapping:
		b.WriteString("+MAP")
		if v.Flow {
			b.WriteString(" {}")
		}
		if err := writeProps(b, v.Props, handles); err != nil {
			return err
		}
		b.WriteByte('\n')
		for _, p := range v.Pairs {
			if err := writeEvents(b, p.Key, handles); err != nil {
				return err
			}
			if err := writeEvents(b, p.Value, handles); err != nil {
				return err
			}
		}
		b.WriteString("-MAP\n")
	case *Sequence:
		b.WriteString("+SEQ")
		if v.Flow {
			b.WriteString(" []")
		}
		if err := writeProps(b, v.Props, handles); err != nil {
			return err
		}
		b.WriteByte('\n')
		for _, it := range v.Items {
			if err := writeEvents(b, it, handles); err != nil {
				return err
			}
		}
		b.WriteString("-SEQ\n")
	case *Scalar:
		b.WriteString("=VAL")
		if err := writeProps(b, v.Props, handles); err != nil {
			return err
		}
		b.WriteByte(' ')
		b.WriteByte(":'\"|>"[v.Style])
		for _, r := range v.Value() {
			switch r {
			case '\\':
				b.WriteString(`\\`)
			case 0:
				b.WriteString(`\0`)
			case '\b':
				b.WriteString(`\b`)
			case '\t':
				b.WriteString(`\t`)
			case '\n':
				b.WriteString(`\n`)
			case '\r':
				b.WriteString(`\r`)
			default:
				b.WriteRune(r)
			}
		}
		b.WriteByte('\n')
	case *Alias:
		b.WriteString("=ALI *")
		b.WriteString(v.Name())
		b.WriteByte('\n')
	}
	return nil
}

// Load parses input, which must hold at most one document, and returns the value of the document as
// LoadAll does, or nil for a stream without documents.
func Load(input string) (any, error) {
	vs, err := LoadAll(input)
	if err != nil {
		return nil, err
	}
	switch len(vs) {
	case 0:
		return nil, nil
	case 1:
		return vs[0], nil
	}
	return nil, fmt.Errorf("yaml: %d documents, expected one", len(vs))
}

// LoadAll parses input, checks it as Valid does, and returns the value of each document, composed with
// the YAML 1.2 core schema (10.3):
//
//   - a mapping is a map[string]any if all of its keys are strings, and a map[any]any otherwise; a key
//     that is a mapping or a sequence is an error, and so is a key that occurs twice;
//   - a sequence is a []any;
//   - a plain scalar without a tag is nil (null, Null, NULL, ~ or empty), a bool (true, True, TRUE,
//     false, False, FALSE), an int64 (decimal, 0o octal or 0x hexadecimal), a float64 (with .inf,
//     -.inf and .nan in the three cases) or a string; an integer outside the range of int64 is an error;
//   - a quoted or block scalar, and any scalar with the tag ! or !!str, is a string;
//   - the tags !!null, !!bool, !!int and !!float require a value that resolves to their type (or an int
//     for !!float), whatever its style, and !!map and !!seq a mapping and a sequence; other tags do not
//     change the value;
//   - an alias is the value of the node with the anchor, the same map or slice for a collection; an
//     alias of an undefined anchor, or of a node that contains the alias, is an error.
func LoadAll(input string) ([]any, error) {
	s, err := parseChecked(input)
	if err != nil {
		return nil, err
	}
	vs := make([]any, len(s.Documents))
	for i, d := range s.Documents {
		if vs[i], err = d.Load(); err != nil {
			return nil, err
		}
	}
	return vs, nil
}

// Load returns the value of the document (see LoadAll). It does not run Check, but reports the same
// errors in the document.
func (d *Document) Load() (any, error) {
	handles, err := d.tagHandles()
	if err != nil {
		return nil, err
	}
	c := composer{handles: handles, anchors: map[string]anchored{}}
	return c.value(d.Root)
}

type anchored struct {
	v    any
	done bool
}

type composer struct {
	handles map[string]string
	anchors map[string]anchored
}

func (c *composer) value(v Value) (any, error) {
	var p *Properties
	switch v := v.(type) {
	case *Mapping:
		p = v.Props
	case *Sequence:
		p = v.Props
	case *Scalar:
		p = v.Props
	case *Alias:
		a, ok := c.anchors[v.Name()]
		if !ok {
			return nil, errorAt(v.Span, "undefined alias "+v.Text)
		}
		if !a.done {
			return nil, errorAt(v.Span, "alias "+v.Text+" inside the node it refers to")
		}
		return a.v, nil
	}
	tag := ""
	if t := p.tag(); t != nil {
		var err error
		if tag, err = resolveTag(t, c.handles); err != nil {
			return nil, err
		}
	}
	anchor := p.anchor()
	if anchor != nil {
		c.anchors[anchor.Name()] = anchored{}
	}
	x, err := c.content(v, tag)
	if err != nil {
		return nil, err
	}
	if anchor != nil {
		c.anchors[anchor.Name()] = anchored{x, true}
	}
	return x, nil
}

func (c *composer) content(v Value, tag string) (any, error) {
	switch v := v.(type) {
	case *Mapping:
		if tag == CoreTagPrefix+"seq" || isCoreScalarTag(tag) {
			return nil, errorAt(v.Span, "a mapping with the tag "+tag)
		}
		return c.mapping(v)
	case *Sequence:
		if tag == CoreTagPrefix+"map" || isCoreScalarTag(tag) {
			return nil, errorAt(v.Span, "a sequence with the tag "+tag)
		}
		a := make([]any, len(v.Items))
		for i, it := range v.Items {
			x, err := c.value(it)
			if err != nil {
				return nil, err
			}
			a[i] = x
		}
		return a, nil
	case *Scalar:
		return scalarValue(v, tag)
	}
	return nil, fmt.Errorf("yaml: unexpected value %T", v)
}

func isCoreScalarTag(tag string) bool {
	switch strings.TrimPrefix(tag, CoreTagPrefix) {
	case "null", "bool", "int", "float", "str":
		return strings.HasPrefix(tag, CoreTagPrefix)
	}
	return false
}

func (c *composer) mapping(m *Mapping) (any, error) {
	keys := make([]any, len(m.Pairs))
	vals := make([]any, len(m.Pairs))
	allStrings := true
	for i, p := range m.Pairs {
		k, err := c.value(p.Key)
		if err != nil {
			return nil, err
		}
		switch k.(type) {
		case map[string]any, map[any]any, []any:
			return nil, errorAt(valueSpan(p.Key), "a collection as a mapping key")
		case string:
		default:
			allStrings = false
		}
		keys[i] = k
		if vals[i], err = c.value(p.Value); err != nil {
			return nil, err
		}
	}
	if allStrings {
		r := make(map[string]any, len(keys))
		for i, k := range keys {
			if _, dup := r[k.(string)]; dup {
				return nil, errorAt(valueSpan(m.Pairs[i].Key), fmt.Sprintf("duplicate key %q", k))
			}
			r[k.(string)] = vals[i]
		}
		return r, nil
	}
	r := make(map[any]any, len(keys))
	for i, k := range keys {
		if f, ok := k.(float64); ok && math.IsNaN(f) {
			return nil, errorAt(valueSpan(m.Pairs[i].Key), "NaN as a mapping key")
		}
		if _, dup := r[k]; dup {
			return nil, errorAt(valueSpan(m.Pairs[i].Key), fmt.Sprintf("duplicate key %v", k))
		}
		r[k] = vals[i]
	}
	return r, nil
}

func valueSpan(v Value) Span {
	switch v := v.(type) {
	case *Mapping:
		return v.Span
	case *Sequence:
		return v.Span
	case *Scalar:
		return v.Span
	case *Alias:
		return v.Span
	}
	return Span{}
}

// scalarValue resolves a scalar with the core schema.
func scalarValue(s *Scalar, tag string) (any, error) {
	text := s.Value()
	if tag == "" && s.Style == Plain {
		v := resolvePlain(text)
		if err, ok := v.(error); ok {
			return nil, errorAt(s.Span, err.Error())
		}
		return v, nil
	}
	if !strings.HasPrefix(tag, CoreTagPrefix) {
		return text, nil
	}
	want := tag[len(CoreTagPrefix):]
	switch want {
	case "str":
		return text, nil
	case "null", "bool", "int", "float":
		v := resolvePlain(text)
		ok := false
		switch v.(type) {
		case nil:
			ok = want == "null"
		case bool:
			ok = want == "bool"
		case int64:
			ok = want == "int"
			if want == "float" {
				return float64(v.(int64)), nil
			}
		case float64:
			ok = want == "float"
		}
		if !ok {
			if e, isErr := v.(error); isErr {
				return nil, errorAt(s.Span, e.Error())
			}
			return nil, errorAt(s.Span, fmt.Sprintf("%q is not a %s", text, want))
		}
		return v, nil
	case "map", "seq":
		return nil, errorAt(s.Span, "a scalar with the tag "+tag)
	}
	return text, nil
}

// resolvePlain resolves the text of a plain scalar with the core schema (10.3.2). An integer out of
// range resolves to an error value.
func resolvePlain(t string) any {
	switch t {
	case "", "~", "null", "Null", "NULL":
		return nil
	case "true", "True", "TRUE":
		return true
	case "false", "False", "FALSE":
		return false
	case ".inf", ".Inf", ".INF", "+.inf", "+.Inf", "+.INF":
		return math.Inf(1)
	case "-.inf", "-.Inf", "-.INF":
		return math.Inf(-1)
	case ".nan", ".NaN", ".NAN":
		return math.NaN()
	}
	c := t[0]
	if c != '-' && c != '+' && c != '.' && (c < '0' || c > '9') {
		return t
	}
	switch {
	case isInt(t, 0, 10):
		return parseInt(t, 0, 10)
	case strings.HasPrefix(t, "0o") && isInt(t, 2, 8):
		return parseInt(t, 2, 8)
	case strings.HasPrefix(t, "0x") && isInt(t, 2, 16):
		return parseInt(t, 2, 16)
	case isFloat(t):
		f, err := strconv.ParseFloat(t, 64)
		if err != nil && !errors.Is(err, strconv.ErrRange) {
			return t
		}
		return f
	}
	return t
}

// isInt reports whether t[from:] is an integer in the base: [-+]?[0-9]+ in base 10, digits only
// otherwise.
func isInt(t string, from, base int) bool {
	i := from
	if base == 10 && i < len(t) && (t[i] == '-' || t[i] == '+') {
		i++
	}
	if i == len(t) {
		return false
	}
	for ; i < len(t); i++ {
		c := t[i]
		switch {
		case c >= '0' && c <= '7':
		case c >= '8' && c <= '9' && base >= 10:
		case base == 16 && (c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F'):
		default:
			return false
		}
	}
	return true
}

func parseInt(t string, from, base int) any {
	v, err := strconv.ParseInt(t[from:], base, 64)
	if err != nil {
		return fmt.Errorf("integer %s out of range", t)
	}
	return v
}

// isFloat reports whether t matches [-+]? ( \. [0-9]+ | [0-9]+ ( \. [0-9]* )? ) ( [eE] [-+]? [0-9]+ )?
func isFloat(t string) bool {
	i := 0
	if t[i] == '-' || t[i] == '+' {
		i++
	}
	digits := func() int {
		j := i
		for i < len(t) && t[i] >= '0' && t[i] <= '9' {
			i++
		}
		return i - j
	}
	n := digits()
	if i < len(t) && t[i] == '.' {
		i++
		if digits() == 0 && n == 0 {
			return false
		}
	} else if n == 0 {
		return false
	}
	if i < len(t) && (t[i] == 'e' || t[i] == 'E') {
		i++
		if i < len(t) && (t[i] == '-' || t[i] == '+') {
			i++
		}
		if digits() == 0 {
			return false
		}
	}
	return i == len(t)
}
