// Package python parses Python 3.14 as CPython 3.14.0 parses it, with a parser generated by PEGO
// from python.pego. It depends only on the standard library.
//
// ParseModule parses a module (a file of Python source, as ast.parse does with mode "exec") into a
// typed AST modeled on Python's ast module: *Module holds Stmt values (*FunctionDef, *If, ...) that
// hold Expr values (*BinOp, *Call, ...), and every node embeds a Span, the positions of its text
// in code points (or bytes: pass Bytes). ParseAST is the parser alone, Recognize only checks the
// syntax and Parse returns the generic tree of *Node.
//
// The AST differs from Python's in a few ways, so as to stay a tree of the source: identifiers
// are strings, with "" for Python's None (NormalizeName gives the NFKC form that Python uses);
// ctx is "Load", "Store" or "Del"; operators are *Op holding their source text (OpName gives
// Python's class name); the values of constants and the literal parts of f-strings are source text
// (Constant.Value, FStringMiddle.Value and the like decode them: integers, floats, strings with
// their escapes, concatenated adjacent literals, and so on); FormattedValue and Interpolation keep
// the text of their expression, '=' and conversion; Python's List, Match and Expr are ListExpr,
// MatchStmt and ExprStmt. Dump prints a tree as ast.dump does, and DumpWithPositions with
// positions as CPython computes them (see LineIndex).
//
// # Conformance
//
// The parser accepts the programs that CPython 3.14.0's ast.parse accepts, and rejects the others,
// including the whole language: PEP 695 type parameters and defaults, match statements, except*,
// f-strings of PEP 701, t-strings of PEP 750, unparenthesized except lists (PEP 758) and the rules
// of the tokenizer for indentation (with its tab rules), line continuations, brackets, numbers
// and identifiers (Unicode 16.0). Compared with CPython, the trees (ast.dump) and the positions of
// every node were the same on all the 1,055 files of the installed standard library, 1,112 files
// of CPython's Lib/test, and 26,199 of the 61,540 snippets of code in the strings and doctests of
// Lib/test that CPython accepts; the other 35,341 snippets are rejected by both. The tests also
// compare on random mutations of the snippets and on random line structures. The README of the
// module has the numbers and the commands.
//
// # Deviations
//
//   - Check, which ParseModule calls, makes what CPython checks outside its grammar: names in
//     \N{...} escapes, the limit of 4300 digits of an integer literal, `from __future__` imports
//     of features that do not exist, identifiers that normalize to None, True or False, and the
//     choice between '!=' and '<>' (after `from __future__ import barry_as_FLUFL`). ParseAST does
//     not make these checks.
//   - Only the accepted programs are compared with CPython. The errors are *SyntaxError values
//     with the position and either what was expected or a short message ("invalid syntax",
//     "unexpected indent"); CPython's messages, from the second pass of its parser, are not
//     reproduced, and neither are its error classes (TabError, IndentationError) and positions.
//   - The input is text, as for ast.parse(str): no encoding declaration or byte order mark is
//     read, and invalid UTF-8 is read as U+FFFD (accepted in strings and comments only).
//   - Only mode "exec", with no type comments and no feature version.
//   - Nesting: brackets 200 deep and blocks 99 deep are the limits of CPython. CPython also
//     rejects expressions that need a very deep parse stack (thousands of nested `not`, lambdas or
//     conditionals, and chains of 20,000 operators); this parser accepts them up to the generated
//     parser's limit of 100,000 rule calls (about 30,000 levels of `not`), and then fails with an
//     error.
//   - The Spans of the AST do not always match CPython's positions: those of a binary operation,
//     attribute, subscript or call do not include the parentheses of an operand at their edge,
//     the span of a decorated definition starts at its first decorator, and that of a compound
//     statement stops before a ';' that ends its last line (CPython's includes it).
//     DumpWithPositions computes CPython's from the source.
package python

import (
	"fmt"
	"reflect"
	"strings"
	"unicode/utf8"
)

// ParseModule parses a module (a file of Python source) like ParseAST and then makes the checks
// that CPython's ast.parse makes outside its grammar (see Check).
func ParseModule(src string, unit ...Unit) (*Module, error) {
	m, err := ParseAST(src, unitOptions(unit)...)
	if err != nil {
		return nil, err
	}
	if err := Check(m, src, unit...); err != nil {
		return nil, err
	}
	return m, nil
}

// Check makes the checks of ast.parse that the grammar does not make, on a module returned by
// ParseAST for src:
//
//   - the names in \N{...} escapes must be names (or aliases) of characters;
//   - a decimal integer literal may have at most 4300 digits (CPython's default limit of
//     sys.set_int_max_str_digits);
//   - the `from __future__ import` statements at the start of the module (after the docstring)
//     must name features that exist ("braces" is "not a chance");
//   - the inequality operator is '!=', or '<>' after `from __future__ import barry_as_FLUFL` (the
//     grammar accepts both).
func Check(m *Module, src string, unit ...Unit) error {
	pos := func(off int) *SyntaxError {
		line, col := 1, 1
		i := 0
		for n := 0; i < len(src) && n < off; n++ {
			r, size := utf8.DecodeRuneInString(src[i:])
			if len(unit) > 0 && unit[0] == Bytes {
				n += size - 1
			}
			if r == '\n' {
				line, col = line+1, 1
			} else {
				col++
			}
			i += size
		}
		return &SyntaxError{Pos: off, Line: line, Col: col}
	}
	fail := func(off int, format string, args ...any) error {
		e := pos(off)
		e.Messages = []string{fmt.Sprintf(format, args...)}
		return e
	}
	if err := checkFuture(m, fail); err != nil {
		return err
	}
	if strings.Contains(src, "<>") || strings.Contains(src, "barry_as_FLUFL") {
		if err := checkBarry(m, fail); err != nil {
			return err
		}
	}
	ascii := isASCII(src)
	if ascii && !strings.Contains(src, `\N{`) && !hasLongDigits(src) {
		return nil
	}
	var err error
	Inspect(m, func(n any) bool {
		if err != nil {
			return false
		}
		if !ascii {
			for _, id := range identifiersOf(n) {
				switch NormalizeName(id) {
				case "None", "True", "False":
					err = fail(nodeSpan(n).Start, "identifier field can't represent '%s' constant", NormalizeName(id))
					return false
				}
			}
		}
		switch n := n.(type) {
		case *Constant:
			v, e := constValue(n.Text)
			switch {
			case e != nil:
				err = fail(n.Start, "%s", strings.TrimPrefix(e.Error(), "python: "))
			case v.kind == kInt && isDecimal(n.Text):
				if d := len(v.i.String()); d > 4300 {
					err = fail(n.Start, "Exceeds the limit (4300 digits) for integer string conversion: value has %d digits", d)
				}
			}
		case *FStringMiddle:
			if _, e := decodeFStringText(n.Text, false); e != nil {
				err = fail(n.Start, "%s", strings.TrimPrefix(e.Error(), "python: "))
			}
		}
		return true
	})
	return err
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= utf8.RuneSelf {
			return false
		}
	}
	return true
}

// nodeSpan returns the span of a node of the AST.
func nodeSpan(n any) Span {
	if v := reflect.ValueOf(n); v.Kind() == reflect.Pointer && !v.IsNil() {
		if f := v.Elem().FieldByName("Span"); f.IsValid() {
			return f.Interface().(Span)
		}
	}
	return Span{}
}

// identifiersOf returns the identifiers that a node holds in fields of its own.
func identifiersOf(n any) []string {
	switch n := n.(type) {
	case *Name:
		return []string{n.Id}
	case *Attribute:
		return []string{n.Attr}
	case *FunctionDef:
		return []string{n.Name}
	case *AsyncFunctionDef:
		return []string{n.Name}
	case *ClassDef:
		return []string{n.Name}
	case *Arg:
		return []string{n.Arg}
	case *Keyword:
		return []string{n.Arg}
	case *Alias:
		return append(strings.Split(n.Name, "."), n.AsName)
	case *ImportFrom:
		return strings.Split(n.Module, ".")
	case *ExceptHandler:
		return []string{n.Name}
	case *MatchAs:
		return []string{n.Name}
	case *MatchStar:
		return []string{n.Name}
	case *MatchMapping:
		return []string{n.Rest}
	case *Identifier:
		return []string{n.Text}
	case *TypeVar:
		return []string{n.Name}
	case *ParamSpec:
		return []string{n.Name}
	case *TypeVarTuple:
		return []string{n.Name}
	}
	return nil
}

func isDecimal(lit string) bool {
	return !strings.ContainsAny(lit, ".eEjJxXoObB")
}

// hasLongDigits reports whether src has a run of more than 4300 digits (and underscores).
func hasLongDigits(src string) bool {
	n := 0
	for i := 0; i < len(src); i++ {
		if c := src[i]; c >= '0' && c <= '9' || c == '_' {
			if n++; n > 4300 {
				return true
			}
		} else {
			n = 0
		}
	}
	return false
}

// The features of __future__ (Lib/__future__.py), and "braces".
var futureFeatures = map[string]bool{"nested_scopes": true, "generators": true, "division": true,
	"absolute_import": true, "with_statement": true, "print_function": true, "unicode_literals": true,
	"barry_as_FLUFL": true, "generator_stop": true, "annotations": true}

// checkFuture checks the future statements at the start of the module, after its docstring, as
// CPython's future.c does.
func checkFuture(m *Module, fail func(int, string, ...any) error) error {
	body := m.Body
	if len(body) > 0 {
		if e, ok := body[0].(*ExprStmt); ok {
			if c, ok := e.Value.(*Constant); ok && c.Text != "" && strings.ContainsAny(c.Text[:1], "'\"rRuU") {
				if v, err := constValue(c.Text); err == nil && v.kind == kStr {
					body = body[1:]
				}
			}
		}
	}
	for _, s := range body {
		imp, ok := s.(*ImportFrom)
		if !ok || imp.Level != 0 || imp.Module != "__future__" {
			return nil
		}
		for _, a := range imp.Names {
			switch {
			case a.Name == "braces":
				return fail(a.Start, "not a chance")
			case !futureFeatures[a.Name]:
				return fail(a.Start, "future feature %s is not defined", a.Name)
			}
		}
	}
	return nil
}

// checkBarry checks the inequality operators: '<>' is an error, unless it comes after `from
// __future__ import barry_as_FLUFL`, and then '!=' is the error.
func checkBarry(m *Module, fail func(int, string, ...any) error) error {
	barry := -1 // the end of the first import of barry_as_FLUFL
	var ops []*Op
	Inspect(m, func(n any) bool {
		switch n := n.(type) {
		case *ImportFrom:
			if n.Level == 0 && n.Module == "__future__" {
				for _, a := range n.Names {
					if a.Name == "barry_as_FLUFL" && (barry < 0 || n.End < barry) {
						barry = n.End
					}
				}
			}
		case *Compare:
			for _, o := range n.Ops {
				if o.Text == "<>" || o.Text == "!=" {
					ops = append(ops, o)
				}
			}
		}
		return true
	})
	for _, o := range ops {
		after := barry >= 0 && o.Start >= barry
		switch {
		case o.Text == "<>" && !after:
			return fail(o.Start, "invalid syntax")
		case o.Text == "!=" && after:
			return fail(o.Start, "with Barry as BDFL, use '<>' instead of '!='")
		}
	}
	return nil
}

// Inspect traverses the tree of node in depth-first order: it calls f(n) for each node n (a
// pointer to a struct or terminal type of this package), and then, if f returns true, for each of
// its children in the order of their fields.
func Inspect(node any, f func(node any) bool) {
	inspect(reflect.ValueOf(node), f)
}

func inspect(v reflect.Value, f func(any) bool) {
	switch v.Kind() {
	case reflect.Interface:
		if !v.IsNil() {
			inspect(v.Elem(), f)
		}
	case reflect.Pointer:
		if v.IsNil() || v.Elem().Kind() != reflect.Struct {
			return
		}
		if !f(v.Interface()) {
			return
		}
		s := v.Elem()
		for i := 0; i < s.NumField(); i++ {
			switch fv := s.Field(i); fv.Kind() {
			case reflect.Interface, reflect.Pointer, reflect.Slice:
				inspect(fv, f)
			}
		}
	case reflect.Slice:
		for i := 0; i < v.Len(); i++ {
			inspect(v.Index(i), f)
		}
	}
}

// unitOptions preserves the first-unit policy of the handwritten convenience API.
func unitOptions(units []Unit) []ParseOption {
	if len(units) == 0 {
		return nil
	}
	return []ParseOption{WithUnit(units[0])}
}
