// Package python parses Python 3.14 with a parser generated by PEGO from python.pego.
package python

import (
	"fmt"
	"reflect"
	"strings"
	"unicode/utf8"
)

// ParseModule parses a module (a file of Python source) like ParseAST and then makes the checks
// that CPython's ast.parse makes outside its grammar (see Check).
func ParseModule(src string, unit ...Unit) (*Module, error) {
	m, err := ParseAST(src, unit...)
	if err != nil {
		return nil, err
	}
	if err := Check(m, src, unit...); err != nil {
		return nil, err
	}
	return m, nil
}

// Check makes the checks of ast.parse that the grammar does not make, on a module returned by
// ParseAST for src:
//
//   - the names in \N{...} escapes must be names (or aliases) of characters;
//   - a decimal integer literal may have at most 4300 digits (CPython's default limit of
//     sys.set_int_max_str_digits);
//   - the `from __future__ import` statements at the start of the module (after the docstring)
//     must name features that exist ("braces" is "not a chance").
func Check(m *Module, src string, unit ...Unit) error {
	pos := func(off int) *SyntaxError {
		line, col := 1, 1
		i := 0
		for n := 0; i < len(src) && n < off; n++ {
			r, size := utf8.DecodeRuneInString(src[i:])
			if len(unit) > 0 && unit[0] == Bytes {
				n += size - 1
			}
			if r == '\n' {
				line, col = line+1, 1
			} else {
				col++
			}
			i += size
		}
		return &SyntaxError{Pos: off, Line: line, Col: col}
	}
	fail := func(off int, format string, args ...any) error {
		e := pos(off)
		e.Messages = []string{fmt.Sprintf(format, args...)}
		return e
	}
	if err := checkFuture(m, fail); err != nil {
		return err
	}
	ascii := isASCII(src)
	if ascii && !strings.Contains(src, `\N{`) && !hasLongDigits(src) {
		return nil
	}
	var err error
	Inspect(m, func(n any) bool {
		if err != nil {
			return false
		}
		if !ascii {
			for _, id := range identifiersOf(n) {
				switch NormalizeName(id) {
				case "None", "True", "False":
					err = fail(nodeSpan(n).Start, "identifier field can't represent '%s' constant", NormalizeName(id))
					return false
				}
			}
		}
		switch n := n.(type) {
		case *Constant:
			v, e := constValue(n.Text)
			switch {
			case e != nil:
				err = fail(n.Start, "%s", strings.TrimPrefix(e.Error(), "python: "))
			case v.kind == kInt && isDecimal(n.Text):
				if d := len(v.i.String()); d > 4300 {
					err = fail(n.Start, "Exceeds the limit (4300 digits) for integer string conversion: value has %d digits", d)
				}
			}
		case *FStringMiddle:
			if _, e := decodeFStringText(n.Text, false); e != nil {
				err = fail(n.Start, "%s", strings.TrimPrefix(e.Error(), "python: "))
			}
		}
		return true
	})
	return err
}

func isASCII(s string) bool {
	for i := 0; i < len(s); i++ {
		if s[i] >= utf8.RuneSelf {
			return false
		}
	}
	return true
}

// nodeSpan returns the span of a node of the AST.
func nodeSpan(n any) Span {
	if v := reflect.ValueOf(n); v.Kind() == reflect.Pointer && !v.IsNil() {
		if f := v.Elem().FieldByName("Span"); f.IsValid() {
			return f.Interface().(Span)
		}
	}
	return Span{}
}

// identifiersOf returns the identifiers that a node holds in fields of its own.
func identifiersOf(n any) []string {
	switch n := n.(type) {
	case *Name:
		return []string{n.Id}
	case *Attribute:
		return []string{n.Attr}
	case *FunctionDef:
		return []string{n.Name}
	case *AsyncFunctionDef:
		return []string{n.Name}
	case *ClassDef:
		return []string{n.Name}
	case *Arg:
		return []string{n.Arg}
	case *Keyword:
		return []string{n.Arg}
	case *Alias:
		return append(strings.Split(n.Name, "."), n.AsName)
	case *ImportFrom:
		return strings.Split(n.Module, ".")
	case *ExceptHandler:
		return []string{n.Name}
	case *MatchAs:
		return []string{n.Name}
	case *MatchStar:
		return []string{n.Name}
	case *MatchMapping:
		return []string{n.Rest}
	case *Identifier:
		return []string{n.Text}
	case *TypeVar:
		return []string{n.Name}
	case *ParamSpec:
		return []string{n.Name}
	case *TypeVarTuple:
		return []string{n.Name}
	}
	return nil
}

func isDecimal(lit string) bool {
	return !strings.ContainsAny(lit, ".eEjJxXoObB")
}

// hasLongDigits reports whether src has a run of more than 4300 digits (and underscores).
func hasLongDigits(src string) bool {
	n := 0
	for i := 0; i < len(src); i++ {
		if c := src[i]; c >= '0' && c <= '9' || c == '_' {
			if n++; n > 4300 {
				return true
			}
		} else {
			n = 0
		}
	}
	return false
}

// The features of __future__ (Lib/__future__.py), and "braces".
var futureFeatures = map[string]bool{"nested_scopes": true, "generators": true, "division": true,
	"absolute_import": true, "with_statement": true, "print_function": true, "unicode_literals": true,
	"barry_as_FLUFL": true, "generator_stop": true, "annotations": true}

// checkFuture checks the future statements at the start of the module, after its docstring, as
// CPython's future.c does.
func checkFuture(m *Module, fail func(int, string, ...any) error) error {
	body := m.Body
	if len(body) > 0 {
		if e, ok := body[0].(*ExprStmt); ok {
			if c, ok := e.Value.(*Constant); ok && c.Text != "" && strings.ContainsAny(c.Text[:1], "'\"rRuU") {
				if v, err := constValue(c.Text); err == nil && v.kind == kStr {
					body = body[1:]
				}
			}
		}
	}
	for _, s := range body {
		imp, ok := s.(*ImportFrom)
		if !ok || imp.Level != 0 || imp.Module != "__future__" {
			return nil
		}
		for _, a := range imp.Names {
			switch {
			case a.Name == "braces":
				return fail(a.Start, "not a chance")
			case !futureFeatures[a.Name]:
				return fail(a.Start, "future feature %s is not defined", a.Name)
			}
		}
	}
	return nil
}

// Inspect traverses the tree of node in depth-first order: it calls f(n) for each node n (a
// pointer to a struct or terminal type of this package), and then, if f returns true, for each of
// its children in the order of their fields.
func Inspect(node any, f func(node any) bool) {
	inspect(reflect.ValueOf(node), f)
}

func inspect(v reflect.Value, f func(any) bool) {
	switch v.Kind() {
	case reflect.Interface:
		if !v.IsNil() {
			inspect(v.Elem(), f)
		}
	case reflect.Pointer:
		if v.IsNil() || v.Elem().Kind() != reflect.Struct {
			return
		}
		if !f(v.Interface()) {
			return
		}
		s := v.Elem()
		for i := 0; i < s.NumField(); i++ {
			switch fv := s.Field(i); fv.Kind() {
			case reflect.Interface, reflect.Pointer, reflect.Slice:
				inspect(fv, f)
			}
		}
	case reflect.Slice:
		for i := 0; i < v.Len(); i++ {
			inspect(v.Index(i), f)
		}
	}
}
