package python

import (
	"bytes"
	"compress/zlib"
	_ "embed"
	"fmt"
	"io"
	"strconv"
	"strings"
	"sync"
)

// runeRange is an inclusive range of code points.
type runeRange struct{ lo, hi rune }

// hexName is a family of character names of the form Prefix-XXXX.
type hexName struct {
	prefix string
	ranges []runeRange
}

func inRanges(r rune, rs []runeRange) bool {
	lo, hi := 0, len(rs)
	for lo < hi {
		m := (lo + hi) / 2
		switch {
		case r < rs[m].lo:
			hi = m
		case r > rs[m].hi:
			lo = m + 1
		default:
			return true
		}
	}
	return false
}

// isPrintable reports whether str.isprintable() holds for r.
func isPrintable(r rune) bool {
	if r < 0x80 {
		return r >= 0x20 && r < 0x7f
	}
	return !inRanges(r, nonPrintable)
}

// The character names and aliases that \N{...} accepts, and the data of NFKC normalization,
// generated by tools/gentables.py. It is read when it is first needed.
//
//go:embed unicode.bin
var unicodeZ []byte

var (
	unicodeOnce sync.Once
	names       map[string]rune  // names and aliases, in upper case
	nfkd        map[rune][]rune  // compatibility decompositions of identifier characters
	ccc         map[rune]uint8   // canonical combining classes other than 0
	compose     map[[2]rune]rune // canonical compositions
)

func loadUnicode() {
	names, nfkd, ccc, compose = map[string]rune{}, map[rune][]rune{}, map[rune]uint8{}, map[[2]rune]rune{}
	r, err := zlib.NewReader(bytes.NewReader(unicodeZ))
	if err != nil {
		panic(err)
	}
	data, err := io.ReadAll(r)
	if err != nil {
		panic(err)
	}
	hexes := func(s string) []rune {
		var rs []rune
		for _, f := range strings.Fields(s) {
			v, err := strconv.ParseUint(f, 16, 32)
			if err != nil {
				panic(err)
			}
			rs = append(rs, rune(v))
		}
		return rs
	}
	for _, line := range strings.Split(string(data), "\n") {
		f := strings.Split(line, "\t")
		if len(f) != 3 {
			continue
		}
		switch f[0] {
		case "N":
			names[f[1]] = hexes(f[2])[0]
		case "D":
			nfkd[hexes(f[1])[0]] = hexes(f[2])
		case "C":
			v, _ := strconv.Atoi(f[2])
			ccc[hexes(f[1])[0]] = uint8(v)
		case "P":
			p := hexes(f[1])
			compose[[2]rune{p[0], p[1]}] = hexes(f[2])[0]
		}
	}
}

// Jamo short names, for the names of Hangul syllables.
var (
	jamoL = []string{"G", "GG", "N", "D", "DD", "R", "M", "B", "BB", "S", "SS", "", "J", "JJ", "C", "K", "T", "P", "H"}
	jamoV = []string{"A", "AE", "YA", "YAE", "EO", "E", "YEO", "YE", "O", "WA", "WAE", "OE", "YO", "U", "WEO", "WE", "WI",
		"YU", "EU", "YI", "I"}
	jamoT = []string{"", "G", "GG", "GS", "N", "NJ", "NH", "D", "L", "LG", "LM", "LB", "LS", "LT", "LP", "LH", "M", "B",
		"BS", "S", "SS", "NG", "J", "C", "K", "T", "P", "H"}
)

// lookupName returns the character a \N{name} escape stands for, as CPython's unicode-escape
// codec resolves it: names and aliases (not named sequences) without regard to case, except that
// Hangul syllables and CJK unified ideographs, which CPython computes, need upper-case jamo and
// hexadecimal digits.
func lookupName(name string) (rune, bool) {
	upper := strings.ToUpper(name)
	if strings.HasPrefix(upper, "HANGUL SYLLABLE ") {
		return hangulSyllable(name[len("HANGUL SYLLABLE "):])
	}
	if strings.HasPrefix(upper, "CJK UNIFIED IDEOGRAPH-") {
		h := name[len("CJK UNIFIED IDEOGRAPH-"):]
		if len(h) != 4 && len(h) != 5 || strings.ToUpper(h) != h {
			return 0, false
		}
		v, err := strconv.ParseUint(h, 16, 32)
		if err != nil || !inRanges(rune(v), hexNames[0].ranges) {
			return 0, false
		}
		return rune(v), true
	}
	for _, hn := range hexNames[1:] {
		if h, ok := strings.CutPrefix(upper, hn.prefix+"-"); ok {
			v, err := strconv.ParseUint(h, 16, 32)
			if err != nil || !inRanges(rune(v), hn.ranges) || fmt.Sprintf("%04X", v) != h {
				return 0, false
			}
			return rune(v), true
		}
	}
	unicodeOnce.Do(loadUnicode)
	r, ok := names[upper]
	return r, ok
}

func hangulSyllable(s string) (rune, bool) {
	find := func(s string, names []string) (int, int) {
		best, n := -1, -1
		for i, x := range names {
			if len(x) > n && strings.HasPrefix(s, x) {
				best, n = i, len(x)
			}
		}
		return best, n
	}
	l, n := find(s, jamoL)
	s = s[n:]
	v, n := find(s, jamoV)
	if v < 0 {
		return 0, false
	}
	s = s[n:]
	t, n := find(s, jamoT)
	if l < 0 || t < 0 || n != len(s) {
		return 0, false
	}
	return rune(0xAC00 + (l*21+v)*28 + t), true
}

// Hangul syllables (algorithmic decomposition and composition).
const (
	hangulS, hangulL, hangulV, hangulT                     = 0xAC00, 0x1100, 0x1161, 0x11A7
	hangulLCount, hangulVCount, hangulTCount, hangulSCount = 19, 21, 28, 11172
)

// NormalizeName returns the identifier as Python's ast module has it: normalized with NFKC
// (identifiers in this package's AST are as written). An ASCII name is returned as is.
func NormalizeName(name string) string {
	ascii := true
	for i := 0; i < len(name); i++ {
		if name[i] >= 0x80 {
			ascii = false
			break
		}
	}
	if ascii {
		return name
	}
	unicodeOnce.Do(loadUnicode)
	// Decompose.
	var d []rune
	for _, r := range name {
		switch {
		case r >= hangulS && r < hangulS+hangulSCount:
			s := r - hangulS
			d = append(d, hangulL+s/(hangulVCount*hangulTCount), hangulV+s%(hangulVCount*hangulTCount)/hangulTCount)
			if t := s % hangulTCount; t != 0 {
				d = append(d, hangulT+t)
			}
		case nfkd[r] != nil:
			d = append(d, nfkd[r]...)
		default:
			d = append(d, r)
		}
	}
	// Order the combining marks of each run by their combining class.
	for i := 1; i < len(d); i++ {
		for j := i; j > 0 && ccc[d[j]] != 0 && ccc[d[j-1]] > ccc[d[j]]; j-- {
			d[j], d[j-1] = d[j-1], d[j]
		}
	}
	// Compose.
	out := d[:0:0]
	starter, last := -1, -1
	for _, r := range d {
		c := int(ccc[r])
		if starter >= 0 && (len(out)-1 == starter || last < c) {
			if x, ok := composePair(out[starter], r); ok {
				out[starter] = x
				continue
			}
		}
		if c == 0 {
			starter = len(out)
		}
		last = c
		out = append(out, r)
	}
	return string(out)
}

func composePair(a, b rune) (rune, bool) {
	switch {
	case a >= hangulL && a < hangulL+hangulLCount && b >= hangulV && b < hangulV+hangulVCount:
		return hangulS + ((a-hangulL)*hangulVCount+(b-hangulV))*hangulTCount, true
	case a >= hangulS && a < hangulS+hangulSCount && (a-hangulS)%hangulTCount == 0 && b > hangulT && b < hangulT+hangulTCount:
		return a + (b - hangulT), true
	}
	x, ok := compose[[2]rune{a, b}]
	return x, ok
}
