package engine

import (
	_ "embed"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode/utf8"

	"github.com/ornew/pego/grammar"
)

//go:embed genrt/runtime.go
var runtimeSource string

//go:embed genrt/typed.go
var typedSource string

// GenOptions configures code generation.
type GenOptions struct {
	// Package is the package name of the generated code.
	Package string
	// Start is the start rule of the generated Parse function.
	Start string
	// Types also generates a Go type for each type of the grammar and ParseAST, which returns the
	// result as values of those types (see gen_types.go).
	Types bool
	// Recognize also generates Recognize, which checks the input without building a tree (as the
	// engine's ParseOptions.Recognize does).
	Recognize bool
	// OmitPackageDoc leaves out the package comment, for a package that documents itself in another
	// file.
	OmitPackageDoc bool
	// convertTypes makes ParseAST convert the result of Parse even when the typed runtime could
	// build it (for tests).
	convertTypes bool
}

// Generate generates the source code of a Go parser for a grammar.
//
// The generated code depends only on the standard library. Each parsing expression becomes a Go method and
// actions and predicates become Go expressions; the embedded runtime (genrt) behaves exactly like the engine
// in this package. Stream and incremental parsing are not generated (#stream becomes a plain repetition).
func Generate(g *grammar.Grammar, opts GenOptions) ([]byte, error) {
	prog, err := Compile(g, Options{})
	if err != nil {
		return nil, err
	}
	start := prog.byName[opts.Start]
	if start == nil {
		return nil, fmt.Errorf("start rule %s is not defined", opts.Start)
	}
	if opts.Package == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if !token.IsIdentifier(opts.Package) || opts.Package == "_" {
		return nil, fmt.Errorf("invalid package name %q", opts.Package)
	}
	gen := &generator{prog: prog, table: "rules"}
	gen.desc(fixedDescs[0]) // the fixed expectations come first
	gen.rules()
	var rec *Program
	if opts.Recognize {
		// The recognizer: the program in which no rule builds a value (Program.recognizer), in a
		// rule table of its own.
		if rec, err = prog.recognizer(); err != nil {
			return nil, err
		}
		gen.prog, gen.table = rec, "recRules"
		gen.rules()
		gen.prog, gen.table = prog, "rules"
	}
	fmt.Fprintf(&gen.init, "\tdescs = %s\n", goStrings(gen.descs))

	var out strings.Builder
	out.WriteString("// Code generated by pego. DO NOT EDIT.\n\n")
	if !opts.OmitPackageDoc {
		fmt.Fprintf(&out, "// Package %s is a parser generated from a PEGO grammar.\n", opts.Package)
	}
	rt := runtimeSource[strings.Index(runtimeSource, "package genrt"):]
	rt = strings.Replace(rt, "package genrt", "package "+opts.Package, 1)
	out.WriteString(rt)
	out.WriteString("\n// --- Generated code ---\n\n")
	fmt.Fprintf(&out, "// Parse parses the whole input with the rule %s. unit selects the position unit (CodePoints by default).\n", start.name)
	out.WriteString("// If the parse recovered from errors with #recover, it returns the node together with SyntaxErrors.\n")
	fmt.Fprintf(&out, "func Parse(input string, unit ...Unit) (*Node, error) { return parse(rules[%d], nseen, input, unit) }\n\n", start.id)
	if rec != nil {
		fmt.Fprintf(&out, "// Recognize checks that the whole input matches the rule %s without building a tree, and returns the\n", start.name)
		out.WriteString("// syntax errors Parse would return (SyntaxErrors for errors recovered with #recover). Actions are not\n// evaluated, so it does not report runtime errors in actions.\n")
		fmt.Fprintf(&out, "func Recognize(input string, unit ...Unit) error {\n\t_, err := parse(recRules[%d], recNseen, input, unit)\n\treturn err\n}\n\n", rec.byName[start.name].id)
		out.WriteString("// recRules is the rule table of Recognize, and recNseen its number of rules with rule.seen set.\nvar recRules []*rule\nvar recNseen int\n\n")
	}
	out.WriteString(`// ParseRule parses the whole input with the rule name.
func ParseRule(name, input string, unit ...Unit) (*Node, error) {
	r := ruleByName(name)
	if r == nil {
		return nil, fmt.Errorf("rule %s is not defined", name)
	}
	return parse(r, nseen, input, unit)
}

`)
	if opts.Types {
		typed, span, err := gen.typedGo(start, opts.convertTypes)
		if err != nil {
			return nil, err
		}
		// The typed runtime's imports (fmt and sync) join those of the runtime.
		rt := typedSource[strings.Index(typedSource, "\n)\n")+len("\n)\n"):]
		if span != "Span" {
			rt = regexp.MustCompile(`\bSpan\b`).ReplaceAllString(rt, span)
		}
		out.WriteString("\n// --- Typed runtime ---\n")
		out.WriteString(rt)
		out.WriteString("\n")
		out.WriteString(typed)
		out.WriteString("\n")
	}
	out.WriteString(gen.vars.String())
	out.WriteString("\nfunc init() {\n")
	out.WriteString(gen.init.String())
	out.WriteString("}\n\n")
	out.WriteString(gen.methods.String())
	src, err := format.Source([]byte(out.String()))
	if err != nil {
		return []byte(out.String()), fmt.Errorf("generated code does not compile: %w", err)
	}
	return src, nil
}

type generator struct {
	prog  *Program
	table string // the rule table being generated: rules, or recRules for Recognize
	cur   *rule  // the rule being generated
	// proj holds the projected repetition captures of the rule being generated (projections).
	proj map[string]string
	// final is the struct constructor that makes an action's result in the typed runtime: its
	// range is the rule's (see tctx.result), so it computes none and is not recorded as created.
	final grammar.Term
	// caps maps capture names to the Go variables that hold them in a direct rule of the typed
	// runtime (see gen_direct.go), instead of frame slots.
	caps    map[string]string
	vars    strings.Builder
	init    strings.Builder
	methods strings.Builder
	n       int
	// descs is the expectation table of the generated parser (descs in genrt); descIDs maps a
	// description to its ID.
	descs   []string
	descIDs map[string]expID
}

// desc returns the expectation ID of description s, adding it to the table.
func (g *generator) desc(s string) expID {
	if g.descIDs == nil {
		g.descIDs = map[string]expID{}
		for i, d := range fixedDescs {
			g.descs = append(g.descs, d)
			g.descIDs[d] = expID(i)
		}
	}
	if id, ok := g.descIDs[s]; ok {
		return id
	}
	id := expID(len(g.descs))
	g.descs = append(g.descs, s)
	g.descIDs[s] = id
	return id
}

func (g *generator) name(prefix string) string {
	g.n++
	return fmt.Sprintf("%s%d", prefix, g.n)
}

func goStrings(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = strconv.Quote(x)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func (g *generator) rules() {
	init := &g.init
	bodies := map[*rule]string{}
	scopes := map[*rule]*scope{}
	directs := map[*rule]*direct{}
	all := append(append([]*rule(nil), g.prog.rules...), g.prog.twins...)
	for _, r := range all {
		s := newScope()
		scopes[r] = s
		if g.table == "trules" {
			// A rule compiled into the method that calls it has no body of its own.
			if d := g.directRule(r); d != nil {
				directs[r] = d
				continue
			}
		}
		if _, ok := r.def.Expr.(*grammar.Pratt); !ok {
			g.cur, g.proj = r, g.projections(r)
			bodies[r] = g.expr(r.def.Expr, s, !r.lean)
			g.proj = nil
		}
	}
	if g.table == "trules" {
		// The typed rules share the analysis results of the rules.
		init.WriteString("\ttrules = []*trule{\n")
		for _, r := range all {
			fmt.Fprintf(init, "\t\t{rule: rules[%d]},\n", r.id)
		}
		init.WriteString("\t}\n\tdefer tinit()\n")
	} else {
		fmt.Fprintf(init, "\t%s = []*rule{\n", g.table)
		for _, r := range all {
			fmt.Fprintf(init, "\t\t{id: %d, name: %q, scope: %s, bodyIsSeq: %v, terminalType: %q, memo: %v, leader: %v, seen: %d, novalue: %v, vars: %s},\n",
				r.id, r.name, goStrings(scopes[r].names), r.bodyIsSeq, r.terminalType, r.memo && !r.transient, r.leader, r.seen, r.novalue, goStrings(r.vars))
		}
		init.WriteString("\t}\n")
		fmt.Fprintf(init, "\tfor _, r := range %s {\n\t\tr.kinds = newRuleKinds(r.name, r.terminalType)\n\t}\n", g.table)
		fmt.Fprintf(init, "\t%s = %d\n", g.seenVar(), g.prog.nseen)
	}
	for _, r := range all {
		if pr, ok := r.def.Expr.(*grammar.Pratt); ok {
			g.cur = r
			g.pratt(r, pr)
			continue
		}
		if d := directs[r]; d != nil {
			g.typedCall(r, "", scopes[r], d)
			continue
		}
		fmt.Fprintf(init, "\t%s[%d].body = func(p *%s, _ int) (%s, bool) { return p.%s() }\n", g.table, r.id, g.recv(), g.valType(), bodies[r])
		if r.action != nil && g.table == "trules" {
			// A function of its own, which typedCall calls directly.
			g.proj, g.final = g.projections(r), r.action
			fmt.Fprintf(&g.methods, "// The action of %s.\nfunc ta%d(c *tctx) any { return %s }\n\n", r.name, r.id, g.term(r.action, scopes[r], nil))
			g.proj, g.final = nil, nil
			fmt.Fprintf(init, "\ttrules[%d].action = ta%d\n", r.id, r.id)
		} else if r.action != nil {
			g.proj = g.projections(r)
			fmt.Fprintf(init, "\t%s[%d].action = func(c *%s) any { return %s }\n", g.table, r.id, g.ctxType(), g.term(r.action, scopes[r], nil))
			g.proj = nil
		}
		if g.table == "trules" {
			g.typedCall(r, bodies[r], scopes[r], nil)
		} else if r.plain {
			g.plainCall(r, bodies[r])
		}
	}
	if g.table != "rules" {
		return // the recognizer shares the struct fields
	}
	// Struct fields, used to detect references to undeclared fields at run time.
	var names []string
	for name, spec := range g.prog.types {
		if _, ok := spec.(*grammar.StructSpec); ok {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		var fields []string
		for _, f := range g.prog.types[name].(*grammar.StructSpec).Fields {
			fields = append(fields, fmt.Sprintf("%q: true", f.Name))
		}
		fmt.Fprintf(init, "\tstructFields[%q] = map[string]bool{%s}\n", name, strings.Join(fields, ", "))
		fmt.Fprintf(init, "\ttypeKinds[%q] = kindOf(%q, \"\")\n", name, name)
	}
}

// typedCall writes the methods that call the rule r in the typed runtime: s<id> for a rule never
// memoized and without captures (what invokePlain does), and otherwise u<id> (what call does, the
// memo kept by callMemo) and i<id> (what invoke does). Each calls the body's method and the action
// directly and finishes the value as the rule's kind requires (what finish does), so a call goes
// through no rule table entry or function value.
//
// For a direct rule (d, see gen_direct.go), the method that runs the body (s<id>, v<id> or i<id>)
// has it inlined, with the action.
func (g *generator) typedCall(r *rule, body string, s *scope, d *direct) {
	if _, pratt := r.def.Expr.(*grammar.Pratt); pratt || r.leader {
		return // the general call
	}
	m := &g.methods
	entry := fmt.Sprintf("u%d", r.id)
	if r.plain {
		entry = fmt.Sprintf("s%d", r.id)
	}
	fmt.Fprintf(&g.init, "\ttrules[%d].entry = (*tparser).%s\n", r.id, entry)
	ncaps := len(s.names)
	if d != nil {
		ncaps = len(r.scope.names)
	}
	finish := func(frame string) {
		switch {
		case r.novalue:
			m.WriteString("\t\tv = nil\n")
		case r.action != nil:
			fmt.Fprintf(m, "\t\tc := p.useCtx(tctx{p: p, f: %s, start: start, end: p.pos, cbase: len(p.created)})\n", frame)
			if usesItems(r.action) {
				if r.bodyIsSeq {
					m.WriteString("\t\tif n := asTval(v); n != nil {\n\t\t\tc.items = n.tkids()\n\t\t} else {\n\t\t\tc.one[0] = nil\n\t\t\tc.items = c.one[:]\n\t\t}\n")
				} else {
					m.WriteString("\t\tc.one[0] = v\n\t\tc.items = c.one[:]\n")
				}
			}
			fmt.Fprintf(m, "\t\tv = c.result(ta%d, %q)\n", r.id, r.name)
		case r.terminalType != "":
			fmt.Fprintf(m, "\t\tv = trules[%d].term(p, start, p.pos, p.text(start, p.pos))\n", r.id)
		default:
			if len(s.names) > 0 {
				fmt.Fprintf(m, "\t\tv = p.attachCaptures(v, trules[%d].scope, %s.vals, start, p.pos)\n", r.id, frame)
			}
			m.WriteString("\t\tif n := asTval(v); n != nil {\n\t\t\tn.tsetFresh(false)\n\t\t}\n")
		}
	}
	plain := func(name string) {
		if d != nil {
			g.directMethod(r, d, name, "called as by invokePlain", true)
			return
		}
		fmt.Fprintf(m, "// %s, called as by invokePlain\nfunc (p *tparser) %s() (any, bool) {\n", r.name, name)
		m.WriteString("\tstart, rec, trail := p.pos, len(p.recovered), len(p.trail)\n\tprevEnv, prevCut := p.env, p.cut\n\tp.cut = false\n\tp.depth++\n\tif p.depth > maxDepth {\n\t\tp.tooDeep()\n\t}\n")
		fmt.Fprintf(m, "\tv, ok := p.%s()\n\tp.depth--\n\tp.cut = prevCut\n\tp.trail = p.trail[:trail]\n\tif ok {\n", body)
		finish("emptyTFrame")
		m.WriteString("\t} else {\n\t\tp.pos = start\n\t\tp.recovered = p.recovered[:rec]\n\t}\n\tp.env = prevEnv\n\treturn v, ok\n}\n\n")
	}
	if r.plain {
		plain(fmt.Sprintf("s%d", r.id))
		return
	}
	// u<id>: the call. An unmemoized call of a rule without captures is plain.
	fmt.Fprintf(m, "// %s, called as by call\nfunc (p *tparser) u%d() (any, bool) {\n", r.name, r.id)
	memo := r.memo && !r.transient
	if memo {
		fmt.Fprintf(m, "\tif !p.firstCall(rules[%d]) {\n\t\treturn p.callMemo(trules[%d], (*tparser).i%d)\n\t}\n", r.id, r.id, r.id)
	}
	if ncaps == 0 {
		fmt.Fprintf(m, "\treturn p.v%d()\n}\n\n", r.id)
		plain(fmt.Sprintf("v%d", r.id))
	} else {
		fmt.Fprintf(m, "\tstart, rec := p.pos, len(p.recovered)\n\tv, ok := p.i%d()\n\tif !ok {\n\t\tp.pos = start\n\t\tp.recovered = p.recovered[:rec]\n\t}\n\treturn v, ok\n}\n\n", r.id)
	}
	// i<id>: the invocation (also used by the memo).
	if d != nil {
		g.directMethod(r, d, fmt.Sprintf("i%d", r.id), "invoked as by invoke", false)
		return
	}
	fmt.Fprintf(m, "// %s, invoked as by invoke\nfunc (p *tparser) i%d() (any, bool) {\n", r.name, r.id)
	fmt.Fprintf(m, "\tf := p.newFrame(%d)\n\tprevFrame, prevEnv, prevCut, trail := p.frame, p.env, p.cut, len(p.trail)\n\tp.frame, p.cut = f, false\n\tp.depth++\n\tif p.depth > maxDepth {\n\t\tp.tooDeep()\n\t}\n\tstart := p.pos\n\t_ = start\n", len(s.names))
	fmt.Fprintf(m, "\tv, ok := p.%s()\n\tp.depth--\n\tp.frame, p.cut = prevFrame, prevCut\n\tp.trail = p.trail[:trail]\n\tif ok {\n", body)
	finish("f")
	m.WriteString("\t}\n\tp.env = prevEnv\n\tp.freeFrame(f)\n\treturn v, ok\n}\n\n")
}

// plainPrefix is the prefix of the methods written by plainCall, and seenVar the variable that
// holds the number of rules with rule.seen set, for the rule table being generated.
func (g *generator) plainPrefix() string {
	switch g.table {
	case "rules":
		return "r"
	case "trules":
		return "s"
	}
	return "q"
}

// pick returns untyped for the Node runtime and typed for the typed runtime (trules).
func (g *generator) pick(untyped, typed string) string {
	if g.table == "trules" {
		return typed
	}
	return untyped
}

func (g *generator) recv() string     { return g.pick("parser", "tparser") }
func (g *generator) valType() string  { return g.pick("*Node", "any") }
func (g *generator) ctxType() string  { return g.pick("actx", "tctx") }
func (g *generator) rt() string       { return g.pick("rt", "trt") }
func (g *generator) frameVar() string { return g.pick("emptyFrame", "emptyTFrame") }

func (g *generator) seenVar() string {
	if g.table == "rules" {
		return "nseen"
	}
	return "recNseen"
}

// method emits a method with the given body and returns its name.
func (g *generator) method(comment, body string) string {
	name := g.name("e")
	if comment != "" {
		fmt.Fprintf(&g.methods, "// %s\n", comment)
	}
	fmt.Fprintf(&g.methods, "func (p *%s) %s() (%s, bool) {\n%s}\n\n", g.recv(), name, g.valType(), body)
	return name
}

func describe(e grammar.Expr) string {
	s := grammar.FormatExpr(e)
	if strings.Contains(s, "\n") || len(s) > 100 {
		return ""
	}
	return s
}

// plainCall writes the method r<id>, which does what invokePlain does for the rule r (a rule never
// memoized and without captures) with a direct call of its body.
func (g *generator) plainCall(r *rule, body string) {
	fmt.Fprintf(&g.methods, "// %s, called as by invokePlain\nfunc (p *%s) %s%d() (%s, bool) {\n", r.name, g.recv(), g.plainPrefix(), r.id, g.valType())
	g.methods.WriteString(`	start, rec, trail := p.pos, len(p.recovered), len(p.trail)
	prevEnv, prevCut := p.env, p.cut
	p.cut = false
	p.depth++
	if p.depth > maxDepth {
		p.tooDeep()
	}
`)
	fmt.Fprintf(&g.methods, "\tv, ok := p.%s()\n", body)
	g.methods.WriteString(`	p.depth--
	p.cut = prevCut
	p.trail = p.trail[:trail]
	if ok {
`)
	if r.novalue {
		g.methods.WriteString("\t\tv = nil\n")
	} else {
		fmt.Fprintf(&g.methods, "\t\tv = p.finish(%s[%d], %s, v, start)\n", g.table, r.id, g.frameVar())
	}
	g.methods.WriteString(`	} else {
		p.pos = start
		p.recovered = p.recovered[:rec]
	}
	p.env = prevEnv
	return v, ok
}

`)
}

// projections returns the projected repetition captures of the rule r (see ruleProjections), none
// in the recognizer.
func (g *generator) projections(r *rule) map[string]string {
	if g.table == "recRules" {
		return nil
	}
	return ruleProjections(g.prog, r)
}

// projected reports whether the map call t reads a projected capture (projections), and returns
// the capture.
func (g *generator) projected(t *grammar.Call, locals map[string]string) (grammar.Term, bool) {
	x, ok := projectedMap(t, g.proj, func(name string) bool { _, local := locals[name]; return local })
	return x, ok
}

// projectRepeat writes a repetition that gathers the values of the capture field of its elements
// (see projections). The elements build no values of their own, and share one capture frame.
func (g *generator) projectRepeat(b *strings.Builder, e *grammar.Repeat, field string) {
	elemScope := newScope()
	m := g.expr(e.Expr, elemScope, false)
	slot := elemScope.slots[field]
	fmt.Fprintf(b, "\tstart := p.pos\n\tbase := len(p.kidStack)\n\tf := p.newFrame(%d)\n\tcount := 0\n", len(elemScope.names))
	if e.Max < 0 {
		b.WriteString("\tfor {\n")
	} else {
		fmt.Fprintf(b, "\tfor n := 0; n < %d; n++ {\n", e.Max)
	}
	b.WriteString("\t\tclear(f.vals)\n\t\tm0 := p.mark()\n\t\tprevCut, prevFrame := p.cut, p.frame\n\t\tp.cut = false\n\t\tp.frame = f\n")
	fmt.Fprintf(b, "\t\t_, ok := p.%s()\n", m)
	b.WriteString("\t\tcut := p.cut\n\t\tp.cut, p.frame = prevCut, prevFrame\n\t\tif !ok {\n\t\t\tp.reset(m0)\n\t\t\tif cut {\n\t\t\t\tp.dropKids(base)\n\t\t\t\treturn nil, false\n\t\t\t}\n\t\t\tbreak\n\t\t}\n")
	fmt.Fprintf(b, "\t\tcount++\n\t\tp.kidStack = append(p.kidStack, f.vals[%d])\n", slot)
	fmt.Fprintf(b, "\t\tif p.pos == m0.pos && count >= %d {\n\t\t\tbreak\n\t\t}\n\t}\n", e.Min)
	fmt.Fprintf(b, "\tif count < %d {\n\t\tp.dropKids(base)\n\t\treturn nil, false\n\t}\n", e.Min)
	b.WriteString(g.pick("\treturn p.newNode(Node{kind: kindList, Start: int32(start), End: int32(p.pos), Children: p.kids(base), fresh: true}), true\n",
		"\treturn p.newNode(\"List\", start, p.pos, p.kids(base)), true\n"))
}

func (g *generator) expr(e grammar.Expr, s *scope, build bool) string {
	var b strings.Builder
	switch e := e.(type) {
	case *grammar.Literal:
		v := g.name("lit")
		fmt.Fprintf(&g.vars, "var %s = []rune(%q)\n", v, e.Value)
		fmt.Fprintf(&b, "\treturn p.matchLiteral(%s, %q, %d, %v)\n", v, e.Value, g.desc(strconv.Quote(e.Value)), build)
	case *grammar.CharClass:
		fmt.Fprintf(&b, "\tch, size, ok := p.peek()\n\tif !ok || %s {\n\t\tp.expect(p.pos, %d)\n\t\treturn nil, false\n\t}\n",
			classReject(e), g.desc(charClassString(e)))
		fmt.Fprintf(&b, "\treturn p.single(size, %v)\n", build)
	case *grammar.Any:
		fmt.Fprintf(&b, "\treturn p.matchAny(%v)\n", build)
	case *grammar.Ref:
		fmt.Fprintf(&b, "\treturn %s\n", g.refCall(e, build))
	case *grammar.Seq:
		var items []string
		for _, it := range e.Items {
			items = append(items, g.expr(it, s, build))
		}
		if build {
			nvis := 0
			for _, it := range e.Items {
				if visible(it) {
					nvis++
				}
			}
			fmt.Fprintf(&b, "\tstart := p.pos\n\tkids := p.%s(%d)[:0]\n", g.pick("nodes", "newVals"), nvis)
		}
		for i, it := range e.Items {
			if build && visible(it) {
				fmt.Fprintf(&b, "\tif v, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t} else {\n\t\tkids = append(kids, v)\n\t}\n", items[i])
			} else {
				fmt.Fprintf(&b, "\tif _, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t}\n", items[i])
			}
		}
		if build {
			b.WriteString(g.pick("\treturn p.newNode(Node{kind: kindSeq, Start: int32(start), End: int32(p.pos), Children: kids, fresh: true}), true\n",
				"\treturn p.newNode(\"Seq\", start, p.pos, kids), true\n"))
		} else {
			b.WriteString("\treturn nil, true\n")
		}
	case *grammar.Choice:
		b.WriteString("\tm0 := p.mark()\n")
		peeked := false
		for _, alt := range e.Alts {
			m := g.expr(alt, s, build)
			if cond, desc, depth, ok := g.first(alt, 0, map[string]bool{}); ok {
				// An alternative whose first terminal does not match the next character is skipped,
				// with the expectation it would record (see first).
				if !peeked {
					b.WriteString("\tch, _, more := p.peek()\n")
					peeked = true
				}
				fmt.Fprintf(&b, "\tif !(more && (%s)) && p.depth+%d <= maxDepth {\n\t\tp.expect(p.pos, %d)\n\t} else ", cond, depth, desc)
			}
			fmt.Fprintf(&b, "\t{\n\t\tprevCut := p.cut\n\t\tp.cut = false\n\t\tv, ok := p.%s()\n\t\tcut := p.cut\n\t\tp.cut = prevCut\n"+
				"\t\tif ok {\n\t\t\treturn v, true\n\t\t}\n\t\tp.reset(m0)\n\t\tif cut {\n\t\t\treturn nil, false\n\t\t}\n\t}\n", m)
		}
		b.WriteString("\treturn nil, false\n")
	case *grammar.Repeat:
		g.repeat(&b, e, s, build)
	case *grammar.Optional:
		m := g.expr(e.Expr, s, build)
		fmt.Fprintf(&b, "\tm0 := p.mark()\n\tprevCut := p.cut\n\tp.cut = false\n\tv, ok := p.%s()\n\tcut := p.cut\n\tp.cut = prevCut\n"+
			"\tif ok {\n\t\treturn v, true\n\t}\n\tp.reset(m0)\n\tif cut {\n\t\treturn nil, false\n\t}\n\treturn nil, true\n", m)
	case *grammar.And:
		m := g.expr(e.Expr, s, build && hasCaptures(e.Expr))
		fmt.Fprintf(&b, "\tstart, prevCut := p.pos, p.cut\n\tp.silent++\n\t_, ok := p.%s()\n\tp.silent--\n\tp.cut = prevCut\n\tp.pos = start\n\treturn nil, ok\n", m)
	case *grammar.Not:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\tm0 := p.mark()\n\tprevCut := p.cut\n\tp.silent++\n\t_, ok := p.%s()\n\tp.silent--\n\tp.cut = prevCut\n\tp.reset(m0)\n\treturn nil, !ok\n", m)
	case *grammar.Atomic:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\tstart := p.pos\n\tif _, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t}\n", m)
		if build {
			b.WriteString(g.pick("\treturn p.newNode(Node{kind: kindMatch, Start: int32(start), End: int32(p.pos), Text: p.text(start, p.pos), terminal: true, fresh: true}), true\n",
				"\treturn p.newMatch(start, p.pos, p.text(start, p.pos), true), true\n"))
		} else {
			b.WriteString("\t_ = start\n\treturn nil, true\n")
		}
	case *grammar.Discard:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\t_, ok := p.%s()\n\treturn nil, ok\n", m)
	case *grammar.Capture:
		if !build && g.cur != nil && g.cur.predCaps != nil && !g.cur.predCaps[e.Name] {
			// In the recognizer, captures not referenced by predicates are not recorded (as in
			// the engine).
			return g.expr(e.Expr, s, false)
		}
		slot := s.slot(e.Name)
		var m string
		if field := g.proj[e.Name]; field != "" {
			var rb strings.Builder
			g.projectRepeat(&rb, e.Expr.(*grammar.Repeat), field)
			m = g.method(describe(e.Expr)+" (projected to "+field+")", rb.String())
		} else {
			m = g.expr(e.Expr, s, true)
		}
		fmt.Fprintf(&b, "\tv, ok := p.%s()\n\tif ok {\n\t\tp.setCapture(%d, v)\n\t}\n", m, slot)
		if build {
			b.WriteString("\treturn v, ok\n")
		} else {
			b.WriteString("\treturn nil, ok\n")
		}
	case *grammar.Cut:
		b.WriteString("\tp.cut = true\n\treturn nil, true\n")
	case *grammar.Top:
		if build {
			b.WriteString(g.pick("\treturn p.newNode(Node{kind: kindMatch, Start: int32(p.pos), End: int32(p.pos), terminal: true, fresh: true}), true\n",
				"\treturn p.newMatch(p.pos, p.pos, \"\", true), true\n"))
		} else {
			b.WriteString("\treturn nil, true\n")
		}
	case *grammar.Bottom:
		b.WriteString("\treturn nil, false\n")
	case *grammar.BeginInput:
		b.WriteString("\treturn p.anchor(p.pos == 0, idBeginInput)\n")
	case *grammar.EndInput:
		b.WriteString("\treturn p.anchor(p.atEnd(), idEndInput)\n")
	case *grammar.BeginLine:
		b.WriteString("\treturn p.anchor(p.atLineStart(), idBeginLine)\n")
	case *grammar.EndLine:
		b.WriteString("\treturn p.anchor(p.atLineEnd(), idEndLine)\n")
	case *grammar.Predicate:
		if a, ok := e.Term.(*grammar.Assign); ok {
			fmt.Fprintf(&b, "\treturn nil, p.assign(%q, func(c *%s) any { return %s })\n", a.Name, g.ctxType(), g.term(a.Value, s, nil))
		} else {
			fmt.Fprintf(&b, "\treturn nil, p.predicate(func(c *%s) any { return %s })\n", g.ctxType(), g.term(e.Term, s, nil))
		}
	case *grammar.Attributed:
		return g.attributed(e, s, build)
	default:
		panic(fmt.Sprintf("unsupported expression %T", e))
	}
	return g.method(describe(e), b.String())
}

// refCall returns the Go call of the rule the reference e calls (its value-free twin unless
// build).
func (g *generator) refCall(e *grammar.Ref, build bool) string {
	r := g.prog.byName[e.Name]
	min := 0
	if e.Level != "" {
		for i, l := range r.def.Expr.(*grammar.Pratt).Levels {
			if l.Name == e.Level {
				min = i
			}
		}
	}
	if !build && r.twin != nil {
		r = r.twin
	}
	_, pratt := r.def.Expr.(*grammar.Pratt)
	switch {
	case r.plain && !pratt:
		// Never memoized and without captures: call does nothing but invokePlain, which a
		// method of its own does with a direct call of the body (see plainCalls).
		return fmt.Sprintf("p.%s%d()", g.plainPrefix(), r.id)
	case g.table == "trules" && !pratt && !r.leader:
		// The typed runtime calls a method of the rule's own (typedCall).
		return fmt.Sprintf("p.u%d()", r.id)
	case r.plain:
		return fmt.Sprintf("p.invokePlain(%s[%d], %d)", g.table, r.id, min)
	}
	return fmt.Sprintf("p.call(%s[%d], %d)", g.table, r.id, min)
}

func (g *generator) repeat(b *strings.Builder, e *grammar.Repeat, s *scope, build bool) {
	if !build && g.scanRepeat(b, e) {
		return
	}
	// An element with captures has its own scope per iteration (elementScoped).
	elemScope := s
	if elementScoped(e.Expr) {
		elemScope = newScope()
	}
	m := g.expr(e.Expr, elemScope, build)
	own := elemScope != s
	if build {
		// Element values are gathered on p.kidStack and copied out once.
		b.WriteString("\tstart := p.pos\n\tbase := len(p.kidStack)\n")
	}
	b.WriteString("\tcount := 0\n")
	if e.Max < 0 {
		b.WriteString("\tfor {\n")
	} else {
		fmt.Fprintf(b, "\tfor n := 0; n < %d; n++ {\n", e.Max)
	}
	b.WriteString("\t\tm0 := p.mark()\n\t\tprevCut, prevFrame := p.cut, p.frame\n\t\tp.cut = false\n")
	scopeVar := ""
	if own {
		scopeVar = g.name("scope")
		fmt.Fprintf(&g.vars, "var %s = %s\n", scopeVar, goStrings(elemScope.names))
		fmt.Fprintf(b, "\t\tf := p.newFrame(%d)\n\t\tp.frame = f\n", len(elemScope.names))
	}
	if build {
		fmt.Fprintf(b, "\t\tv, ok := p.%s()\n", m)
	} else {
		fmt.Fprintf(b, "\t\t_, ok := p.%s()\n", m)
	}
	b.WriteString("\t\tcut := p.cut\n\t\tp.cut, p.frame = prevCut, prevFrame\n\t\tif !ok {\n\t\t\tp.reset(m0)\n\t\t\tif cut {\n")
	if build {
		b.WriteString("\t\t\t\tp.dropKids(base)\n")
	}
	b.WriteString("\t\t\t\treturn nil, false\n\t\t\t}\n\t\t\tbreak\n\t\t}\n")
	if own && build {
		fmt.Fprintf(b, "\t\tv = p.attachCaptures(v, %s, %s, m0.pos, p.pos)\n", scopeVar, g.pick("f", "f.vals"))
	}
	if own && g.table == "trules" {
		// The element's frame is dead: its values are in v, and the trail entries since m0 all
		// refer to it (or to frames of its own elements), so they can go too.
		b.WriteString("\t\tp.trail = p.trail[:m0.trail]\n\t\tp.freeFrame(f)\n")
	}
	b.WriteString("\t\tcount++\n")
	if build {
		b.WriteString("\t\tp.kidStack = append(p.kidStack, v)\n")
	}
	fmt.Fprintf(b, "\t\tif p.pos == m0.pos && count >= %d {\n\t\t\tbreak\n\t\t}\n\t}\n", e.Min)
	fmt.Fprintf(b, "\tif count < %d {\n", e.Min)
	if build {
		b.WriteString("\t\tp.dropKids(base)\n")
	}
	b.WriteString("\t\treturn nil, false\n\t}\n")
	if !build {
		b.WriteString("\treturn nil, true\n")
		return
	}
	b.WriteString(g.pick("\treturn p.newNode(Node{kind: kindList, Start: int32(start), End: int32(p.pos), Children: p.kids(base), fresh: true}), true\n",
		"\treturn p.newNode(\"List\", start, p.pos, p.kids(base)), true\n"))
}

// scanRepeat generates a value-free repetition of a single-character expression (a character
// class or .) as a scan loop without per-iteration backtracking state, like the engine's
// compiler.scanRepeat. It reports whether e qualifies. Expectations are recorded as in a general
// repetition: once, where the element last failed.
func (g *generator) scanRepeat(b *strings.Builder, e *grammar.Repeat) bool {
	var cond string
	switch x := e.Expr.(type) {
	case *grammar.CharClass:
		cond = fmt.Sprintf("!ok || %s {\n\t\t\tp.expect(p.pos, %d)", classReject(x), g.desc(charClassString(x)))
		b.WriteString("\tcount := 0\n")
	case *grammar.Any:
		cond = "!ok {\n\t\t\tp.expect(p.pos, idAny)"
		b.WriteString("\tcount := 0\n")
	default:
		return false
	}
	if e.Max < 0 {
		b.WriteString("\tfor {\n")
	} else {
		fmt.Fprintf(b, "\tfor count < %d {\n", e.Max)
	}
	if _, isAny := e.Expr.(*grammar.Any); isAny {
		b.WriteString("\t\t_, size, ok := p.peek()\n")
	} else {
		b.WriteString("\t\tch, size, ok := p.peek()\n")
	}
	fmt.Fprintf(b, "\t\tif %s\n\t\t\tbreak\n\t\t}\n\t\tp.pos += size\n\t\tcount++\n\t}\n", cond)
	fmt.Fprintf(b, "\treturn nil, count >= %d\n", e.Min)
	return true
}

// first returns the condition on the next character ch under which the expression e can match,
// when e must begin with a given terminal (a literal or a character class, possibly behind
// sequences, captures, @, - and calls of rules that are not left-recursive or Pratt), with the
// expectation e records when the condition does not hold and the number of rule calls on the way.
// Then e fails at once without the terminal, recording only that expectation (a call memoizes the
// same failure, and memoization only affects speed), so a choice can skip it; unless the calls on
// the way would exceed the nesting limit.
func (g *generator) first(e grammar.Expr, depth int, seen map[string]bool) (string, expID, int, bool) {
	switch e := e.(type) {
	case *grammar.Literal:
		if e.Value == "" {
			break
		}
		r, _ := utf8.DecodeRuneInString(e.Value)
		return fmt.Sprintf("ch == %d", r), g.desc(strconv.Quote(e.Value)), depth, true
	case *grammar.CharClass:
		return "!" + classReject(e), g.desc(charClassString(e)), depth, true
	case *grammar.Seq:
		if len(e.Items) > 0 {
			return g.first(e.Items[0], depth, seen)
		}
	case *grammar.Capture:
		return g.first(e.Expr, depth, seen)
	case *grammar.Atomic:
		return g.first(e.Expr, depth, seen)
	case *grammar.Discard:
		return g.first(e.Expr, depth, seen)
	case *grammar.Ref:
		r := g.prog.byName[e.Name]
		if r == nil || r.leader || seen[e.Name] {
			break
		}
		if _, pratt := r.def.Expr.(*grammar.Pratt); pratt {
			break
		}
		seen[e.Name] = true
		return g.first(r.def.Expr, depth+1, seen)
	}
	return "", 0, 0, false
}

// classReject returns a Go condition on ch that is true when ch is not accepted by the class.
func classReject(e *grammar.CharClass) string {
	var in []string
	for _, r := range e.Ranges {
		if r.Lo == r.Hi {
			in = append(in, fmt.Sprintf("ch == %d", r.Lo))
		} else {
			in = append(in, fmt.Sprintf("ch >= %d && ch <= %d", r.Lo, r.Hi))
		}
	}
	if len(in) == 0 {
		in = []string{"ch < 0"} // never true; mentions ch so that it is used
	}
	cond := strings.Join(in, " || ")
	if e.Negated {
		return "(" + cond + ")"
	}
	return "!(" + cond + ")"
}

func (g *generator) attributed(e *grammar.Attributed, s *scope, build bool) string {
	m := g.expr(e.Expr, s, build)
	for _, a := range e.Attrs {
		switch a.Name {
		case "error":
			msg := a.Args[0].Value.(*grammar.Literal).Value
			m = g.method("#error", fmt.Sprintf("\treturn p.errorAttr((*%s).%s, msgBit|%d)\n", g.recv(), m, g.desc(msg)))
		case "recover":
			skipExpr, _ := a.Arg("skip")
			skip := g.expr(skipExpr, s, false)
			m = g.method("#recover", fmt.Sprintf("\treturn p.recoverAttr((*%s).%s, (*%s).%s, %v)\n", g.recv(), m, g.recv(), skip, build && visible(e.Expr)))
		}
	}
	return m
}

func (g *generator) pratt(r *rule, e *grammar.Pratt) {
	var b strings.Builder
	fmt.Fprintf(&b, "\t%s[%d].pratt = &%s{\n", g.table, r.id, g.pick("pratt", "tpratt"))
	if e.Skip != nil {
		fmt.Fprintf(&b, "\t\tskip: (*%s).%s,\n", g.recv(), g.expr(e.Skip, newScope(), false))
	}
	fmt.Fprintf(&b, "\t\toperands: []*%s{\n", g.pick("prattLine", "tprattLine"))
	for _, o := range e.Operands {
		fmt.Fprintf(&b, "\t\t\t%s,\n", g.prattLine(o.Expr, o.Action, false))
	}
	b.WriteString("\t\t},\n")
	var prefix, led []string
	id := 0
	for i, l := range e.Levels {
		for _, op := range l.Operators {
			s := fmt.Sprintf("{id: %d, kind: %q, assoc: %q, level: %d, line: %s}", id, op.Kind, op.Assoc, i+1, g.prattLine(op.Expr, op.Action, true))
			id++
			if op.Kind == grammar.Prefix {
				prefix = append(prefix, s)
			} else {
				led = append(led, s)
			}
		}
	}
	op := g.pick("prattOp", "tprattOp")
	fmt.Fprintf(&b, "\t\tprefix: []*%s{%s},\n", op, strings.Join(prefix, ",\n"))
	fmt.Fprintf(&b, "\t\tled: []*%s{%s},\n", op, strings.Join(led, ",\n"))
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\t%s[%d].body = func(p *%s, min int) (%s, bool) { return p.prattParse(%s[%d], min) }\n", g.table, r.id, g.recv(), g.valType(), g.table, r.id)
	g.init.WriteString(b.String())
}

func (g *generator) prattLine(e grammar.Expr, action grammar.Term, operator bool) string {
	s := newScope()
	var locals []string
	if operator {
		locals = []string{"lhs", "rhs", "op"}
	}
	// Lines whose value is unused are matched without values, as in the engine; so are all lines
	// of a rule without a value (in the recognizer).
	m := g.expr(e, s, !g.cur.novalue && !leanLine(action, locals))
	_, isSeq := e.(*grammar.Seq)
	act := "nil"
	if action != nil && !g.cur.novalue {
		var locals map[string]string
		if operator {
			locals = map[string]string{"lhs": "c.lhs", "rhs": "c.rhs", "op": "c.op"}
		}
		if g.table == "trules" {
			g.final = action // re-ranged by tctx.result, as an action's result
		}
		act = fmt.Sprintf("func(c *%s) any { return %s }", g.ctxType(), g.term(action, s, locals))
		g.final = nil
	}
	return fmt.Sprintf("&%s{scope: %s, m: (*%s).%s, action: %s, isSeq: %v}", g.pick("prattLine", "tprattLine"), goStrings(s.names), g.recv(), m, act, isSeq)
}

// term converts a value expression into a Go expression of type any. locals maps names, such as lambda
// parameters, to Go expressions.
func (g *generator) term(t grammar.Term, s *scope, locals map[string]string) string {
	switch t := t.(type) {
	case *grammar.IntLit:
		return fmt.Sprintf("any(%d)", t.Value)
	case *grammar.StringLit:
		return fmt.Sprintf("any(%q)", t.Value)
	case *grammar.BoolLit:
		return fmt.Sprintf("any(%v)", t.Value)
	case *grammar.NilLit:
		return "any(nil)"
	case *grammar.CaptureRef:
		if l, ok := locals[t.Name]; ok {
			return l
		}
		if g.caps != nil {
			return g.caps[t.Name]
		}
		return fmt.Sprintf("c.cap(%d)", s.slots[t.Name])
	case *grammar.IndexRef:
		return fmt.Sprintf("c.item(%d)", t.Index)
	case *grammar.VarRef:
		return fmt.Sprintf("c.lookup(%q)", t.Name)
	case *grammar.Member:
		return fmt.Sprintf("c.member(%s, %q)", g.term(t.X, s, locals), t.Name)
	case *grammar.New:
		name, spec := g.prog.structType(t.Type)
		if g.table == "trules" {
			// The typed runtime calls the constructor of the type (tmk_T, see typedRuntime) with
			// the fields in declaration order.
			// The fields are evaluated in the order written (an error in one must win over the
			// next), then passed in declaration order.
			var b strings.Builder
			b.WriteString("func() any { ")
			vars := map[string]string{}
			for _, given := range t.Fields {
				v := g.name("f_")
				vars[given.Name] = v
				fmt.Fprintf(&b, "%s := %s; ", v, g.term(given.Value, s, locals))
			}
			args := []string{"c", strconv.FormatBool(grammar.Term(t) == g.final)}
			for _, f := range spec.Fields {
				if v, ok := vars[f.Name]; ok {
					args = append(args, v)
				} else {
					args = append(args, "nil")
				}
			}
			b.WriteString("return tmk_" + name + "(" + strings.Join(args, ", ") + ") }()")
			return b.String()
		}
		args := []string{strconv.Quote(name)}
		for _, f := range t.Fields {
			args = append(args, strconv.Quote(f.Name), g.term(f.Value, s, locals))
		}
		return "c.newStruct(" + strings.Join(args, ", ") + ")"
	case *grammar.Call:
		if t.Func == "concat" && fusable(t) {
			// Push the elements of list, map and concat arguments directly (see fusable and
			// evalCtx.pushConcatArg).
			var b strings.Builder
			b.WriteString("func() any { b := len(c.p.kidStack); ")
			g.concatParts(&b, t, s, locals)
			b.WriteString("return c.endList(b) }()")
			return b.String()
		}
		args := make([]string, len(t.Args))
		for i, a := range t.Args {
			if _, ok := a.(*grammar.Lambda); !ok {
				args[i] = g.term(a, s, locals)
			}
		}
		switch t.Func {
		case "len":
			return "c.length(" + args[0] + ")"
		case "text":
			return "c.text(" + args[0] + ")"
		case "foldl", "foldr":
			return fmt.Sprintf("%sFold(%q, %v, %s, %s, %s)", g.rt(), t.Func, t.Func == "foldr", args[0], args[1], g.lambda(t.Args[2], s, locals))
		case "map":
			if x, ok := g.projected(t, locals); ok {
				return "c.newList(" + g.pick("listItems", "tlistItems") + "(\"map\", " + g.term(x, s, locals) + "))"
			}
			return fmt.Sprintf("c.mapList(%s, %s)", args[0], g.lambda(t.Args[1], s, locals))
		case "list":
			return "c.list(" + strings.Join(args, ", ") + ")"
		case "concat":
			return "c.concat(" + strings.Join(args, ", ") + ")"
		}
	case *grammar.Binary:
		if lx, ok := textArg(t.L); ok && (t.Op == "==" || t.Op == "!=") {
			if rx, ok := textArg(t.R); ok {
				// Compare the strings directly (see evalCtx.binary).
				return fmt.Sprintf("any(c.textStr(%s) %s c.textStr(%s))", g.term(lx, s, locals), t.Op, g.term(rx, s, locals))
			}
		}
		l, r := g.term(t.L, s, locals), g.term(t.R, s, locals)
		switch t.Op {
		case "&&":
			return fmt.Sprintf("%sAnd(%s, func() any { return %s })", g.rt(), l, r)
		case "||":
			return fmt.Sprintf("%sOr(%s, func() any { return %s })", g.rt(), l, r)
		}
		return fmt.Sprintf("%sBinary(%q, %s, %s)", g.rt(), t.Op, l, r)
	case *grammar.Unary:
		return fmt.Sprintf("%sUnary(%q, %s)", g.rt(), t.Op, g.term(t.X, s, locals))
	}
	panic(fmt.Sprintf("unsupported term %T", t))
}

// concatParts writes the statements that push the elements of the arguments of the concat call t.
func (g *generator) concatParts(b *strings.Builder, t *grammar.Call, s *scope, locals map[string]string) {
	for _, a := range t.Args {
		call, ok := a.(*grammar.Call)
		switch {
		case ok && call.Func == "list":
			args := make([]string, len(call.Args))
			for i, x := range call.Args {
				args[i] = g.term(x, s, locals)
			}
			b.WriteString("c.pushList(" + strings.Join(args, ", ") + "); ")
		case ok && call.Func == "map" && len(call.Args) == 2:
			if x, ok := g.projected(call, locals); ok {
				b.WriteString("c.pushItems(" + g.term(x, s, locals) + "); ")
				break
			}
			fmt.Fprintf(b, "c.pushMap(%s, %s); ", g.term(call.Args[0], s, locals), g.lambda(call.Args[1], s, locals))
		case ok && call.Func == "concat":
			g.concatParts(b, call, s, locals)
		default:
			b.WriteString("c.pushItems(" + g.term(a, s, locals) + "); ")
		}
	}
}

func (g *generator) lambda(t grammar.Term, s *scope, locals map[string]string) string {
	l := t.(*grammar.Lambda)
	inner := map[string]string{}
	for k, v := range locals {
		inner[k] = v
	}
	params := make([]string, len(l.Params))
	for i, p := range l.Params {
		params[i] = g.name("l_")
		inner[p] = params[i]
	}
	return fmt.Sprintf("func(%s any) any { return %s }", strings.Join(params, ", "), g.term(l.Body, s, inner))
}
