package engine

import (
	_ "embed"
	"fmt"
	"go/format"
	"go/token"
	"sort"
	"strconv"
	"strings"

	"github.com/ornew/pego/grammar"
)

//go:embed genrt/runtime.go
var runtimeSource string

// GenOptions configures code generation.
type GenOptions struct {
	// Package is the package name of the generated code.
	Package string
	// Start is the start rule of the generated Parse function.
	Start string
}

// Generate generates the source code of a Go parser for a grammar.
//
// The generated code depends only on the standard library. Each parsing expression becomes a Go method and
// actions and predicates become Go expressions; the embedded runtime (genrt) behaves exactly like the engine
// in this package. Stream and incremental parsing are not generated (#stream becomes a plain repetition).
func Generate(g *grammar.Grammar, opts GenOptions) ([]byte, error) {
	prog, err := Compile(g, Options{})
	if err != nil {
		return nil, err
	}
	start := prog.byName[opts.Start]
	if start == nil {
		return nil, fmt.Errorf("start rule %s is not defined", opts.Start)
	}
	if opts.Package == "" {
		return nil, fmt.Errorf("package name is required")
	}
	if !token.IsIdentifier(opts.Package) {
		return nil, fmt.Errorf("invalid package name %q", opts.Package)
	}
	gen := &generator{prog: prog}
	gen.desc(fixedDescs[0]) // the fixed expectations come first
	gen.rules()
	fmt.Fprintf(&gen.init, "\tdescs = %s\n", goStrings(gen.descs))

	var out strings.Builder
	out.WriteString("// Code generated by pego. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "// Package %s is a parser generated from a PEGO grammar.\n", opts.Package)
	rt := runtimeSource[strings.Index(runtimeSource, "package genrt"):]
	out.WriteString(strings.Replace(rt, "package genrt", "package "+opts.Package, 1))
	out.WriteString("\n// --- Generated code ---\n\n")
	fmt.Fprintf(&out, "// Parse parses the whole input with the rule %s. unit selects the position unit (CodePoints by default).\n", start.name)
	out.WriteString("// If the parse recovered from errors with #recover, it returns the node together with SyntaxErrors.\n")
	fmt.Fprintf(&out, "func Parse(input string, unit ...Unit) (*Node, error) { return parse(rules[%d], input, unit) }\n\n", start.id)
	out.WriteString(`// ParseRule parses the whole input with the rule name.
func ParseRule(name, input string, unit ...Unit) (*Node, error) {
	r := ruleByName(name)
	if r == nil {
		return nil, fmt.Errorf("rule %s is not defined", name)
	}
	return parse(r, input, unit)
}

`)
	out.WriteString(gen.vars.String())
	out.WriteString("\nfunc init() {\n")
	out.WriteString(gen.init.String())
	out.WriteString("}\n\n")
	out.WriteString(gen.methods.String())
	src, err := format.Source([]byte(out.String()))
	if err != nil {
		return []byte(out.String()), fmt.Errorf("generated code does not compile: %w", err)
	}
	return src, nil
}

type generator struct {
	prog    *Program
	vars    strings.Builder
	init    strings.Builder
	methods strings.Builder
	n       int
	// descs is the expectation table of the generated parser (descs in genrt); descIDs maps a
	// description to its ID.
	descs   []string
	descIDs map[string]expID
}

// desc returns the expectation ID of description s, adding it to the table.
func (g *generator) desc(s string) expID {
	if g.descIDs == nil {
		g.descIDs = map[string]expID{}
		for i, d := range fixedDescs {
			g.descs = append(g.descs, d)
			g.descIDs[d] = expID(i)
		}
	}
	if id, ok := g.descIDs[s]; ok {
		return id
	}
	id := expID(len(g.descs))
	g.descs = append(g.descs, s)
	g.descIDs[s] = id
	return id
}

func (g *generator) name(prefix string) string {
	g.n++
	return fmt.Sprintf("%s%d", prefix, g.n)
}

func goStrings(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = strconv.Quote(x)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}

func (g *generator) rules() {
	init := &g.init
	bodies := map[*rule]string{}
	scopes := map[*rule]*scope{}
	all := append(append([]*rule(nil), g.prog.rules...), g.prog.twins...)
	for _, r := range all {
		s := newScope()
		scopes[r] = s
		if _, ok := r.def.Expr.(*grammar.Pratt); !ok {
			bodies[r] = g.expr(r.def.Expr, s, !r.lean)
		}
	}
	init.WriteString("\trules = []*rule{\n")
	for _, r := range all {
		fmt.Fprintf(init, "\t\t{id: %d, name: %q, scope: %s, bodyIsSeq: %v, terminalType: %q, memo: %v, leader: %v, seen: %d, novalue: %v, vars: %s},\n",
			r.id, r.name, goStrings(scopes[r].names), r.bodyIsSeq, r.terminalType, r.memo && !r.transient, r.leader, r.seen, r.novalue, goStrings(r.vars))
	}
	init.WriteString("\t}\n")
	fmt.Fprintf(init, "\tnseen = %d\n", g.prog.nseen)
	for _, r := range all {
		if pr, ok := r.def.Expr.(*grammar.Pratt); ok {
			g.pratt(r, pr)
			continue
		}
		fmt.Fprintf(init, "\trules[%d].body = func(p *parser, _ int) (*Node, bool) { return p.%s() }\n", r.id, bodies[r])
		if r.action != nil {
			fmt.Fprintf(init, "\trules[%d].action = func(c *actx) any { return %s }\n", r.id, g.term(r.action, scopes[r], nil))
		}
	}
	// Struct fields, used to detect references to undeclared fields at run time.
	var names []string
	for name, spec := range g.prog.types {
		if _, ok := spec.(*grammar.StructSpec); ok {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		var fields []string
		for _, f := range g.prog.types[name].(*grammar.StructSpec).Fields {
			fields = append(fields, fmt.Sprintf("%q: true", f.Name))
		}
		fmt.Fprintf(init, "\tstructFields[%q] = map[string]bool{%s}\n", name, strings.Join(fields, ", "))
	}
}

// method emits a method with the given body and returns its name.
func (g *generator) method(comment, body string) string {
	name := g.name("e")
	if comment != "" {
		fmt.Fprintf(&g.methods, "// %s\n", comment)
	}
	fmt.Fprintf(&g.methods, "func (p *parser) %s() (*Node, bool) {\n%s}\n\n", name, body)
	return name
}

func describe(e grammar.Expr) string {
	s := grammar.FormatExpr(e)
	if strings.Contains(s, "\n") || len(s) > 100 {
		return ""
	}
	return s
}

func (g *generator) expr(e grammar.Expr, s *scope, build bool) string {
	var b strings.Builder
	switch e := e.(type) {
	case *grammar.Literal:
		v := g.name("lit")
		fmt.Fprintf(&g.vars, "var %s = []rune(%q)\n", v, e.Value)
		fmt.Fprintf(&b, "\treturn p.matchLiteral(%s, %q, %d, %v)\n", v, e.Value, g.desc(strconv.Quote(e.Value)), build)
	case *grammar.CharClass:
		fmt.Fprintf(&b, "\tch, size, ok := p.peek()\n\tif !ok || %s {\n\t\tp.expect(p.pos, %d)\n\t\treturn nil, false\n\t}\n",
			classReject(e), g.desc(charClassString(e)))
		fmt.Fprintf(&b, "\treturn p.single(size, %v)\n", build)
	case *grammar.Any:
		fmt.Fprintf(&b, "\treturn p.matchAny(%v)\n", build)
	case *grammar.Ref:
		r := g.prog.byName[e.Name]
		min := 0
		if e.Level != "" {
			for i, l := range r.def.Expr.(*grammar.Pratt).Levels {
				if l.Name == e.Level {
					min = i
				}
			}
		}
		if !build && r.twin != nil {
			r = r.twin
		}
		fmt.Fprintf(&b, "\treturn p.call(rules[%d], %d)\n", r.id, min)
	case *grammar.Seq:
		var items []string
		for _, it := range e.Items {
			items = append(items, g.expr(it, s, build))
		}
		if build {
			nvis := 0
			for _, it := range e.Items {
				if visible(it) {
					nvis++
				}
			}
			fmt.Fprintf(&b, "\tstart := p.pos\n\tkids := p.nodes(%d)[:0]\n", nvis)
		}
		for i, it := range e.Items {
			if build && visible(it) {
				fmt.Fprintf(&b, "\tif v, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t} else {\n\t\tkids = append(kids, v)\n\t}\n", items[i])
			} else {
				fmt.Fprintf(&b, "\tif _, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t}\n", items[i])
			}
		}
		if build {
			b.WriteString("\treturn p.newNode(Node{Type: \"Seq\", Start: start, End: p.pos, Children: kids, fresh: true}), true\n")
		} else {
			b.WriteString("\treturn nil, true\n")
		}
	case *grammar.Choice:
		b.WriteString("\tm0 := p.mark()\n")
		for _, alt := range e.Alts {
			m := g.expr(alt, s, build)
			fmt.Fprintf(&b, "\t{\n\t\tprevCut := p.cut\n\t\tp.cut = false\n\t\tv, ok := p.%s()\n\t\tcut := p.cut\n\t\tp.cut = prevCut\n"+
				"\t\tif ok {\n\t\t\treturn v, true\n\t\t}\n\t\tp.reset(m0)\n\t\tif cut {\n\t\t\treturn nil, false\n\t\t}\n\t}\n", m)
		}
		b.WriteString("\treturn nil, false\n")
	case *grammar.Repeat:
		g.repeat(&b, e, s, build)
	case *grammar.Optional:
		m := g.expr(e.Expr, s, build)
		fmt.Fprintf(&b, "\tm0 := p.mark()\n\tprevCut := p.cut\n\tp.cut = false\n\tv, ok := p.%s()\n\tcut := p.cut\n\tp.cut = prevCut\n"+
			"\tif ok {\n\t\treturn v, true\n\t}\n\tp.reset(m0)\n\tif cut {\n\t\treturn nil, false\n\t}\n\treturn nil, true\n", m)
	case *grammar.And:
		m := g.expr(e.Expr, s, build && hasCaptures(e.Expr))
		fmt.Fprintf(&b, "\tstart, prevCut := p.pos, p.cut\n\tp.silent++\n\t_, ok := p.%s()\n\tp.silent--\n\tp.cut = prevCut\n\tp.pos = start\n\treturn nil, ok\n", m)
	case *grammar.Not:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\tm0 := p.mark()\n\tprevCut := p.cut\n\tp.silent++\n\t_, ok := p.%s()\n\tp.silent--\n\tp.cut = prevCut\n\tp.reset(m0)\n\treturn nil, !ok\n", m)
	case *grammar.Atomic:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\tstart := p.pos\n\tif _, ok := p.%s(); !ok {\n\t\treturn nil, false\n\t}\n", m)
		if build {
			b.WriteString("\treturn p.newNode(Node{Type: \"Match\", Start: start, End: p.pos, Text: p.text(start, p.pos), terminal: true, fresh: true}), true\n")
		} else {
			b.WriteString("\t_ = start\n\treturn nil, true\n")
		}
	case *grammar.Discard:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "\t_, ok := p.%s()\n\treturn nil, ok\n", m)
	case *grammar.Capture:
		slot := s.slot(e.Name)
		m := g.expr(e.Expr, s, true)
		fmt.Fprintf(&b, "\tv, ok := p.%s()\n\tif ok {\n\t\tp.setCapture(%d, v)\n\t}\n", m, slot)
		if build {
			b.WriteString("\treturn v, ok\n")
		} else {
			b.WriteString("\treturn nil, ok\n")
		}
	case *grammar.Cut:
		b.WriteString("\tp.cut = true\n\treturn nil, true\n")
	case *grammar.Top:
		if build {
			b.WriteString("\treturn p.newNode(Node{Type: \"Match\", Start: p.pos, End: p.pos, terminal: true, fresh: true}), true\n")
		} else {
			b.WriteString("\treturn nil, true\n")
		}
	case *grammar.Bottom:
		b.WriteString("\treturn nil, false\n")
	case *grammar.BeginInput:
		b.WriteString("\treturn p.anchor(p.pos == 0, idBeginInput)\n")
	case *grammar.EndInput:
		b.WriteString("\treturn p.anchor(p.atEnd(), idEndInput)\n")
	case *grammar.BeginLine:
		b.WriteString("\treturn p.anchor(p.atLineStart(), idBeginLine)\n")
	case *grammar.EndLine:
		b.WriteString("\treturn p.anchor(p.atLineEnd(), idEndLine)\n")
	case *grammar.Predicate:
		if a, ok := e.Term.(*grammar.Assign); ok {
			fmt.Fprintf(&b, "\treturn nil, p.assign(%q, func(c *actx) any { return %s })\n", a.Name, g.term(a.Value, s, nil))
		} else {
			fmt.Fprintf(&b, "\treturn nil, p.predicate(func(c *actx) any { return %s })\n", g.term(e.Term, s, nil))
		}
	case *grammar.Attributed:
		return g.attributed(e, s, build)
	default:
		panic(fmt.Sprintf("unsupported expression %T", e))
	}
	return g.method(describe(e), b.String())
}

func (g *generator) repeat(b *strings.Builder, e *grammar.Repeat, s *scope, build bool) {
	if !build && g.scanRepeat(b, e) {
		return
	}
	// An element with captures has its own scope per iteration.
	elemScope := s
	if hasCaptures(e.Expr) {
		elemScope = newScope()
	}
	m := g.expr(e.Expr, elemScope, build)
	own := elemScope != s
	if build {
		// Element values are gathered on p.kidStack and copied out once.
		b.WriteString("\tstart := p.pos\n\tbase := len(p.kidStack)\n")
	}
	b.WriteString("\tcount := 0\n")
	if e.Max < 0 {
		b.WriteString("\tfor {\n")
	} else {
		fmt.Fprintf(b, "\tfor n := 0; n < %d; n++ {\n", e.Max)
	}
	b.WriteString("\t\tm0 := p.mark()\n\t\tprevCut, prevFrame := p.cut, p.frame\n\t\tp.cut = false\n")
	scopeVar := ""
	if own {
		scopeVar = g.name("scope")
		fmt.Fprintf(&g.vars, "var %s = %s\n", scopeVar, goStrings(elemScope.names))
		fmt.Fprintf(b, "\t\tf := p.newFrame(%d)\n\t\tp.frame = f\n", len(elemScope.names))
	}
	if build {
		fmt.Fprintf(b, "\t\tv, ok := p.%s()\n", m)
	} else {
		fmt.Fprintf(b, "\t\t_, ok := p.%s()\n", m)
	}
	b.WriteString("\t\tcut := p.cut\n\t\tp.cut, p.frame = prevCut, prevFrame\n\t\tif !ok {\n\t\t\tp.reset(m0)\n\t\t\tif cut {\n")
	if build {
		b.WriteString("\t\t\t\tp.dropKids(base)\n")
	}
	b.WriteString("\t\t\t\treturn nil, false\n\t\t\t}\n\t\t\tbreak\n\t\t}\n")
	if own && build {
		fmt.Fprintf(b, "\t\tv = p.attachCaptures(v, %s, f, m0.pos, p.pos)\n", scopeVar)
	}
	b.WriteString("\t\tcount++\n")
	if build {
		b.WriteString("\t\tp.kidStack = append(p.kidStack, v)\n")
	}
	fmt.Fprintf(b, "\t\tif p.pos == m0.pos && count >= %d {\n\t\t\tbreak\n\t\t}\n\t}\n", e.Min)
	fmt.Fprintf(b, "\tif count < %d {\n", e.Min)
	if build {
		b.WriteString("\t\tp.dropKids(base)\n")
	}
	b.WriteString("\t\treturn nil, false\n\t}\n")
	if !build {
		b.WriteString("\treturn nil, true\n")
		return
	}
	b.WriteString("\treturn p.newNode(Node{Type: \"List\", Start: start, End: p.pos, Children: p.kids(base), fresh: true}), true\n")
}

// scanRepeat generates a value-free repetition of a single-character expression (a character
// class or .) as a scan loop without per-iteration backtracking state, like the engine's
// compiler.scanRepeat. It reports whether e qualifies. Expectations are recorded as in a general
// repetition: once, where the element last failed.
func (g *generator) scanRepeat(b *strings.Builder, e *grammar.Repeat) bool {
	var cond string
	switch x := e.Expr.(type) {
	case *grammar.CharClass:
		cond = fmt.Sprintf("!ok || %s {\n\t\t\tp.expect(p.pos, %d)", classReject(x), g.desc(charClassString(x)))
		b.WriteString("\tcount := 0\n")
	case *grammar.Any:
		cond = "!ok {\n\t\t\tp.expect(p.pos, idAny)"
		b.WriteString("\tcount := 0\n")
	default:
		return false
	}
	if e.Max < 0 {
		b.WriteString("\tfor {\n")
	} else {
		fmt.Fprintf(b, "\tfor count < %d {\n", e.Max)
	}
	if _, isAny := e.Expr.(*grammar.Any); isAny {
		b.WriteString("\t\t_, size, ok := p.peek()\n")
	} else {
		b.WriteString("\t\tch, size, ok := p.peek()\n")
	}
	fmt.Fprintf(b, "\t\tif %s\n\t\t\tbreak\n\t\t}\n\t\tp.pos += size\n\t\tcount++\n\t}\n", cond)
	fmt.Fprintf(b, "\treturn nil, count >= %d\n", e.Min)
	return true
}

// classReject returns a Go condition on ch that is true when ch is not accepted by the class.
func classReject(e *grammar.CharClass) string {
	var in []string
	for _, r := range e.Ranges {
		if r.Lo == r.Hi {
			in = append(in, fmt.Sprintf("ch == %d", r.Lo))
		} else {
			in = append(in, fmt.Sprintf("ch >= %d && ch <= %d", r.Lo, r.Hi))
		}
	}
	if len(in) == 0 {
		in = []string{"ch < 0"} // never true; mentions ch so that it is used
	}
	cond := strings.Join(in, " || ")
	if e.Negated {
		return "(" + cond + ")"
	}
	return "!(" + cond + ")"
}

func (g *generator) attributed(e *grammar.Attributed, s *scope, build bool) string {
	m := g.expr(e.Expr, s, build)
	for _, a := range e.Attrs {
		switch a.Name {
		case "error":
			msg := a.Args[0].Value.(*grammar.Literal).Value
			m = g.method("#error", fmt.Sprintf("\treturn p.errorAttr((*parser).%s, msgBit|%d)\n", m, g.desc(msg)))
		case "recover":
			skipExpr, _ := a.Arg("skip")
			skip := g.expr(skipExpr, s, false)
			m = g.method("#recover", fmt.Sprintf("\treturn p.recoverAttr((*parser).%s, (*parser).%s, %v)\n", m, skip, build))
		}
	}
	return m
}

func (g *generator) pratt(r *rule, e *grammar.Pratt) {
	var b strings.Builder
	fmt.Fprintf(&b, "\trules[%d].pratt = &pratt{\n", r.id)
	if e.Skip != nil {
		fmt.Fprintf(&b, "\t\tskip: (*parser).%s,\n", g.expr(e.Skip, newScope(), false))
	}
	b.WriteString("\t\toperands: []*prattLine{\n")
	for _, o := range e.Operands {
		fmt.Fprintf(&b, "\t\t\t%s,\n", g.prattLine(o.Expr, o.Action, false))
	}
	b.WriteString("\t\t},\n")
	var prefix, led []string
	id := 0
	for i, l := range e.Levels {
		for _, op := range l.Operators {
			s := fmt.Sprintf("{id: %d, kind: %q, assoc: %q, level: %d, line: %s}", id, op.Kind, op.Assoc, i+1, g.prattLine(op.Expr, op.Action, true))
			id++
			if op.Kind == grammar.Prefix {
				prefix = append(prefix, s)
			} else {
				led = append(led, s)
			}
		}
	}
	fmt.Fprintf(&b, "\t\tprefix: []*prattOp{%s},\n", strings.Join(prefix, ",\n"))
	fmt.Fprintf(&b, "\t\tled: []*prattOp{%s},\n", strings.Join(led, ",\n"))
	b.WriteString("\t}\n")
	fmt.Fprintf(&b, "\trules[%d].body = func(p *parser, min int) (*Node, bool) { return p.prattParse(rules[%d], min) }\n", r.id, r.id)
	g.init.WriteString(b.String())
}

func (g *generator) prattLine(e grammar.Expr, action grammar.Term, operator bool) string {
	s := newScope()
	var locals []string
	if operator {
		locals = []string{"lhs", "rhs", "op"}
	}
	// Lines whose value is unused are matched without values, as in the engine.
	m := g.expr(e, s, !leanLine(action, locals))
	_, isSeq := e.(*grammar.Seq)
	act := "nil"
	if action != nil {
		var locals map[string]string
		if operator {
			locals = map[string]string{"lhs": "c.lhs", "rhs": "c.rhs", "op": "c.op"}
		}
		act = fmt.Sprintf("func(c *actx) any { return %s }", g.term(action, s, locals))
	}
	return fmt.Sprintf("&prattLine{scope: %s, m: (*parser).%s, action: %s, isSeq: %v}", goStrings(s.names), m, act, isSeq)
}

// term converts a value expression into a Go expression of type any. locals maps names, such as lambda
// parameters, to Go expressions.
func (g *generator) term(t grammar.Term, s *scope, locals map[string]string) string {
	switch t := t.(type) {
	case *grammar.IntLit:
		return fmt.Sprintf("any(%d)", t.Value)
	case *grammar.StringLit:
		return fmt.Sprintf("any(%q)", t.Value)
	case *grammar.BoolLit:
		return fmt.Sprintf("any(%v)", t.Value)
	case *grammar.NilLit:
		return "any(nil)"
	case *grammar.CaptureRef:
		if l, ok := locals[t.Name]; ok {
			return l
		}
		return fmt.Sprintf("c.cap(%d)", s.slots[t.Name])
	case *grammar.IndexRef:
		return fmt.Sprintf("c.item(%d)", t.Index)
	case *grammar.VarRef:
		return fmt.Sprintf("c.lookup(%q)", t.Name)
	case *grammar.Member:
		return fmt.Sprintf("c.member(%s, %q)", g.term(t.X, s, locals), t.Name)
	case *grammar.New:
		args := []string{strconv.Quote(t.Type)}
		for _, f := range t.Fields {
			args = append(args, strconv.Quote(f.Name), g.term(f.Value, s, locals))
		}
		return "c.newStruct(" + strings.Join(args, ", ") + ")"
	case *grammar.Call:
		args := make([]string, len(t.Args))
		for i, a := range t.Args {
			if _, ok := a.(*grammar.Lambda); !ok {
				args[i] = g.term(a, s, locals)
			}
		}
		switch t.Func {
		case "len":
			return "c.length(" + args[0] + ")"
		case "text":
			return "c.text(" + args[0] + ")"
		case "foldl", "foldr":
			return fmt.Sprintf("rtFold(%q, %v, %s, %s, %s)", t.Func, t.Func == "foldr", args[0], args[1], g.lambda(t.Args[2], s, locals))
		case "map":
			return fmt.Sprintf("c.mapList(%s, %s)", args[0], g.lambda(t.Args[1], s, locals))
		case "list":
			return "c.list(" + strings.Join(args, ", ") + ")"
		case "concat":
			return "c.concat(" + strings.Join(args, ", ") + ")"
		}
	case *grammar.Binary:
		l, r := g.term(t.L, s, locals), g.term(t.R, s, locals)
		switch t.Op {
		case "&&":
			return fmt.Sprintf("rtAnd(%s, func() any { return %s })", l, r)
		case "||":
			return fmt.Sprintf("rtOr(%s, func() any { return %s })", l, r)
		}
		return fmt.Sprintf("rtBinary(%q, %s, %s)", t.Op, l, r)
	case *grammar.Unary:
		return fmt.Sprintf("rtUnary(%q, %s)", t.Op, g.term(t.X, s, locals))
	}
	panic(fmt.Sprintf("unsupported term %T", t))
}

func (g *generator) lambda(t grammar.Term, s *scope, locals map[string]string) string {
	l := t.(*grammar.Lambda)
	inner := map[string]string{}
	for k, v := range locals {
		inner[k] = v
	}
	params := make([]string, len(l.Params))
	for i, p := range l.Params {
		params[i] = g.name("l_")
		inner[p] = params[i]
	}
	return fmt.Sprintf("func(%s any) any { return %s }", strings.Join(params, ", "), g.term(l.Body, s, inner))
}
