package engine

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"

	"github.com/ornew/pego/grammar"
)

//go:embed tsrt/runtime.ts
var tsRuntimeSource string

// tsRuntimeMarker starts the part of tsrt/runtime.ts that is copied into generated code.
const tsRuntimeMarker = "// --- Runtime ---\n"

// GenerateTS generates the source code of a TypeScript parser for a grammar: a single ES module
// without dependencies that behaves exactly like the engine (and the generated Go parsers).
//
// Each parsing expression becomes a function and actions and predicates become TypeScript
// expressions, as in Generate; the embedded runtime (tsrt/runtime.ts) mirrors genrt. opts.Package
// is not used, and opts.Types is not supported.
func GenerateTS(g *grammar.Grammar, opts GenOptions) ([]byte, error) {
	if opts.Types {
		return nil, fmt.Errorf("typed values are not supported for TypeScript")
	}
	prog, err := Compile(g, Options{})
	if err != nil {
		return nil, err
	}
	start := prog.byName[opts.Start]
	if start == nil {
		return nil, fmt.Errorf("start rule %s is not defined", opts.Start)
	}
	gen := &tsGen{generator: &generator{prog: prog, table: "rules"}, plainUsed: map[*rule]bool{}}
	gen.desc(fixedDescs[0]) // the fixed expectations come first
	gen.rules()
	var rec *Program
	if opts.Recognize {
		if rec, err = prog.recognizer(); err != nil {
			return nil, err
		}
		gen.prog, gen.table = rec, "recRules"
		gen.rules()
		gen.prog, gen.table = prog, "rules"
	}

	var out strings.Builder
	out.WriteString("// Code generated by pego. DO NOT EDIT.\n\n")
	out.WriteString("// A parser generated from a PEGO grammar. It has no dependencies; see parse below.\n\n")
	out.WriteString("/* eslint-disable */\n\n")
	i := strings.Index(tsRuntimeSource, tsRuntimeMarker)
	out.WriteString(tsRuntimeSource[i+len(tsRuntimeMarker):])
	out.WriteString("\n// --- Generated code ---\n\n")
	fmt.Fprintf(&out, "/**\n * Parses the whole input with the rule %s. unit selects the position unit (CodePoints by default).\n", start.name)
	out.WriteString(" * A string is parsed as its UTF-8 encoding would be (lone surrogates as U+FFFD), and bytes are\n")
	out.WriteString(" * decoded as UTF-8 (invalid sequences as U+FFFD, one per byte). If the parse recovered from errors\n")
	out.WriteString(" * with #recover, the result has both the node and SyntaxErrors.\n */\n")
	fmt.Fprintf(&out, "export function parse(input: string | Uint8Array, unit?: Unit): ParseResult {\n  return run(R%d, nseen, input, unit);\n}\n\n", start.id)
	out.WriteString(`/** Parses the whole input with the rule name. */
export function parseRule(name: string, input: string | Uint8Array, unit?: Unit): ParseResult {
  const r = ruleIn(rules, name);
  if (r === null) {
    return { node: null, error: new Error(` + "`rule ${name} is not defined`" + `) };
  }
  return run(r, nseen, input, unit);
}

`)
	if rec != nil {
		fmt.Fprintf(&out, "/**\n * Checks that the whole input matches the rule %s without building a tree, and returns the syntax\n", start.name)
		out.WriteString(" * error parse would return (SyntaxErrors for errors recovered with #recover), or null. Actions are not\n")
		out.WriteString(" * evaluated, so it does not report runtime errors in actions.\n */\n")
		fmt.Fprintf(&out, "export function recognize(input: string | Uint8Array, unit?: Unit): Error | null {\n  return run(Q%d, recNseen, input, unit).error;\n}\n\n", rec.byName[start.name].id)
	}
	out.WriteString(gen.vars.String())
	fmt.Fprintf(&out, "\ndescs = %s;\n", tsStrings(gen.descs))
	fmt.Fprintf(&out, "printRuns = %q;\n\n", tsPrintRuns())
	out.WriteString(gen.init.String())
	out.WriteString("\n")
	out.WriteString(gen.methods.String())
	return []byte(out.String()), nil
}

// tsPrintRuns returns the code points that strconv.IsPrint accepts, for the runtime's quoteGo: the
// lengths of the alternating runs of code points that it rejects and accepts, from U+0000, in base
// 36 separated by commas (about 3 KB). Writing the table of the Go that generates the parser, rather
// than relying on the JavaScript runtime's Unicode properties, makes toString quote as the engine's
// Node.String does even where their Unicode versions differ.
var tsPrintRuns = sync.OnceValue(func() string {
	var b strings.Builder
	prev, start := false, 0
	for r := 0; r <= unicode.MaxRune; r++ {
		if p := strconv.IsPrint(rune(r)); p != prev {
			if b.Len() > 0 {
				b.WriteByte(',')
			}
			b.WriteString(strconv.FormatInt(int64(r-start), 36))
			prev, start = p, r
		}
	}
	return b.String()
})

// tsGen generates TypeScript. It shares the expectation table, names and analyses of generator.
type tsGen struct {
	*generator
	// plainUsed holds the plain rules whose function (plainCall) is called.
	plainUsed map[*rule]bool
}

// tsString returns s as a TypeScript string literal (JSON is valid TypeScript).
func tsString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

func tsStrings(xs []string) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = tsString(x)
	}
	return "[" + strings.Join(q, ", ") + "]"
}

func tsInts[T ~int32 | ~byte](xs []T) string {
	q := make([]string, len(xs))
	for i, x := range xs {
		q[i] = strconv.Itoa(int(x))
	}
	return "[" + strings.Join(q, ", ") + "]"
}

// tsCond converts a condition on ch written by first or classReject to TypeScript.
func tsCond(cond string) string {
	return strings.ReplaceAll(cond, " == ", " === ")
}

// tsMark declares the variables of a mark (parser.mark in genrt) with the given indentation, and
// tsReset returns to it.
func tsMark(indent string) string {
	return indent + "const m0pos = p.pos;\n" + indent + "const m0env = p.env;\n" + indent + "const m0trail = p.trail.length;\n" + indent + "const m0rec = p.recovered.length;\n"
}

const tsReset = "p.reset(m0pos, m0env, m0trail, m0rec);"

func (g *tsGen) seenVar() string {
	if g.table == "rules" {
		return "nseen"
	}
	return "recNseen"
}

// ruleVar returns the constant that holds the rule r of the table being generated.
func (g *tsGen) ruleVar(r *rule) string {
	if g.table == "rules" {
		return fmt.Sprintf("R%d", r.id)
	}
	return fmt.Sprintf("Q%d", r.id)
}

func (g *tsGen) plainPrefix() string {
	if g.table == "rules" {
		return "r"
	}
	return "q"
}

// method emits a function of an expression with the given body and returns its name.
//
// The functions of expressions are called through call expressions (see expr), and fn turns a
// call expression into a function.
func (g *tsGen) method(comment, body string) string {
	name := g.name("e")
	if comment != "" {
		fmt.Fprintf(&g.methods, "// %s\n", comment)
	}
	param := "p"
	if !strings.Contains(body, "p.") && !strings.Contains(body, "(p)") {
		param = "_p" // not reported as unused (the body is in generated code only, without user text)
	}
	fmt.Fprintf(&g.methods, "function %s(%s: Parser): R {\n%s}\n\n", name, param, body)
	return name
}

// fn returns a function (a Matcher) that does what the call expression x does.
func (g *tsGen) fn(x string) string {
	if name, ok := strings.CutSuffix(x, "(p)"); ok && !strings.ContainsAny(name, "(). ") {
		return name
	}
	return g.method("", "  return "+x+";\n")
}

// action emits a function that evaluates the term t (an action or a predicate) and returns its name.
func (g *tsGen) action(t grammar.Term, s *scope, locals map[string]string) string {
	name := g.name("a")
	param := "c"
	if !tsUsesCtx(t, locals) {
		param = "_c" // not reported as unused
	}
	fmt.Fprintf(&g.methods, "function %s(%s: Actx): Value {\n  return %s;\n}\n\n", name, param, g.term(t, s, locals))
	return name
}

// tsUsesCtx reports whether the TypeScript expression term makes of t refers to the evaluation
// context c. locals are as for term.
func tsUsesCtx(t grammar.Term, locals map[string]string) bool {
	switch t := t.(type) {
	case *grammar.IntLit, *grammar.StringLit, *grammar.BoolLit, *grammar.NilLit:
		return false
	case *grammar.CaptureRef:
		l, ok := locals[t.Name]
		return !ok || strings.HasPrefix(l, "c.")
	case *grammar.Call:
		if t.Func != "foldl" && t.Func != "foldr" {
			return true
		}
		for _, a := range t.Args {
			if tsUsesCtx(a, locals) {
				return true
			}
		}
		return false
	case *grammar.Lambda:
		inner := map[string]string{}
		for k, v := range locals {
			inner[k] = v
		}
		for _, p := range t.Params {
			inner[p] = p
		}
		return tsUsesCtx(t.Body, inner)
	case *grammar.Binary:
		return tsUsesCtx(t.L, locals) || tsUsesCtx(t.R, locals)
	case *grammar.Unary:
		return tsUsesCtx(t.X, locals)
	}
	return true // IndexRef, VarRef, Member, New
}

func (g *tsGen) rules() {
	init := &g.init
	bodies := map[*rule]string{}
	scopes := map[*rule]*scope{}
	all := append(append([]*rule(nil), g.prog.rules...), g.prog.twins...)
	for _, r := range all {
		s := newScope()
		scopes[r] = s
		if _, ok := r.def.Expr.(*grammar.Pratt); !ok {
			g.cur, g.proj = r, g.projections(r)
			bodies[r] = g.expr(r.def.Expr, s, !r.lean)
			g.proj = nil
		}
	}
	// Each rule is a constant, which the generated code refers to.
	var vars []string
	for _, r := range all {
		fmt.Fprintf(init, "const %s = mkRule(%d, %s, %s, %v, %s, %v, %v, %d, %v, %s);\n", g.ruleVar(r),
			r.id, tsString(r.name), tsStrings(scopes[r].names), r.bodyIsSeq, tsString(r.terminalType), r.memo && !r.transient, r.leader, r.seen, r.novalue, tsStrings(r.vars))
		vars = append(vars, g.ruleVar(r))
	}
	if g.table == "rules" {
		// The table, for parseRule (the recognizer has none).
		fmt.Fprintf(init, "const rules: Rule[] = [%s];\n", strings.Join(vars, ", "))
	}
	fmt.Fprintf(init, "const %s = %d;\n", g.seenVar(), g.prog.nseen)
	for _, r := range all {
		if pr, ok := r.def.Expr.(*grammar.Pratt); ok {
			g.cur = r
			g.pratt(r, pr)
			continue
		}
		fmt.Fprintf(init, "%s.body = %s;\n", g.ruleVar(r), g.fn(bodies[r]))
		if r.action != nil {
			g.proj = g.projections(r)
			fmt.Fprintf(init, "%s.action = %s;\n", g.ruleVar(r), g.action(r.action, scopes[r], nil))
			g.proj = nil
		}
	}
	// The functions of plain rules that are called (all calls are generated by now).
	for _, r := range all {
		if g.plainUsed[r] {
			g.plainCall(r, bodies[r])
		}
	}
	if g.table != "rules" {
		return // the recognizer shares the struct fields
	}
	// Struct fields, used to detect references to undeclared fields at run time.
	var names []string
	for name, spec := range g.prog.types {
		if _, ok := spec.(*grammar.StructSpec); ok {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		var fields []string
		for _, f := range g.prog.types[name].(*grammar.StructSpec).Fields {
			fields = append(fields, f.Name)
		}
		fmt.Fprintf(init, "structFields.set(%s, new Set(%s));\n", tsString(name), tsStrings(fields))
	}
}

// plainCall writes the function r<id>, which does what invokePlain does for the rule r (a rule never
// memoized and without captures) with a direct call of its body.
func (g *tsGen) plainCall(r *rule, body string) {
	m := &g.methods
	fmt.Fprintf(m, "// %s, called as by invokePlain\nfunction %s%d(p: Parser): R {\n", r.name, g.plainPrefix(), r.id)
	m.WriteString(`  const start = p.pos;
  const rec = p.recovered.length;
  const trail = p.trail.length;
  const prevEnv = p.env;
  const prevCut = p.cut;
  p.cut = false;
  if (++p.depth > maxDepth) {
    p.tooDeep();
  }
`)
	fmt.Fprintf(m, "  let v = %s;\n", body)
	m.WriteString(`  p.depth--;
  p.cut = prevCut;
  p.trail.length = trail;
  if (v !== undefined) {
`)
	if r.novalue {
		m.WriteString("    v = null;\n")
	} else {
		fmt.Fprintf(m, "    v = p.finish(%s, emptyFrame, v, start);\n", g.ruleVar(r))
	}
	m.WriteString(`  } else {
    p.pos = start;
    p.recovered.length = rec;
  }
  p.env = prevEnv;
  return v;
}

`)
}

// projectRepeat writes a repetition that gathers the values of the capture field of its elements
// (see projections). The elements build no values of their own, and share one capture frame.
func (g *tsGen) projectRepeat(b *strings.Builder, e *grammar.Repeat, field string) {
	elemScope := newScope()
	m := g.expr(e.Expr, elemScope, false)
	slot := elemScope.slots[field]
	fmt.Fprintf(b, "  const start = p.pos;\n  const base = p.kidStack.length;\n  const f = p.newFrame(%d);\n  let count = 0;\n", len(elemScope.names))
	if e.Max < 0 {
		b.WriteString("  for (;;) {\n")
	} else {
		fmt.Fprintf(b, "  for (let n = 0; n < %d; n++) {\n", e.Max)
	}
	b.WriteString("    f.fill(null);\n" + tsMark("    ") + "    const prevCut = p.cut;\n    const prevFrame = p.frame;\n    p.cut = false;\n    p.frame = f;\n")
	fmt.Fprintf(b, "    const v = %s;\n", m)
	b.WriteString("    const cut = p.cut;\n    p.cut = prevCut;\n    p.frame = prevFrame;\n    if (v === undefined) {\n      " + tsReset + "\n      if (cut) {\n        p.dropKids(base);\n        return undefined;\n      }\n      break;\n    }\n")
	fmt.Fprintf(b, "    count++;\n    p.kidStack.push(f[%d]!);\n", slot)
	b.WriteString("    if (p.pos === m0pos) {\n      break;\n    }\n  }\n")
	fmt.Fprintf(b, "  if (count < %d) {\n    p.dropKids(base);\n    return undefined;\n  }\n", e.Min)
	b.WriteString("  return new Node(\"List\", \"\", start, p.pos, \"\", p.kids(base), noFields, true, false);\n")
}

// expr returns a TypeScript call expression of type R that matches e. Most expressions become a
// function of their own, called as e<n>(p); literals, . , anchors and rule calls are called
// directly, which saves a stack frame per call (JavaScript stacks are small).
func (g *tsGen) expr(e grammar.Expr, s *scope, build bool) string {
	var b strings.Builder
	switch e := e.(type) {
	case *grammar.Literal:
		v := g.name("lit")
		fmt.Fprintf(&g.vars, "const %s: Lit = { text: %s, cps: %s, bytes: %s };\n", v, tsString(e.Value), tsInts([]rune(e.Value)), tsInts([]byte(e.Value)))
		return fmt.Sprintf("p.matchLiteral(%s, %d, %v)", v, g.desc(strconv.Quote(e.Value)), build)
	case *grammar.CharClass:
		fmt.Fprintf(&b, "  const ch = p.peek();\n  if (ch < 0 || %s) {\n    p.expect(p.pos, %d);\n    return undefined;\n  }\n",
			tsCond(classReject(e)), g.desc(charClassString(e)))
		fmt.Fprintf(&b, "  return p.single(p.psize, %v);\n", build)
	case *grammar.Any:
		return fmt.Sprintf("p.matchAny(%v)", build)
	case *grammar.Ref:
		r := g.prog.byName[e.Name]
		min := 0
		if e.Level != "" {
			for i, l := range r.def.Expr.(*grammar.Pratt).Levels {
				if l.Name == e.Level {
					min = i
				}
			}
		}
		if !build && r.twin != nil {
			r = r.twin
		}
		_, pratt := r.def.Expr.(*grammar.Pratt)
		switch {
		case r.plain && !pratt:
			// Never memoized and without captures: call does nothing but invokePlain, which a
			// function of its own does with a direct call of the body (see plainCall).
			g.plainUsed[r] = true
			return fmt.Sprintf("%s%d(p)", g.plainPrefix(), r.id)
		case r.plain:
			return fmt.Sprintf("p.invokePlain(%s, %d)", g.ruleVar(r), min)
		default:
			return fmt.Sprintf("p.call(%s, %d)", g.ruleVar(r), min)
		}
	case *grammar.Seq:
		var items []string
		for _, it := range e.Items {
			items = append(items, g.expr(it, s, build))
		}
		if build {
			b.WriteString("  const start = p.pos;\n  const kids: (Node | null)[] = [];\n")
		}
		for i, it := range e.Items {
			if build && visible(it) {
				fmt.Fprintf(&b, "  const v%d = %s;\n  if (v%d === undefined) {\n    return undefined;\n  }\n  kids.push(v%d);\n", i, items[i], i, i)
			} else {
				fmt.Fprintf(&b, "  if (%s === undefined) {\n    return undefined;\n  }\n", items[i])
			}
		}
		if build {
			b.WriteString("  return new Node(\"Seq\", \"\", start, p.pos, \"\", kids, noFields, true, false);\n")
		} else {
			b.WriteString("  return null;\n")
		}
	case *grammar.Choice:
		b.WriteString(tsMark("  "))
		peeked := false
		for _, alt := range e.Alts {
			m := g.expr(alt, s, build)
			if cond, desc, depth, ok := g.first(alt, 0, map[string]bool{}); ok {
				// An alternative whose first terminal does not match the next character is skipped,
				// with the expectation it would record (see generator.first).
				if !peeked {
					b.WriteString("  const ch = p.peek();\n")
					peeked = true
				}
				fmt.Fprintf(&b, "  if (!(ch >= 0 && (%s)) && p.depth + %d <= maxDepth) {\n    p.expect(p.pos, %d);\n  } else ", tsCond(cond), depth, desc)
			} else {
				b.WriteString("  ")
			}
			fmt.Fprintf(&b, "{\n    const prevCut = p.cut;\n    p.cut = false;\n    const v = %s;\n    const cut = p.cut;\n    p.cut = prevCut;\n"+
				"    if (v !== undefined) {\n      return v;\n    }\n    %s\n    if (cut) {\n      return undefined;\n    }\n  }\n", m, tsReset)
		}
		b.WriteString("  return undefined;\n")
	case *grammar.Repeat:
		g.repeat(&b, e, s, build)
	case *grammar.Optional:
		m := g.expr(e.Expr, s, build)
		fmt.Fprintf(&b, "%s  const prevCut = p.cut;\n  p.cut = false;\n  const v = %s;\n  const cut = p.cut;\n  p.cut = prevCut;\n"+
			"  if (v !== undefined) {\n    return v;\n  }\n  %s\n  if (cut) {\n    return undefined;\n  }\n  return null;\n", tsMark("  "), m, tsReset)
	case *grammar.And:
		m := g.expr(e.Expr, s, build && hasCaptures(e.Expr))
		fmt.Fprintf(&b, "  const start = p.pos;\n  const prevCut = p.cut;\n  p.silent++;\n  const v = %s;\n  p.silent--;\n  p.cut = prevCut;\n  p.pos = start;\n  return v === undefined ? undefined : null;\n", m)
	case *grammar.Not:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "%s  const prevCut = p.cut;\n  p.silent++;\n  const v = %s;\n  p.silent--;\n  p.cut = prevCut;\n  %s\n  return v === undefined ? null : undefined;\n", tsMark("  "), m, tsReset)
	case *grammar.Atomic:
		m := g.expr(e.Expr, s, false)
		if build {
			fmt.Fprintf(&b, "  const start = p.pos;\n  if (%s === undefined) {\n    return undefined;\n  }\n", m)
			b.WriteString("  return new Node(\"Match\", \"\", start, p.pos, p.text(start, p.pos), noNodes, noFields, true, true);\n")
		} else {
			fmt.Fprintf(&b, "  return %s === undefined ? undefined : null;\n", m)
		}
	case *grammar.Discard:
		m := g.expr(e.Expr, s, false)
		fmt.Fprintf(&b, "  return %s === undefined ? undefined : null;\n", m)
	case *grammar.Capture:
		if !build && g.cur != nil && g.cur.predCaps != nil && !g.cur.predCaps[e.Name] {
			// In the recognizer, captures not referenced by predicates are not recorded (as in
			// the engine).
			return g.expr(e.Expr, s, false)
		}
		slot := s.slot(e.Name)
		var m string
		if field := g.proj[e.Name]; field != "" {
			var rb strings.Builder
			g.projectRepeat(&rb, e.Expr.(*grammar.Repeat), field)
			m = g.method(describe(e.Expr)+" (projected to "+field+")", rb.String()) + "(p)"
		} else {
			m = g.expr(e.Expr, s, true)
		}
		fmt.Fprintf(&b, "  const v = %s;\n  if (v !== undefined) {\n    p.setCapture(%d, v);\n  }\n", m, slot)
		if build {
			b.WriteString("  return v;\n")
		} else {
			b.WriteString("  return v === undefined ? undefined : null;\n")
		}
	case *grammar.Cut:
		b.WriteString("  p.cut = true;\n  return null;\n")
	case *grammar.Top:
		if build {
			b.WriteString("  return new Node(\"Match\", \"\", p.pos, p.pos, \"\", noNodes, noFields, true, true);\n")
		} else {
			b.WriteString("  return null;\n")
		}
	case *grammar.Bottom:
		b.WriteString("  return undefined;\n")
	case *grammar.BeginInput:
		return "p.anchor(p.pos === 0, idBeginInput)"
	case *grammar.EndInput:
		return "p.anchor(p.atEnd(), idEndInput)"
	case *grammar.BeginLine:
		return "p.anchor(p.atLineStart(), idBeginLine)"
	case *grammar.EndLine:
		return "p.anchor(p.atLineEnd(), idEndLine)"
	case *grammar.Predicate:
		if a, ok := e.Term.(*grammar.Assign); ok {
			fmt.Fprintf(&b, "  return p.assign(%s, %s) ? null : undefined;\n", tsString(a.Name), g.action(a.Value, s, nil))
		} else {
			fmt.Fprintf(&b, "  return p.predicate(%s) ? null : undefined;\n", g.action(e.Term, s, nil))
		}
	case *grammar.Attributed:
		return g.attributed(e, s, build)
	default:
		panic(fmt.Sprintf("unsupported expression %T", e))
	}
	return g.method(describe(e), b.String()) + "(p)"
}

func (g *tsGen) repeat(b *strings.Builder, e *grammar.Repeat, s *scope, build bool) {
	if !build && g.scanRepeat(b, e) {
		return
	}
	// An element with captures has its own scope per iteration (elementScoped).
	elemScope := s
	if elementScoped(e.Expr) {
		elemScope = newScope()
	}
	m := g.expr(e.Expr, elemScope, build)
	own := elemScope != s
	if build {
		// Element values are gathered on p.kidStack and copied out once.
		b.WriteString("  const start = p.pos;\n  const base = p.kidStack.length;\n")
	}
	b.WriteString("  let count = 0;\n")
	if e.Max < 0 {
		b.WriteString("  for (;;) {\n")
	} else {
		fmt.Fprintf(b, "  for (let n = 0; n < %d; n++) {\n", e.Max)
	}
	b.WriteString(tsMark("    ") + "    const prevCut = p.cut;\n    const prevFrame = p.frame;\n    p.cut = false;\n")
	scopeVar := ""
	if own {
		if build {
			scopeVar = g.name("scope")
			fmt.Fprintf(&g.vars, "const %s: string[] = %s;\n", scopeVar, tsStrings(elemScope.names))
		}
		fmt.Fprintf(b, "    const f = p.newFrame(%d);\n    p.frame = f;\n", len(elemScope.names))
	}
	fmt.Fprintf(b, "    let v = %s;\n", m)
	b.WriteString("    const cut = p.cut;\n    p.cut = prevCut;\n    p.frame = prevFrame;\n    if (v === undefined) {\n      " + tsReset + "\n      if (cut) {\n")
	if build {
		b.WriteString("        p.dropKids(base);\n")
	}
	b.WriteString("        return undefined;\n      }\n      break;\n    }\n")
	if own && build {
		fmt.Fprintf(b, "    v = p.attachCaptures(v, %s, f, m0pos, p.pos);\n", scopeVar)
	}
	b.WriteString("    count++;\n")
	if build {
		b.WriteString("    p.kidStack.push(v);\n")
	}
	b.WriteString("    if (p.pos === m0pos) {\n      break;\n    }\n  }\n")
	fmt.Fprintf(b, "  if (count < %d) {\n", e.Min)
	if build {
		b.WriteString("    p.dropKids(base);\n")
	}
	b.WriteString("    return undefined;\n  }\n")
	if !build {
		b.WriteString("  return null;\n")
		return
	}
	b.WriteString("  return new Node(\"List\", \"\", start, p.pos, \"\", p.kids(base), noFields, true, false);\n")
}

// scanRepeat generates a value-free repetition of a single-character expression (a character
// class or .) as a scan loop without per-iteration backtracking state, like generator.scanRepeat.
func (g *tsGen) scanRepeat(b *strings.Builder, e *grammar.Repeat) bool {
	var cond string
	switch x := e.Expr.(type) {
	case *grammar.CharClass:
		cond = fmt.Sprintf("ch < 0 || %s) {\n      p.expect(p.pos, %d);", tsCond(classReject(x)), g.desc(charClassString(x)))
	case *grammar.Any:
		cond = "ch < 0) {\n      p.expect(p.pos, idAny);"
	default:
		return false
	}
	b.WriteString("  let count = 0;\n")
	if e.Max < 0 {
		b.WriteString("  for (;;) {\n")
	} else {
		fmt.Fprintf(b, "  while (count < %d) {\n", e.Max)
	}
	fmt.Fprintf(b, "    const ch = p.peek();\n    if (%s\n      break;\n    }\n    p.pos += p.psize;\n    count++;\n  }\n", cond)
	fmt.Fprintf(b, "  return count >= %d ? null : undefined;\n", e.Min)
	return true
}

func (g *tsGen) attributed(e *grammar.Attributed, s *scope, build bool) string {
	m := g.expr(e.Expr, s, build)
	for _, a := range e.Attrs {
		switch a.Name {
		case "error":
			msg := a.Args[0].Value.(*grammar.Literal).Value
			m = g.method("#error", fmt.Sprintf("  return p.errorAttr(%s, msgBit | %d);\n", g.fn(m), g.desc(msg))) + "(p)"
		case "recover":
			skipExpr, _ := a.Arg("skip")
			skip := g.expr(skipExpr, s, false)
			m = g.method("#recover", fmt.Sprintf("  return p.recoverAttr(%s, %s, %v);\n", g.fn(m), g.fn(skip), build && visible(e.Expr))) + "(p)"
		}
	}
	return m
}

func (g *tsGen) pratt(r *rule, e *grammar.Pratt) {
	var b strings.Builder
	fmt.Fprintf(&b, "%s.pratt = {\n", g.ruleVar(r))
	if e.Skip != nil {
		fmt.Fprintf(&b, "  skip: %s,\n", g.fn(g.expr(e.Skip, newScope(), false)))
	} else {
		b.WriteString("  skip: null,\n")
	}
	b.WriteString("  operands: [\n")
	for _, o := range e.Operands {
		fmt.Fprintf(&b, "    %s,\n", g.prattLine(o.Expr, o.Action, false))
	}
	b.WriteString("  ],\n")
	var prefix, led []string
	id := 0
	for i, l := range e.Levels {
		for _, op := range l.Operators {
			s := fmt.Sprintf("    { id: %d, kind: %s, assoc: %s, level: %d, line: %s },\n", id, tsString(op.Kind), tsString(op.Assoc), i+1, g.prattLine(op.Expr, op.Action, true))
			id++
			if op.Kind == grammar.Prefix {
				prefix = append(prefix, s)
			} else {
				led = append(led, s)
			}
		}
	}
	fmt.Fprintf(&b, "  prefix: [\n%s  ],\n", strings.Join(prefix, ""))
	fmt.Fprintf(&b, "  led: [\n%s  ],\n", strings.Join(led, ""))
	b.WriteString("};\n")
	fmt.Fprintf(&b, "%s.body = (p: Parser, min: number): R => p.prattParse(%s, min);\n", g.ruleVar(r), g.ruleVar(r))
	g.init.WriteString(b.String())
}

func (g *tsGen) prattLine(e grammar.Expr, action grammar.Term, operator bool) string {
	s := newScope()
	var locals []string
	if operator {
		locals = []string{"lhs", "rhs", "op"}
	}
	// Lines whose value is unused are matched without values, as in the engine; so are all lines
	// of a rule without a value (in the recognizer).
	m := g.fn(g.expr(e, s, !g.cur.novalue && !leanLine(action, locals)))
	_, isSeq := e.(*grammar.Seq)
	act := "null"
	if action != nil && !g.cur.novalue {
		var locals map[string]string
		if operator {
			locals = map[string]string{"lhs": "c.lhs", "rhs": "c.rhs", "op": "c.op"}
		}
		act = g.action(action, s, locals)
	}
	return fmt.Sprintf("{ scope: %s, m: %s, action: %s, isSeq: %v }", tsStrings(s.names), m, act, isSeq)
}

// tsInt returns the TypeScript value of the int v: a number when it is a safe integer, otherwise a
// bigint (see the runtime's ints).
func tsInt(v int) string {
	const maxSafe = 1<<53 - 1
	if v >= -maxSafe && v <= maxSafe {
		return strconv.Itoa(v)
	}
	return "BigInt(\"" + strconv.Itoa(v) + "\")"
}

// term converts a value expression into a TypeScript expression of type Value. locals maps names,
// such as lambda parameters, to TypeScript expressions.
func (g *tsGen) term(t grammar.Term, s *scope, locals map[string]string) string {
	switch t := t.(type) {
	case *grammar.IntLit:
		return tsInt(t.Value)
	case *grammar.StringLit:
		return tsString(t.Value)
	case *grammar.BoolLit:
		return strconv.FormatBool(t.Value)
	case *grammar.NilLit:
		return "null"
	case *grammar.CaptureRef:
		if l, ok := locals[t.Name]; ok {
			return l
		}
		return fmt.Sprintf("c.cap(%d)", s.slots[t.Name])
	case *grammar.IndexRef:
		return fmt.Sprintf("c.item(%d)", t.Index)
	case *grammar.VarRef:
		return fmt.Sprintf("c.lookup(%s)", tsString(t.Name))
	case *grammar.Member:
		return fmt.Sprintf("c.member(%s, %s)", g.term(t.X, s, locals), tsString(t.Name))
	case *grammar.New:
		name, _ := g.prog.structType(t.Type)
		args := []string{tsString(name)}
		for _, f := range t.Fields {
			args = append(args, tsString(f.Name), g.term(f.Value, s, locals))
		}
		return "c.newStruct(" + strings.Join(args, ", ") + ")"
	case *grammar.Call:
		if t.Func == "concat" && fusable(t) {
			// Push the elements of list, map and concat arguments directly (see fusable and
			// evalCtx.pushConcatArg).
			var b strings.Builder
			b.WriteString("((): Value => { const b = c.p.kidStack.length; ")
			g.concatParts(&b, t, s, locals)
			b.WriteString("return c.endList(b); })()")
			return b.String()
		}
		args := make([]string, len(t.Args))
		for i, a := range t.Args {
			if _, ok := a.(*grammar.Lambda); !ok {
				args[i] = g.term(a, s, locals)
			}
		}
		switch t.Func {
		case "len":
			return "c.length(" + args[0] + ")"
		case "text":
			return "c.text(" + args[0] + ")"
		case "foldl", "foldr":
			return fmt.Sprintf("rtFold(%s, %v, %s, %s, %s)", tsString(t.Func), t.Func == "foldr", args[0], args[1], g.lambda(t.Args[2], s, locals))
		case "map":
			if x, ok := g.projected(t, locals); ok {
				return "c.newList(listItems(\"map\", " + g.term(x, s, locals) + "))"
			}
			return fmt.Sprintf("c.mapList(%s, %s)", args[0], g.lambda(t.Args[1], s, locals))
		case "list":
			return "c.list(" + strings.Join(args, ", ") + ")"
		case "concat":
			return "c.concat(" + strings.Join(args, ", ") + ")"
		}
	case *grammar.Binary:
		if lx, ok := textArg(t.L); ok && (t.Op == "==" || t.Op == "!=") {
			if rx, ok := textArg(t.R); ok {
				// Compare the strings directly (see evalCtx.binary).
				return fmt.Sprintf("(c.textStr(%s) %s= c.textStr(%s))", g.term(lx, s, locals), t.Op, g.term(rx, s, locals))
			}
		}
		l, r := g.term(t.L, s, locals), g.term(t.R, s, locals)
		switch t.Op {
		case "&&":
			return fmt.Sprintf("rtAnd(%s, (): Value => %s)", l, r)
		case "||":
			return fmt.Sprintf("rtOr(%s, (): Value => %s)", l, r)
		}
		return fmt.Sprintf("rtBinary(%s, %s, %s)", tsString(t.Op), l, r)
	case *grammar.Unary:
		return fmt.Sprintf("rtUnary(%s, %s)", tsString(t.Op), g.term(t.X, s, locals))
	}
	panic(fmt.Sprintf("unsupported term %T", t))
}

// concatParts writes the statements that push the elements of the arguments of the concat call t.
func (g *tsGen) concatParts(b *strings.Builder, t *grammar.Call, s *scope, locals map[string]string) {
	for _, a := range t.Args {
		call, ok := a.(*grammar.Call)
		switch {
		case ok && call.Func == "list":
			args := make([]string, len(call.Args))
			for i, x := range call.Args {
				args[i] = g.term(x, s, locals)
			}
			b.WriteString("c.pushList(" + strings.Join(args, ", ") + "); ")
		case ok && call.Func == "map" && len(call.Args) == 2:
			if x, ok := g.projected(call, locals); ok {
				b.WriteString("c.pushItems(" + g.term(x, s, locals) + "); ")
				break
			}
			fmt.Fprintf(b, "c.pushMap(%s, %s); ", g.term(call.Args[0], s, locals), g.lambda(call.Args[1], s, locals))
		case ok && call.Func == "concat":
			g.concatParts(b, call, s, locals)
		default:
			b.WriteString("c.pushItems(" + g.term(a, s, locals) + "); ")
		}
	}
}

func (g *tsGen) lambda(t grammar.Term, s *scope, locals map[string]string) string {
	l := t.(*grammar.Lambda)
	inner := map[string]string{}
	for k, v := range locals {
		inner[k] = v
	}
	params := make([]string, len(l.Params))
	for i, p := range l.Params {
		params[i] = g.name("_l") // a leading _: an unused parameter is not reported
		inner[p] = params[i]
	}
	for i := range params {
		params[i] += ": Value"
	}
	return fmt.Sprintf("(%s): Value => %s", strings.Join(params, ", "), g.term(l.Body, s, inner))
}
