alter table x set (a=1);
alter table x alter column a set (a=1);
alter table x alter a set statistics 5;
alter table x alter a set statistics default;
alter table x alter 3 set statistics -5;
alter table x alter a set storage plain;
alter table x alter a set compression default;
alter table x alter a add generated always as identity (start 1);
alter table x alter a restart with 5 set generated always set increment 3;
alter table x alter a type int collate "C" using a+1;
alter table x add column if not exists a int, drop b cascade, alter constraint c deferrable initially deferred, add check (a>0) not valid, owner to current_user, replica identity using index i, of foo.bar, inherit p, alter a options (add x 'y');
alter table x alter constraint c inherit;
alter table x alter a set default 1, alter a drop default;
alter table x attach partition y for values in (1,2);
alter table x detach partition y concurrently;
alter table x detach partition y finalize;
alter table x set access method default;
alter table x set access method foo;
alter table all in tablespace a owned by r1, r2 set tablespace b nowait;
alter type t add attribute a int cascade, drop attribute if exists b, alter attribute c type text collate "x";
alter table x enable trigger all, disable rule r, set tablespace t, cluster on i, set without cluster, set logged, not of, no inherit p, force row level security;
alter table x alter a set expression as (a+1), alter a drop expression if exists, alter a drop identity if exists, alter a set not null, alter a drop not null;
alter index i attach partition j;
alter materialized view all in tablespace a set tablespace b;
alter table x validate constraint c, drop constraint if exists d restrict;
alter table x alter constraint c not enforced;
alter table x alter constraint c not valid;
alter table x alter constraint c no inherit;
alter table x add constraint f foreign key (a, period b) references y (c, period d) match full on update cascade on delete set default (a) not valid;
