-- hash partition bounds: the checks of gram.y
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4, modulus 5, remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4, remainder 1, remainder 2);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (foo 4, remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4, remainder 1, foo 2);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4 remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus, remainder);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 'a', remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 4.5, remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus -4, remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (MODULUS 4, REMAINDER 1, );
CREATE TABLE t PARTITION OF p FOR VALUES WITH (MODULUS 4, REMAINDER 1) FOR VALUES IN (1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH ("MODULUS" 4, remainder 1);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 2147483647, remainder 0);
CREATE TABLE t PARTITION OF p FOR VALUES WITH (modulus 2147483648, remainder 0);
CREATE TABLE t PARTITION OF p FOR VALUES IN ();
CREATE TABLE t PARTITION OF p FOR VALUES FROM () TO ();
CREATE TABLE t PARTITION OF p FOR VALUES FROM (1);
CREATE TABLE t PARTITION OF p FOR VALUES FROM (1) TO;
CREATE TABLE t PARTITION OF p FOR VALUES;
CREATE TABLE t PARTITION OF p FOR;
CREATE TABLE t PARTITION OF p;
CREATE TABLE t PARTITION OF;
CREATE TABLE t PARTITION p DEFAULT;
CREATE TABLE t PARTITION OF p DEFAULT DEFAULT;
CREATE TABLE t PARTITION OF p, q DEFAULT;
CREATE TABLE t PARTITION OF p FOR VALUES IN (1) INHERITS (q);
-- partition strategies and elements
CREATE TABLE t (a int) PARTITION BY foo (a);
CREATE TABLE t (a int) PARTITION BY (a);
CREATE TABLE t (a int) PARTITION BY RANGE;
CREATE TABLE t (a int) PARTITION BY RANGE ();
CREATE TABLE t (a int) PARTITION BY RANGE (a,);
CREATE TABLE t (a int) PARTITION BY RANGE (a b);
CREATE TABLE t (a int) PARTITION BY RANGE (a COLLATE);
CREATE TABLE t (a int) PARTITION BY RANGE (a text_ops COLLATE "C");
CREATE TABLE t (a int) PARTITION BY RANGE (period);
CREATE TABLE t (a int) PARTITION BY RANGE (list);
CREATE TABLE t (a int) PARTITION BY RANGE (hash);
CREATE TABLE t (a int) PARTITION BY RANGE ("range");
CREATE TABLE t (a int) PARTITION BY RANGE (a) USING heap PARTITION BY LIST (a);
CREATE TABLE t (a int) PARTITION BY RANGE (f());
CREATE TABLE t (a int) PARTITION BY RANGE (f(a, b) COLLATE "C" my_ops);
CREATE TABLE t (a int) PARTITION BY RANGE (a ASC);
CREATE TABLE t (a int) PARTITION BY RANGE (a NULLS FIRST);
CREATE TABLE t (a int) PARTITION BY RANGE (a nulls);
CREATE TABLE t (a int) PARTITION BY RANGE (a nulls nulls);
CREATE TABLE t (a int) PARTITION BY RANGE (a, (b), (c) text_ops, lower(d) COLLATE "C");
CREATE TABLE t (a int) PARTITION BY RANGE ((a + b), (a));
CREATE TABLE t (a int) PARTITION BY RANGE ((SELECT 1));
CREATE TABLE t (a int) PARTITION BY RANGE (a::int);
CREATE TABLE t (a int) PARTITION BY RANGE (-a);
CREATE TABLE t (a int) PARTITION BY RANGE (CAST(a AS int));
CREATE TABLE t (a int) PARTITION BY RANGE (coalesce(a, 0));
CREATE TABLE t (a int) PARTITION BY RANGE (CURRENT_DATE);
CREATE TABLE t (a int) PARTITION BY RANGE (extract(year from a));
CREATE TABLE t (a int) PARTITION BY RANGE (a, extract(year from b));
-- names that are keywords
CREATE TABLE t (cache int, restart int, modulus int, remainder int, partition int, "like" int, increment int, owned int, start int);
CREATE TABLE t (inherits int, include int, exclude int, period int, overlaps int);
CREATE TABLE t (key int, generated int, always int, identity int, stored int, virtual int);
CREATE TABLE t (enforced int, deferrable int);
CREATE TABLE t (deferred int, immediate int, initially int);
CREATE TABLE t (valid int, inherit int, no int);
CREATE TABLE t (match int, full int, simple int);
CREATE TABLE t (cascade int, restrict int, action int);
CREATE TABLE t (comments int, constraints int, defaults int, indexes int, statistics int, including int, excluding int);
CREATE TABLE t (data int, oids int, options int, preserve int, rows int, commit int, delete_ int, drop_ int);
CREATE TABLE t (tablespace int, storage int, compression int, access int, method int);
CREATE TABLE t (nulls int, distinct_ int, without int);
CREATE TABLE t (a int REFERENCES period);
CREATE TABLE t (a int REFERENCES r (period));
CREATE TABLE t (a int REFERENCES r (a, period));
CREATE TABLE t (period int REFERENCES period (period) ON DELETE SET NULL (period));
CREATE TABLE period (period int, PRIMARY KEY (period WITHOUT OVERLAPS), FOREIGN KEY (period, PERIOD period) REFERENCES period (period, PERIOD period));
CREATE TABLE exclude (exclude int, EXCLUDE (exclude WITH =));
CREATE TABLE t (exclude int, exclude int);
CREATE TABLE t (exclude, exclude);
CREATE TABLE t (exclude WITH =);
CREATE TABLE t OF typ (exclude WITH OPTIONS);
CREATE TABLE t OF typ (exclude using gist (a with =));
CREATE TABLE t OF typ (exclude using);
CREATE TABLE t OF typ (exclude (a with =));
CREATE TABLE t OF typ (exclude not null);
CREATE TABLE t OF typ (period);
CREATE TABLE t (a int, exclude);
CREATE TABLE t (a int, exclude USING gist (a WITH =));
CREATE TABLE t (a int, exclude (a WITH =));
CREATE TABLE t (a int, exclude int);
CREATE TABLE t (a int, exclude int NOT NULL);
CREATE TABLE t (a int, exclude int, exclude USING gist (a WITH =));
CREATE TABLE t (a int) INHERITS ();
CREATE TABLE t (a int) INHERITS (p,);
CREATE TABLE t (a int) INHERITS p;
CREATE TABLE t (a int,);
CREATE TABLE t (,a int);
CREATE TABLE t (a int b int);
CREATE TABLE t a int;
CREATE TABLE (a int);
CREATE TABLE t;
CREATE TABLE;
CREATE TABLE t (a);
CREATE TABLE t (a int) (b int);
CREATE TABLE t (a int) ON COMMIT;
CREATE TABLE t (a int) ON COMMIT PRESERVE;
CREATE TABLE t (a int) ON COMMIT DELETE;
CREATE TABLE t (a int) TABLESPACE;
CREATE TABLE t (a int) USING;
CREATE TABLE t (a int) WITH;
CREATE TABLE t (a int) WITH ();
CREATE TABLE t (a int) WITHOUT;
CREATE TABLE t (a int) WITH OIDS;
CREATE TABLE t (a int) WITHOUT OIDS WITH (a = 1);
CREATE TABLE t (a int) WITH (a = 1) WITHOUT OIDS;
CREATE TABLE t (a int) TABLESPACE ts USING heap;
CREATE TABLE t (a int) ON COMMIT DROP WITH (a = 1);
CREATE TABLE t (a int) USING heap USING heap;
CREATE TABLE t (a int) PARTITION BY LIST (a) INHERITS (p);
CREATE TABLE t (a int) INHERITS (p) INHERITS (q);
CREATE TABLE IF EXISTS t (a int);
CREATE TABLE IF NOT t (a int);
CREATE TABLE IF NOT EXISTS IF NOT EXISTS t (a int);
CREATE TABLE t (a int) INHERITS (p) PARTITION BY RANGE (a) USING heap WITH (x = 1) ON COMMIT DROP TABLESPACE ts TABLESPACE ts2;
CREATE TEMP UNLOGGED TABLE t (a int);
CREATE UNLOGGED TEMP TABLE t (a int);
CREATE LOCAL GLOBAL TEMP TABLE t (a int);
CREATE LOCAL TABLE t (a int);
CREATE GLOBAL TABLE t (a int);
CREATE TEMP TEMP TABLE t (a int);
CREATE OR REPLACE TABLE t (a int);
CREATE FOREIGN TABLE IF NOT EXISTS ft (a int) SERVER s;
-- statements of other regions that start like the ones of this region are rejected here (not run: see the report)
CREATE STATISTICS;
CREATE SEQUENCE;
CREATE INDEX;
CREATE VIEW;
CREATE DOMAIN;
CREATE MATERIALIZED VIEW;
CREATE FOREIGN TABLE;
ALTER TABLE x ADD a int, RENAME TO y;
-- case and comments
alter /* a */ table /* b */ t /* c */ add /* d */ column /* e */ a /* f */ int /* g */ not /* h */ null;
ALTER TABLE T ADD COLUMN A INT NOT NULL DEFAULT 1;
Alter Table T Alter Column A Set Not Null;
aLtEr tAbLe t aDd cOnStRaInT c cHeCk (a > 0) nOt vAlId;
create table t (a int) partition by hash (a);
Create Table T (A Int Primary Key, B Int References X (Y) On Delete Cascade);
CREATE TABLE t (a int, b int, CHECK (a > b) -- trailing comment
);
CREATE TABLE t (a int /* x */ NOT /* y */ NULL, b int);
CREATE /*x*/ UNIQUE /*y*/ INDEX /*z*/ CONCURRENTLY /*w*/ IF /*v*/ NOT /*u*/ EXISTS /*t*/ i /*s*/ ON /*r*/ t /*q*/ (/*p*/a/*o*/)/*n*/;
