package sample

import (
	"cmp"
	"math/rand/v2"
	"slices"
	"unicode/utf8"

	"github.com/ornew/pego/grammar"
)

// The generator walks the grammar AST and writes a candidate input, making a random decision at each
// choice, repetition and optional expression. It is written in continuation-passing style: generating an
// expression calls a continuation that generates the rest of the input, and returns false if no way to
// finish the input was found. A decision whose continuation fails is undone and the next option is
// tried, so the generation is a depth-first search, bounded by a budget of steps.
//
// The search prunes candidates that the parser would read differently from how they were generated:
//
//   - predicates are evaluated on the generated text when the generator can compute their value
//     (captures, variables, len, text, comparisons and arithmetic);
//   - a positive lookahead &e generates a text for e and forces the input that follows to start with it;
//   - checks that a partial matcher evaluates as the text grows: when the generator takes the
//     alternative i of an ordered choice, the alternatives before i must not match there; when it stops
//     a repetition or skips an optional expression, the element must not match there (repetitions are
//     greedy); a negative lookahead !e must not match.
//
// The pruning is only a heuristic: a candidate is returned only after the parser accepts it.

// quickFailure is the number of steps within which an option is considered to have failed right away.
const quickFailure = 8

// matchBudget is the budget of the matcher in an attempt, in multiples of the generation budget.
const matchBudget = 1000

// hopeless is the number of failed attempts after which coverage mode stops preferring a target that no
// accepted input has exercised: the parser may never take it (because of a cut, or because an earlier
// alternative of the choice matches whatever it matches, which may show only late in the search).
const hopeless = 10

// maxIterations returns how many iterations beyond its minimum a repetition may take at most, a hard
// limit (see WithMaxRepeat). Without it, a repetition whose stop keeps failing (an
// indentation that a predicate rejects, at every width) would iterate until the budget runs out.
func maxIterations(maxRepeat int) int { return 8*maxRepeat + 4 }

// maxNesting returns how many recursive rule calls may nest at most, a hard limit (see WithMaxDepth).
// Past maxDepth the generator prefers the shortest way out, but backtracking can still try deeper and
// deeper calls; without the limit, a dead alternative that fails only after a nested call (as in
// s = "(" s ")" / "x" / "(" s ")" "!") makes attempts several times slower.
func maxNesting(maxDepth int) int { return maxDepth + 8 }

// cont is a continuation that receives the value of the expression just generated.
type cont func(v val) bool

// check is a condition on the input at a position that the input generated so far cannot decide yet
// (a persistent list).
type check struct {
	pos      int
	e        grammar.Expr
	pratt    *prattCheck
	neg      bool // e must not match (otherwise it must match)
	progress bool // with neg, only a match that consumes input violates the check
	next     *check
}

// sibling is the text generated by a call of a rule in the current rule invocation, for the calls that
// a predicate compares (a persistent list; see genRef).
type sibling struct {
	key  string
	text string
	next *sibling
}

type gen struct {
	in      *info
	cfg     *config
	rng     *rand.Rand
	covered bitset // targets exercised by accepted inputs
	settled bitset // targets that coverage mode no longer pursues: covered or hopeless
	// rejected counts, for each target, the failed attempts that tried it while it was not exercised
	// yet: searches that ended without a candidate, and candidates that the parser rejected.
	rejected []int

	// The state of one attempt. Every function that changes it restores it before returning, so that a
	// failed option leaves no trace.
	out     []byte
	forced  string // text that the input must continue with (from a positive lookahead)
	endAt   int    // if >= 0, the input must end there (from $$)
	pending *check
	caps    *capture
	vars    *variable
	sib     *sibling
	active  []int // number of active calls of each rule
	depth   int   // calls of rules that were already active: the recursion depth
	steps   int
	tent    bitset // targets exercised by the current attempt
	tried   []int  // targets the current attempt tried while they were not exercised yet
	triedB  bitset
	trail   []int // targets in tent, in the order they were added

	m         matcher
	matchWork int // steps of the matcher in the current attempt

	scratch     []byte
	result      string
	resultTrail []int
}

func newGen(in *info, cfg *config) *gen {
	return &gen{
		in:       in,
		cfg:      cfg,
		m:        matcher{in: in},
		rng:      rand.New(rand.NewPCG(cfg.seed, 0x9e3779b97f4a7c15)),
		covered:  newBitset(len(in.targets)),
		rejected: make([]int, len(in.targets)),
		tent:     newBitset(len(in.targets)),
		triedB:   newBitset(len(in.targets)),
		settled:  newBitset(len(in.targets)),
		active:   make([]int, len(in.order)),
	}
}

// attempt runs one search for a candidate input. It returns the candidate and the targets it
// exercised.
func (g *gen) attempt() (string, []int, bool) {
	g.out, g.forced, g.endAt, g.pending = g.out[:0], "", -1, nil
	g.caps, g.vars, g.sib = nil, nil, nil
	clear(g.active)
	g.depth, g.steps, g.matchWork = 0, 0, 0
	for _, t := range g.trail {
		g.tent.clear(t)
	}
	g.trail = g.trail[:0]
	for _, t := range g.tried {
		g.triedB.clear(t)
	}
	g.tried = g.tried[:0]
	ok := g.genRef(&grammar.Ref{Name: g.in.start.def.Name}, func(val) bool { return g.finish() }, false)
	return g.result, g.resultTrail, ok
}

// finish is the final continuation: the input is complete.
func (g *gen) finish() bool {
	if g.forced != "" {
		return false
	}
	for c := g.pending; c != nil; c = c.next {
		if violated, _ := g.evalCheck(c, true); violated {
			return false
		}
	}
	g.result = string(g.out)
	g.resultTrail = append(g.resultTrail[:0], g.trail...)
	return true
}

// exhausted reports whether the attempt has used up its budget: generation steps, and the steps of the
// matcher that evaluates checks. Every character written re-evaluates the pending checks, so the
// matcher can do far more work than the generation itself (with many pending lookaheads over a long
// text); it gets a budget of its own, matchBudget times the generation budget.
func (g *gen) exhausted() bool {
	return g.steps > g.cfg.budget || g.matchWork > matchBudget*g.cfg.budget
}

// retry reports whether a decision that started at step s0 may try another option. A decision gives
// up once its failed options have taken more than the retry limit: when a doomed decision was made
// earlier, the options of the later decisions are often all equivalent, and trying them all would take
// exponential time. The decision before it, or the next attempt, tries something else instead.
func (g *gen) retry(s0 int) bool {
	return !g.exhausted() && g.steps-s0 <= g.cfg.retry
}

// minimal reports whether the generator should take the shortest way to finish: the recursion is
// deep enough or the input long enough.
func (g *gen) minimal() bool {
	return g.depth >= g.cfg.maxDepth || len(g.out) >= g.cfg.maxLen
}

// untouched reports whether the target has been exercised neither by an accepted input nor by the
// current attempt.
func (g *gen) untouched(t int) bool { return !g.covered.has(t) && !g.tent.has(t) }

// wanted reports whether coverage mode prefers the target: it is untouched, and attempts that tried it
// did not fail too often.
func (g *gen) wanted(t int) bool { return g.untouched(t) && !g.settled.has(t) }

// accepted records the targets of an accepted input.
func (g *gen) accepted(trail []int) {
	for _, t := range trail {
		g.covered.set(t)
		g.settled.set(t)
	}
}

// failed records a failed attempt (a search without a candidate, or a candidate the parser rejected)
// against the targets it tried while they were not exercised yet. A target that keeps failing is
// settled: coverage mode no longer prefers it, nor options that reach it.
func (g *gen) failed() {
	for _, t := range g.tried {
		g.rejected[t]++
		if g.rejected[t] >= hopeless {
			g.settled.set(t)
		}
	}
}

// mark records that the current attempt exercises the target, and returns a mark for unmark.
func (g *gen) mark(t int) int {
	n := len(g.trail)
	if g.cfg.coverage && !g.covered.has(t) && !g.triedB.has(t) {
		g.triedB.set(t)
		g.tried = append(g.tried, t)
	}
	if !g.tent.has(t) {
		g.tent.set(t)
		g.trail = append(g.trail, t)
	}
	return n
}

func (g *gen) unmark(n int) {
	for _, t := range g.trail[n:] {
		g.tent.clear(t)
	}
	g.trail = g.trail[:n]
}

// slice returns the text of the input in [start, end), which may extend into the forced text.
func (g *gen) slice(start, end int) string {
	if end <= len(g.out) {
		return string(g.out[start:end])
	}
	v := string(g.out) + g.forced
	return v[min(start, len(v)):min(end, len(v))]
}

// text returns the input known so far: the generated text followed by the forced text.
func (g *gen) text() []byte {
	if g.forced == "" {
		return g.out
	}
	g.scratch = append(append(g.scratch[:0], g.out...), g.forced...)
	return g.scratch
}

// evalCheck evaluates a check. keep is true if it cannot be decided yet.
func (g *gen) evalCheck(c *check, final bool) (violated, keep bool) {
	// The input is complete at the end, or where $$ requires it to end.
	final = g.forced == "" && (final || g.endAt == len(g.out))
	var st status
	var end int
	if c.pratt != nil {
		st, end = g.m.runPrattStop(c.pratt, g.text(), c.pos, final)
	} else {
		st, end = g.m.run(c.e, g.text(), c.pos, final)
	}
	g.matchWork += g.m.steps
	switch st {
	case matched:
		return c.neg && (!c.progress || end > c.pos), false
	case failed:
		return !c.neg, false
	case more:
		return false, true
	}
	return false, false // unknown: the parser decides
}

// addPrattCheck installs a longest-selection check with its own immutable scope snapshot.
func (g *gen) addPrattCheck(p *prattCheck) bool {
	c := &check{pos: len(g.out), pratt: p, neg: true, progress: true}
	violated, keep := g.evalCheck(c, false)
	if violated {
		return false
	}
	if keep {
		c.next = g.pending
		g.pending = c
	}
	return true
}

// addCheck adds a check at the current position. It returns false if the check already fails. The
// caller restores g.pending.
func (g *gen) addCheck(e grammar.Expr, neg, progress bool) bool {
	if neg && !progress && g.in.alwaysMatches(e) {
		// It matches whatever follows: the matcher would only find out once the text after it is
		// written.
		return false
	}
	c := &check{pos: len(g.out), e: e, neg: neg, progress: progress}
	violated, keep := g.evalCheck(c, false)
	if violated {
		return false
	}
	if keep {
		c.next = g.pending
		g.pending = c
	}
	return true
}

// recheck re-evaluates the pending checks after the input grew.
func (g *gen) recheck() bool {
	var kept *check
	changed := false
	for c := g.pending; c != nil; c = c.next {
		violated, keep := g.evalCheck(c, false)
		if violated || g.exhausted() {
			return false
		}
		if keep {
			kept = &check{pos: c.pos, e: c.e, pratt: c.pratt, neg: c.neg, progress: c.progress, next: kept}
		} else {
			changed = true
		}
	}
	if changed {
		g.pending = kept
	}
	return true
}

// emit appends s to the input and calls k with its start position.
func (g *gen) emit(s string, k func(start int) bool) bool {
	start := len(g.out)
	if s == "" {
		return k(start)
	}
	if g.endAt >= 0 && start+len(s) > g.endAt {
		return false
	}
	f := g.forced
	n := min(len(s), len(f))
	if s[:n] != f[:n] {
		return false
	}
	pending := g.pending
	g.out = append(g.out, s...)
	g.forced = f[n:]
	ok := g.recheck() && !g.exhausted() && k(start)
	g.out = g.out[:start]
	g.forced = f
	g.pending = pending
	return ok
}

// emitText emits a terminal.
func (g *gen) emitText(s string, k cont) bool {
	return g.emit(s, func(start int) bool { return k(val{kind: vText, start: start, end: start + len(s)}) })
}

func (g *gen) gen(e grammar.Expr, k cont) bool {
	g.steps++
	if g.exhausted() {
		return false
	}
	pos := len(g.out)
	switch e := e.(type) {
	case *grammar.Literal:
		return g.emitText(e.Value, k)
	case *grammar.CharClass:
		return g.genClass(e, k)
	case *grammar.Any:
		return g.genAny(k)
	case *grammar.Seq:
		return g.genSeq(e.Items, pos, k)
	case *grammar.Choice:
		return g.genChoice(e, k)
	case *grammar.Repeat:
		return g.genRepeat(e, k)
	case *grammar.Optional:
		return g.genOptional(e, k)
	case *grammar.And:
		return g.genAnd(e, k)
	case *grammar.Not:
		pending := g.pending
		ok := g.addCheck(e.Expr, true, false) && k(val{kind: vNone, start: pos, end: pos})
		g.pending = pending
		return ok
	case *grammar.Atomic:
		return g.gen(e.Expr, func(v val) bool { return k(val{kind: vText, start: pos, end: len(g.out)}) })
	case *grammar.Discard:
		return g.gen(e.Expr, func(v val) bool { return k(val{kind: vNone, start: pos, end: len(g.out)}) })
	case *grammar.Capture:
		bind := func(v val) bool {
			caps := g.caps
			g.caps = &capture{name: e.Name, v: v, next: caps}
			ok := k(v)
			g.caps = caps
			return ok
		}
		if r, ok := e.Expr.(*grammar.Ref); ok && g.in.compared[e] {
			return g.genRef(r, bind, true)
		}
		return g.gen(e.Expr, bind)
	case *grammar.Attributed:
		return g.gen(e.Expr, k)
	case *grammar.Ref:
		return g.genRef(e, k, false)
	case *grammar.Predicate:
		ok, def := g.predicate(e)
		if !ok {
			return false
		}
		if def == nil {
			return k(val{kind: vNone, start: pos, end: pos})
		}
		vars := g.vars
		def.next = vars
		g.vars = def
		ok = k(val{kind: vNone, start: pos, end: pos})
		g.vars = vars
		return ok
	case *grammar.Top:
		return k(val{kind: vText, start: pos, end: pos})
	case *grammar.Cut:
		return k(val{kind: vNone, start: pos, end: pos})
	case *grammar.Bottom:
		return false
	case *grammar.BeginInput:
		return pos == 0 && k(val{kind: vNone, start: pos, end: pos})
	case *grammar.BeginLine:
		return (pos == 0 || g.out[pos-1] == '\n') && k(val{kind: vNone, start: pos, end: pos})
	case *grammar.EndInput:
		if g.forced != "" || (g.endAt >= 0 && g.endAt != pos) {
			return false
		}
		endAt, pending := g.endAt, g.pending
		g.endAt = pos
		ok := g.recheck() && k(val{kind: vNone, start: pos, end: pos})
		g.endAt, g.pending = endAt, pending
		return ok
	case *grammar.EndLine:
		pending := g.pending
		ok := g.addCheck(e, false, false) && k(val{kind: vNone, start: pos, end: pos})
		g.pending = pending
		return ok
	case *grammar.Pratt:
		// Only reachable as a rule body, which genRef handles.
		return false
	}
	return false
}

func (g *gen) genSeq(items []grammar.Expr, start int, k cont) bool {
	if len(items) == 0 {
		return k(val{kind: vNode, start: start, end: len(g.out)})
	}
	return g.gen(items[0], func(val) bool { return g.genSeq(items[1:], start, k) })
}

// option describes one way to continue at a decision.
type option struct {
	height int    // minimal height; inf if the option can never succeed
	length int    // minimal length of its text in bytes
	own    int    // the option's own target, or -1
	reach  bitset // targets the option can exercise, or nil
}

// order returns the order in which to try the options. Options that can never succeed are left out.
// When the generator must finish quickly, the options with the shortest text (once the text is long
// enough) or the fewest nested rule calls (once the recursion is deep enough) come first; in coverage
// mode, options whose own target, and then options that reach a target, not exercised yet come first.
// Ties are broken at random.
func (g *gen) order(opts []option) []int {
	idx := make([]int, 0, len(opts))
	for i, o := range opts {
		if o.height < inf {
			idx = append(idx, i)
		}
	}
	g.rng.Shuffle(len(idx), func(i, j int) { idx[i], idx[j] = idx[j], idx[i] })
	switch {
	case len(g.out) >= g.cfg.maxLen:
		// The text is long enough: the shortest text first, then the fewest rule calls.
		slices.SortStableFunc(idx, func(a, b int) int {
			return cmp.Or(cmp.Compare(opts[a].length, opts[b].length), cmp.Compare(opts[a].height, opts[b].height))
		})
	case g.minimal():
		// Deep enough: the fewest nested rule calls first, then the shortest text.
		slices.SortStableFunc(idx, func(a, b int) int {
			return cmp.Or(cmp.Compare(opts[a].height, opts[b].height), cmp.Compare(opts[a].length, opts[b].length))
		})
	case g.cfg.coverage:
		rank := func(o option) int {
			switch {
			case o.own >= 0 && g.wanted(o.own):
				return 0
			case o.reach != nil && o.reach.anyNotIn(g.settled, g.tent):
				return 1
			}
			return 2
		}
		slices.SortStableFunc(idx, func(a, b int) int { return rank(opts[a]) - rank(opts[b]) })
	}
	return idx
}

func (g *gen) genChoice(e *grammar.Choice, k cont) bool {
	base := g.in.altBase[e]
	opts := make([]option, len(e.Alts))
	for i, a := range e.Alts {
		opts[i] = option{height: g.in.height(a), length: g.in.length(a), own: base + i, reach: g.in.reach(a)}
	}
	pending := g.pending
	s0 := g.steps
	for _, i := range g.order(opts) {
		// The parser takes the first alternative that matches: the ones before i must fail here.
		ok := true
		for j := 0; j < i && ok; j++ {
			ok = g.addCheck(e.Alts[j], true, false)
		}
		if ok {
			m := g.mark(base + i)
			ok = g.gen(e.Alts[i], k)
			g.unmark(m)
		}
		g.pending = pending
		if ok {
			return true
		}
		if !g.retry(s0) {
			return false
		}
	}
	return false
}

func (g *gen) genOptional(e *grammar.Optional, k cont) bool {
	pos := len(g.out)
	take := func() bool { return g.gen(e.Expr, k) }
	skip := func() bool {
		pending := g.pending
		ok := g.addCheck(e.Expr, true, true) && k(val{kind: vNil, start: pos, end: pos})
		g.pending = pending
		return ok
	}
	s0 := g.steps
	takeFirst := g.rng.IntN(2) == 0
	switch {
	case g.minimal():
		takeFirst = false
	case g.cfg.coverage && g.in.reach(e.Expr).anyNotIn(g.settled, g.tent):
		takeFirst = g.rng.IntN(4) != 0
	}
	if takeFirst {
		return take() || (g.retry(s0) && skip())
	}
	return skip() || (g.retry(s0) && take())
}

func (g *gen) genRepeat(e *grammar.Repeat, k cont) bool {
	start := len(g.out)
	// The number of iterations to aim for; the search may end up with another.
	want := e.Min
	if !g.minimal() {
		// Each further iteration with probability 1/2: short repetitions are the most common.
		for extra := 0; extra < g.cfg.maxRepeat && g.rng.IntN(2) == 0; extra++ {
			want++
		}
		if g.cfg.coverage && g.rng.IntN(4) != 0 && g.in.reach(e.Expr).anyNotIn(g.settled, g.tent) {
			want = max(want, e.Min+1)
		}
	}
	// As in the engine, an element gets its own capture scope per iteration only if it contains
	// captures: one without captures cannot read any (the compiler rejects predicates that read the
	// enclosing rule's captures), so it needs none.
	scoped := g.in.hasCaptures(e.Expr)
	limit := e.Min + maxIterations(g.cfg.maxRepeat)
	if e.Max >= 0 {
		want = min(want, e.Max)
		limit = min(limit, e.Max)
	}
	var iter func(i int) bool
	iter = func(i int) bool {
		s0 := g.steps
		done := func() bool {
			return k(val{kind: vList, start: start, end: len(g.out), n: i})
		}
		another := func() bool {
			if i >= limit {
				return false
			}
			pos := len(g.out)
			caps := g.caps
			if scoped {
				g.caps = nil // each iteration is a capture scope
			}
			ok := g.gen(e.Expr, func(val) bool {
				inner := g.caps
				g.caps = caps
				var ok bool
				if len(g.out) == pos {
					// The first empty iteration ends the repetition, even below
					// its minimum. Retry a consuming body instead of inventing
					// further empty iterations.
					ok = i+1 >= e.Min && k(val{kind: vList, start: start, end: pos, n: i + 1})
				} else {
					ok = iter(i + 1)
				}
				g.caps = inner
				return ok
			})
			g.caps = caps
			return ok
		}
		stop := func() bool {
			if i < e.Min {
				return false
			}
			if e.Max >= 0 && i >= e.Max {
				return done()
			}
			// The repetition is greedy: another iteration must not match here.
			pending := g.pending
			ok := g.addCheck(e.Expr, true, true) && done()
			g.pending = pending
			return ok
		}
		if i < want {
			return another() || (g.retry(s0) && stop())
		}
		// Iterating more than aimed for helps when stopping failed right away (a predicate after the
		// repetition wants a longer match) or soon (two tokens ran together without the whitespace
		// between them); when it failed later, more iterations seldom help, and they would make a
		// doomed decision before the repetition expensive to undo.
		return stop() || ((g.steps-s0 <= quickFailure || i < want+2) && g.retry(s0) && another())
	}
	return iter(0)
}

// genAnd handles the lookahead &e. It first generates a text for e and requires the input to continue
// with it; captures and variables made in e stay in effect, as in the parser. If that fails and e makes
// no captures and defines no variables, it then only requires, with a check, that e match the text that
// follows, so that the text generated after the lookahead decides: &(. .) "ab" cannot guess "ab" in
// advance.
func (g *gen) genAnd(e *grammar.And, k cont) bool {
	pos := len(g.out)
	s0 := g.steps
	forced := g.gen(e.Expr, func(val) bool {
		t := string(g.out[pos:])
		f := g.forced
		g.out = g.out[:pos]
		g.forced = t + f
		ok := k(val{kind: vNone, start: pos, end: pos})
		g.out = append(g.out[:pos], t...)
		g.forced = f
		return ok
	})
	if forced || g.in.binds(e.Expr) || !g.retry(s0) {
		return forced
	}
	pending := g.pending
	ok := g.addCheck(e.Expr, false, false) && k(val{kind: vNone, start: pos, end: pos})
	g.pending = pending
	return ok
}

// Characters that generated input prefers: printable ASCII and a few multi-byte characters.
var niceRunes = func() []rune {
	var rs []rune
	for r := rune(' '); r <= '~'; r++ {
		rs = append(rs, r)
	}
	return append(rs, []rune("éßΩж日本語😀")...)
}()

// classRune returns a random code point that the class matches, preferring nice runes, then, for a
// negated class, code points below U+3000. Otherwise it picks a range of the code points that the class
// actually matches (see classRanges) and a code point in it, so that classes with few or unusual code
// points (the complement of almost everything, ranges that span the surrogates) are generated too.
func (g *gen) classRune(c *grammar.CharClass) (rune, bool) {
	if g.rng.IntN(4) != 0 {
		for range 8 {
			if r := niceRunes[g.rng.IntN(len(niceRunes))]; inClass(c, r) {
				return r, true
			}
		}
	}
	if c.Negated {
		for range 16 {
			if r := rune(0x20 + g.rng.IntN(0x3000-0x20)); inClass(c, r) {
				return r, true
			}
		}
	}
	if !c.Negated && len(c.Ranges) > 0 {
		// One of the class's own ranges, then a code point in it that is not a surrogate.
		rg := c.Ranges[g.rng.IntN(len(c.Ranges))]
		size := int64(rg.Hi-rg.Lo) + 1
		if lo, hi := max(rg.Lo, 0xD800), min(rg.Hi, 0xDFFF); lo <= hi {
			size -= int64(hi-lo) + 1
		}
		if size > 0 {
			r := rg.Lo + rune(g.rng.Int64N(size))
			if r >= 0xD800 && rg.Lo < 0xD800 {
				r += 0x800 // skip the surrogates
			} else if rg.Lo >= 0xD800 && rg.Lo <= 0xDFFF {
				r += 0xE000 - rg.Lo
			}
			return r, true
		}
	}
	rs := g.in.classRanges(c)
	if len(rs) == 0 {
		return 0, false
	}
	rg := rs[g.rng.IntN(len(rs))]
	return rg.Lo + rune(g.rng.Int64N(int64(rg.Hi-rg.Lo)+1)), true
}

func (g *gen) genClass(c *grammar.CharClass, k cont) bool {
	if g.forced != "" {
		r, n := utf8.DecodeRuneInString(g.forced)
		return inClass(c, r) && g.emitText(g.forced[:n], k)
	}
	s0 := g.steps
	var tried []rune
	for range 2 {
		r, ok := g.classRune(c)
		if !ok || slices.Contains(tried, r) {
			continue
		}
		tried = append(tried, r)
		if g.emitText(string(r), k) {
			return true
		}
		// Another character is tried only if this one failed by itself (a check rejected it):
		// when the rest of the input failed, the other characters would mostly fail the same way.
		if g.steps != s0 {
			return false
		}
	}
	return false
}

func (g *gen) genAny(k cont) bool {
	if g.forced != "" {
		_, n := utf8.DecodeRuneInString(g.forced)
		return g.emitText(g.forced[:n], k)
	}
	s0 := g.steps
	var tried []rune
	for range 2 {
		var r rune
		switch n := g.rng.IntN(20); {
		case n == 0:
			r = '\n'
		case n == 1:
			r = '\t'
		default:
			r = niceRunes[g.rng.IntN(len(niceRunes))]
		}
		if slices.Contains(tried, r) {
			continue
		}
		tried = append(tried, r)
		if g.emitText(string(r), k) {
			return true
		}
		// Another character is tried only if this one failed by itself (a check rejected it):
		// when the rest of the input failed, the other characters would mostly fail the same way.
		if g.steps != s0 {
			return false
		}
	}
	return false
}

// genRef generates a call of a rule. If compared is set, the call is captured by a capture that a
// predicate reads: the call may then repeat the text of an earlier such call of the same rule in the
// same rule invocation, which is how inputs where a predicate requires two texts to be equal (such as
// matching start and end tags) are found.
func (g *gen) genRef(e *grammar.Ref, k cont, compared bool) bool {
	ri := g.in.rules[e.Name]
	if ri == nil || ri.height >= inf {
		return false
	}
	if !compared {
		return g.callRule(ri, e.Level, "", k)
	}
	key := e.Name + "(" + e.Level + ")"
	// Texts generated by earlier calls of the same rule in this rule invocation.
	var reuse []string
	for s := g.sib; s != nil && len(reuse) < 2; s = s.next {
		if s.key == key && s.text != "" && !slices.Contains(reuse, s.text) {
			reuse = append(reuse, s.text)
		}
	}
	s0 := g.steps
	fresh := func() bool { return g.callRule(ri, e.Level, key, k) }
	again := func() bool {
		for _, t := range reuse {
			if g.reuseRule(ri, key, t, k) {
				return true
			}
			if !g.retry(s0) {
				return false
			}
		}
		return false
	}
	if len(reuse) > 0 && g.rng.IntN(3) == 0 {
		return again() || (g.retry(s0) && fresh())
	}
	return fresh() || (len(reuse) > 0 && g.retry(s0) && again())
}

// callRule generates the body of a rule. If key is not empty, the text is recorded as a sibling.
func (g *gen) callRule(ri *ruleInfo, level, key string, k cont) bool {
	recursive := g.active[ri.index] > 0
	if recursive {
		if g.depth >= maxNesting(g.cfg.maxDepth) {
			return false
		}
		g.depth++
	}
	g.active[ri.index]++
	caps, vars, sib := g.caps, g.vars, g.sib
	g.caps, g.sib = nil, nil // a rule body is a capture scope; it reads the caller's variables
	m := g.mark(ri.index)
	start := len(g.out)
	ret := func(v val) bool {
		// Return to the caller.
		innerCaps, innerVars, innerSib := g.caps, g.vars, g.sib
		hadCaps := g.caps != nil
		g.active[ri.index]--
		if recursive {
			g.depth--
		}
		g.caps, g.vars = caps, vars
		if key != "" {
			g.sib = &sibling{key: key, text: string(g.out[start:]), next: sib}
		} else {
			g.sib = sib
		}
		ok := k(ruleValue(ri, v, start, len(g.out), hadCaps))
		g.active[ri.index]++
		if recursive {
			g.depth++
		}
		g.caps, g.vars, g.sib = innerCaps, innerVars, innerSib
		return ok
	}
	var ok bool
	if ri.pratt != nil {
		minLevel := 0
		if level != "" {
			minLevel = ri.levels[level]
		}
		ok = g.genPratt(ri, minLevel, ret)
	} else {
		ok = g.gen(ri.def.Expr, ret)
	}
	g.unmark(m)
	g.active[ri.index]--
	if recursive {
		g.depth--
	}
	g.caps, g.vars, g.sib = caps, vars, sib
	return ok
}

// reuseRule emits a text that an earlier call of the rule generated.
func (g *gen) reuseRule(ri *ruleInfo, key, text string, k cont) bool {
	return g.emit(text, func(start int) bool {
		sib := g.sib
		g.sib = &sibling{key: key, text: text, next: sib}
		ok := k(ruleValue(ri, val{kind: vNode}, start, len(g.out), true))
		g.sib = sib
		return ok
	})
}

// ruleValue returns the value of a rule whose body produced v.
func ruleValue(ri *ruleInfo, v val, start, end int, hadCaps bool) val {
	switch {
	case ri.def.Action != nil || ri.pratt != nil:
		return val{kind: vUnknown, start: start, end: end}
	case ri.terminal:
		return val{kind: vText, start: start, end: end}
	case hadCaps:
		return val{kind: vNode, start: start, end: end}
	}
	return v
}
