// Package bench benchmarks the PEGO backends against each other and against Go standard library parsers.
//
//	go test ./bench -bench . -benchmem
//
// docs/benchmarks.md is generated from a run of these benchmarks: go run ./bench/report measures them
// and rewrites it (see package report).
//
// gen/ holds parsers generated by pego gen; regenerate them with go generate ./bench.
package bench

//go:generate go run ../cmd/pego gen -g ../parsers/json/json.pego -pkg json -recognize -types -o gen/json/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/csv/csv.pego -pkg csv -recognize -types -o gen/csv/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/xml/xml.pego -pkg xml -recognize -types -o gen/xml/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/calculator/calc.pego -pkg calc -recognize -types -o gen/calc/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/calculator/calc_lr.pego -pkg calclr -recognize -types -o gen/calclr/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/minilang/minilang.pego -pkg minilang -recognize -types -o gen/minilang/parser.go
//go:generate go run ../cmd/pego gen -g ../examples/outline/outline.pego -pkg outline -recognize -types -o gen/outline/parser.go
