-- routine bodies
create function f() returns int language sql begin atomic select 'a;b'; end;
create function f() returns int language sql begin atomic select 1 union select 2; values (1), (2); end;
create function f() returns int language sql begin atomic select (case when true then 1 else 2 end); end;
create function f() returns int language sql begin atomic select case when true then 1 end; end;
create function f(a int) returns int language sql begin atomic update t set x = a where y = a returning x; return a; end;
create function f(a int) returns int language sql begin atomic merge into t using s on t.a = s.a when matched then delete; end;
create function f() returns int language sql begin atomic with c as (select 1) insert into t select * from c; end;
create function f() returns int language sql begin atomic return case when true then 1 else 2 end; end;
create function f() returns int language sql begin atomic return; end;
create function f() returns int language sql return;
create function f() returns int language sql begin atomic return 1, 2; end;
create function f() returns int language sql begin atomic return (1, 2); end;
create function f() returns int language sql begin atomic return 1; return 2; end;
create function f() returns int language sql begin atomic return 1;; return 2;; end;
create function f() returns int language sql begin atomic begin atomic end; end;
create function f() returns int language sql begin atomic ; end;
create function f() returns int language sql begin atomic ;;; end;
create function f() returns int language sql begin atomic /* c */ select /* c */ 1 /* c */ ; /* c */ end /* c */ ;
create function f() returns int language sql begin atomic select 1 -- c
; end;
create function f() returns int language sql BEGIN ATOMIC SELECT 1; END;
create function f() returns int language sql return 1 + (select 2);
create function f() returns int language sql return 1 as 'x';
create function f() returns int language sql return 1 language sql;
create function f() returns int language sql return 1 return 2;
create function f() returns int language sql begin atomic select 1; end begin atomic select 2; end;
create function f() returns int language sql begin atomic select 1; end language sql;
create function f() returns int language sql begin atomic select 1; end strict;
create function f() returns int language sql begin atomic select 1; end select 2;
create function f() returns int language sql begin atomic call p(); end;
create function f() returns int language sql begin atomic copy t from stdin; end;
create function f() returns int language sql begin atomic explain select 1; end;
create function f() returns int language sql begin atomic set x = 1; end;
create function f() returns int language sql begin atomic begin; end;
create function f() returns int language sql begin atomic commit; end;
create function f() returns int language sql begin atomic do 'x'; end;
create function f() returns int language sql begin atomic drop table t; end;
create function f() returns int language sql begin atomic alter table t add column a int; end;
create function f() returns int language sql begin atomic create view v as select 1; end;
create function f() returns int language sql begin atomic create type t as enum ('a'); end;
create function f() returns int language sql begin atomic alter function g() strict; end;
create function f() returns int language sql begin atomic drop cast (int as text); end;
create procedure p() language sql begin atomic select 1; insert into t values (1); end;
create procedure p() language sql begin atomic return 1; end;
create or replace procedure p() language sql return 1;
create function f() returns int language sql begin atomic select 1; end;
select 1;
create function g() returns int language sql begin atomic select 2; end; select 3;
