-- CREATE CAST / DROP CAST
create cast (int as text) with function f(int);
create cast (int as text) with function f(int) as implicit;
create cast (int as text) with function f(int) as assignment;
create cast (int as text) with function f;
create cast (int as text) with function a.f(int, text) as implicit;
create cast (int as text) with function f(a int, b text) as assignment;
create cast (int as text) without function;
create cast (int as text) without function as implicit;
create cast (int as text) without function as assignment;
create cast (int as text) with inout;
create cast (int as text) with inout as implicit;
create cast (int as text) with inout as assignment;
create cast (numeric(10, 2) as varchar(5)) with function f(numeric);
create cast (int[] as text[]) without function;
create cast (a.b as "C d") without function;
create cast (timestamp with time zone as time without time zone) with function f(int);
create cast (setof int as text) without function;
create cast (a.b%type as text) without function;
create cast (int as text) with function f(variadic int[]);
create cast (int as text) with function f(out int);
create cast (int as text) with function f(int, none);
create cast (int as text) with function;
create cast (int as text) with;
create cast (int as text);
create cast (int as text) as implicit;
create cast (int as text) without function as explicit;
create cast (int as text) with inout as;
create cast (int text) without function;
create cast (int as) without function;
create cast (int, text) without function;
create cast int as text without function;
create or replace cast (int as text) without function;
create cast (int as text) with function f(int) as implicit as assignment;
CREATE CAST (INT AS TEXT) WITH FUNCTION F(INT) AS IMPLICIT;
create /* c */ cast /* c */ ( /* c */ int /* c */ as /* c */ text /* c */ ) /* c */ with /* c */ function /* c */ f /* c */ ( /* c */ int ) /* c */ as /* c */ implicit;
drop cast (int as text);
drop cast if exists (int as text);
drop cast (int as text) cascade;
drop cast (int as text) restrict;
drop cast if exists (a.b[] as numeric(3)) cascade;
drop cast if exists (int as text) restrict;
drop cast (int as text), (text as int);
drop cast int as text;
drop cast (int as text) cascade restrict;
drop cast if not exists (int as text);
drop cast ();
drop cast (int);
-- CREATE TRANSFORM / DROP TRANSFORM
create transform for int language sql (from sql with function f(int), to sql with function g(int));
create transform for int language sql (to sql with function g(int), from sql with function f(int));
create transform for int language sql (from sql with function f(int));
create transform for int language sql (to sql with function g(int));
create or replace transform for int language plpythonu (from sql with function a.f(internal), to sql with function g(internal));
create transform for a.b[] language "sql" (from sql with function f);
create transform for numeric(3,1) language sql (from sql with function f(int, text, out int));
create transform for int language sql ();
create transform for int language sql (from sql with function f(int), from sql with function g(int));
create transform for int language sql (to sql with function f(int), to sql with function g(int));
create transform for int language sql (from sql with function f(int), to sql with function g(int), from sql with function f(int));
create transform for int language sql (from sql function f(int));
create transform for int language sql (from with function f(int));
create transform for int language sql (from sql with f(int));
create transform for int language sql (from sql with function);
create transform for int language sql from sql with function f(int);
create transform for int (from sql with function f(int));
create transform int language sql (from sql with function f(int));
create transform for int language (from sql with function f(int));
create transform if not exists for int language sql (from sql with function f(int));
CREATE TRANSFORM FOR INT LANGUAGE SQL (FROM SQL WITH FUNCTION F(INT), TO SQL WITH FUNCTION G(INT));
create /* c */ transform /* c */ for /* c */ int /* c */ language /* c */ sql /* c */ ( /* c */ from /* c */ sql /* c */ with /* c */ function /* c */ f /* c */ ( /* c */ int /* c */ ) /* c */ ) ;
drop transform for int language sql;
drop transform if exists for int language sql;
drop transform for int language sql cascade;
drop transform for int language sql restrict;
drop transform if exists for a.b[] language "Sql" cascade;
drop transform for int language sql, for text language sql;
drop transform for int;
drop transform int language sql;
drop transform for int language;
drop transform if not exists for int language sql;
drop transform for int language sql cascade restrict;
