-- CREATE AGGREGATE, new syntax
create aggregate foo(int) (sfunc = f, stype = int);
create aggregate foo(*) (sfunc = f, stype = int);
create aggregate foo(int, text) (sfunc = f, stype = int, initcond = '0');
create aggregate foo(a int, b text) (sfunc = f, stype = int);
create aggregate foo(in a int, variadic b text[]) (sfunc = f, stype = int);
create aggregate foo(variadic "any") (sfunc = f, stype = int);
create aggregate foo(int order by int) (sfunc = f, stype = int);
create aggregate foo(order by int) (sfunc = f, stype = int);
create aggregate foo(order by a int, b text) (sfunc = f, stype = int);
create aggregate foo(int, int order by text, int) (sfunc = f, stype = int);
create aggregate foo(int, variadic int[] order by variadic int[]) (sfunc = f, stype = int);
create aggregate foo(variadic int[] order by variadic int[]) (sfunc = f, stype = int);
create aggregate foo(variadic int[] order by variadic text[]) (sfunc = f, stype = int);
create aggregate foo(int, variadic int[] order by int) (sfunc = f, stype = int);
create aggregate foo(int, variadic int[] order by variadic int[], int) (sfunc = f, stype = int);
create aggregate foo(int, variadic int[] order by variadic int) (sfunc = f, stype = int);
create aggregate foo(a int, variadic b int[] order by variadic c int[]) (sfunc = f, stype = int);
create aggregate foo(out a int) (sfunc = f, stype = int);
create aggregate foo(inout a int) (sfunc = f, stype = int);
create aggregate foo(int default 1) (sfunc = f, stype = int);
create aggregate foo() (sfunc = f, stype = int);
create aggregate foo(int order by) (sfunc = f, stype = int);
create aggregate foo(order by) (sfunc = f, stype = int);
create aggregate foo(int, *) (sfunc = f, stype = int);
create aggregate foo(* order by int) (sfunc = f, stype = int);
create aggregate foo(int order by int order by int) (sfunc = f, stype = int);
create aggregate a.foo(int) (sfunc = f, stype = int);
create aggregate a.b.foo(int) (sfunc = f, stype = int);
create or replace aggregate foo(int) (sfunc = f, stype = int);
create aggregate foo(int) (sfunc = a.f, stype = int[], finalfunc = g, combinefunc = h, parallel = safe, sortop = <, initcond = '', msfunc = a.b, hypothetical);
create aggregate foo(int) (sfunc = f, stype = int, sortop = operator(pg_catalog.<));
create aggregate foo(int) (sfunc = f, stype = int, serialfunc = x, deserialfunc = y, minitcond = 'z');
create aggregate foo(int) (sfunc = f, stype = numeric(3,2), sspace = 100, mstype = text, msspace = -1, finalfunc_extra, finalfunc_modify = read_only);
create aggregate foo(int) (sfunc = f, stype = int, order = 1.5);
create aggregate foo(int) ();
create aggregate foo(int);
create aggregate foo(int) (sfunc);
create aggregate foo(int) (sfunc = );
create aggregate foo(int) (sfunc = f,);
create aggregate foo(int) (sfunc = default, stype = null, x = none, y = 'z', "Q" = 1);
create aggregate foo(int) (sfunc = f, stype = int, x = -1, y = +2, z = -1.5);
create aggregate foo (int) (sfunc = f, stype = int) ;
-- CREATE AGGREGATE, old syntax
create aggregate foo (basetype = int, sfunc = f, stype = int);
create aggregate foo (basetype = any, sfunc = f, stype = int, initcond = 'x');
create or replace aggregate foo (basetype = int, sfunc = f, stype = int);
create aggregate foo (sfunc = f);
create aggregate a.b.foo (basetype = int, sfunc = f, stype = int);
create aggregate foo (basetype = int, sfunc);
create aggregate foo (basetype = int, "sfunc" = f);
create aggregate foo (basetype);
create aggregate foo (sfunc1 = f, basetype = int, stype1 = int, sortop = >);
create aggregate foo (default = 1);
create aggregate foo (type = 1);
create aggregate foo (basetype = int,);
create aggregate foo ();
-- CREATE OPERATOR
create operator === (leftarg = int, rightarg = int, procedure = f);
create operator === (rightarg = int, function = f);
create operator + (leftarg = int, procedure = f);
create operator a.=== (procedure = f);
create operator pg_catalog.+ (procedure = f);
create operator < (procedure = f, commutator = >, negator = >=, restrict = scalarltsel, join = scalarltjoinsel, hashes, merges);
create operator <=> (procedure = f, commutator = operator(a.<=>), negator = operator(<>));
create operator === (leftarg = a.b, rightarg = int[], procedure = a.f);
create operator ~ (procedure = f);
create operator !! (procedure = f);
create operator -> (procedure = f);
create operator @@@ (procedure = f);
create operator =- (procedure = f);
create operator <> (procedure = f);
create operator != (procedure = f);
create operator * (procedure = f);
create operator / (procedure = f);
create operator % (procedure = f);
create operator ^ (procedure = f);
create operator = (procedure = f);
create operator >= (procedure = f);
create operator => (procedure = f);
create operator || (procedure = f);
create operator a.b.c.+ (procedure = f);
create operator === ();
create operator === ;
create operator === (procedure);
create operator foo (procedure = f);
create operator or replace === (procedure = f);
create or replace operator === (procedure = f);
create operator === (leftarg = none, procedure = f);
create operator "===" (procedure = f);
create operator operator(a.+) (procedure = f);
create operator class;
CREATE OPERATOR === (PROCEDURE = F);
create /* c */ operator /* c */ === /* c */ ( /* c */ procedure /* c */ = /* c */ f /* c */ ) ;
-- CREATE TYPE
create type t;
create type a.b;
create type a.b.c;
create type a.b.c.d;
create type t (input = i, output = o);
create type t (input = i, output = o, internallength = 4, passedbyvalue, alignment = int4, storage = plain, like = int4, category = 'N', preferred = true, default = 0, element = int, delimiter = ',', collatable = true);
create type a.t (input = a.i, output = a.o, internallength = variable, storage = external);
create type t (input = i, output = o, default = 'x', typmod_in = a, typmod_out = b, analyze = c, subscript = d, send = e, receive = f);
create type t ();
create type t (input);
create type t (input = );
create type t (internallength = 1.5, alignment = -1, x = 'a' );
create type t (x = none, y = default, z = null);
create type "T" ("Input" = i);
create type t as (a int, b text);
create type t as (a int);
create type t as ();
create type a.t as (a int, b a.c, c int[], d numeric(3,2), e text collate "C");
create type a.b.t as (a int);
create type a.b.c.t as (a int);
create type t as (a);
create type t as (int);
create type t as (a int,);
create type t as (a int primary key);
create type t as (a int not null);
create type t as (a int default 1);
create type t as (a int collate "C");
create type t as (a setof int);
create type t as (a t%type);
create type "A b" as ("C d" "E f");
create type t as enum ();
create type t as enum ('a');
create type t as enum ('a', 'b', 'c');
create type a.t as enum ('a', E'b\n', $$c$$, U&'d');
create type a.b.c.t as enum ('a');
create type t as enum (a);
create type t as enum ('a',);
create type t as enum ('a' 'b');
create type t as range (subtype = int);
create type t as range (subtype = int, subtype_opclass = a.b, collation = "C", canonical = f, subtype_diff = g, multirange_type_name = m);
create type a.t as range (subtype = a.b);
create type t as range ();
create type t as range;
create type t as range (subtype);
create type t as table (a int);
create type t as something;
create type t as;
create type or replace t;
create or replace type t;
create type if not exists t;
CREATE TYPE T AS ENUM ('A');
create /* c */ type /* c */ t /* c */ as /* c */ ( /* c */ a /* c */ int /* c */ ) /* c */ ;
-- ALTER TYPE
alter type t add value 'a';
alter type a.b add value 'a';
alter type t add value if not exists 'a';
alter type t add value 'a' before 'b';
alter type t add value 'a' after 'b';
alter type t add value if not exists 'a' before 'b';
alter type t add value if not exists 'a' after 'b';
alter type t add value E'a\n' after $$b$$;
alter type t add value 'a' before;
alter type t add value 'a' before 'b' after 'c';
alter type t add value;
alter type t add value a;
alter type t add value if exists 'a';
alter type t add 'a';
alter type t rename value 'a' to 'b';
alter type a.b rename value 'a' to 'b';
alter type t rename value 'a' to;
alter type t rename value 'a';
alter type t rename value to 'b';
alter type t rename 'a' to 'b';
alter type t drop value 'a';
alter type t drop value if exists 'a';
alter type t set (storage = plain);
alter type t set (storage = plain, send = f, receive = g, typmod_in = h, typmod_out = i, analyze = j, subscript = k);
alter type t set (storage = none);
alter type t set (x = none, y, z = 1, w = -1, v = 'a', u = int, t = a.b, s = default, r = operator(a.+), q = +);
alter type a.b set (x = 1);
alter type t set ();
alter type t set (x = );
alter type t set (x,);
alter type t set x = 1;
alter type t set (x = 1) (y = 2);
alter type t set (x = 1.5);
alter type t set (x = array);
alter type t set (x = setof int);
alter type t set (x = a%type);
alter type t set (x = a.b%type);
alter type t set (default = 1);
alter type t set (x = default);
alter type t set (x = 'a' 'b');
ALTER TYPE T ADD VALUE IF NOT EXISTS 'A' BEFORE 'B';
alter /* c */ type /* c */ t /* c */ add /* c */ value /* c */ 'a' /* c */ ;
-- ALTER OPERATOR
alter operator === (int, int) set (restrict = f, join = g);
alter operator === (int, none) set (restrict = none, join = j, x, y = 1);
alter operator === (none, int) set (restrict = none);
alter operator a.=== (a.b, int[]) set (restrict = a.f);
alter operator + (int, int) set (commutator = +, negator = operator(a.-), hashes, merges);
alter operator === (int, int) set (restrict = none, join = none);
alter operator === (int, int) set (x = none, y = none, z);
alter operator === (int, int) set (none = none);
alter operator === (int, int) set (x = none none);
alter operator === (int, int) set (x = none.y);
alter operator === (int, int) set ();
alter operator === (int, int) set (x);
alter operator === (int, int) set (x = );
alter operator === (int) set (x = 1);
alter operator === (none, none) set (x = 1);
alter operator === set (x = 1);
alter operator === () set (x = 1);
alter operator === (int, int) set x;
alter operator === (int, int) set (x = 1)(y = 2);
alter operator === (int, int) rename to ===;
alter operator === (int, int) owner to x;
alter operator === (int, int) set schema s;
alter operator === (int, int) set (x = 1, y = 'a', z = -1.5, w = default, v = array, u = a.b);
alter operator === (setof int, int) set (x = 1);
alter operator === (int, a.b%type) set (x = 1);
ALTER OPERATOR === (INT, NONE) SET (RESTRICT = NONE);
alter /* c */ operator /* c */ === /* c */ ( /* c */ int /* c */ , /* c */ none /* c */ ) /* c */ set /* c */ ( /* c */ x /* c */ = /* c */ none /* c */ ) /* c */ ;
