-- CREATE LANGUAGE
create language l;
create or replace language l;
create trusted language l;
create procedural language l;
create trusted procedural language l;
create or replace trusted procedural language l;
create or replace procedural language l;
create or replace trusted language l;
create language "L";
create language a.l;
create language l handler h;
create language l handler a.h;
create language l handler h inline i;
create language l handler h inline a.i;
create language l handler h validator v;
create language l handler h validator a.v;
create language l handler h no validator;
create language l handler h inline i validator v;
create language l handler h inline i no validator;
create language l handler h validator v inline i;
create or replace trusted procedural language l handler a.h inline a.i validator a.v;
create trusted language l handler h;
create procedural language l handler h;
create language l handler h inline;
create language l handler h validator;
create language l handler h no;
create language l handler;
create language l handler a.b.c.h;
create language l handler h.i.j;
create language l inline i;
create language l validator v;
create language l no validator;
create language l handler h inline i inline j;
create language l handler h validator v validator w;
create language l handler h no validator validator v;
create language;
create language l handler h,i;
create language l handler "H";
create language l handler select;
create language l handler user.x;
create language l handler a.select;
create language l handler a.user.x;
create language if not exists l;
create language l if not exists;
create trusted trusted language l;
create procedural procedural language l;
create procedural trusted language l;
create or replace or replace language l;
CREATE OR REPLACE TRUSTED PROCEDURAL LANGUAGE L HANDLER H INLINE I VALIDATOR V;
create /* c */ trusted /* c */ procedural /* c */ language /* c */ l /* c */ handler /* c */ h /* c */ no /* c */ validator /* c */ ;
-- CREATE EXTENSION
create extension e;
create extension if not exists e;
create extension e with schema s;
create extension e schema s;
create extension e with version '1.0';
create extension e version '1.0';
create extension e version v;
create extension e version "V";
create extension e with cascade;
create extension e cascade;
create extension e with schema s version '1' cascade;
create extension e schema s version '1' cascade;
create extension e cascade version '1' schema s;
create extension e with with schema s;
create extension e schema s schema t;
create extension e version '1' version '2';
create extension e cascade cascade;
create extension if not exists e with schema s version 'x' cascade;
create extension e from '1';
create extension e from v;
create extension e with from '1';
create extension e schema;
create extension e version;
create extension e with;
create extension e schema 's';
create extension e version 1;
create extension e version 1.0;
create extension e version null;
create extension e version select;
create extension e version user;
create extension e schema select;
create extension e schema user;
create extension e schema a.b;
create extension "e-f";
create extension a.b;
create extension e if not exists;
create extension if exists e;
create extension if not e;
create extension;
create extension select;
create extension user;
create extension e with schema s with version '1';
create extension e, f;
create or replace extension e;
CREATE EXTENSION IF NOT EXISTS E WITH SCHEMA S VERSION '1' CASCADE;
create /* c */ extension /* c */ e /* c */ with /* c */ schema /* c */ s /* c */ ;
-- ALTER EXTENSION UPDATE
alter extension e update;
alter extension e update to '2';
alter extension e update to v;
alter extension e update to "V";
alter extension e update to 'a' to 'b';
alter extension e update to;
alter extension e update to 1;
alter extension e update to null;
alter extension e update to select;
alter extension e update version '2';
alter extension e update schema s;
alter extension e update cascade;
alter extension e update to '2' cascade;
alter extension e;
alter extension update;
alter extension a.b update;
alter extension "E" update to '2';
alter extension if exists e update;
alter extension e update to 'a', 'b';
ALTER EXTENSION E UPDATE TO '2';
alter /* c */ extension /* c */ e /* c */ update /* c */ to /* c */ '2' ;
alter extension e set schema s;
alter extension e set schema;
-- ALTER EXTENSION ADD / DROP
alter extension e add table t;
alter extension e drop table t;
alter extension e add table a.b;
alter extension e add table a.b.c;
alter extension e add table a.b.c.d;
alter extension e add sequence s;
alter extension e add view v;
alter extension e add materialized view v;
alter extension e add index i;
alter extension e add foreign table t;
alter extension e add collation c;
alter extension e add conversion c;
alter extension e add statistics s;
alter extension e add text search parser p;
alter extension e add text search dictionary d;
alter extension e add text search template t;
alter extension e add text search configuration c;
alter extension e add access method m;
alter extension e add event trigger t;
alter extension e add extension x;
alter extension e add foreign data wrapper w;
alter extension e add language l;
alter extension e add procedural language l;
alter extension e add publication p;
alter extension e add schema s;
alter extension e add server s;
alter extension e add database d;
alter extension e add role r;
alter extension e add subscription s;
alter extension e add tablespace t;
alter extension e add schema a.b;
alter extension e add role a.b;
alter extension e add language a.b;
alter extension e add table;
alter extension e add table t, u;
alter extension e add schema s, t;
alter extension e add aggregate f(int);
alter extension e add aggregate f(*);
alter extension e add aggregate a.f(int, text);
alter extension e add aggregate f(order by int);
alter extension e add aggregate f(int order by text);
alter extension e add aggregate f(variadic int[] order by variadic int[]);
alter extension e add aggregate f(out int);
alter extension e add aggregate f;
alter extension e add aggregate f();
alter extension e drop aggregate f(int);
alter extension e add cast (int as text);
alter extension e drop cast (int as text);
alter extension e add cast (a.b[] as numeric(3));
alter extension e add cast (int);
alter extension e add cast int as text;
alter extension e add domain d;
alter extension e add domain a.d;
alter extension e add domain int[];
alter extension e add domain setof int;
alter extension e add domain numeric(3,2);
alter extension e drop domain d;
alter extension e add function f;
alter extension e add function f(int);
alter extension e add function a.f(int, out text);
alter extension e add function a.b.c.f(int);
alter extension e add function f();
alter extension e add function a.b.f;
alter extension e add function a.b.c.d.f;
alter extension e add function "F";
alter extension e add function text;
alter extension e add function a.text;
alter extension e add function f(variadic int[]);
alter extension e add function f(a int default 1);
alter extension e drop function f(int);
alter extension e add operator ===(int, int);
alter extension e add operator === (int, none);
alter extension e add operator a.=== (none, int);
alter extension e add operator + (int, int);
alter extension e add operator === (int);
alter extension e add operator ===;
alter extension e add operator (int, int);
alter extension e drop operator === (int, int);
alter extension e add operator class c using btree;
alter extension e add operator class a.c using btree;
alter extension e add operator class a.b.c using btree;
alter extension e add operator class c using;
alter extension e add operator class c;
alter extension e add operator class using btree;
alter extension e add operator family f using btree;
alter extension e add operator family a.f using "btree";
alter extension e add operator family f;
alter extension e drop operator class c using btree;
alter extension e drop operator family f using btree;
alter extension e add procedure p;
alter extension e add procedure p(int);
alter extension e add procedure a.p();
alter extension e drop procedure p(int);
alter extension e add routine r;
alter extension e add routine r(int);
alter extension e drop routine r(int, text);
alter extension e add transform for int language sql;
alter extension e add transform for a.b[] language sql;
alter extension e add transform for int language "SQL";
alter extension e add transform for int;
alter extension e add transform int language sql;
alter extension e drop transform for int language sql;
alter extension e add type t;
alter extension e add type a.t;
alter extension e add type int[];
alter extension e add type setof int;
alter extension e add type numeric(3,2);
alter extension e add type timestamp with time zone;
alter extension e drop type t;
alter extension e add trigger t;
alter extension e add rule r;
alter extension e add policy p;
alter extension e add column c;
alter extension e add large object 1;
alter extension e add constraint c;
alter extension e add function;
alter extension e add;
alter extension e drop;
alter extension e add table t cascade;
alter extension e add table t restrict;
alter extension e drop table if exists t;
alter extension e add if not exists table t;
alter extension e add aggregate;
alter extension e add 1;
ALTER EXTENSION E ADD TABLE T;
alter /* c */ extension /* c */ e /* c */ add /* c */ foreign /* c */ data /* c */ wrapper /* c */ w;
alter extension e add materialized /* c */ view v;
alter extension e add text -- c
  search -- c
  configuration c;
-- CREATE ACCESS METHOD
create access method am type index handler h;
create access method am type table handler h;
create access method am type table handler a.h;
create access method "AM" type index handler "H";
create access method a.am type index handler h;
create access method am type index;
create access method am handler h;
create access method am type handler h;
create access method am type sequence handler h;
create access method am type 'index' handler h;
create access method type index handler h;
create access method am type index handler a.b.c.d;
create access method am type index handler h inline i;
create access method am type index handler;
create access method am type index handler select;
create or replace access method am type index handler h;
create access method if not exists am type index handler h;
CREATE ACCESS METHOD AM TYPE TABLE HANDLER H;
create /* c */ access /* c */ method /* c */ am /* c */ type /* c */ index /* c */ handler /* c */ h;
