-- CREATE FUNCTION / PROCEDURE
create function f() returns int as 'select 1' language sql;
create or replace function f(a int, b text default 'x', c int = 1) returns text language plpgsql as $$ begin return 'x'; end $$;
CREATE FUNCTION f(IN a int, OUT b int, INOUT c int, VARIADIC d int[]) returns record as 'x' language sql;
create function f(in out a int, b in int, c out text, d inout text, e variadic text[]) returns void as 'x' language c;
create function f(int, text, a.b%type, setof int) returns setof int as 'x', 'y' language c strict;
create function f(a b.c%type default null) returns setof b.c.d%type language sql as 'x';
create function f() returns setof t.c%type as 'x' language sql;
create function a.b.c() returns int as 'x' language sql;
create function f() returns table(x int);
create function f(a int) returns table(x int, y text, z numeric(10,2)) language sql as 'select 1';
create function f(a int, in b text, variadic c int[]) returns table(x int) language sql as 'select 1';
create function f(out a int) returns table(x int) language sql as 'select 1';
create function f(inout a int) returns table(x int) language sql as 'select 1';
create function f(out a int) returns table(x int, y int) language sql as 'select 1';
create function f() returns table(x int[], y setof int) language sql as 'select 1';
create function f() returns table(x t.c%type) language sql as 'select 1';
create function f() language sql as 'select 1';
create function f() as 'x' language c;
create function f() returns null on null input language sql as 'x';
create function f() returns int returns null on null input language sql as 'x';
create function f() returns int called on null input language sql as 'x';
create function f() returns int strict immutable stable volatile as 'x' language sql;
create function f() returns int as 'x' language sql external security definer;
create function f() returns int as 'x' language sql external security invoker;
create function f() returns int as 'x' language sql security definer;
create function f() returns int as 'x' language sql security invoker;
create function f() returns int as 'x' language sql leakproof not leakproof;
create function f() returns int as 'x' language sql cost 10 rows 5;
create function f() returns int as 'x' language sql cost 1.5 rows -2;
create function f() returns int as 'x' language sql cost +3;
create function f() returns int as 'x' language sql support a.b;
create function f() returns int as 'x' language sql support b;
create function f() returns int as 'x' language sql parallel safe;
create function f() returns int as 'x' language sql parallel unsafe;
create function f() returns int as 'x' language sql parallel restricted;
create function f() returns int as 'x' language sql parallel "weird";
create function f() returns int as 'x' language sql window;
create function f() returns int as 'x' language 'sql';
create function f() returns int as 'x' language sql transform for type int;
create function f() returns int as 'x' language sql transform for type int, for type text, for type numeric(3);
create function f() returns int as 'x' language sql set search_path = a, b;
create function f() returns int as 'x' language sql set search_path to a, 'b', 1, -1, 2.5, -2.5, +3, on, true, false, off;
create function f() returns int as 'x' language sql set search_path = default;
create function f() returns int as 'x' language sql set search_path to default;
create function f() returns int as 'x' language sql set a.b.c from current;
create function f() returns int as 'x' language sql set x from current;
create function f() returns int as 'x' language sql reset x;
create function f() returns int as 'x' language sql reset all;
create function f() returns int as 'x' language sql reset a.b;
create function f() returns int as 'x' language sql set "Foo" = 'x' set bar = 1;
create function f() returns int language sql return 1 + 2;
create function f() returns int language sql return (select 1);
create function f(a int, b int) returns int language sql immutable return a + b;
create function f() returns int language sql begin atomic select 1; end;
create function f() returns int language sql begin atomic end;
create function f() returns int language sql begin atomic; end;
create function f() returns int language sql begin atomic select 1; select 2; end;
create function f() returns int language sql begin atomic ;; select 1;; ; select 2 ;;; end;
create function f() returns int language sql begin atomic return 1; end;
create function f() returns int language sql begin atomic select 1; return 2; end;
create function f() returns int language sql begin atomic insert into t values (1); update t set a = 1; delete from t; end;
create function f() returns int language sql begin atomic with x as (select 1) select * from x; return 3; end;
create function f() returns int language sql begin atomic create function g() returns int language sql return 1; end;
create function f() returns int language sql begin atomic create function g() returns int language sql begin atomic select 2; end; end;
create function f() returns int language sql begin atomic select 1 end;
create function f() returns int language sql begin atomic return 1 end;
create function f() returns int language sql begin atomic select 1; select;
create function f() returns int begin atomic select 1; end;
create function f() returns int language sql begin atomic; select 1; end;
create function f() language sql return 1;
create function f() return 1;
create function f() returns int as 'x' language sql return 1;
create function f() returns int return 1 begin atomic end;
create or replace procedure p() language sql as 'x';
create procedure p(a int, inout b int, out c int, variadic d int[]) language sql as 'x';
create procedure p(a int default 1, b int = 2) language sql as 'x';
create procedure p() language sql begin atomic select 1; end;
create procedure p() language sql return 1;
create procedure p() returns int language sql as 'x';
create procedure p() returns null on null input language sql as 'x';
create procedure p() called on null input security definer set x = 1 language sql as 'x';
create procedure p() strict;
create procedure p();
create function f(a int, a int);
create function f(a int,) returns int;
create function f(a int default 1 + 2, b int = 3 * 4) returns int;
create function f(a int default (select 1)) returns int;
create function f(a int default) returns int;
create function f("A" "B") returns "C" as 'x' language "sql";
create function f(a int) returns int as 'x' language sql cost 1 cost 2 rows 3 language c;
create function f(int default 1);
create function f(a int default 1, int);
create or replace function if not exists f();
create function f() returns numeric(10,2) as 'x' language sql;
create function f() returns timestamp with time zone as 'x' language sql;
create function f() returns int[] as 'x' language sql;
create function f() returns setof int[] as 'x' language sql;
create function f() returns int array[3] as 'x' language sql;
create function f() returns "a b" as 'x' language sql;
create function /* c */ f /* c */ ( /* c */ ) /* c */ returns /* c */ int /* c */ as /* c */ 'x' /* c */ , /* c */ 'y' language c;
CREATE OR REPLACE FUNCTION F() RETURNS INT AS 'x' LANGUAGE SQL;
cReAtE fUnCtIoN f() rEtUrNs iNt aS 'x' lAnGuAgE sQl sTrIcT;
create function f() returns int as $$x$$ language sql;
create function f() returns int as $a$x$a$, $b$y$b$ language c;
create function f() returns int as E'x\n' language sql;
create function f() returns int as 'x' 'y' language sql;
create function f() returns int as 'x' language sql parallel;
create function f() returns int as language sql;
create function f() returns int as x language sql;
create function f() returns int as 'x', language sql;
create function f() returns int as 'x', 'y', 'z' language sql;
create function f() returns int language;
create function f() returns int language sql set;
create function f() returns int language sql set x;
create function f() returns int language sql set x = ;
create function f() returns int language sql set time zone 'UTC';
create function f() returns int language sql set schema 'x';
create function f() returns int language sql set local x = 1;
create function f() returns int language sql set session x = 1;
create function f() returns int language sql reset time zone;
create function f() returns int language sql set x = 1 reset y;
create function f() returns int language sql reset;
create function f() returns int cost;
create function f() returns int rows 'x';
create function f() returns int cost 1.5e3;
create function f() returns int cost 99999999999;
create function f() returns int cost -1.5;
create function f() returns int support;
create function f() returns int support a.;
create function f() returns int transform for type;
create function f() returns int transform for int;
create function f() returns int transform type int;
-- ALTER FUNCTION / PROCEDURE / ROUTINE
alter function f cost 3;
alter function f(int) strict;
alter function f(int, out text, variadic int[]) cost 3;
alter function a.f() called on null input;
alter function a.b.f() returns null on null input;
alter function f stable immutable volatile;
alter function f external security definer;
alter function f security invoker leakproof;
alter function f not leakproof cost 2 rows 3;
alter function f support a.b parallel safe;
alter function f set search_path = x;
alter function f set search_path to 'a', 1;
alter function f set x from current;
alter function f reset x;
alter function f reset all;
alter function f(int) set a = 1 reset b security definer restrict;
alter function f strict restrict;
alter function f restrict;
alter function f;
alter function f();
alter function f() restrict;
alter function f(a int, b text) strict;
alter function f(int) language sql;
alter function f(int) window;
alter function f(int) as 'x';
alter function f(int) transform for type int;
alter function f(int) rename to g;
alter function f(int) owner to x;
alter function f(int) set schema x;
alter function f(int) default 1;
alter function f(a int default 1) strict;
alter function f(variadic int[]) strict;
alter function f(int, out text) strict;
alter function f(setof int) strict;
alter function f(t.c%type) strict;
alter function if exists f() strict;
alter function "F" strict;
alter function text strict;
alter function a.text strict;
alter function f strict strict strict;
alter function f.a.b.c strict;
alter function f(int) restrict strict;
alter function f(int) cascade;
alter procedure p stable;
alter procedure p(int, text) strict set x = 1;
alter procedure a.p() security definer;
alter procedure p;
alter routine r immutable;
alter routine r(int) security definer reset all;
alter routine r;
alter routine a.b.r() cost 1;
ALTER FUNCTION F COST 3;
alter /* c */ function /* c */ f /* c */ ( /* c */ int /* c */ ) /* c */ strict /* c */ restrict;
