-- more CREATE FUNCTION / ALTER FUNCTION
create function a.b.c.d.e() returns int as 'x' language sql;
create function f[1]() returns int as 'x' language sql;
create function f.*() returns int as 'x' language sql;
create function "F"."G"(a "T") returns "U"."V" as 'x' language sql;
create function text() returns int as 'x' language sql;
create function int() returns int as 'x' language sql;
create function a.int() returns int as 'x' language sql;
create function left() returns int as 'x' language sql;
create function user() returns int as 'x' language sql;
create function a.user() returns int as 'x' language sql;
create function f(user int) returns int as 'x' language sql;
create function f(a user) returns int as 'x' language sql;
create function f(left int) returns int as 'x' language sql;
create function f(between int) returns int as 'x' language sql;
create function f(in int) returns int as 'x' language sql;
create function f(in in int) returns int as 'x' language sql;
create function f(out out int) returns int as 'x' language sql;
create function f(inout inout int) returns int as 'x' language sql;
create function f(variadic variadic int) returns int as 'x' language sql;
create function f(a in out int) returns int as 'x' language sql;
create function f(a out int, b in int, c inout int, d variadic int) returns int as 'x' language sql;
create function f(a out) returns int as 'x' language sql;
create function f(in out) returns int as 'x' language sql;
create function f(out) returns int as 'x' language sql;
create function f(text) returns int as 'x' language sql;
create function f(a.b) returns int as 'x' language sql;
create function f(a b c) returns int as 'x' language sql;
create function f(a b.c) returns int as 'x' language sql;
create function f(a, b) returns int as 'x' language sql;
create function f(a int, b) returns int as 'x' language sql;
create function f(int, b int) returns int as 'x' language sql;
create function f(a int = 1, b int default 2, c int) returns int as 'x' language sql;
create function f(a int default 1 + 2 * 3, b text default 'a' || 'b', c int default (1), d int default null) returns int as 'x' language sql;
create function f(a int default 'a'::text, b int default array[1,2], c int[] default '{}', d int default -1) returns int as 'x' language sql;
create function f(a int default b between 1 and 2) returns int as 'x' language sql;
create function f(a int default 1, b int = a) returns int as 'x' language sql;
create function f(a int = ) returns int as 'x' language sql;
create function f(a int default default) returns int as 'x' language sql;
create function f(a int default 1 default 2) returns int as 'x' language sql;
create function f(a int default 1 = 2) returns int as 'x' language sql;
create function f(a int = 1 = 2) returns int as 'x' language sql;
create function f(a int, = 1) returns int as 'x' language sql;
create function f(variadic a int[] default array[1]) returns int as 'x' language sql;
create function f(out a int default 1) returns int as 'x' language sql;
create function f(a numeric(10), b varchar(5), c timestamp(3) with time zone, d interval day to second(3), e bit(3), f char) returns int as 'x' language sql;
create function f(a setof int) returns int as 'x' language sql;
create function f(a setof t.c%type) returns int as 'x' language sql;
create function f(a t.c%type, b t.c%type[]) returns int as 'x' language sql;
create function f(a t%type) returns int as 'x' language sql;
create function f(a "T".c%type) returns int as 'x' language sql;
create function f(a t.c%TYPE) returns int as 'x' language sql;
create function f(a t.c % type) returns int as 'x' language sql;
create function f(a t.c%rowtype) returns int as 'x' language sql;
create function f() returns t%type as 'x' language sql;
create function f() returns a.b.c.d%type as 'x' language sql;
create function f() returns setof setof int as 'x' language sql;
create function f() returns int[][] as 'x' language sql;
create function f() returns text array as 'x' language sql;
create function f() returns record as 'x' language sql;
create function f() returns trigger as 'x' language plpgsql;
create function f() returns "any" as 'x' language c;
create function f() returns double precision as 'x' language sql;
create function f() returns character varying(10) as 'x' language sql;
create function f() returns bit varying(3) as 'x' language sql;
create function f() returns national character(2) as 'x' language sql;
create function f() returns float(10) as 'x' language sql;
create function f() returns float(30) as 'x' language sql;
create function f() returns float(0) as 'x' language sql;
create function f() returns float(60) as 'x' language sql;
create function f() returns interval as 'x' language sql;
create function f() returns interval(3) as 'x' language sql;
create function f() returns interval year as 'x' language sql;
create function f() returns time(3) without time zone as 'x' language sql;
create function f() returns table(a int, b int) as 'x' language sql;
create function f() returns table(a int) language sql as 'x' set x = 1;
create function f() returns table(a int, b text) rows 10 language sql as 'x';
create function f() returns table(a setof int) language sql as 'x';
create function f() returns table(a int array[3]) language sql as 'x';
create function f() returns table(in a int) language sql as 'x';
create function f() returns table(a in int) language sql as 'x';
create function f() returns table(int) language sql as 'x';
create function f() returns table(a) language sql as 'x';
create function f() returns table() language sql as 'x';
create function f() returns table(a int,) language sql as 'x';
create function f() returns table(a int default 1) language sql as 'x';
create function f() returns table(a int, a int) language sql as 'x';
create function f() returns table as 'x' language sql;
create function f() returns setof table(a int) as 'x' language sql;
create function f(a int) returns table(b int) as 'x' language sql;
create function f(variadic a int[]) returns table(b int) as 'x' language sql;
create function f(inout a int) returns table(b int) as 'x' language sql;
create function f(a int, out b int) returns table(c int) as 'x' language sql;
create procedure p(a int) returns table(b int) as 'x' language sql;
create function f() returns table(user int) as 'x' language sql;
create function f() returns table(between int) as 'x' language sql;
create function f() returns table(a user) as 'x' language sql;
create function f() returns int language sql as 'a' set x = 1 as 'b';
create function f() returns int language sql parallel safe window strict;
create function f() returns int as 'a' language sql as 'b';
create function f() returns int strict strict;
create function f() returns int language plpgsql set x = 1 set y = 2 set z from current reset w reset all;
create function f() returns int language plpgsql set x to 1, 2, 3;
create function f() returns int language plpgsql set x = 1 2;
create function f() returns int language plpgsql set x = a b;
create function f() returns int language plpgsql set x = 'a' 'b';
create function f() returns int language plpgsql set x = select;
create function f() returns int language plpgsql set x = user;
create function f() returns int language plpgsql set x = float;
create function f() returns int language plpgsql set x = none;
create function f() returns int language plpgsql set x = off;
create function f() returns int language plpgsql set x = "On";
create function f() returns int language plpgsql set x = on;
create function f() returns int language plpgsql set x = true;
create function f() returns int language plpgsql set x = false, on, off;
create function f() returns int language plpgsql set x = 1e3;
create function f() returns int language plpgsql set x = -1e3;
create function f() returns int language plpgsql set x = - 1;
create function f() returns int language plpgsql set x = +-1;
create function f() returns int language plpgsql set x = --1;
create function f() returns int language plpgsql set x = 0x10;
create function f() returns int language plpgsql set x = 99999999999;
create function f() returns int language plpgsql set x = -99999999999;
create function f() returns int language plpgsql set x = .5;
create function f() returns int language plpgsql set x = 5.;
create function f() returns int language plpgsql set x = E'a\n';
create function f() returns int language plpgsql set x = $$a$$;
create function f() returns int language plpgsql set x = U&'a';
create function f() returns int language plpgsql set x = 1 + 2;
create function f() returns int language plpgsql set x = (1);
create function f() returns int language plpgsql set x = a.b;
create function f() returns int language plpgsql set x = 'a'::text;
create function f() returns int language plpgsql set x = ARRAY[1];
create function f() returns int language plpgsql set a.b.c.d = 1;
create function f() returns int language plpgsql set "A"."B" = 1;
create function f() returns int language plpgsql set a . b = 1;
create function f() returns int language plpgsql set select = 1;
create function f() returns int language plpgsql set user = 1;
create function f() returns int language plpgsql set a.select = 1;
create function f() returns int language plpgsql set a.user = 1;
create function f() returns int language plpgsql set float = 1;
create function f() returns int language plpgsql set a.float = 1;
create function f() returns int language plpgsql set work_mem to '1MB';
create function f() returns int language plpgsql set x = default;
create function f() returns int language plpgsql set x to default;
create function f() returns int language plpgsql set x to default, 1;
create function f() returns int language plpgsql set x = ;
create function f() returns int language plpgsql set x to;
create function f() returns int language plpgsql set x from current, 1;
create function f() returns int language plpgsql set x from;
create function f() returns int language plpgsql set x current;
create function f() returns int language plpgsql set from current;
create function f() returns int language plpgsql reset a.b.c;
create function f() returns int language plpgsql reset "A";
create function f() returns int language plpgsql reset all all;
create function f() returns int language plpgsql reset x, y;
create function f() returns int language plpgsql reset select;
create function f() returns int language plpgsql reset session authorization;
create function f() returns int language plpgsql reset transaction isolation level;
create function f() returns int language plpgsql set session authorization default;
create function f() returns int language plpgsql set role 'x';
create function f() returns int language plpgsql set names 'x';
create function f() returns int language plpgsql set xml option document;
create function f() returns int language plpgsql set transaction snapshot 'x';
create function f() returns int language plpgsql set catalog 'x';
create function f() returns int language plpgsql set time zone default;
create function f() returns int language plpgsql set time zone local;
create function f() returns int language plpgsql set time zone 1;
create function f() returns int language plpgsql set time zone interval '1' hour;
create function f() returns int language plpgsql set time zone interval '1' day;
create function f() returns int language plpgsql set time zone x;
create function f() returns int language plpgsql set schema 'x';
create function f() returns int language plpgsql set search_path from current;
alter function f(int) set a.b = 1;
alter function f(int) set a = 'x', 'y';
alter function f(int) set a = default;
alter function f(int) set a to default;
alter function f(int) reset a.b;
alter function f(int) set time zone 'UTC';
alter function f(int) set schema 'x';
alter function f(int) set role 'x';
alter function f(int) reset time zone;
alter function f(int) reset session authorization;
alter function f(int) reset transaction isolation level;
alter function f[1] strict;
alter function f.* strict;
alter function f(int)[1] strict;
alter function a.b.c.d.e strict;
alter function a.b.c.d.e() strict;
alter function a.b.c.d.e(int) strict;
alter function user strict;
alter function a.user strict;
alter function left strict;
alter function a.left strict;
alter function a.b.left(int) strict;
alter function f(user int) strict;
alter function f(int default 1) strict;
alter function f(a int = 1) strict;
alter function f(a int, b) strict;
alter function f(a int, int) strict;
alter function f(in out a int) strict;
alter function f(setof int) strict;
alter function f(a.b%type) strict;
alter function f(a b%type) strict;
alter function f(numeric(3,2), varchar(5)) strict;
alter function f(int[], text array) strict;
alter function f(double precision, "char") strict;
alter function f(a.b.c.d) strict;
alter function f(a.b.c.d.e) strict;
alter function f(out int) strict;
alter function f(inout int) strict;
alter function f(variadic int) strict;
alter function f(in variadic int) strict;
alter function f(a out int, b int) strict;
alter function f(a variadic int[]) strict;
alter function f(a in out int) strict;
alter procedure f(out a int, b int) strict;
alter routine f(inout a int, out b int, c int) strict;
alter function f(int, out text) set x = 1;
alter function f volatile parallel unsafe;
alter function f parallel;
alter function f parallel safe unsafe;
alter function f security;
alter function f external;
alter function f external security;
alter function f external security definer invoker;
alter function f not;
alter function f not strict;
alter function f returns null;
alter function f returns null on;
alter function f returns null on null;
alter function f returns null on null input;
alter function f called on;
alter function f called on null;
alter function f called on null input restrict restrict;
alter function f cost;
alter function f cost 1 cost 2;
alter function f rows;
alter function f rows 1.5e3;
alter function f cost -1;
alter function f cost - 1;
alter function f cost + 1;
alter function f cost 'x';
alter function f cost x;
alter function f cost (1);
alter function f support;
alter function f support a.b.c.d;
alter function f support "S";
alter function f support select;
alter function f support user;
alter function f support a.user;
alter function f parallel "safe";
alter function f parallel 'safe';
alter function f parallel user;
alter function f parallel float;
alter function f parallel select;
alter function f parallel group;
alter function f set;
alter function f reset;
alter function f set x;
alter function f set x = 1 y = 2;
alter function f language sql strict;
alter function f strict language sql;
alter function f as 'x';
alter function f window;
alter function f transform for type int;
alter function f return 1;
alter function f begin atomic end;
