-- CREATE OPERATOR CLASS
create operator class c for type int using btree as operator 1 <;
create operator class c default for type int using btree as operator 1 <, operator 2 <=, function 1 f(int, int);
create operator class a.c default for type a.t using hash family a.f as operator 1 =, function 1 f(int);
create operator class c for type int using btree family f as storage int;
create operator class c for type int using btree as operator 1 < (int, int);
create operator class c for type int using btree as operator 1 a.< (int, int), operator 2 operator(a.<=) (int, int);
create operator class c for type int using btree as operator 1 < (int, int) for search;
create operator class c for type int using btree as operator 1 < for search;
create operator class c for type int using btree as operator 1 < for order by a.f;
create operator class c for type int using btree as operator 1 < (int, int) for order by f;
create operator class c for type int using btree as operator 1 < for order by;
create operator class c for type int using btree as operator 1 < for order;
create operator class c for type int using btree as operator 1 < for;
create operator class c for type int using btree as operator 1 < (int, none);
create operator class c for type int using btree as operator 1 < (none, int);
create operator class c for type int using btree as operator 1 < (int);
create operator class c for type int using btree as operator 1 < ();
create operator class c for type int using btree as operator < ;
create operator class c for type int using btree as operator 0 <;
create operator class c for type int using btree as operator -1 <;
create operator class c for type int using btree as operator 1.5 <;
create operator class c for type int using btree as operator x <;
create operator class c for type int using btree as function 1 f(int, int);
create operator class c for type int using btree as function 1 (int, int) f(int, int);
create operator class c for type int using btree as function 1 (int) a.f(int);
create operator class c for type int using btree as function 1 (a.b, int[], numeric(3)) f(int);
create operator class c for type int using btree as function 1 f;
create operator class c for type int using btree as function 1 a.f;
create operator class c for type int using btree as function 1 () f(int);
create operator class c for type int using btree as function 1 (int,) f(int);
create operator class c for type int using btree as function 1 (int);
create operator class c for type int using btree as function f(int);
create operator class c for type int using btree as function 1 f(out int);
create operator class c for type int using btree as function 1 f(a int, variadic int[]);
create operator class c for type int using btree as function 1 f(int) for search;
create operator class c for type int using btree as storage;
create operator class c for type int using btree as storage int[];
create operator class c for type int using btree as storage a.b, storage c;
create operator class c for type int using btree as storage setof int;
create operator class c for type int using btree as operator 1 <, operator 2 <=, operator 3 =, operator 4 >=, operator 5 >, function 1 btint4cmp(int4, int4), function 2 btint4sortsupport(internal), storage int;
create operator class c for type int using btree as operator 1 <,;
create operator class c for type int using btree as ;
create operator class c for type int using btree;
create operator class c for type int using btree family as operator 1 <;
create operator class c for type int using as operator 1 <;
create operator class c for type int btree as operator 1 <;
create operator class c for int using btree as operator 1 <;
create operator class c type int using btree as operator 1 <;
create operator class c using btree as operator 1 <;
create operator class for type int using btree as operator 1 <;
create operator class c default default for type int using btree as operator 1 <;
create operator class c for type setof int using btree as operator 1 <;
create operator class c for type int[] using btree as operator 1 <;
create operator class c for type a.b%type using btree as operator 1 <;
create operator class a.b.c for type int using btree as operator 1 <;
create operator class a.b.c.d for type int using btree as operator 1 <;
create operator class c for type int using btree family a.b.c.d as operator 1 <;
create operator class c for type int using "btree" as operator 1 <;
create operator class c for type int using a.btree as operator 1 <;
create or replace operator class c for type int using btree as operator 1 <;
create operator class if not exists c for type int using btree as operator 1 <;
CREATE OPERATOR CLASS C DEFAULT FOR TYPE INT USING BTREE FAMILY F AS OPERATOR 1 <, FUNCTION 1 F(INT), STORAGE INT;
create /* c */ operator /* c */ class /* c */ c /* c */ for /* c */ type /* c */ int /* c */ using /* c */ btree /* c */ as /* c */ operator /* c */ 1 /* c */ < /* c */ , /* c */ function /* c */ 1 /* c */ f /* c */ ( /* c */ int /* c */ ) ;
-- CREATE OPERATOR FAMILY / ALTER OPERATOR FAMILY / DROP
create operator family f using btree;
create operator family a.f using a.btree;
create operator family a.b.f using btree;
create operator family a.b.c.f using btree;
create operator family f using "btree";
create operator family f using;
create operator family f;
create operator family using btree;
create operator family f using btree family g;
create or replace operator family f using btree;
create operator family if not exists f using btree;
alter operator family f using btree add operator 1 <;
alter operator family a.f using btree add operator 1 < (int, int) for search, operator 2 <= (int, int) for order by g, function 1 f(int), function 1 (int, int) f(int), storage int;
alter operator family f using btree add operator 1 <, function 1 f(int);
alter operator family f using btree add;
alter operator family f using btree add storage int;
alter operator family f using btree drop operator 1 (int, int);
alter operator family f using btree drop function 1 (int, int);
alter operator family f using btree drop operator 1 (int, int), function 2 (int), operator 3 (a.b, c);
alter operator family f using btree drop operator 1;
alter operator family f using btree drop operator 1 ();
alter operator family f using btree drop operator 1 (int, none);
alter operator family f using btree drop function 1;
alter operator family f using btree drop storage int;
alter operator family f using btree drop;
alter operator family f using btree drop operator 1 (int, int),;
alter operator family f using btree drop operator < (int, int);
alter operator family f using btree add operator 1 < drop operator 1 (int, int);
alter operator family f using btree rename to g;
alter operator family f using btree owner to x;
alter operator family f using btree set schema s;
alter operator family f add operator 1 <;
alter operator family f using btree;
alter operator family f using add operator 1 <;
ALTER OPERATOR FAMILY F USING BTREE ADD OPERATOR 1 <;
alter /* c */ operator /* c */ family /* c */ f /* c */ using /* c */ btree /* c */ drop /* c */ operator /* c */ 1 /* c */ ( /* c */ int /* c */ ) ;
drop operator class c using btree;
drop operator class a.c using btree;
drop operator class a.b.c using btree;
drop operator class a.b.c.d using btree;
drop operator class if exists c using btree;
drop operator class c using btree cascade;
drop operator class c using btree restrict;
drop operator class if exists a.c using btree cascade;
drop operator class c using "btree" restrict;
drop operator class c using a.btree;
drop operator class c, d using btree;
drop operator class c using btree, using hash;
drop operator class c;
drop operator class using btree;
drop operator class c using;
drop operator class if not exists c using btree;
drop operator class c using btree cascade restrict;
drop operator class if exists;
drop operator family f using btree;
drop operator family a.f using btree;
drop operator family a.b.f using btree;
drop operator family a.b.c.f using btree;
drop operator family if exists f using btree;
drop operator family f using btree cascade;
drop operator family f using btree restrict;
drop operator family if exists a.f using btree cascade;
drop operator family f using "btree";
drop operator family f, g using btree;
drop operator family f;
drop operator family using btree;
drop operator family f using;
drop operator family if not exists f using btree;
drop operator family f using btree cascade restrict;
DROP OPERATOR CLASS IF EXISTS C USING BTREE CASCADE;
DROP OPERATOR FAMILY IF EXISTS F USING BTREE CASCADE;
drop /* c */ operator /* c */ class /* c */ if /* c */ exists /* c */ c /* c */ using /* c */ btree /* c */ cascade;
drop /* c */ operator /* c */ family /* c */ f /* c */ using /* c */ btree;
