-- CREATE TEXT SEARCH
create text search parser p (start = s, gettoken = g, end = e, lextypes = l);
create text search parser a.p (start = a.s, gettoken = g, end = e, lextypes = l, headline = h);
create text search dictionary d (template = simple);
create text search dictionary a.d (template = a.snowball, language = english, stopwords = english, "Foo" = 'bar');
create text search dictionary d (template = simple, stopwords);
create text search template t (init = i, lexize = l);
create text search template a.t (lexize = a.l);
create text search configuration c (parser = p);
create text search configuration a.c (copy = english);
create text search configuration c (parser = a.p, x = 1);
create text search configuration a.b.c (parser = p);
create text search configuration a.b.c.d (parser = p);
create text search configuration c ();
create text search configuration c;
create text search configuration c (parser);
create text search configuration c (parser = );
create text search configuration (parser = p);
create text search dictionary d (template = default);
create text search dictionary d (template = null);
create text search dictionary d (template = none);
create text search dictionary d (template = -1);
create text search dictionary d (template = 'x');
create text search dictionary d (template = int);
create text search dictionary d (template = setof int);
create text search dictionary d (template = a.b%type);
create text search dictionary d (template = +);
create text search dictionary d (template = operator(a.+));
create text search dictionary d (template = operator(+));
create text search dictionary d (template = ==);
create text search dictionary d (template = a.b.c.d);
create text search dictionary d (template = "Q", language = E'x\n', b = $$y$$);
create text search dictionary d (default);
create text search dictionary d (a = b, c = d,);
create text search dictionary d (a.b = c);
create text search dictionary d (a = b.c);
create text search dictionary d (select = 1);
create text search dictionary d (select);
create text search dictionary d (a = select);
create text search dictionary d (a = from, b = table, c = user, d = all);
create text search dictionary d (a = float, b = int, c = char(3), d = timestamp with time zone);
create text search dictionary d (a = 1.5e3, b = 0x10, c = 1_000);
create text search dictionary d (a = true, b = false);
create text search dictionary d (a = array);
create text search dictionary d (a = int[]);
create text search dictionary d (a = interval year to month);
create text search dictionary d (a = double precision);
create text search dictionary d (a = bit varying(3));
create text search dictionary d (a = numeric(3,2));
create text search dictionary d (a = "double precision");
create text search dictionary d (a = pg_catalog.int4);
create text search dictionary d (a = b collate c);
create text search stuff x (a = b);
create text search d (a = b);
create text parser p (start = s);
create or replace text search dictionary d (a = b);
create text search dictionary if not exists d (a = b);
CREATE TEXT SEARCH DICTIONARY D (TEMPLATE = SIMPLE);
create /* c */ text /* c */ search /* c */ dictionary /* c */ d /* c */ ( /* c */ template /* c */ = /* c */ simple /* c */ ) ;
-- ALTER TEXT SEARCH
alter text search dictionary d (stopwords = english);
alter text search dictionary a.d (stopwords = english, a = 1, b);
alter text search dictionary d ();
alter text search dictionary d;
alter text search dictionary d set (stopwords = english);
alter text search dictionary d (a = b,);
alter text search dictionary a.b.c.d (a = b);
alter text search dictionary d rename to e;
alter text search dictionary d owner to x;
alter text search dictionary d set schema s;
alter text search parser p rename to q;
alter text search configuration c add mapping for a with d;
alter text search configuration c add mapping for a, b with d, e;
alter text search configuration a.c add mapping for a, b, c with a.d, b.e, f;
alter text search configuration c add mapping for a with d with e;
alter text search configuration c add mapping for a;
alter text search configuration c add mapping with d;
alter text search configuration c add mapping for with d;
alter text search configuration c add mapping for a with;
alter text search configuration c add mapping for a,  with d;
alter text search configuration c add mapping for a with d,;
alter text search configuration c add mapping for "A", int with "D";
alter text search configuration c add mapping for asciiword with english_stem, simple;
alter text search configuration c add mapping for a.b with d;
alter text search configuration c add mapping for select with d;
alter text search configuration c add mapping for user with d;
alter text search configuration c add mapping for a with select;
alter text search configuration c add mapping for a with time;
alter text search configuration c add mapping for a with ordinality;
alter text search configuration c add mapping for time with ordinality;
alter text search configuration c add mapping for a with time, ordinality;
alter text search configuration c alter mapping for a with d;
alter text search configuration c alter mapping for a, b with d, e;
alter text search configuration c alter mapping for a with a.b.c;
alter text search configuration c alter mapping for a with a.b.c.d;
alter text search configuration c alter mapping for a;
alter text search configuration c alter mapping for a with;
alter text search configuration c alter mapping with d;
alter text search configuration c alter mapping replace d with e;
alter text search configuration c alter mapping replace a.d with a.e;
alter text search configuration c alter mapping replace d with e, f;
alter text search configuration c alter mapping replace d, e with f;
alter text search configuration c alter mapping replace d with;
alter text search configuration c alter mapping replace d;
alter text search configuration c alter mapping replace with e;
alter text search configuration c alter mapping for a replace d with e;
alter text search configuration c alter mapping for a, b replace a.d with a.e;
alter text search configuration c alter mapping for a replace d;
alter text search configuration c alter mapping for a replace with e;
alter text search configuration c alter mapping for replace d with e;
alter text search configuration c alter mapping for a replace d with e with f;
alter text search configuration c drop mapping for a;
alter text search configuration c drop mapping for a, b;
alter text search configuration a.c drop mapping for a, b, c;
alter text search configuration c drop mapping if exists for a;
alter text search configuration c drop mapping if exists for a, b;
alter text search configuration c drop mapping;
alter text search configuration c drop mapping for;
alter text search configuration c drop mapping if exists;
alter text search configuration c drop mapping if not exists for a;
alter text search configuration c drop mapping for a with d;
alter text search configuration c drop mapping for a,;
alter text search configuration c rename to d;
alter text search configuration c owner to x;
alter text search configuration c set schema s;
alter text search configuration c;
alter text search configuration c add;
alter text search configuration c add mapping;
alter text search configuration c set mapping for a with d;
alter text search configuration a.b.c.d add mapping for a with d;
alter text search configuration c add mapping for a with a.b.c.d;
alter text search configuration c add mapping for a.b.c with d;
ALTER TEXT SEARCH CONFIGURATION C ADD MAPPING FOR A WITH D;
alter /* c */ text /* c */ search /* c */ configuration /* c */ c /* c */ drop /* c */ mapping /* c */ if /* c */ exists /* c */ for /* c */ a ;
alter text search template t (a = b);
alter text search parser p (a = b);
-- CREATE COLLATION / ALTER COLLATION
create collation c (locale = 'en_US');
create collation c (provider = icu, locale = 'x', deterministic = false, rules = '', version = '1');
create collation a.c (lc_collate = 'C', lc_ctype = 'C');
create collation c (locale = en);
create collation c from d;
create collation c from a.d;
create collation a.c from a.d;
create collation c from a.b.d;
create collation c from a.b.c.d;
create collation a.b.c.d from d;
create collation if not exists c (locale = 'x');
create collation if not exists c from d;
create collation if not exists a.c from "D";
create collation c;
create collation c ();
create collation c from;
create collation c from d (locale = 'x');
create collation c (locale = 'x') from d;
create collation c (from = d);
create collation c (locale);
create collation c (locale = );
create collation c (locale = 'x',);
create collation if exists c (locale = 'x');
create collation if not c (locale = 'x');
create or replace collation c (locale = 'x');
create collation c (locale = 1, a = -1, b = +1, c = 1.5, d = -2.5, e = true, f = null, g = default);
create collation c from d, e;
create collation c from "d";
create collation c from d.e.f.g;
CREATE COLLATION C (LOCALE = 'X');
create /* c */ collation /* c */ if /* c */ not /* c */ exists /* c */ c /* c */ from /* c */ d;
alter collation c refresh version;
alter collation a.c refresh version;
alter collation a.b.c refresh version;
alter collation a.b.c.d refresh version;
alter collation c refresh;
alter collation c version;
alter collation refresh version;
alter collation c refresh version x;
alter collation c rename to d;
alter collation c owner to x;
alter collation c set schema s;
alter collation if exists c refresh version;
ALTER COLLATION C REFRESH VERSION;
alter /* c */ collation /* c */ c /* c */ refresh /* c */ version ;
-- CREATE CONVERSION
create conversion c for 'utf8' to 'latin1' from f;
create default conversion c for 'utf8' to 'latin1' from f;
create conversion a.c for 'utf8' to 'latin1' from a.f;
create conversion a.b.c for 'utf8' to 'latin1' from a.b.f;
create conversion c for 'utf8' to 'latin1' from a.b.c.f;
create conversion c for E'utf8\n' to $$latin1$$ from f;
create conversion c for 'utf8' 'x' to 'latin1' from f;
create conversion c for utf8 to 'latin1' from f;
create conversion c for 'utf8' to latin1 from f;
create conversion c for 'utf8' to 'latin1' from "F";
create conversion c for 'utf8' to 'latin1' from;
create conversion c for 'utf8' to 'latin1';
create conversion c for 'utf8' from f;
create conversion c to 'latin1' from f;
create conversion c from f;
create conversion for 'utf8' to 'latin1' from f;
create conversion c for 'utf8' to 'latin1' from f, g;
create or replace conversion c for 'utf8' to 'latin1' from f;
create default default conversion c for 'utf8' to 'latin1' from f;
create conversion if not exists c for 'utf8' to 'latin1' from f;
CREATE DEFAULT CONVERSION C FOR 'UTF8' TO 'LATIN1' FROM F;
create /* c */ default /* c */ conversion /* c */ c /* c */ for /* c */ 'a' /* c */ to /* c */ 'b' /* c */ from /* c */ f ;
