// The runtime embedded in TypeScript parsers generated by pego gen -lang ts.
//
// pego gen copies everything after the "--- Runtime ---" line below and appends the code generated
// from a grammar (the expression functions and the statements that set up the rule table), producing
// a single module without dependencies. It mirrors internal/engine/genrt/runtime.go, the runtime of
// generated Go parsers, line for line where it can: the results must equal the engine's exactly, which
// the generator tests in internal/engine check by running the generated code with Node.js.
//
// The code uses only erasable TypeScript syntax (no enums, namespaces or parameter properties), so
// runtimes that strip types can run it directly, and only the ES2020 library (BigInt).

// --- Runtime ---

/**
 * A value of an action, a predicate or a node field: a node, an int, a string, a bool or null. An int
 * is a number, or a bigint when it is outside the safe integer range (ints are 64-bit, as in the
 * engine, and wrap around on overflow).
 */
export type Value = Node | number | bigint | string | boolean | null;

/** The unit of input positions. */
export type Unit = 0 | 1;
/** CodePoints counts Unicode code points. It is the default. */
export const CodePoints: Unit = 0;
/** Bytes counts UTF-8 bytes. */
export const Bytes: Unit = 1;

/** A field of a node: a struct field or a capture. */
export interface NodeField {
  readonly name: string;
  value: Value;
}

const noNodes: readonly (Node | null)[] = Object.freeze([]);
const noFields: readonly NodeField[] = Object.freeze([]);

/** The JSON form of a node (Node.toJSON). */
export interface NodeJSON {
  type: string;
  rule?: string;
  start: number;
  end: number;
  text?: string;
  children?: readonly (Node | null)[];
  fields?: { [name: string]: unknown };
}

/** A value produced by parsing: a CST node, a terminal, a list, or a struct built by an action. */
export class Node {
  /** The type name: Match, Seq, List, Operator, Error, or a type of the grammar. */
  type: string;
  /** The name of the rule that produced the node, when it has no action. */
  rule: string;
  /** The range in the input, in the position unit (end is exclusive). */
  start: number;
  end: number;
  /** The text of a terminal. */
  text: string;
  /** The children of Seq, List and Operator nodes. Omitted elements are null. */
  children: readonly (Node | null)[];
  /** The struct fields and captures, in the order they were set. */
  fields: readonly NodeField[];
  /** @internal The node was made in the rule body being evaluated, which may change it. */
  fresh: boolean;
  /** @internal The node is a terminal. */
  terminal: boolean;

  constructor(
    type: string,
    rule: string,
    start: number,
    end: number,
    text: string,
    children: readonly (Node | null)[],
    fields: readonly NodeField[],
    fresh: boolean,
    terminal: boolean,
  ) {
    this.type = type;
    this.rule = rule;
    this.start = start;
    this.end = end;
    this.text = text;
    this.children = children;
    this.fields = fields;
    this.fresh = fresh;
    this.terminal = terminal;
  }

  /** Returns the value of the field name (null if there is none). */
  field(name: string): Value {
    for (const f of this.fields) {
      if (f.name === name) {
        return f.value;
      }
    }
    return null;
  }

  /** Reports whether the node is a terminal. */
  isTerminal(): boolean {
    return this.terminal;
  }

  /** Formats the node as an S-expression-like string, as the engine's Node.String does. */
  toString(): string {
    return print(this, writeValue);
  }

  /**
   * Returns the JSON form of the node, which JSON.stringify uses. Ints outside the safe integer range
   * become (inexact) numbers; marshal encodes them exactly.
   */
  toJSON(): NodeJSON {
    // The keys in the order of the engine's JSON (objects keep the order of insertion).
    const o: NodeJSON =
      this.rule !== ""
        ? { type: this.type, rule: this.rule, start: this.start, end: this.end }
        : { type: this.type, start: this.start, end: this.end };
    if (this.text !== "") {
      o.text = this.text;
    }
    if (this.children.length > 0) {
      o.children = this.children;
    }
    if (this.fields.length > 0) {
      // Without a prototype, a field named __proto__ is a field like the others.
      const fs: { [name: string]: unknown } = Object.create(null);
      for (const f of sortedFields(this.fields)) {
        fs[f.name] = typeof f.value === "bigint" ? Number(f.value) : f.value;
      }
      o.fields = fs;
    }
    return o;
  }
}

function sortedFields(fs: readonly NodeField[]): NodeField[] {
  return fs.slice().sort((a, b) => compareStrings(a.name, b.name));
}

function setField(n: Node, name: string, v: Value): void {
  if (n.fields === noFields) {
    n.fields = [{ name, value: v }];
    return;
  }
  const fs = n.fields as NodeField[];
  for (const f of fs) {
    if (f.name === name) {
      f.value = v;
      return;
    }
  }
  fs.push({ name, value: v });
}

/**
 * Encodes a node (or null) as JSON exactly as Go's encoding/json encodes the engine's Node: the same
 * keys in the same order, field names sorted, and the same escapes (including <, > and &). Unlike
 * encoding/json, which fails beyond 10,000 levels, it encodes trees of any depth.
 */
export function marshal(n: Node | null): string {
  return print(n, marshalValue);
}

// Pending is a value that a printer has yet to write.
class Pending {
  v: Value;
  constructor(v: Value) {
    this.v = v;
  }
}

// print writes v with write, which writes a value as text and Pending values (its parts, such as
// the children of a node), and writes those in turn. It keeps the values to write on a stack of
// its own, so that it can write trees of any depth: parses build trees deeper than the JavaScript
// stack allows recursion (left recursion, foldl and Pratt operators nest without nesting calls).
function print(v: Value, write: (v: Value, out: (string | Pending)[]) => void): string {
  const b: string[] = [];
  const stack: (string | Pending)[] = [new Pending(v)];
  const parts: (string | Pending)[] = [];
  while (stack.length > 0) {
    const x = stack.pop()!;
    if (typeof x === "string") {
      b.push(x);
      continue;
    }
    parts.length = 0;
    write(x.v, parts);
    for (let i = parts.length - 1; i >= 0; i--) {
      stack.push(parts[i]!);
    }
  }
  return b.join("");
}

function marshalValue(v: Value, out: (string | Pending)[]): void {
  if (v === null) {
    out.push("null");
  } else if (v instanceof Node) {
    out.push('{"type":' + quoteJSON(v.type));
    if (v.rule !== "") {
      out.push(',"rule":' + quoteJSON(v.rule));
    }
    out.push(',"start":' + v.start + ',"end":' + v.end);
    if (v.text !== "") {
      out.push(',"text":' + quoteJSON(v.text));
    }
    if (v.children.length > 0) {
      out.push(',"children":[');
      v.children.forEach((c, i) => {
        if (i > 0) {
          out.push(",");
        }
        out.push(new Pending(c));
      });
      out.push("]");
    }
    if (v.fields.length > 0) {
      out.push(',"fields":{');
      sortedFields(v.fields).forEach((f, i) => {
        out.push((i > 0 ? "," : "") + quoteJSON(f.name) + ":", new Pending(f.value));
      });
      out.push("}");
    }
    out.push("}");
  } else if (typeof v === "string") {
    out.push(quoteJSON(v));
  } else {
    out.push(String(v));
  }
}

const hex = "0123456789abcdef";

const replacementChar = String.fromCharCode(0xfffd);

// quoteJSON quotes s as Go's encoding/json does with HTML escaping.
function quoteJSON(s: string): string {
  let out = '"';
  let from = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    let esc = "";
    if (c < 0x20 || c === 0x22 || c === 0x5c || c === 0x3c || c === 0x3e || c === 0x26) {
      switch (c) {
        case 0x22:
          esc = '\\"';
          break;
        case 0x5c:
          esc = "\\\\";
          break;
        case 0x08:
          esc = "\\b";
          break;
        case 0x0c:
          esc = "\\f";
          break;
        case 0x0a:
          esc = "\\n";
          break;
        case 0x0d:
          esc = "\\r";
          break;
        case 0x09:
          esc = "\\t";
          break;
        default:
          esc = "\\u00" + hex[c >> 4] + hex[c & 15];
      }
    } else if (c === 0x2028 || c === 0x2029) {
      esc = "\\u202" + hex[c & 15];
    } else if (c >= 0xd800 && c <= 0xdfff) {
      // A lone surrogate is not valid UTF-8: an invalid byte (see decodeBytes), which Go writes as
      // U+FFFD.
      if (c < 0xdc00 && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
        i++;
        continue;
      }
      esc = replacementChar;
    } else {
      continue;
    }
    out += s.slice(from, i) + esc;
    from = i + 1;
  }
  return out + s.slice(from) + '"';
}

// writeValue writes v as the engine's Node.String does (see print).
function writeValue(v: Value, out: (string | Pending)[]): void {
  if (v === null) {
    out.push("nil");
  } else if (v instanceof Node) {
    writeNode(v, out);
  } else if (typeof v === "string") {
    out.push("`" + v + "`");
  } else {
    out.push(String(v));
  }
}

function writeNode(n: Node, out: (string | Pending)[]): void {
  if (n.type === "List") {
    out.push("[");
    n.children.forEach((c, i) => {
      if (i > 0) {
        out.push(" ");
      }
      out.push(new Pending(c));
    });
    writeFields(n, n.children.length > 0, out);
    out.push("]");
  } else if (n.terminal) {
    if (n.type !== "Match") {
      out.push(n.type);
    }
    out.push(quoteGo(n.text));
    if (n.fields.length > 0) {
      out.push("{");
      writeFields(n, false, out);
      out.push("}");
    }
  } else {
    out.push("(" + n.type);
    for (const c of n.children) {
      out.push(" ", new Pending(c));
    }
    writeFields(n, true, out);
    out.push(")");
  }
  if (n.rule !== "") {
    out.push("@" + n.rule);
  }
}

function writeFields(n: Node, sep: boolean, out: (string | Pending)[]): void {
  for (const f of sortedFields(n.fields)) {
    out.push((sep ? " " : "") + f.name + "=", new Pending(f.value));
    sep = true;
  }
}

// printRuns is the table of the code points that Go's strconv.IsPrint accepts, which the generated
// code sets: the lengths of the alternating runs of code points that it rejects and accepts, from
// U+0000, in base 36 separated by commas. It comes from the Go that generated the parser, so that
// quoteGo does not depend on the version of Unicode of the JavaScript runtime.
let printRuns = "";

// printStarts holds the starts of the runs of printRuns, decoded on first use.
let printStarts: number[] | null = null;

// isPrint reports whether Go's strconv.IsPrint accepts r.
function isPrint(r: number): boolean {
  let starts = printStarts;
  if (starts === null) {
    starts = [];
    let x = 0;
    for (const d of printRuns === "" ? [] : printRuns.split(",")) {
      x += parseInt(d, 36);
      starts.push(x);
    }
    printStarts = starts;
  }
  // The number of runs that start at or before r, which is odd in a run of accepted code points.
  let lo = 0;
  let hi = starts.length;
  while (lo < hi) {
    const mid = (lo + hi) >>> 1;
    if (starts[mid]! <= r) {
      lo = mid + 1;
    } else {
      hi = mid;
    }
  }
  return lo % 2 === 1;
}

// quoteGo quotes s as Go's strconv.Quote does.
function quoteGo(s: string): string {
  let out = '"';
  for (const ch of s) {
    const r = ch.codePointAt(0) as number;
    if (r === 0x22 || r === 0x5c) {
      out += "\\" + ch;
    } else if ((r >= 0x20 && r < 0x7f) || (r >= 0x80 && isPrint(r))) {
      out += ch;
    } else if (r === 0x07) {
      out += "\\a";
    } else if (r === 0x08) {
      out += "\\b";
    } else if (r === 0x0c) {
      out += "\\f";
    } else if (r === 0x0a) {
      out += "\\n";
    } else if (r === 0x0d) {
      out += "\\r";
    } else if (r === 0x09) {
      out += "\\t";
    } else if (r === 0x0b) {
      out += "\\v";
    } else if (r < 0x20 || r === 0x7f) {
      out += "\\x" + hex[r >> 4] + hex[r & 15];
    } else if (r >= 0xdc80 && r <= 0xdcff) {
      out += "\\x" + hex[(r >> 4) & 15] + hex[r & 15]; // an invalid byte (see decodeBytes)
    } else if (r >= 0xd800 && r <= 0xdfff) {
      out += replacementChar; // other lone surrogates do not occur
    } else if (r < 0x10000) {
      out += "\\u" + r.toString(16).padStart(4, "0");
    } else {
      out += "\\U" + r.toString(16).padStart(8, "0");
    }
  }
  return out + '"';
}

/** SyntaxError reports that the input does not match the grammar. Its message is "line:col: reason". */
export class SyntaxError extends Error {
  /** The position of the error, in the position unit. */
  pos: number;
  /** The line and column (both from 1; the column in the position unit). */
  line: number;
  col: number;
  /** The descriptions of what was expected, sorted. */
  expected: string[];
  /** The messages of #error attributes. */
  messages: string[];

  constructor(pos: number, line: number, col: number, expected: string[], messages: string[]) {
    super(`${line}:${col}: ${reason(expected, messages)}`);
    this.name = "SyntaxError";
    this.pos = pos;
    this.line = line;
    this.col = col;
    this.expected = expected;
    this.messages = messages;
  }

  /** Describes the error without its position (Message in Go). */
  reason(): string {
    return reason(this.expected, this.messages);
  }
}

function reason(expected: string[], messages: string[]): string {
  if (messages.length > 0) {
    return messages.join("; ");
  }
  if (expected.length > 0) {
    return "syntax error: expected " + expected.join(", ");
  }
  return "syntax error";
}

/** SyntaxErrors lists the syntax errors recovered from with #recover. */
export class SyntaxErrors extends Error {
  errors: SyntaxError[];

  constructor(errors: SyntaxError[]) {
    super(errors.map((e) => e.message).join("\n"));
    this.name = "SyntaxErrors";
    this.errors = errors;
  }
}

/**
 * The result of a parse. A failed parse has a null node and an error: a SyntaxError, or an Error for
 * a runtime error in an action or too deep nesting. A parse that recovered from errors with #recover
 * has both the node and SyntaxErrors.
 */
export interface ParseResult {
  node: Node | null;
  error: Error | null;
}

// --- Rules ---

// R is the result of a matcher: a value (null for none) on success, undefined on failure.
type R = Node | null | undefined;

type Matcher = (p: Parser) => R;

type Action = (c: Actx) => Value;

type Frame = (Node | null)[];

const emptyFrame: Frame = [];

interface Rule {
  id: number;
  name: string;
  scope: string[]; // capture names of the rule body, in slot order
  body: (p: Parser, min: number) => R;
  action: Action | null;
  bodyIsSeq: boolean;
  terminalType: string;
  // memo means the rule's results are memoized. It is false for transient rules, whose entries
  // could never be reused.
  memo: boolean;
  // leader is the leader of a left-recursive cycle; its results are always memoized.
  leader: boolean;
  // seen is the rule's index among the memoized rules whose memoization is deferred to the second
  // call at a position (firstCall), or -1.
  seen: number;
  pratt: Pratt | null;
  novalue: boolean; // value-free twin, called where the value is discarded
  // vars are the variables the rule or its callees read, sorted. Memo entries are keyed by their
  // values at the call, since definitions inside the rule are undone when it returns.
  vars: string[];
}

function failBody(): R {
  return undefined;
}

function mkRule(
  id: number,
  name: string,
  scope: string[],
  bodyIsSeq: boolean,
  terminalType: string,
  memo: boolean,
  leader: boolean,
  seen: number,
  novalue: boolean,
  vars: string[],
): Rule {
  return {
    id,
    name,
    scope,
    body: failBody,
    action: null,
    bodyIsSeq,
    terminalType,
    memo,
    leader,
    seen,
    pratt: null,
    novalue,
    vars,
  };
}

// descs maps expectation IDs to their descriptions; the generated code sets the whole table.
let descs: string[] = [];

// structFields holds the field names of each struct type.
const structFields = new Map<string, Set<string>>();

function ruleIn(table: Rule[], name: string): Rule | null {
  for (const r of table) {
    if (r.name === name) {
      return r;
    }
  }
  return null;
}

// maxDepth is the maximum nesting of rule calls, the same default as the engine.
const maxDepth = 100_000;

// Selected at generation time; large rule tables allocate visited regions only.
const sparseSeen = true;

// run parses the whole input with rule r of a rule table with seen rules that have rule.seen set.
function run(r: Rule, seen: number, input: string | Uint8Array, unit: Unit | undefined): ParseResult {
  let p: Parser | null = null;
  try {
    // Made inside the try, so that decoding the input fails as parsing does.
    p = new Parser(input, unit === Bytes ? Bytes : CodePoints, seen);
    return result(p, p.call(r, 0));
  } catch (x) {
    if (x instanceof Fatal) {
      return { node: null, error: x.err };
    }
    if (isStackOverflow(x)) {
      // The JavaScript stack is smaller than the nesting limit allows.
      return {
        node: null,
        error: new Error(`nesting too deep: the JavaScript stack overflowed at ${p === null ? 0 : p.depth} rule calls`),
      };
    }
    throw x;
  }
}

// isStackOverflow reports whether x is what a JavaScript engine throws when the stack is exhausted:
// a RangeError "Maximum call stack size exceeded" in V8 and JavaScriptCore, an InternalError "too much
// recursion" in SpiderMonkey.
function isStackOverflow(x: unknown): boolean {
  return (
    x instanceof Error && (x instanceof RangeError || x.name === "InternalError") && /stack|recursion/i.test(x.message)
  );
}

// result returns the result of a parse whose call of the start rule returned v.
function result(p: Parser, v: R): ParseResult {
  if (v !== undefined && p.pos === p.n) {
    if (p.recovered.length > 0) {
      return { node: v, error: new SyntaxErrors(p.recovered) };
    }
    return { node: v, error: null };
  }
  if (v !== undefined) {
    p.expect(p.pos, idEndInput);
  }
  return { node: null, error: p.makeError(p.farthest, p.exp.slice(p.expBase, p.expTop)) };
}

// --- Input ---

// decodedSize is the size of the sequence decodeRune decoded last.
let decodedSize = 0;

// decodeRune decodes the UTF-8 sequence at b[i] (i < n) as Go's utf8.DecodeRune does: an invalid
// or truncated sequence decodes as U+FFFD of one byte.
function decodeRune(b: Uint8Array, i: number, n: number): number {
  const c0 = b[i]!;
  decodedSize = 1;
  if (c0 < 0x80) {
    return c0;
  }
  if (c0 < 0xc2 || c0 > 0xf4) {
    return 0xfffd;
  }
  const c1 = i + 1 < n ? b[i + 1]! : 0;
  if (c0 < 0xe0) {
    if ((c1 & 0xc0) !== 0x80) {
      return 0xfffd;
    }
    decodedSize = 2;
    return ((c0 & 0x1f) << 6) | (c1 & 0x3f);
  }
  const lo = c0 === 0xe0 ? 0xa0 : c0 === 0xf0 ? 0x90 : 0x80;
  const hi = c0 === 0xed ? 0x9f : c0 === 0xf4 ? 0x8f : 0xbf;
  if (c1 < lo || c1 > hi) {
    return 0xfffd;
  }
  const c2 = i + 2 < n ? b[i + 2]! : 0;
  if ((c2 & 0xc0) !== 0x80) {
    return 0xfffd;
  }
  if (c0 < 0xf0) {
    decodedSize = 3;
    return ((c0 & 0x0f) << 12) | ((c1 & 0x3f) << 6) | (c2 & 0x3f);
  }
  const c3 = i + 3 < n ? b[i + 3]! : 0;
  if ((c3 & 0xc0) !== 0x80) {
    return 0xfffd;
  }
  decodedSize = 4;
  return ((c0 & 0x07) << 18) | ((c1 & 0x3f) << 12) | ((c2 & 0x3f) << 6) | (c3 & 0x3f);
}

// encodeUTF8 encodes s in UTF-8, with lone surrogates as U+FFFD.
function encodeUTF8(s: string): Uint8Array {
  const out = new Uint8Array(utf8Len(s));
  let j = 0;
  for (let i = 0; i < s.length; i++) {
    let c = s.charCodeAt(i);
    if (c < 0x80) {
      out[j++] = c;
      continue;
    }
    if (c >= 0xd800 && c <= 0xdfff) {
      if (c < 0xdc00 && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
        c = 0x10000 + ((c - 0xd800) << 10) + (s.charCodeAt(i + 1) - 0xdc00);
        i++;
      } else {
        c = 0xfffd;
      }
    }
    if (c < 0x800) {
      out[j++] = 0xc0 | (c >> 6);
      out[j++] = 0x80 | (c & 0x3f);
    } else if (c < 0x10000) {
      out[j++] = 0xe0 | (c >> 12);
      out[j++] = 0x80 | ((c >> 6) & 0x3f);
      out[j++] = 0x80 | (c & 0x3f);
    } else {
      out[j++] = 0xf0 | (c >> 18);
      out[j++] = 0x80 | ((c >> 12) & 0x3f);
      out[j++] = 0x80 | ((c >> 6) & 0x3f);
      out[j++] = 0x80 | (c & 0x3f);
    }
  }
  return out;
}

// utf8Len returns the length of s in UTF-8: the number of bytes utf8Bytes returns.
function utf8Len(s: string): number {
  let n = s.length;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c < 0x80) {
      continue;
    }
    if (c < 0x800) {
      n++;
    } else if (c >= 0xd800 && c < 0xdc00 && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
      n += 2; // a pair: 2 units, 4 bytes
      i++;
    } else if (c < 0xdc80 || c > 0xdcff) {
      n += 2; // an invalid byte (see decodeBytes) is one byte
    }
  }
  return n;
}

// utf8Bytes returns the bytes of s: its UTF-8 encoding, with the surrogates that stand for invalid
// bytes (see decodeBytes) as those bytes.
function utf8Bytes(s: string): number[] {
  const out: number[] = [];
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    if (c >= 0xdc80 && c <= 0xdcff) {
      out.push(c & 0xff);
      continue;
    }
    for (const x of encodeUTF8(ch)) {
      out.push(x);
    }
  }
  return out;
}

// isByte reports whether s[i] is a surrogate that stands for an invalid byte (see decodeBytes).
function isByte(s: string, i: number): boolean {
  const c = s.charCodeAt(i);
  return c >= 0xdc80 && c <= 0xdcff && !(i > 0 && (s.charCodeAt(i - 1) & 0xfc00) === 0xd800);
}

// runeCount returns the number of code points in s.
function runeCount(s: string): number {
  let n = s.length;
  for (let i = 0; i + 1 < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 0xd800 && c < 0xdc00 && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
      n--;
      i++;
    }
  }
  return n;
}

// wellFormed replaces the lone surrogates of s with U+FFFD.
function wellFormed(s: string): string {
  const parts: string[] = [];
  let from = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdfff) {
      if (c < 0xdc00 && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
        i++;
        continue;
      }
      parts.push(s.slice(from, i), replacementChar);
      from = i + 1;
    }
  }
  if (from === 0) {
    return s;
  }
  parts.push(s.slice(from));
  return parts.join("");
}

// compareStrings compares strings by the byte order of their UTF-8 encodings (Go's string order),
// which is the order of their code points.
function compareStrings(a: string, b: string): number {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) {
    let x = a.charCodeAt(i);
    let y = b.charCodeAt(i);
    if (x !== y) {
      if (isByte(a, i) || isByte(b, i)) {
        // An invalid byte compares as a byte with the bytes of the other string.
        const p = utf8Bytes(a.slice(i));
        const q = utf8Bytes(b.slice(i));
        for (let k = 0; k < p.length && k < q.length; k++) {
          if (p[k] !== q[k]) {
            return p[k]! < q[k]! ? -1 : 1;
          }
        }
        return p.length < q.length ? -1 : p.length > q.length ? 1 : 0;
      }
      if (x >= 0xd800 && y >= 0xd800) {
        // Surrogates (code points above U+FFFF) sort after U+E000-U+FFFF.
        x = x >= 0xe000 ? x - 0x800 : x + 0x2000;
        y = y >= 0xe000 ? y - 0x800 : y + 0x2000;
      }
      return x < y ? -1 : 1;
    }
  }
  return a.length < b.length ? -1 : a.length > b.length ? 1 : 0;
}

// --- Parser state ---

// An expectation is an index into descs; with msgBit set, it is an #error message.
const msgBit = 1 << 30;

// Expectations at the start of every descs table.
const idAny = 0;
const idBeginInput = 1;
const idEndInput = 2;
const idBeginLine = 3;
const idEndLine = 4;

interface Env {
  name: string;
  val: Value;
  next: Env | null;
}

interface MemoEntry {
  node: R;
  errs: SyntaxError[]; // errors recovered in this call, recorded again on reuse
  expected: number[]; // expectations at far, recorded again on reuse
  next: MemoEntry | null; // next entry at the same position
  env: Value[] | null; // values of the rule's variables at the call (memo key)
  end: number;
  far: number;
  rule: number;
  min: number;
  ok: boolean;
  // silent means the result was computed inside a lookahead without recording expectations;
  // outside lookaheads it is computed again.
  silent: boolean;
  // growing marks a provisional result of a growing left-recursive call.
  growing: boolean;
}

function newEntry(node: R, ok: boolean, end: number, silent: boolean, growing: boolean, errs: SyntaxError[]): MemoEntry {
  return { node, errs, expected: noExp, next: null, env: null, end, far: 0, rule: 0, min: 0, ok, silent, growing };
}

const noExp: number[] = [];
const noErrs: SyntaxError[] = [];

// sameValues reports whether two lists of variable values are equal.
function sameValues(a: Value[] | null, b: Value[] | null): boolean {
  if (a === null || b === null) {
    return (a === null ? 0 : a.length) === (b === null ? 0 : b.length);
  }
  if (a.length !== b.length) {
    return false;
  }
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) {
      return false;
    }
  }
  return true;
}

// Lit is a literal: its code points and its UTF-8 bytes (Go's []rune and []byte of the literal).
interface Lit {
  text: string;
  cps: number[];
  bytes: number[];
}

class Parser {
  unit: Unit;
  cps: Int32Array; // code points (CodePoints)
  bs: Uint8Array; // the input (Bytes)
  n: number; // input length in units
  // src is the input as a string (with U+FFFD for invalid UTF-8), and offs maps positions to
  // offsets in src (null when they are the same).
  src: string;
  offs: Int32Array | null;
  pos = 0;
  psize = 0; // the size of the character peek returned

  depth = 0; // nesting of rule calls
  created: Node[] = []; // struct nodes made by the action being evaluated (from Actx.cbase)
  env: Env | null = null;
  bound: Set<string> | null = null; // names assigned anywhere in this parse (a lookup hint)
  frame: Frame = emptyFrame;
  trail: { f: Frame; slot: number; old: Node | null }[] = [];
  cut = false;

  // The memo: entries per position, chained.
  slots: (MemoEntry | null | undefined)[] = [];
  // seen is a bit set of the (position, rule) pairs called once (firstCall), with stride bits per
  // position.
  seen: Int32Array = new Int32Array(0);
  stride: number;
  sparse: boolean;
  seenPages: ((number | undefined)[] | undefined)[] | null = null;
  seenPageChunks: Int32Array[] | null = null;
  seenPageCount = 0;
  // calls and repeats count, per rule number, the calls and the repeated calls at a position; once
  // repeats are frequent, the rule is memoized on the first call (eager).
  calls: Int32Array;
  repeats: Int32Array;
  eager: Uint8Array;

  // silent is positive inside lookaheads, where expectations are not recorded.
  silent = 0;
  farthest = 0;
  // exp[expBase:expTop] are the current expectations, all expected at farthest. The records of
  // enclosing isolated calls are below expBase.
  exp: number[] = [];
  expBase = 0;
  expTop = 0;
  lastKept: number[] = noExp;

  recovered: SyntaxError[] = [];

  kidStack: (Node | null)[] = []; // gathers repetition children and list elements
  lines: number[] | null = null; // positions where lines start (makeError)
  ac: Actx;
  saved: (Node | null)[] = []; // captures saved across a reset in longest

  constructor(input: string | Uint8Array, unit: Unit, stride: number) {
    this.unit = unit;
    this.stride = stride;
    this.calls = new Int32Array(stride);
    this.repeats = new Int32Array(stride);
    this.eager = new Uint8Array(stride);
    this.ac = new Actx(this);
    this.cps = new Int32Array(0);
    this.bs = new Uint8Array(0);
    this.offs = null;
    if (unit === Bytes) {
      this.bs = typeof input === "string" ? encodeUTF8(input) : input;
      this.n = this.bs.length;
      this.src = this.decodeBytes();
    } else if (typeof input === "string") {
      this.src = this.decodeString(input);
      this.n = this.cps.length;
    } else {
      this.src = this.decodeCodePoints(input);
      this.n = this.cps.length;
    }
    this.sparse = sparseSeen && stride > 64 && this.n > 1024;
  }

  // decodeString sets cps (and offs) from s, with lone surrogates as U+FFFD, and returns s with the
  // same replacement.
  decodeString(s: string): string {
    const n = runeCount(s);
    const cps = new Int32Array(n);
    let offs: Int32Array | null = null;
    let lone = false;
    let j = 0;
    for (let i = 0; i < s.length; i++) {
      let c = s.charCodeAt(i);
      if (c >= 0xd800 && c <= 0xdfff) {
        if (c < 0xdc00 && i + 1 < s.length && (s.charCodeAt(i + 1) & 0xfc00) === 0xdc00) {
          if (offs === null) {
            offs = new Int32Array(n + 1);
            for (let k = 0; k < j; k++) {
              offs[k] = k;
            }
          }
          offs[j] = i;
          cps[j++] = 0x10000 + ((c - 0xd800) << 10) + (s.charCodeAt(i + 1) - 0xdc00);
          i++;
          continue;
        }
        c = 0xfffd;
        lone = true;
      }
      if (offs !== null) {
        offs[j] = i;
      }
      cps[j++] = c;
    }
    if (offs !== null) {
      offs[n] = s.length;
    }
    this.cps = cps;
    this.offs = offs;
    return lone ? wellFormed(s) : s;
  }

  // decodeCodePoints sets cps (and offs) by decoding b as Go does, and returns the text.
  decodeCodePoints(b: Uint8Array): string {
    const cps = new Int32Array(b.length);
    let j = 0;
    let astral = false;
    for (let i = 0; i < b.length; i += decodedSize) {
      const c = decodeRune(b, i, b.length);
      astral = astral || c > 0xffff;
      cps[j++] = c;
    }
    this.cps = cps.subarray(0, j);
    if (astral) {
      const offs = new Int32Array(j + 1);
      let o = 0;
      for (let k = 0; k < j; k++) {
        offs[k] = o;
        o += cps[k]! > 0xffff ? 2 : 1;
      }
      offs[j] = o;
      this.offs = offs;
    }
    return codePointsString(this.cps);
  }

  // decodeBytes sets offs from bs and returns the text, decoding bs as Go does. offs maps the
  // positions where a character starts (all positions a parse reaches) to offsets in the text.
  //
  // Text in byte mode holds bytes, as in Go, where text of invalid UTF-8 keeps the bytes: an invalid
  // byte b is the lone surrogate U+DC00+b in the text (U+DC80-U+DCFF, as Python's surrogateescape),
  // so that len, comparisons and toString see the bytes. JSON (marshal) writes it as U+FFFD, as Go
  // does.
  decodeBytes(): string {
    const b = this.bs;
    const n = b.length;
    let ascii = true;
    for (let i = 0; i < n; i++) {
      if (b[i]! >= 0x80) {
        ascii = false;
        break;
      }
    }
    const cps = new Int32Array(n);
    const offs = ascii ? null : new Int32Array(n + 1);
    let j = 0;
    let o = 0;
    for (let i = 0; i < n; i += decodedSize) {
      let c = decodeRune(b, i, n);
      if (decodedSize === 1 && c === 0xfffd) {
        c = 0xdc00 + b[i]!; // an invalid byte
      }
      if (offs !== null) {
        offs[i] = o;
      }
      o += c > 0xffff ? 2 : 1;
      cps[j++] = c;
    }
    if (offs !== null) {
      offs[n] = o;
    }
    this.offs = offs;
    return codePointsString(cps.subarray(0, j));
  }

  // firstCall records a call of rule r at the current position and reports whether its
  // memoization is deferred: it is the first call there, and repeated calls of the rule have been
  // rare so far. Results are reused only when a rule is called again at a position, which is rare,
  // so memoizing every first call cost an entry each for nothing; deferring memoization to the
  // second call evaluates a rule at most twice per position, which keeps parse time linear.
  firstCall(r: Rule): boolean {
    if (r.seen < 0) {
      return false;
    }
    const s = r.seen;
    if (this.eager[s] !== 0) {
      return false;
    }
    this.calls[s]!++;
    const first = this.sparse
      ? this.markSparseSeen(this.pos, s)
      : this.markSeen(this.pos, s);
    if (first) {
      return true;
    }
    // Deferring costs an extra evaluation for each position where the rule is called again, and
    // saves a memo entry for each position where it is not.
    this.repeats[s]!++;
    if (this.repeats[s]! * 16 > this.calls[s]!) {
      this.eager[s] = 1;
    }
    return false;
  }

  memoGet(rule: number, pos: number, min: number, env: Value[] | null): MemoEntry | null {
    for (let e = this.slots[pos]; e; e = e.next) {
      if (e.rule === rule && e.min === min && sameValues(e.env, env)) {
        return e;
      }
    }
    return null;
  }

  // memoPut stores e under the key, replacing an entry with the same key.
  memoPut(rule: number, pos: number, min: number, env: Value[] | null, e: MemoEntry): void {
    e.rule = rule;
    e.min = min;
    e.env = env;
    let prev: MemoEntry | null = null;
    for (let x = this.slots[pos]; x; prev = x, x = x.next) {
      if (x.rule === rule && x.min === min && sameValues(x.env, env)) {
        e.next = x.next;
        if (prev === null) {
          this.slots[pos] = e;
        } else {
          prev.next = e;
        }
        return;
      }
    }
    if (this.slots.length === 0) {
      // One slot per position, allocated at once: writes far beyond the end of an array would
      // make it a slow dictionary.
      this.slots = new Array(this.n + 1).fill(null);
    }
    e.next = this.slots[pos] || null;
    this.slots[pos] = e;
  }

  // envValues returns the current values of the variables names (null for an undefined variable).
  envValues(names: string[]): Value[] | null {
    if (names.length === 0) {
      return null;
    }
    const vals: Value[] = new Array(names.length);
    for (let i = 0; i < names.length; i++) {
      vals[i] = null;
      for (let e = this.env; e !== null; e = e.next) {
        if (e.name === names[i]) {
          vals[i] = e.val;
          break;
        }
      }
    }
    return vals;
  }

  newFrame(n: number): Frame {
    if (n === 0) {
      return emptyFrame; // never written, so shared
    }
    const f: Frame = new Array(n);
    for (let i = 0; i < n; i++) {
      f[i] = null;
    }
    return f;
  }

  // kids returns kidStack[base:] as a child list and pops it.
  kids(base: number): (Node | null)[] {
    const ks = this.kidStack.slice(base);
    this.kidStack.length = base;
    return ks;
  }

  // dropKids pops kidStack[base:].
  dropKids(base: number): void {
    this.kidStack.length = base;
  }

  // reset returns to a mark: the position, variables, recovered errors and captures (undoing the
  // trail) at the time it was taken.
  reset(pos: number, env: Env | null, trail: number, recovered: number): void {
    this.pos = pos;
    this.env = env;
    this.recovered.length = recovered;
    for (let i = this.trail.length - 1; i >= trail; i--) {
      const u = this.trail[i]!;
      u.f[u.slot] = u.old;
    }
    this.trail.length = trail;
  }

  setCapture(slot: number, v: Node | null): void {
    this.trail.push({ f: this.frame, slot, old: this.frame[slot]! });
    this.frame[slot] = v;
  }

  // peek returns the character at the current position (-1 at the end) and sets psize to its size
  // in units.
  peek(): number {
    if (this.pos >= this.n) {
      return -1;
    }
    if (this.unit === Bytes) {
      const c = this.bs[this.pos]!;
      if (c < 0x80) {
        this.psize = 1;
        return c;
      }
      const r = decodeRune(this.bs, this.pos, this.n);
      this.psize = decodedSize;
      return r;
    }
    this.psize = 1;
    return this.cps[this.pos]!;
  }

  unitLen(s: string): number {
    return this.unit === Bytes ? utf8Len(s) : runeCount(s);
  }

  // expect records that id was expected at pos.
  expect(pos: number, id: number): void {
    if (this.silent > 0 || pos < this.farthest) {
      return;
    }
    if (pos > this.farthest) {
      this.farthest = pos;
      this.expTop = this.expBase;
    }
    for (let i = this.expBase; i < this.expTop; i++) {
      if (this.exp[i] === id) {
        return;
      }
    }
    this.exp[this.expTop++] = id;
  }

  // keep copies exp[from:to] for a memo entry or a recovery.
  keep(from: number, to: number): number[] {
    if (from === to) {
      return noExp;
    }
    const last = this.lastKept;
    if (last.length === to - from) {
      let same = true;
      for (let i = 0; i < last.length; i++) {
        if (last[i] !== this.exp[from + i]) {
          same = false;
          break;
        }
      }
      if (same) {
        return last; // the same set often repeats
      }
    }
    this.lastKept = this.exp.slice(from, to);
    return this.lastKept;
  }

  // mergeExpected records the expectations exp[from:to] at far. They may lie above the current
  // record (writes only happen below the read position).
  mergeExpected(far: number, from: number, to: number): void {
    for (let i = from; i < to; i++) {
      this.expect(far, this.exp[i]!);
    }
  }

  mergeKept(far: number, ids: number[]): void {
    for (const x of ids) {
      this.expect(far, x);
    }
  }

  text(start: number, end: number): string {
    if (this.offs === null) {
      return this.src.slice(start, end);
    }
    return this.src.slice(this.offs[start], this.offs[end]);
  }

  makeError(pos: number, expected: number[]): SyntaxError {
    const exp: string[] = [];
    const msgs: string[] = [];
    for (const x of expected) {
      if ((x & msgBit) !== 0) {
        msgs.push(descs[x & ~msgBit]!);
      } else {
        exp.push(descs[x]!);
      }
    }
    exp.sort(compareStrings);
    // Look the line up in a table of line starts, built on the first error, instead of scanning
    // from the start of the input for each error.
    if (this.lines === null) {
      const lines = [0];
      const units = this.unit === Bytes ? this.bs : this.cps;
      for (let i = 0; i < this.n; i++) {
        if (units[i] === 0x0a) {
          lines.push(i + 1);
        }
      }
      this.lines = lines;
    }
    pos = Math.min(pos, this.n);
    // The number of line starts at or before pos.
    let lo = 0;
    let hi = this.lines.length;
    while (lo < hi) {
      const mid = (lo + hi) >>> 1;
      if (this.lines[mid]! < pos + 1) {
        lo = mid + 1;
      } else {
        hi = mid;
      }
    }
    return new SyntaxError(pos, lo, pos - this.lines[lo - 1]! + 1, exp, msgs);
  }

  markSeen(pos: number, s: number): boolean {
    const i = pos * this.stride + s;
    const w = Math.floor(i / 32);
    const bit = 1 << i % 32;
    if (w >= this.seen.length) {
      const grown = new Int32Array(Math.max(w + 1, 2 * this.seen.length, 64));
      grown.set(this.seen);
      this.seen = grown;
    }
    if ((this.seen[w]! & bit) === 0) {
      this.seen[w]! |= bit;
      return true;
    }
    return false;
  }

  // Page directories hold integer arena offsets, avoiding one typed-array
  // object per page. Chunks contain 64 pages of 1,024 position bits each.
  markSparseSeen(pos: number, s: number): boolean {
    if (this.seenPages === null) {
      this.seenPages = [];
      this.seenPageChunks = [];
    }
    let pages = this.seenPages[s];
    if (pages === undefined) {
      pages = [];
      this.seenPages[s] = pages;
    }
    const at = Math.floor(pos / 1024);
    let page = pages[at];
    if (page === undefined) {
      page = this.seenPageCount++;
      if (page % 64 === 0) {
        this.seenPageChunks!.push(new Int32Array(64 * 32));
      }
      pages[at] = page;
    }
    const chunk = this.seenPageChunks![Math.floor(page / 64)]!;
    const word = (page % 64) * 32 + Math.floor((pos % 1024) / 32);
    const bit = 1 << (pos % 32);
    if ((chunk[word]! & bit) !== 0) {
      return false;
    }
    chunk[word]! |= bit;
    return true;
  }

  // --- Rule calls ---

  // call calls rule r at level min.
  call(r: Rule, min: number): R {
    const start = this.pos;
    if ((!r.memo && !r.leader) || this.firstCall(r)) {
      // Unmemoized call: no memo bookkeeping, and expectations need no isolation.
      if (r.scope.length === 0) {
        return this.invokePlain(r, min);
      }
      const rec = this.recovered.length;
      const v = this.invoke(r, min);
      if (v === undefined) {
        this.pos = start;
        this.recovered.length = rec;
      }
      return v;
    }
    const env = this.envValues(r.vars);
    // See the engine's callBegin: entries with recovered errors are reused only in the same kind of
    // context (inside or outside a lookahead) they were computed in.
    const e = this.memoGet(r.id, start, min, env);
    if (
      e !== null &&
      (e.growing || ((!e.silent || this.silent > 0) && (e.errs.length === 0 || e.silent === this.silent > 0)))
    ) {
      if (!e.growing) {
        this.mergeKept(e.far, e.expected);
      }
      if (!e.ok) {
        return undefined;
      }
      this.pos = e.end;
      for (const x of e.errs) {
        this.recovered.push(x);
      }
      return e.node;
    }
    const rec = this.recovered.length;
    // The memoized result includes the expectations recorded in this call.
    const mFar = this.farthest;
    const mBase = this.expBase;
    this.expBase = this.expTop;
    this.farthest = start;
    let v: R;
    let entry: MemoEntry;
    if (r.leader) {
      v = this.grow(r, min, env);
      entry = this.memoGet(r.id, start, min, env) as MemoEntry;
    } else {
      v = this.invoke(r, min);
      if (v === undefined) {
        this.recovered.length = rec;
      }
      entry = newEntry(
        v,
        v !== undefined,
        this.pos,
        this.silent > 0,
        false,
        this.recovered.length > rec ? this.recovered.slice(rec) : noErrs,
      );
      this.memoPut(r.id, start, min, env, entry);
    }
    // Unisolate: the inner record is exp[from:to].
    const far = this.farthest;
    const from = this.expBase;
    const to = this.expTop;
    this.expTop = this.expBase;
    this.expBase = mBase;
    this.farthest = mFar;
    entry.far = far;
    entry.expected = this.keep(from, to);
    this.mergeExpected(far, from, to);
    if (v === undefined) {
      this.pos = start;
    }
    return v;
  }

  // grow grows the seed of a left-recursive leader: it memoizes a failure, then evaluates the
  // body again while the match gets longer, and keeps the last longer result.
  grow(r: Rule, min: number, env: Value[] | null): R {
    const start = this.pos;
    const rec = this.recovered.length;
    let best = newEntry(undefined, false, start, false, true, noErrs);
    this.memoPut(r.id, start, min, env, best);
    for (;;) {
      const v = this.invoke(r, min);
      if (v === undefined || (best.ok && this.pos <= best.end)) {
        break;
      }
      best = newEntry(v, true, this.pos, false, true, this.recovered.length > rec ? this.recovered.slice(rec) : noErrs);
      this.memoPut(r.id, start, min, env, best);
      this.pos = start;
      this.recovered.length = rec;
    }
    best.growing = false;
    best.silent = this.silent > 0;
    this.pos = best.end;
    this.recovered.length = rec;
    for (const x of best.errs) {
      this.recovered.push(x);
    }
    return best.ok ? best.node : undefined;
  }

  // invoke evaluates the body of r and makes the rule's value.
  invoke(r: Rule, min: number): R {
    const f = this.newFrame(r.scope.length);
    const prevFrame = this.frame;
    const prevEnv = this.env;
    const prevCut = this.cut;
    const trail = this.trail.length;
    this.frame = f;
    this.cut = false;
    if (++this.depth > maxDepth) {
      this.tooDeep();
    }
    const start = this.pos;
    let v = r.body(this, min);
    this.depth--;
    this.frame = prevFrame;
    this.cut = prevCut;
    this.trail.length = trail;
    if (v !== undefined) {
      v = this.finish(r, f, v, start);
    }
    this.env = prevEnv;
    return v;
  }

  // invokePlain is an unmemoized call of a rule without captures: invoke without the capture
  // frame (the body never writes one, so the caller's stays current), with the failure handling of
  // call.
  invokePlain(r: Rule, min: number): R {
    const start = this.pos;
    const rec = this.recovered.length;
    const trail = this.trail.length;
    const prevEnv = this.env;
    const prevCut = this.cut;
    this.cut = false;
    if (++this.depth > maxDepth) {
      this.tooDeep();
    }
    let v = r.body(this, min);
    this.depth--;
    this.cut = prevCut;
    this.trail.length = trail;
    if (v !== undefined) {
      v = this.finish(r, emptyFrame, v, start);
    } else {
      this.pos = start;
      this.recovered.length = rec;
    }
    this.env = prevEnv;
    return v;
  }

  // tooDeep fails the parse for exceeding the nesting limit.
  tooDeep(): never {
    throw new Fatal(new Error(`nesting too deep: more than ${maxDepth} rule calls`));
  }

  // finish makes the rule's value from the value of its body.
  finish(r: Rule, f: Frame, v: Node | null, start: number): Node | null {
    if (r.novalue) {
      return null;
    }
    if (r.action !== null) {
      const c = this.useCtx(f, start, this.pos, null, null, null);
      if (r.bodyIsSeq && v !== null) {
        c.items = v.children;
      } else {
        c.one[0] = v;
        c.items = c.one;
      }
      return c.result(r.action, r.name);
    }
    if (r.terminalType !== "") {
      return new Node(r.terminalType, r.name, start, this.pos, this.text(start, this.pos), noNodes, noFields, false, true);
    }
    if (r.scope.length > 0) {
      v = this.attachCaptures(v, r.scope, f, start, this.pos);
    }
    if (v === null) {
      return null;
    }
    if (v.fresh) {
      if (v.rule === "") {
        v.rule = r.name;
      }
      v.fresh = false;
    }
    return v;
  }

  // attachCaptures attaches the non-null captures as fields of the node. A node of another rule, or
  // one that is itself captured, is first wrapped in a Seq node.
  attachCaptures(v: Node | null, names: string[], f: Frame, start: number, end: number): Node | null {
    let found = false;
    let wrap = v === null || !v.fresh;
    for (const c of f) {
      if (c !== null) {
        found = true;
        if (c === v) {
          wrap = true;
        }
      }
    }
    if (!found) {
      return v;
    }
    let n = v as Node;
    if (wrap) {
      n = new Node("Seq", "", start, end, "", [v], noFields, true, false);
    }
    for (let i = 0; i < names.length; i++) {
      const c = f[i]!;
      if (c !== null) {
        setField(n, names[i]!, c);
      }
    }
    return n;
  }

  // --- Terminals ---

  matchLiteral(lit: Lit, desc: number, build: boolean): R {
    const start = this.pos;
    if (this.unit === Bytes) {
      const b = lit.bytes;
      if (this.pos + b.length > this.n) {
        return this.matchReplacementLiteral(lit, desc, build);
      }
      for (let i = 0; i < b.length; i++) {
        if (this.bs[this.pos + i] !== b[i]) {
          return this.matchReplacementLiteral(lit, desc, build);
        }
      }
      this.pos += b.length;
    } else {
      for (const r of lit.cps) {
        if (this.pos >= this.n || this.cps[this.pos] !== r) {
          this.expect(start, desc);
          return undefined;
        }
        this.pos++;
      }
    }
    if (!build) {
      return null;
    }
    return new Node("Match", "", start, this.pos, lit.text, noNodes, noFields, true, true);
  }

  // Keep replacement decoding off the successful byte-comparison path.
  matchReplacementLiteral(lit: Lit, desc: number, build: boolean): R {
    const start = this.pos;
    if (!lit.cps.includes(0xfffd)) {
      this.expect(start, desc);
      return undefined;
    }
    for (const want of lit.cps) {
      if (this.peek() !== want) {
        this.expect(start, desc);
        return undefined;
      }
      this.pos += this.psize;
    }
    if (!build) {
      return null;
    }
    return new Node("Match", "", start, this.pos, this.text(start, this.pos), noNodes, noFields, true, true);
  }

  matchAny(build: boolean): R {
    if (this.peek() < 0) {
      this.expect(this.pos, idAny);
      return undefined;
    }
    return this.single(this.psize, build);
  }

  // single consumes one character of size units.
  single(size: number, build: boolean): R {
    const start = this.pos;
    this.pos += size;
    if (!build) {
      return null;
    }
    return new Node("Match", "", start, this.pos, this.text(start, this.pos), noNodes, noFields, true, true);
  }

  anchor(ok: boolean, desc: number): R {
    if (ok) {
      return null;
    }
    this.expect(this.pos, desc);
    return undefined;
  }

  atLineStart(): boolean {
    if (this.pos === 0) {
      return true;
    }
    return (this.unit === Bytes ? this.bs[this.pos - 1] : this.cps[this.pos - 1]) === 0x0a;
  }

  atLineEnd(): boolean {
    const ch = this.peek();
    return ch < 0 || ch === 0x0a || ch === 0x0d;
  }

  atEnd(): boolean {
    return this.pos === this.n;
  }

  // --- Attributes ---

  // errorAttr replaces the expectations of a failing m with the message msg (an ID with msgBit),
  // reported at the farthest position m reached.
  errorAttr(m: Matcher, msg: number): R {
    const mFar = this.farthest;
    const mBase = this.expBase;
    this.expBase = this.expTop;
    this.farthest = this.pos;
    const v = m(this);
    const far = this.farthest;
    const from = this.expBase;
    const to = this.expTop;
    this.expTop = this.expBase;
    this.expBase = mBase;
    this.farthest = mFar;
    if (v !== undefined) {
      this.mergeExpected(far, from, to);
      return v;
    }
    this.expect(far, msg);
    return undefined;
  }

  // recoverAttr records the error of a failing m, skips what skip matches and returns an Error
  // node. It fails without recovering when skip fails or skips nothing.
  recoverAttr(m: Matcher, skip: Matcher, build: boolean): R {
    const m0pos = this.pos;
    const m0env = this.env;
    const m0trail = this.trail.length;
    const m0rec = this.recovered.length;
    const mFar = this.farthest;
    const mBase = this.expBase;
    this.expBase = this.expTop;
    this.farthest = this.pos;
    const v = m(this);
    const far = this.farthest;
    const from = this.expBase;
    const to = this.expTop;
    this.expTop = this.expBase;
    this.expBase = mBase;
    this.farthest = mFar;
    if (v !== undefined) {
      this.mergeExpected(far, from, to);
      return v;
    }
    const expected = this.keep(from, to); // keep them while skipping
    this.reset(m0pos, m0env, m0trail, m0rec);
    if (skip(this) === undefined || this.pos === m0pos) {
      this.reset(m0pos, m0env, m0trail, m0rec);
      this.mergeKept(far, expected);
      return undefined;
    }
    const e = this.makeError(far, expected);
    this.recovered.push(e);
    if (!build) {
      return null;
    }
    return new Node("Error", "", m0pos, this.pos, this.text(m0pos, this.pos), noNodes, [{ name: "message", value: e.message }], true, true);
  }

  // --- Actions and predicates ---

  // useCtx sets up the parser's single evaluation context and returns it. Evaluations never nest,
  // and no reference to the context survives one, so one context per parser can be reused.
  useCtx(f: Frame, start: number, end: number, lhs: Value, rhs: Value, op: Value): Actx {
    const c = this.ac;
    c.f = f;
    c.items = noNodes;
    c.start = start;
    c.end = end;
    c.cbase = this.created.length;
    c.lhs = lhs;
    c.rhs = rhs;
    c.op = op;
    return c;
  }

  predicate(t: Action): boolean {
    const base = this.created.length;
    const kids = this.kidStack.length;
    try {
      const v = t(this.useCtx(this.frame, this.pos, this.pos, null, null, null));
      return v !== false;
    } catch (x) {
      if (!(x instanceof EvalError)) {
        throw x;
      }
      this.dropKids(kids); // elements gathered by a list built-in that failed
      return false;
    } finally {
      this.created.length = base; // drop nodes created by the predicate
    }
  }

  assign(name: string, t: Action): boolean {
    const base = this.created.length;
    const kids = this.kidStack.length;
    try {
      const v = t(this.useCtx(this.frame, this.pos, this.pos, null, null, null));
      if (typeof v === "function") {
        return false;
      }
      this.bind(name, v);
      return true;
    } catch (x) {
      if (!(x instanceof EvalError)) {
        throw x;
      }
      this.dropKids(kids); // elements gathered by a list built-in that failed
      return false;
    } finally {
      this.created.length = base; // drop nodes created by the predicate
    }
  }

  // Preserve environments saved for rollback; first assignments skip searching.
  bind(name: string, val: Value): void {
    const e = this.env;
    if (this.bound === null) this.bound = new Set();
    if (e === null) {
      this.env = { name, val, next: null };
      this.bound.add(name);
      return;
    }
    if (e.name === name) {
      if (e.val !== val) this.env = { name, val, next: e.next };
      return;
    }
    if (!this.bound.has(name)) {
      this.bound.add(name);
      this.env = { name, val, next: e };
      return;
    }
    let old: Env | null = e;
    while (old !== null && old.name !== name) old = old.next;
    if (old === null) {
      this.env = { name, val, next: e };
      return;
    }
    // Variables are checked scalar values; an equal assignment has no effect.
    if (old.val === val) return;
    const head: Env = { name, val, next: null };
    let tail = head;
    for (let cur: Env | null = e; cur !== old; cur = cur!.next) {
      tail.next = { name: cur!.name, val: cur!.val, next: null };
      tail = tail.next;
    }
    tail.next = old.next;
    this.env = head;
  }

  // --- Pratt expressions ---

  skipTrivia(pr: Pratt): void {
    if (pr.skip === null) {
      return;
    }
    const m0pos = this.pos;
    const m0env = this.env;
    const m0trail = this.trail.length;
    const m0rec = this.recovered.length;
    this.silent++;
    const v = pr.skip(this);
    this.silent--;
    if (v === undefined) {
      this.reset(m0pos, m0env, m0trail, m0rec);
    }
  }

  // longest tries every operator and returns the longest match (the first declared among equals),
  // or null when none matched. cutFailed is set when a candidate failed after a cut.
  longest(ops: PrattOp[]): PrattAttempt | null {
    const m0pos = this.pos;
    const m0env = this.env;
    const m0trail = this.trail.length;
    const m0rec = this.recovered.length;
    let best: PrattAttempt | null = null;
    let cutFailed = false;
    for (const op of ops) {
      const prevFrame = this.frame;
      const prevCut = this.cut;
      const f = this.newFrame(op.line.scope.length);
      this.frame = f;
      this.cut = false;
      const v = op.line.m(this);
      let ok = v !== undefined;
      const cut = this.cut;
      this.frame = prevFrame;
      this.cut = prevCut;
      if (ok && this.pos === m0pos && op.kind !== "infix") {
        ok = false; // an empty prefix or postfix match could be applied forever
      }
      if (ok && (best === null || this.pos > best.end)) {
        best = {
          op,
          frame: f,
          v: v as Node | null,
          start: m0pos,
          end: this.pos,
          env: this.env,
          cut,
          errs: this.recovered.length > m0rec ? this.recovered.slice(m0rec) : noErrs,
        };
      }
      if (!ok && cut) {
        cutFailed = true;
      }
      if (f.length === 0) {
        this.reset(m0pos, m0env, m0trail, m0rec);
        continue;
      }
      // reset undoes this candidate's captures; restore them. Nothing parses between saving
      // and restoring, so one buffer per parser suffices.
      this.saved.length = 0;
      for (const x of f) {
        this.saved.push(x);
      }
      this.reset(m0pos, m0env, m0trail, m0rec);
      for (let i = 0; i < f.length; i++) {
        f[i] = this.saved[i]!;
      }
    }
    this.cutFailed = cutFailed;
    return best;
  }

  // cutFailed reports that a candidate of the last longest failed after a cut.
  cutFailed = false;

  apply(a: PrattAttempt): void {
    this.pos = a.end;
    this.env = a.env;
    for (const x of a.errs) {
      this.recovered.push(x);
    }
  }

  // prattParse parses an expression with operators that bind tighter than min. Each level of its
  // recursion (the operand of a prefix operator, the right operand of an infix operator) counts
  // against the nesting limit, like a rule call.
  prattParse(r: Rule, min: number): R {
    if (++this.depth > maxDepth) {
      this.tooDeep();
    }
    const v = this.prattExpr(r, min);
    this.depth--;
    return v;
  }

  prattExpr(r: Rule, min: number): R {
    const pr = r.pratt as Pratt;
    let lhs = this.prattNud(r);
    if (lhs === undefined) {
      return undefined;
    }
    let lastNone = -1;
    for (;;) {
      const m0pos = this.pos;
      const m0env = this.env;
      const m0trail = this.trail.length;
      const m0rec = this.recovered.length;
      this.skipTrivia(pr);
      const a = this.longest(pr.led);
      if (a === null) {
        const cutFailed = this.cutFailed;
        this.reset(m0pos, m0env, m0trail, m0rec);
        if (cutFailed) {
          return undefined;
        }
        break;
      }
      if (a.op.level <= min || (a.op.assoc === "none" && a.op.level === lastNone)) {
        this.reset(m0pos, m0env, m0trail, m0rec);
        break;
      }
      this.apply(a);
      if (a.op.kind === "postfix") {
        lhs = this.prattBuild(r, a, lhs, null);
        lastNone = -1;
        if (this.pos === m0pos) {
          break;
        }
        continue;
      }
      let rmin = a.op.level;
      if (a.op.assoc === "right") {
        rmin--;
      }
      const rhs = this.prattParse(r, rmin);
      if (rhs === undefined) {
        if (a.cut) {
          return undefined;
        }
        this.reset(m0pos, m0env, m0trail, m0rec);
        break;
      }
      lhs = this.prattBuild(r, a, lhs, rhs);
      lastNone = -1;
      if (a.op.assoc === "none") {
        lastNone = a.op.level;
      }
      // An application that consumed no input ends the loop, as an empty iteration ends a
      // repetition: otherwise an operator that can match empty after an operand that can loops
      // forever.
      if (this.pos === m0pos) {
        break;
      }
    }
    return lhs;
  }

  prattNud(r: Rule): R {
    const pr = r.pratt as Pratt;
    this.skipTrivia(pr);
    const m0pos = this.pos;
    const m0env = this.env;
    const m0trail = this.trail.length;
    const m0rec = this.recovered.length;
    const a = this.longest(pr.prefix);
    if (a !== null) {
      this.apply(a);
      const rhs = this.prattParse(r, a.op.level);
      if (rhs !== undefined) {
        return this.prattBuild(r, a, null, rhs);
      }
      if (a.cut) {
        return undefined;
      }
      this.reset(m0pos, m0env, m0trail, m0rec);
    } else if (this.cutFailed) {
      return undefined;
    }
    for (const o of pr.operands) {
      const prevFrame = this.frame;
      const prevCut = this.cut;
      const f = this.newFrame(o.scope.length);
      this.frame = f;
      this.cut = false;
      const v = o.m(this);
      const cut = this.cut;
      this.frame = prevFrame;
      this.cut = prevCut;
      if (v !== undefined) {
        return this.lineResult(r, o, f, v, m0pos);
      }
      this.reset(m0pos, m0env, m0trail, m0rec);
      if (cut) {
        return undefined;
      }
    }
    return undefined;
  }

  lineResult(r: Rule, l: PrattLine, f: Frame, v: Node | null, start: number): Node | null {
    if (r.novalue) {
      return null;
    }
    if (l.action !== null) {
      const c = this.useCtx(f, start, this.pos, null, null, null);
      if (l.isSeq && v !== null) {
        c.items = v.children;
      } else {
        c.one[0] = v;
        c.items = c.one;
      }
      return c.result(l.action, r.name);
    }
    if (l.scope.length > 0) {
      v = this.attachCaptures(v, l.scope, f, start, this.pos);
    }
    if (v !== null && v.fresh) {
      if (v.rule === "") {
        v.rule = r.name;
      }
      v.fresh = false;
    }
    return v;
  }

  prattBuild(r: Rule, a: PrattAttempt, lhs: Node | null, rhs: Node | null): Node | null {
    if (r.novalue) {
      return null;
    }
    let start = a.start;
    let end = this.pos;
    if (lhs !== null) {
      start = lhs.start;
    }
    if (a.op.kind === "postfix") {
      end = a.end;
    }
    const l = a.op.line;
    if (l.action !== null) {
      const op = new Node("Match", "", a.start, a.end, this.text(a.start, a.end), noNodes, noFields, false, true);
      const c = this.useCtx(a.frame, start, end, lhs, rhs, op);
      return c.result(l.action, r.name);
    }
    let opv = a.v;
    if (l.scope.length > 0) {
      opv = this.attachCaptures(opv, l.scope, a.frame, a.start, a.end);
    }
    if (opv !== null) {
      opv.fresh = false;
    }
    let kids: (Node | null)[];
    switch (a.op.kind) {
      case "prefix":
        kids = [opv, rhs];
        break;
      case "postfix":
        kids = [lhs, opv];
        break;
      default:
        kids = [lhs, opv, rhs];
    }
    return new Node("Operator", r.name, start, end, "", kids, [{ name: "operator", value: a.op.id }], false, false);
  }
}

// codePointsString returns the string of the code points cps.
function codePointsString(cps: Int32Array): string {
  const parts: string[] = [];
  const chunk = 4096;
  for (let i = 0; i < cps.length; i += chunk) {
    parts.push(String.fromCodePoint(...cps.subarray(i, Math.min(i + chunk, cps.length))));
  }
  return parts.join("");
}

// Fatal is an error that ends the parse (a runtime error in an action, or too deep nesting).
class Fatal {
  err: Error;
  constructor(err: Error) {
    this.err = err;
  }
}

// EvalError is an error in evaluating a value expression. It fails the whole parse in an action
// and makes a predicate fail.
class EvalError {
  msg: string;
  constructor(msg: string) {
    this.msg = msg;
  }
}

function evalError(msg: string): never {
  throw new EvalError(msg);
}

// Actx is the context of evaluating an action or a predicate.
class Actx {
  p: Parser;
  f: Frame = emptyFrame;
  items: readonly (Node | null)[] = noNodes;
  start = 0;
  end = 0;
  cbase = 0; // start of p.created made by this evaluation
  lhs: Value = null;
  rhs: Value = null;
  op: Value = null;
  one: (Node | null)[] = [null]; // items for a single item

  constructor(p: Parser) {
    this.p = p;
  }

  result(action: Action, where: string): Node | null {
    try {
      const v = action(this);
      if (v === null) {
        return null;
      }
      if (!(v instanceof Node)) {
        return evalError(`result must be a node, got ${typeName(v)}`);
      }
      const n = v;
      const created = this.p.created;
      for (let i = this.cbase; i < created.length; i++) {
        if (created[i] === n) {
          n.start = this.start;
          n.end = this.end;
          break;
        }
      }
      n.fresh = false; // the value of an action is final (see the engine's actionResult)
      return n;
    } catch (x) {
      if (x instanceof EvalError) {
        throw new Fatal(new Error(`action in ${where}: ${x.msg}`));
      }
      throw x;
    } finally {
      this.p.created.length = this.cbase;
    }
  }

  cap(slot: number): Value {
    return this.f[slot]!;
  }

  item(n: number): Value {
    if (n === 0) {
      return this.newList(this.items);
    }
    if (n > this.items.length) {
      evalError(`$${n} is out of range (${this.items.length} elements)`);
    }
    return this.items[n - 1]!;
  }

  lookup(name: string): Value {
    for (let e = this.p.env; e !== null; e = e.next) {
      if (e.name === name) {
        return e.val;
      }
    }
    return evalError(`variable ${name} is not defined`);
  }

  newStruct(typ: string, ...kv: Value[]): Value {
    const n = new Node(typ, "", 0, 0, "", noNodes, noFields, false, false);
    let first = true;
    for (let i = 0; i < kv.length; i += 2) {
      const v = kv[i + 1];
      setField(n, kv[i] as string, v!);
      if (v instanceof Node) {
        if (first || v.start < n.start) {
          n.start = v.start;
        }
        if (first || v.end > n.end) {
          n.end = v.end;
        }
        first = false;
      }
    }
    if (first) {
      n.start = this.start;
      n.end = this.end;
    }
    this.p.created.push(n);
    return n;
  }

  newList(items: readonly (Node | null)[]): Node {
    return this.listNode(items.slice());
  }

  // listNode returns a List node with the child list kids (which it takes over).
  listNode(kids: (Node | null)[]): Node {
    const n = new Node("List", "", this.start, this.start, "", kids, noFields, false, false);
    let first = true;
    for (const it of kids) {
      if (it === null) {
        continue;
      }
      if (first || it.start < n.start) {
        n.start = it.start;
      }
      if (first || it.end > n.end) {
        n.end = it.end;
      }
      first = false;
    }
    return n;
  }

  member(x: Value, name: string): Value {
    if (!(x instanceof Node)) {
      return evalError(`cannot access .${name} of ${typeName(x)}`);
    }
    switch (name) {
      case "startPos":
        return x.start;
      case "endPos":
        return x.end;
      case "children":
        return this.newList(x.children);
    }
    const fields = structFields.get(x.type);
    if (fields !== undefined && !fields.has(name)) {
      evalError(`${x.type} has no field ${name}`);
    }
    return x.field(name);
  }

  length(x: Value): Value {
    if (typeof x === "string") {
      return this.p.unitLen(x);
    }
    if (x === null) {
      return 0;
    }
    if (x instanceof Node) {
      if (x.terminal) {
        return this.p.unitLen(x.text);
      }
      return x.children.length;
    }
    return evalError(`len: invalid argument ${typeName(x)}`);
  }

  text(x: Value): Value {
    return this.textStr(x);
  }

  // textStr returns text(x) as a string.
  textStr(x: Value): string {
    if (x === null) {
      return "";
    }
    if (typeof x === "string") {
      return x;
    }
    if (x instanceof Node) {
      if (x.terminal) {
        return x.text;
      }
      return this.p.text(x.start, x.end);
    }
    return evalError(`text: invalid argument ${typeName(x)}`);
  }

  // The list built-ins gather the elements on kidStack (lambdas that build lists push above them)
  // and hand the copied-out slice to the list node. If one fails, the error unwinds to the action
  // (which fails the parse) or the predicate (which pops what was gathered).

  mapList(list: Value, f: (item: Value) => Value): Value {
    const base = this.p.kidStack.length;
    this.pushMap(list, f);
    return this.endList(base);
  }

  list(...args: Value[]): Value {
    const base = this.p.kidStack.length;
    this.pushList(...args);
    return this.endList(base);
  }

  concat(...args: Value[]): Value {
    const base = this.p.kidStack.length;
    for (const a of args) {
      this.pushItems(a);
    }
    return this.endList(base);
  }

  // pushMap, pushList and pushItems push the elements that map, list and concat make from their
  // arguments. A concat call whose arguments are all list, map or such concat calls is generated
  // as pushes for its arguments followed by endList, so that they build no intermediate list.

  pushMap(list: Value, f: (item: Value) => Value): void {
    for (const it of listItems("map", list)) {
      const v = asNode("map", f(it));
      this.p.kidStack.push(v);
    }
  }

  pushList(...args: Value[]): void {
    for (const a of args) {
      const v = asNode("list", a);
      this.p.kidStack.push(v);
    }
  }

  pushItems(v: Value): void {
    for (const it of listItems("concat", v)) {
      this.p.kidStack.push(it);
    }
  }

  // endList returns a list of the elements pushed since base.
  endList(base: number): Value {
    return this.listNode(this.p.kids(base));
  }
}

function typeName(v: unknown): string {
  if (v === null || v === undefined) {
    return "nil";
  }
  if (v instanceof Node) {
    return v.type;
  }
  switch (typeof v) {
    case "number":
    case "bigint":
      return "int";
    case "string":
      return "string";
    case "boolean":
      return "bool";
    case "function":
      return "func";
  }
  return typeof v;
}

function listItems(fn: string, v: Value): readonly (Node | null)[] {
  if (v === null) {
    return noNodes;
  }
  if (v instanceof Node) {
    return v.children;
  }
  return evalError(`${fn}: expected a list, got ${typeName(v)}`);
}

function asNode(fn: string, v: Value): Node | null {
  if (v === null || v instanceof Node) {
    return v;
  }
  return evalError(`${fn}: list elements must be nodes, got ${typeName(v)}`);
}

function rtFold(fn: string, right: boolean, acc: Value, list: Value, f: (acc: Value, item: Value) => Value): Value {
  const items = listItems(fn, list);
  for (let i = 0; i < items.length; i++) {
    acc = f(acc, items[right ? items.length - 1 - i : i]!);
  }
  return acc;
}

// --- Ints ---

// Ints are 64-bit and wrap around, as in Go. An int is a number while it is a safe integer and a
// bigint otherwise, so equal ints are always ===.

const maxSafe = BigInt(Number.MAX_SAFE_INTEGER);

function intOf(b: bigint): number | bigint {
  b = BigInt.asIntN(64, b);
  return b >= -maxSafe && b <= maxSafe ? Number(b) : b;
}

function isInt(v: Value): v is number | bigint {
  return typeof v === "number" || typeof v === "bigint";
}

function big(v: number | bigint): bigint {
  return typeof v === "bigint" ? v : BigInt(v);
}

function rtUnary(op: string, x: Value): Value {
  switch (op) {
    case "-":
      if (typeof x === "number") {
        return 0 - x; // 0 - x, not -x, which is -0 for 0
      }
      if (typeof x === "bigint") {
        return intOf(-x);
      }
      break;
    case "!":
      if (typeof x === "boolean") {
        return !x;
      }
  }
  return evalError(`invalid operand ${typeName(x)} for unary ${op}`);
}

function rtBool(op: string, v: Value): boolean {
  if (typeof v !== "boolean") {
    return evalError(`invalid operand ${typeName(v)} for ${op}`);
  }
  return v;
}

function rtAnd(l: Value, r: () => Value): Value {
  if (!rtBool("&&", l)) {
    return false;
  }
  return rtBool("&&", r());
}

function rtOr(l: Value, r: () => Value): Value {
  if (rtBool("||", l)) {
    return true;
  }
  return rtBool("||", r());
}

function rtBinary(op: string, l: Value, r: Value): Value {
  switch (op) {
    case "==":
      return l === r;
    case "!=":
      return l !== r;
  }
  if (isInt(l) && isInt(r)) {
    const small = typeof l === "number" && typeof r === "number";
    switch (op) {
      case "+":
        if (small) {
          const s = (l as number) + (r as number);
          if (Number.isSafeInteger(s)) {
            return s;
          }
        }
        return intOf(big(l) + big(r));
      case "-":
        if (small) {
          const s = (l as number) - (r as number);
          if (Number.isSafeInteger(s)) {
            return s + 0;
          }
        }
        return intOf(big(l) - big(r));
      case "*":
        if (small) {
          const s = (l as number) * (r as number);
          if (Number.isSafeInteger(s)) {
            return s + 0;
          }
        }
        return intOf(big(l) * big(r));
      case "/":
      case "%":
        if (r === 0) {
          return evalError("division by zero");
        }
        if (small) {
          // Exact for safe integers; + 0 turns -0 into 0.
          return (op === "/" ? Math.trunc((l as number) / (r as number)) : (l as number) % (r as number)) + 0;
        }
        return intOf(op === "/" ? big(l) / big(r) : big(l) % big(r));
      case "<":
        return l < r;
      case "<=":
        return l <= r;
      case ">":
        return l > r;
      case ">=":
        return l >= r;
    }
  } else if (typeof l === "string" && typeof r === "string") {
    switch (op) {
      case "+":
        return l + r;
      case "<":
        return compareStrings(l, r) < 0;
      case "<=":
        return compareStrings(l, r) <= 0;
      case ">":
        return compareStrings(l, r) > 0;
      case ">=":
        return compareStrings(l, r) >= 0;
    }
  }
  return evalError(`invalid operands ${typeName(l)} and ${typeName(r)} for ${op}`);
}

// --- Pratt expressions ---

interface Pratt {
  skip: Matcher | null;
  operands: PrattLine[];
  prefix: PrattOp[];
  led: PrattOp[];
}

interface PrattLine {
  scope: string[];
  m: Matcher;
  action: Action | null;
  isSeq: boolean;
}

interface PrattOp {
  id: number;
  kind: string;
  assoc: string;
  level: number;
  line: PrattLine;
}

interface PrattAttempt {
  op: PrattOp;
  frame: Frame;
  v: Node | null;
  start: number;
  end: number;
  env: Env | null;
  cut: boolean;
  errs: SyntaxError[];
}

// Declarations that the code generated for a grammar may not use, read here so that projects
// compiling with noUnusedLocals accept the module.
void [idBeginInput, idBeginLine, idEndLine, rtFold, rtUnary, rtAnd, rtOr, rtBinary];
