// Package json parses JSON (RFC 8259) with a parser generated by PEGO from json.pego.
//
// ParseAST returns the document as typed values (Object, Array, String, Number, Bool and Null, each with
// its Span in the input), Parse returns it as a tree of Nodes, and Recognize only checks it. Decode and
// ToAny convert to the Go values that encoding/json decodes into an any.
//
// The parser accepts exactly the texts RFC 8259 defines: any value at the top level, surrounded by
// optional whitespace. Like encoding/json, it accepts invalid UTF-8 and unpaired surrogate escapes, which
// the RFC leaves to the implementation, and decodes them to U+FFFD. It rejects a byte order mark.
package json

import (
	"fmt"
	"strconv"
	"strings"
	"unicode/utf16"
	"unicode/utf8"
)

// Valid reports whether input is a JSON text.
func Valid(input string) bool { return Recognize(input) == nil }

// Decode parses input and returns its value as encoding/json decodes it into an any: map[string]any,
// []any, string, float64, bool or nil. As in encoding/json, the last of duplicate keys wins, and a number
// outside the range of float64 is an error.
func Decode(input string) (any, error) {
	v, err := ParseAST(input)
	if err != nil {
		return nil, err
	}
	return ToAny(v)
}

// ToAny converts a value returned by ParseAST to the Go values Decode returns.
func ToAny(v Value) (any, error) {
	switch v := v.(type) {
	case *Object:
		m := make(map[string]any, len(v.Members))
		for _, mem := range v.Members {
			x, err := ToAny(mem.Value)
			if err != nil {
				return nil, err
			}
			m[mem.Key.Value()] = x
		}
		return m, nil
	case *Array:
		a := make([]any, len(v.Elements))
		for i, e := range v.Elements {
			x, err := ToAny(e)
			if err != nil {
				return nil, err
			}
			a[i] = x
		}
		return a, nil
	case *String:
		return v.Value(), nil
	case *Number:
		return v.Float64()
	case *Bool:
		return v.Value(), nil
	case *Null:
		return nil, nil
	}
	return nil, fmt.Errorf("json: unexpected value %T", v)
}

// Value returns the string the literal denotes, with its escape sequences decoded. Invalid UTF-8 and
// unpaired surrogates (\ud800 without a low surrogate after it) become U+FFFD, as in encoding/json.
func (s *String) Value() string {
	t := s.Text
	if !strings.ContainsRune(t, '\\') && utf8.ValidString(t) {
		return t
	}
	var b strings.Builder
	b.Grow(len(t))
	for i := 0; i < len(t); {
		c := t[i]
		if c != '\\' {
			r, n := utf8.DecodeRuneInString(t[i:])
			b.WriteRune(r) // RuneError for invalid UTF-8
			i += n
			continue
		}
		if i+1 >= len(t) {
			b.WriteRune(utf8.RuneError)
			break
		}
		switch e := t[i+1]; e {
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'u':
			r, ok := hex4(t, i+2)
			if !ok {
				b.WriteRune(utf8.RuneError)
				i += 2
				continue
			}
			i += 6
			if utf16.IsSurrogate(r) {
				if lo, ok := hex4(t, i+2); ok && i+1 < len(t) && t[i] == '\\' && t[i+1] == 'u' {
					if d := utf16.DecodeRune(r, lo); d != utf8.RuneError {
						b.WriteRune(d)
						i += 6
						continue
					}
				}
				r = utf8.RuneError
			}
			b.WriteRune(r)
			continue
		default: // '"', '\\' and '/'
			b.WriteByte(e)
		}
		i += 2
	}
	return b.String()
}

// hex4 decodes the four hexadecimal digits at t[i:].
func hex4(t string, i int) (rune, bool) {
	if i+4 > len(t) {
		return 0, false
	}
	n, err := strconv.ParseUint(t[i:i+4], 16, 16)
	return rune(n), err == nil
}

// Float64 returns the number as a float64. A number outside the range of float64 is an error.
func (n *Number) Float64() (float64, error) {
	f, err := strconv.ParseFloat(n.Text, 64)
	if err != nil {
		return 0, fmt.Errorf("json: number %s: %w", n.Text, err.(*strconv.NumError).Err)
	}
	return f, nil
}

// Int64 returns the number as an int64. A number with a fraction or an exponent, or outside the range of
// int64, is an error.
func (n *Number) Int64() (int64, error) {
	i, err := strconv.ParseInt(n.Text, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("json: number %s: %w", n.Text, err.(*strconv.NumError).Err)
	}
	return i, nil
}

// Value returns the boolean.
func (b *Bool) Value() bool { return b.Text == "true" }
