-- JSON_OBJECT: key value forms
select json_object();
select json_object(returning jsonb);
select json_object(returning text format json);
select json_object(returning text format json encoding utf8);
select json_object(returning bytea format json encoding UTF16);
select json_object(returning bytea format json encoding "utf32");
select json_object(returning bytea format json encoding "UTF-8");
select json_object(returning bytea format json encoding utf7);
select json_object(returning bytea format json encoding);
select json_object('a' : 1);
select json_object('a' : 1, 'b' : 2);
select json_object('a' : 1 format json);
select json_object('a' : 1 format json encoding utf8);
select json_object(a value b);
select json_object(a value b, c value d);
select json_object(a value b format json);
select json_object(a + 1 value b);
select json_object(a + 1 : b);
select json_object(a :: int : b);
select json_object(a :: int value b);
select json_object('a' : 1 null on null);
select json_object('a' : 1 absent on null);
select json_object('a' : 1 with unique);
select json_object('a' : 1 with unique keys);
select json_object('a' : 1 without unique);
select json_object('a' : 1 without unique keys);
select json_object('a' : 1 null on null with unique keys returning jsonb);
select json_object('a' : 1 absent on null without unique returning json format json encoding utf8);
select json_object('a' : 1 returning json);
select json_object('a' : 1 returning varchar(5));
select json_object('a' : 1 returning timestamp with time zone);
select json_object('a' : 1 returning int[]);
select json_object('a' : 1 returning pg_catalog.jsonb);
select json_object('a' : 1 returning jsonb with unique);
select json_object('a' : 1 with unique null on null);
select json_object('a' : 1 returning json null on null);
select json_object('a' : 1 null on null absent on null);
select json_object('a' : 1 with unique without unique);
select json_object('a' : 1, 'b');
select json_object('a' : 1,);
select json_object(key 'a' value 1);
select json_object('a' : 1 key 'b' value 2);
-- legacy json_object(func_arg_list)
select json_object('a', 'b');
select json_object('{a,b}');
select json_object('{a,b}', '{1,2}');
select json_object(variadic x);
select json_object('a', variadic x);
select json_object(x := 1);
select json_object(x => 1, 'b' : 2);
select json_object('a', 1, 'b' : 2);
select json_object(a, b order by c);
select json_object(distinct a);
select json_object(all a);
select json_object(*);
select json_object(a b);
-- JSON_ARRAY
select json_array();
select json_array(returning jsonb);
select json_array(returning text format json encoding utf8);
select json_array(1);
select json_array(1, 2, 3);
select json_array(1 format json);
select json_array(1 format json encoding utf16, 2);
select json_array(1 null on null);
select json_array(1 absent on null);
select json_array(1, 2 null on null returning jsonb);
select json_array(1, 2 absent on null returning text format json);
select json_array(1 returning json);
select json_array(1 returning json format json);
select json_array((select 1));
select json_array((select 1), (select 2));
select json_array((select 1) union (select 2));
select json_array((select 1) union (select 2) returning jsonb);
select json_array((select 1) format json);
select json_array(select 1);
select json_array(select 1 from t);
select json_array(select 1 from t order by 1);
select json_array(select 1 format json);
select json_array(select 1 format json encoding utf8);
select json_array(select 1 returning jsonb);
select json_array(select 1 format json returning jsonb);
select json_array(select 1 returning jsonb format json);
select json_array(select a from t union select b from u);
select json_array(select 1 union select 2 order by 1 returning jsonb);
select json_array(values (1), (2));
select json_array(values (1), (2) returning text);
select json_array(table t);
select json_array(with x as (select 1) select * from x);
select json_array(select 1 null on null);
select json_array(select 1, 2);
select json_array(select 1 for update);
select json_array(1, select 2);
select json_array(null on null);
select json_array(1,);
select json_array(a b);
-- JSON(), JSON_SCALAR, JSON_SERIALIZE
select json('{}');
select json('{}' with unique);
select json('{}' with unique keys);
select json('{}' without unique);
select json('{}' without unique keys);
select json('{}' format json);
select json('{}' format json encoding utf8 with unique keys);
select json(x);
select json(x returning text);
select json('{}', 1);
select json();
select json 'abc';
select json '{}'::jsonb;
select json_scalar(1);
select json_scalar('x' || 'y');
select json_scalar(a, b);
select json_scalar();
select json_scalar(1 returning text);
select json_scalar(1 format json);
select json_serialize(x);
select json_serialize(x format json);
select json_serialize(x format json encoding utf8);
select json_serialize(x returning text);
select json_serialize(x returning bytea format json);
select json_serialize(x returning bytea format json encoding utf16);
select json_serialize(x with unique);
select json_serialize();
select json_serialize(x, y);
-- nested
select json_object('a' : json_array(1, json_object('b' : json_scalar(2))));
select json_array(json_object('a' : 1) format json, json('{}'));
select json_object('a' : json_arrayagg(x) filter (where y));
select coalesce(json_array(1), json_object());
select json_object('a' : sum(x) over ());
select json_array(sum(x) over (), 1);
select json_array(sum(x) filter (where y) over w);
select * from t where json_object('a' : 1) is json;
select * from generate_series(1, json_array(1));
select * from json_array(1);
select * from json_object('a' : 1) as t;
select * from json_scalar(1) with ordinality as t(a, b);
select * from json_serialize('{}');
select * from json('{}');
select * from lateral json_array(1);
select * from json_object('a' : sum(x) over ());
select * from xmlconcat('<a/>', '<b/>') as x;
select * from xmlelement(name a) with ordinality;
select * from xmlparse(document '<a/>');
select * from xmlforest(a as b);
