select * from xmltable('/r' passing x columns a int);
select * from xmltable('/r' passing by ref x columns a int);
select * from xmltable('/r' passing by value x columns a int);
select * from xmltable('/r' passing x by ref columns a int);
select * from xmltable('/r' passing by ref x by ref columns a int) as t;
select * from xmltable('/r' passing x columns a int path 'p');
select * from xmltable('/r' passing x columns a int path 'p' default 1);
select * from xmltable('/r' passing x columns a int default 1 path 'p');
select * from xmltable('/r' passing x columns a int default 1 path 'p' not null);
select * from xmltable('/r' passing x columns a int not null default 1 path 'p');
select * from xmltable('/r' passing x columns a int null);
select * from xmltable('/r' passing x columns a int not null);
select * from xmltable('/r' passing x columns a int path 'p' null default 1);
select * from xmltable('/r' passing x columns i for ordinality, a int);
select * from xmltable('/r' passing x columns a for ordinality);
select * from xmltable('/r' passing x columns a int, b text, c timestamp with time zone path 'c', d varchar(3) default 'x');
select * from xmltable('/r' passing x columns a int, b text[], c setof int);
select * from xmltable('/r' passing x columns a int path 'a' || 'b');
select * from xmltable('/r' passing x columns a int path ('a'));
select * from xmltable('/r' passing x columns a int path a + 1 default b * 2);
select * from xmltable('/r' passing x columns a int default 1 is document);
select * from xmltable('/r' passing x columns a int path 'x'::text);
select * from xmltable('/r' passing x columns a int "path" 'p');
select * from xmltable('/r' passing x columns a int "default" 1);
select * from xmltable('/r' passing x columns a int "path" 'p' "default" 1 null);
select * from xmltable('/r' passing x columns a int "foo" 'p');
select * from xmltable('/r' passing x columns a int "PATH" 'p');
select * from xmltable('/r' passing x columns a int "__pg__is_not_null" 'p');
select * from xmltable('/r' passing x columns a int path 'p' path 'q');
select * from xmltable('/r' passing x columns a int default 1 default 2);
select * from xmltable('/r' passing x columns a int null null);
select * from xmltable('/r' passing x columns a int not null null);
select * from xmltable('/r' passing x columns a int not null not null);
select * from xmltable('/r' passing x columns a int path 'p' "path" 'q');
select * from xmltable(xmlnamespaces('u' as a) , '/r' passing x columns a int);
select * from xmltable(xmlnamespaces('u' as a, 'v' as b, default 'd'), '/r' passing x columns a int);
select * from xmltable(xmlnamespaces(default 'd'), '/r' passing x columns a int);
select * from xmltable(xmlnamespaces(default 'd', 'u' as "A"), '/r' passing x columns a int);
select * from xmltable(xmlnamespaces('u' || 'v' as a), '/r' passing x columns a int);
select * from xmltable(xmlnamespaces('u' as a) '/r' passing x columns a int);
select * from xmltable(xmlnamespaces(), '/r' passing x columns a int);
select * from xmltable('/r' passing x columns a int) t;
select * from xmltable('/r' passing x columns a int) as t;
select * from xmltable('/r' passing x columns a int) as t(c1);
select * from xmltable('/r' passing x columns a int) t(c1, c2);
select * from xmltable('/r' passing x columns a int) t where a > 1;
select * from xmltable('/r' passing x columns a int), t2;
select * from xmltable('/r' passing x columns a int) join t2 on true;
select * from xmltable('/r' passing x columns a int) t join t2 using (a);
select * from xmltable('/r' passing x columns a int) cross join t2;
select * from xmltable('/r' passing x columns a int) natural join t2;
select * from t2 join xmltable('/r' passing x columns a int) on true;
select * from t2 left join xmltable('/r' passing x columns a int) x on true;
select * from t2, lateral xmltable('/r' passing t2.x columns a int);
select * from t2, lateral xmltable('/r' passing t2.x columns a int) as x(a);
select * from t2, xmltable('/r' passing t2.x columns a int);
select * from lateral xmltable('/r' passing x columns a int);
select * from LATERAL XMLTABLE('/r' PASSING x COLUMNS a INT);
select * from xmltable(f(x) passing g(y) columns a int);
select * from xmltable(('/r' || 'x') passing y columns a int);
select * from xmltable('/r' passing (select 1) columns a int);
select * from xmltable((select 'x') passing y columns a int);
select * from xmltable(row() passing null columns v1 timestamp) as f(v1, v2);
select * from xmltable('/r' passing x columns a int path 'a' /* c */ default /* c */ 1 -- c
);
select * from xmltable /* c */ ( /* c */ '/r' passing x columns a int);
select * from xmltable('/r' columns a int);
select * from xmltable('/r' passing x);
select * from xmltable('/r' passing x columns);
select * from xmltable(passing x columns a int);
select * from xmltable('/r' passing x columns a);
select * from xmltable('/r' passing x columns a int,);
select * from xmltable('/r' passing x columns a int path);
select * from (xmltable('/r' passing x columns a int));
select * from xmltable('/r' passing x columns a int) tablesample system (1);
select * from only xmltable('/r' passing x columns a int);
select xmltable.* from xmltable('/r' passing x columns a int);
select * from xmltable('/r' passing x columns a xml, b json, c "my type", d pg_catalog.int4);
select * from xmltable('/r' passing x columns "from" int, "a b" text path 'p');
select * from xmltable('/r' passing x columns nested int, path int, columns text, name text, value text, passing int, version int);
select * from xmltable('/r' passing x columns "xmltable" int);
select * from xmltable('/r' passing x columns a int null, b int not null path 'b');
select * from xmltable('/r' passing x columns a int path 'a' default 'x' not null, b int);
