// Package duckdb parses the SQL dialect of DuckDB, as DuckDB 1.5.6 parses it, with a parser generated by PEGO from
// duckdb.pego: the statements of its grammar (a fork of PostgreSQL's) with the syntax DuckDB adds, and the
// scanner that goes with it.
//
// ParseAST returns a script as typed values: a Script of statements (Select, InsertStmt, CreateTableStmt and the
// others of the Statement union), whose expressions, types and table references are the nodes of the syntax
// tree, each with its Span in the input. Parse returns the same as a tree of Nodes, and Recognize only checks the
// syntax. Split cuts a script into statements as DuckDB does, with the text DuckDB keeps for each, and Kind gives
// the type DuckDB gives a statement.
//
// The parser reads what DuckDB's parser reads and nothing else: keywords are matched without regard to case
// and only where DuckDB's grammar puts them (a keyword of the category column_name may name a column but not
// a function, and so on: see Keyword), the operators are tokens as the scanner of DuckDB cuts them, the
// precedences and the non-associativity of the comparisons are those of the Bison grammar, and identifiers keep
// their case. The methods of Ident, StringLit, BitLit, Number and Param decode what the scanner reads: quoted
// and U& identifiers, escape strings, dollar quotes, strings continued over a line break, digit separators.
// QuoteIdent writes a name back so that it reads as one identifier.
//
// # Conformance
//
// The parser is compared with DuckDB 1.5.6 (its Python module, through extract_statements and
// json_serialize_sql) on 158,605 texts: the 45,912 statements of DuckDB's own tests, 7,655 expressions made of
// every pair of operators, 1,219 literals, names and comments of the scanner, 83,619 uses of every keyword where
// a name may stand, 20,000 mutations of the tests (a token deleted, duplicated, swapped, replaced, inserted,
// or the statement cut short), and 200 texts that an earlier version got wrong. The data is vendored in
// testdata/reference. On every one of them but twelve (testdata/deviations.jsonl) the parser and DuckDB agree on
// whether the text has a syntax error: DuckDB rejects 1,575 of the texts that the parser
// accepts, but not with a syntax error: after parsing, in the step that turns the syntax tree into its own
// (the window that an OVER clause names does not exist, SELECT INTO is not supported, VALUES lists of
// different lengths, and so on: the README counts them). They agree on how a script is split into statements,
// on the type of each statement and on its text, except for the statements that DuckDB expands into several
// (PIVOT, COPY FROM DATABASE, ALTER TABLE ADD COLUMN with a default). A mapping written in the tests builds
// from the syntax tree the JSON that json_serialize_sql returns for a SELECT statement, and the two agree on
// 27,110 of the 27,112 SELECT statements of the tests that the mapping covers, and on all 6,166 expressions.
//
// Known deviations and limits:
//
//   - DuckDB's parser also checks, after parsing, what the grammar cannot show; this parser does not. A text
//     that has one of these errors is accepted (see the README for the list of those that the data shows).
//   - Twelve texts, in testdata/deviations.jsonl, are read differently: six because DuckDB does not replace
//     Unicode white space after a dollar-quoted string that a letter follows, and six constructs that are not
//     understood (the words IN and AND, or a dot, as the first
//     bound of a frame, NOT at the start of that bound, SETOF with a qualified type, a percent sign after a
//     postfix operator in LIMIT).
//   - Split gives one statement for the statements that DuckDB expands.
//   - Nesting stops at the depth limit of the generated parser with an error: 7,000 to 16,000 levels of
//     parentheses, subqueries, calls, lists, CASE and derived tables, and 99,980 prefix operators in a chain
//     (NOT NOT ... a, - - ... a).
//   - The generated parser is large (779,000 lines): its first compilation is expensive; subsequent builds
//     reuse the Go build cache.
//
// See the README for details, how they were measured, and performance.
package duckdb
