// Package golang parses Go source files with a parser generated by PEGO from golang.pego.
//
// The parser accepts the files that go/parser accepts and builds the same tree: ParseAST returns it
// as typed values modeled on go/ast, each with its Span in the input, and ToGoAST and ParseFile
// convert it to go/ast, for go/printer, go/types and other tools. Parse returns the tree as Nodes and
// Recognize only checks the input.
package golang

import (
	"errors"
	"go/ast"
	"go/scanner"
	"go/token"
	"unicode/utf8"
)

// ParseFile parses the Go source file src like go/parser.ParseFile(fset, filename, src,
// parser.SkipObjectResolution) (with mode ParseComments, also like parser.ParseComments, except
// that Doc and Comment fields are not set), and returns its go/ast tree. A syntax error is
// returned as a scanner.ErrorList with one error.
func ParseFile(fset *token.FileSet, filename string, src []byte, mode Mode) (*ast.File, error) {
	s := string(src)
	f, err := parseBytes(s)
	if err != nil {
		var se *SyntaxError
		pos := token.Position{Filename: filename}
		msg := err.Error()
		if errors.As(err, &se) {
			pos.Offset, pos.Line, pos.Column = se.Pos, se.Line, se.Col
			msg = se.Message()
		}
		var list scanner.ErrorList
		list.Add(pos, msg)
		return nil, list
	}
	return ToGoAST(fset, filename, s, f, mode), nil
}

// Valid reports whether src is a Go source file that go/parser accepts.
func Valid(src string) bool {
	return utf8.ValidString(src) && Recognize(src, Bytes) == nil
}

// errInvalidUTF8 is returned for source that is not valid UTF-8.
var errInvalidUTF8 = errors.New("illegal UTF-8 encoding")

// parseBytes parses src with byte positions, rejecting invalid UTF-8 first.
func parseBytes(src string) (*File, error) {
	if !utf8.ValidString(src) {
		for i, r := range src {
			if r == utf8.RuneError {
				if _, size := utf8.DecodeRuneInString(src[i:]); size == 1 {
					return nil, &SyntaxError{Pos: i, Line: 1 + countNewlines(src[:i]), Col: i - lastNewline(src[:i]), Messages: []string{errInvalidUTF8.Error()}}
				}
			}
		}
	}
	return ParseAST(src, Bytes)
}

func countNewlines(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			n++
		}
	}
	return n
}

func lastNewline(s string) int {
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '\n' {
			return i
		}
	}
	return -1
}
