// Package golang parses Go source files with a parser generated by PEGO from golang.pego.
//
// The parser accepts the files that go/parser accepts and builds the same tree. ParseAST returns
// the tree as typed values modeled on go/ast (File, FuncDecl, CallExpr, ...), each with its Span in
// the input; ToGoAST and ParseFile convert it to go/ast, with the positions, line table, //line
// directives and comment groups that go/parser makes, for go/printer, go/format, go/types and other
// tools. Parse returns the tree as Nodes and Recognize only checks the input; Valid does the
// same as go/parser's acceptance test. The literals of the typed tree are decoded by the Value and
// Constant methods of StringLit, CharLit, IntLit, FloatLit and ImagLit.
//
// # Conformance
//
// The grammar mirrors the decisions of go/parser and go/scanner rather than the specification alone,
// so that it accepts and rejects the same files, and builds the same tree, including every position:
// types are expressions, composite literals in statement headers, the type parameter or array
// decision in type declarations, the receive-or-channel-type reassociation, go and defer calls,
// type switch guards, case clauses, line directives and the literal checks of go/scanner. The tests
// compare acceptance and the whole tree, positions included, with the go/parser of the Go toolchain
// that runs them, on every Go file of GOROOT/src, on mutated copies of them and on hand-written
// cases; see the README for the numbers and the commands.
//
// Where go/parser accepts more than the specification (types where expressions are expected, x.(type)
// outside type switches, and so on), so does this parser; the type checker rejects those programs,
// not the parser. The parser follows the go/parser of the toolchain it is tested with: a newer
// toolchain may change what go/parser accepts, and the tests then show the difference.
//
// # Deviations from go/parser
//
//   - A syntax error is reported once, as a *SyntaxError with the expected tokens (from ParseAST,
//     Parse and Recognize), or as a scanner.ErrorList with one error (from ParseFile), and no tree is
//     returned. go/parser reports up to ten errors, with messages of its own, and returns the part of
//     the tree it could parse. Whether a file is accepted is the same.
//   - ParseFile always behaves like go/parser with SkipObjectResolution: Scope, Unresolved and Obj
//     are not set. The only Mode is ParseComments, which collects File.Comments in the groups go/parser
//     makes but does not set the Doc and Comment fields of declarations, fields and specs. There is no
//     ImportsOnly, PackageClauseOnly or AllErrors.
//   - Nesting is limited by the depth limit of the generated parser, 100,000 rule calls: 16,600 levels
//     of parentheses, 25,000 of blocks, where go/parser stops at 100,000 levels. Deeper input fails
//     with an error instead of exhausting the stack.
//   - The parser memoizes while it parses, so that memory grows with the size of the file: ParseAST
//     allocates about 14 times the size of the source (go/parser about 8 times).
//   - Positions are in code points by default. With code points, invalid UTF-8 in comments cannot be
//     told from U+FFFD, which go/scanner accepts: ParseFile and Valid check the encoding first, and
//     with Recognize and ParseAST, pass Bytes for exact results. ToGoAST requires Bytes.
package golang

import (
	"errors"
	"go/ast"
	"go/scanner"
	"go/token"
	"unicode/utf8"
)

// ParseFile parses the Go source file src like go/parser.ParseFile(fset, filename, src,
// parser.SkipObjectResolution) (with mode ParseComments, also like parser.ParseComments, except
// that Doc and Comment fields are not set), and returns its go/ast tree. A syntax error is
// returned as a scanner.ErrorList with one error.
func ParseFile(fset *token.FileSet, filename string, src []byte, mode Mode) (*ast.File, error) {
	s := string(src)
	f, err := parseBytes(s)
	if err != nil {
		var se *SyntaxError
		pos := token.Position{Filename: filename}
		msg := err.Error()
		if errors.As(err, &se) {
			pos.Offset, pos.Line, pos.Column = se.Pos, se.Line, se.Col
			msg = se.Message()
		}
		var list scanner.ErrorList
		list.Add(pos, msg)
		return nil, list
	}
	return ToGoAST(fset, filename, s, f, mode), nil
}

// Valid reports whether src is a Go source file that go/parser accepts.
func Valid(src string) bool {
	return utf8.ValidString(src) && Recognize(src, Bytes) == nil
}

// errInvalidUTF8 is returned for source that is not valid UTF-8.
var errInvalidUTF8 = errors.New("illegal UTF-8 encoding")

// parseBytes parses src with byte positions, rejecting invalid UTF-8 first.
func parseBytes(src string) (*File, error) {
	if !utf8.ValidString(src) {
		for i, r := range src {
			if r == utf8.RuneError {
				if _, size := utf8.DecodeRuneInString(src[i:]); size == 1 {
					return nil, &SyntaxError{Pos: i, Line: 1 + countNewlines(src[:i]), Col: i - lastNewline(src[:i]), Messages: []string{errInvalidUTF8.Error()}}
				}
			}
		}
	}
	return ParseAST(src, Bytes)
}

func countNewlines(s string) int {
	n := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			n++
		}
	}
	return n
}

func lastNewline(s string) int {
	for i := len(s) - 1; i >= 0; i-- {
		if s[i] == '\n' {
			return i
		}
	}
	return -1
}
