// Package xml parses XML 1.0 (Fifth Edition) as a non-validating processor, with a parser generated by
// PEGO from xml.pego, and applies Namespaces in XML 1.0 (Third Edition) on request.
//
// Decode returns a document decoded and checked: references to internal entities expanded, line ends and
// attribute values normalized, attribute defaults applied, and every well-formedness constraint checked
// that does not need an external entity. DecodeBytes does the same from bytes in UTF-8, UTF-16,
// ISO-8859-1 or US-ASCII (Transcode). Tree.ResolveNamespaces sets the namespace names and checks the
// constraints of Namespaces in XML. ParseAST returns the syntax tree, with positions; Parse returns it as
// a tree of Nodes, and Recognize only checks it. These three check the syntax, the Char production and
// the element type match, not the other constraints, and read invalid UTF-8 as U+FFFD.
//
// The external subset and external entities are not read. A reference to an external parsed entity
// stays in the decoded tree as an *EntityRef; after a reference to a parameter entity that is not read,
// entity and attribute-list declarations are not processed unless the document is standalone. The
// replacement text of an internal parameter entity is parsed like the internal subset, without
// conditional sections. XML 1.1 is not supported: a 1.x document is processed as XML 1.0. Entity
// expansion is bounded by ExpansionLimit, and nesting by the generated parser's depth limit (24,999
// levels of elements).
//
// On the W3C XML Conformance Test Suite (xmlts20130923; see the README for how to run it), every test of
// XML 1.0 and Namespaces 1.0 for the fifth edition has the expected outcome: 728 valid and 229 invalid
// documents are accepted (262 with the canonical output compared), and 958 not-well-formed documents are
// rejected; 59 not-well-formed documents are accepted because their errors are in external entities.
package xml

import (
	"errors"
	"strings"
)

// Name returns the name of the entity.
func (r *EntityRef) Name() string { return r.Text[1 : len(r.Text)-1] }

// Name returns the name of the parameter entity.
func (r *PERef) Name() string { return r.Text[1 : len(r.Text)-1] }

// Rune returns the character the reference denotes, and false if it is not a legal character (the
// constraint "Legal Character").
func (r *CharRef) Rune() (rune, bool) { return charRef(r.Text[2 : len(r.Text)-1]) }

// Value returns the character data with line ends normalized (CR LF and CR become LF).
func (t *CharData) Value() string { return newlines(t.Text) }

// Value returns the text of the CDATA section with line ends normalized.
func (t *CDSect) Value() string { return newlines(t.Text) }

// Value returns the text of the comment with line ends normalized.
func (c *Comment) Value() string { return newlines(c.Text) }

// Value returns the data of the processing instruction with line ends normalized.
func (d *PIData) Value() string { return newlines(d.Text) }

// Value returns the literal with line ends normalized.
func (l *SystemLiteral) Value() string { return newlines(l.Text) }

// Value returns the public identifier normalized: line ends and runs of spaces become one space, and
// leading and trailing spaces are removed.
func (l *PubidLiteral) Value() string {
	return strings.Join(strings.FieldsFunc(l.Text, func(r rune) bool { return r == ' ' || r == '\r' || r == '\n' }), " ")
}

// Value returns the attribute value normalized for an attribute of type CDATA (XML 1.0, 3.3.3), for a
// document without entity declarations: character references and the predefined entities (lt, gt, amp,
// apos, quot) are expanded, and white space becomes spaces. A reference to any other entity is an error;
// Decode expands the entities a document declares.
func (v *AttValue) Value() (string, error) {
	if !strings.ContainsAny(v.Text, "&\t\n\r") {
		return v.Text, nil
	}
	p := processor{strict: true, ref: -1, budget: ExpansionLimit}
	var b strings.Builder
	if err := p.attValue(&b, v.Text, true, 0); err != nil {
		return "", errors.New(err.(*WFError).Msg)
	}
	return b.String(), nil
}

// Attr returns the value of the attribute name (as written, a qualified name with namespaces) and
// whether the element has it.
func (e *Elem) Attr(name string) (string, bool) {
	for _, a := range e.Attrs {
		if a.Name == name {
			return a.Value, true
		}
	}
	return "", false
}

// Text returns the character data of the element and its descendants, concatenated.
func (e *Elem) Text() string {
	var b strings.Builder
	e.Walk(func(it Item) bool {
		if t, ok := it.(*Text); ok {
			b.WriteString(t.Data)
		}
		return true
	})
	return b.String()
}

// Elements returns the child elements of the element.
func (e *Elem) Elements() []*Elem {
	var els []*Elem
	for _, c := range e.Children {
		if c, ok := c.(*Elem); ok {
			els = append(els, c)
		}
	}
	return els
}

// Walk calls f for each item in the content of the element, depth first in document order. If f returns
// false for an element, Walk does not descend into it.
func (e *Elem) Walk(f func(Item) bool) {
	for _, c := range e.Children {
		if f(c) {
			if c, ok := c.(*Elem); ok {
				c.Walk(f)
			}
		}
	}
}
