// Package xml parses XML 1.0 (Fifth Edition) with a parser generated by PEGO from xml.pego.
//
// See the README for the conformance and the deviations.
package xml

import (
	"errors"
	"strings"
)

// Name returns the name of the entity.
func (r *EntityRef) Name() string { return r.Text[1 : len(r.Text)-1] }

// Name returns the name of the parameter entity.
func (r *PERef) Name() string { return r.Text[1 : len(r.Text)-1] }

// Rune returns the character the reference denotes, and false if it is not a legal character (the
// constraint "Legal Character").
func (r *CharRef) Rune() (rune, bool) { return charRef(r.Text[2 : len(r.Text)-1]) }

// Value returns the character data with line ends normalized (CR LF and CR become LF).
func (t *CharData) Value() string { return newlines(t.Text) }

// Value returns the text of the CDATA section with line ends normalized.
func (t *CDSect) Value() string { return newlines(t.Text) }

// Value returns the text of the comment with line ends normalized.
func (c *Comment) Value() string { return newlines(c.Text) }

// Value returns the data of the processing instruction with line ends normalized.
func (d *PIData) Value() string { return newlines(d.Text) }

// Value returns the literal with line ends normalized.
func (l *SystemLiteral) Value() string { return newlines(l.Text) }

// Value returns the public identifier normalized: line ends and runs of spaces become one space, and
// leading and trailing spaces are removed.
func (l *PubidLiteral) Value() string {
	return strings.Join(strings.FieldsFunc(l.Text, func(r rune) bool { return r == ' ' || r == '\r' || r == '\n' }), " ")
}

// Value returns the attribute value normalized for an attribute of type CDATA (XML 1.0, 3.3.3), for a
// document without entity declarations: character references and the predefined entities (lt, gt, amp,
// apos, quot) are expanded, and white space becomes spaces. A reference to any other entity is an error;
// Decode expands the entities a document declares.
func (v *AttValue) Value() (string, error) {
	if !strings.ContainsAny(v.Text, "&\t\n\r") {
		return v.Text, nil
	}
	p := processor{strict: true, ref: -1, budget: ExpansionLimit}
	var b strings.Builder
	if err := p.attValue(&b, v.Text, true, 0); err != nil {
		return "", errors.New(err.(*WFError).Msg)
	}
	return b.String(), nil
}

// Attr returns the value of the attribute name (as written, a qualified name with namespaces) and
// whether the element has it.
func (e *Elem) Attr(name string) (string, bool) {
	for _, a := range e.Attrs {
		if a.Name == name {
			return a.Value, true
		}
	}
	return "", false
}

// Text returns the character data of the element and its descendants, concatenated.
func (e *Elem) Text() string {
	var b strings.Builder
	e.Walk(func(it Item) bool {
		if t, ok := it.(*Text); ok {
			b.WriteString(t.Data)
		}
		return true
	})
	return b.String()
}

// Elements returns the child elements of the element.
func (e *Elem) Elements() []*Elem {
	var els []*Elem
	for _, c := range e.Children {
		if c, ok := c.(*Elem); ok {
			els = append(els, c)
		}
	}
	return els
}

// Walk calls f for each item in the content of the element, depth first in document order. If f returns
// false for an element, Walk does not descend into it.
func (e *Elem) Walk(f func(Item) bool) {
	for _, c := range e.Children {
		if f(c) {
			if c, ok := c.(*Elem); ok {
				c.Walk(f)
			}
		}
	}
}
