-- generated by ag-d-gencases.py
select json_exists(a, 'x'  );
select json_exists(a, 'x'  error on empty);
select json_exists(a, 'x'  null on error);
select json_exists(a, 'x'  default 1 on empty);
select json_exists(a, 'x'  empty array on empty empty object on error);
select json_exists(a, 'x'  true on empty false on error);
select json_exists(a, 'x'  unknown on error);
select json_exists(a, 'x'  empty on empty);
select json_exists(a, 'x'  error on error error on empty);
select json_exists(a, 'x' passing 1 as v );
select json_exists(a, 'x' passing 1 as v error on empty);
select json_exists(a, 'x' passing 1 as v null on error);
select json_exists(a, 'x' passing 1 as v default 1 on empty);
select json_exists(a, 'x' passing 1 as v empty array on empty empty object on error);
select json_exists(a, 'x' passing 1 as v true on empty false on error);
select json_exists(a, 'x' passing 1 as v unknown on error);
select json_exists(a, 'x' passing 1 as v empty on empty);
select json_exists(a, 'x' passing 1 as v error on error error on empty);
