select * from json_table(x, '$' columns (a int));
select * from json_table(x, '$' columns (a int path '$.a'));
select * from json_table(x format json, '$' columns (a int));
select * from json_table(x format json encoding utf8, '$' columns (a int));
select * from json_table(x, '$' as p columns (a int));
select * from json_table(x, '$' as "P q" columns (a int));
select * from json_table(x, '$' passing 1 as v columns (a int));
select * from json_table(x, '$' as p passing 1 as v, y as w columns (a int));
select * from json_table(x, '$' passing 1 + 2 as v, '{}' format json as w columns (a int));
select * from json_table(x, '$' columns (a int)) as t;
select * from json_table(x, '$' columns (a int)) t(a);
select * from json_table(x, '$' columns (a int)) t(a, b);
select * from json_table(x, '$' columns (a int)) t where a > 1;
select * from lateral json_table(x, '$' columns (a int));
select * from t, lateral json_table(t.x, '$' columns (a int)) as j;
select * from t, json_table(t.x, '$' columns (a int)) as j;
select * from t join json_table(t.x, '$' columns (a int)) j on true;
select * from t left join lateral json_table(t.x, '$' columns (a int)) j on true;
select * from json_table(x, '$' columns (a int)), json_table(y, '$' columns (b int));
select * from json_table(x, '$' columns (a int)) cross join t;
select * from json_table(x, '$' columns (a int)) natural join t;
select * from json_table(x, '$' columns (a int)) join t using (a);
-- the path is a string constant
select * from json_table(x, ('$') columns (a int));
select * from json_table(x, (('$')) columns (a int));
select * from json_table(x, E'$\n' columns (a int));
select * from json_table(x, $$$$ columns (a int));
select * from json_table(x, '$' || 'a' columns (a int));
select * from json_table(x, '$'::jsonpath columns (a int));
select * from json_table(x, y columns (a int));
select * from json_table(x, 1 columns (a int));
select * from json_table(x, null columns (a int));
select * from json_table(x, true columns (a int));
select * from json_table(x, B'101' columns (a int));
select * from json_table(x, jsonpath '$' columns (a int));
select * from json_table(x, ('$'::text) columns (a int));
select * from json_table(x, '$' 'a' columns (a int));
-- columns
select * from json_table(x, '$' columns (id for ordinality));
select * from json_table(x, '$' columns (id for ordinality, a int, b text));
select * from json_table(x, '$' columns (a int path '$.a', b text path '$.b'));
select * from json_table(x, '$' columns (a int format json));
select * from json_table(x, '$' columns (a int format json path '$.a'));
select * from json_table(x, '$' columns (a text format json encoding utf8));
select * from json_table(x, '$' columns (a text format json encoding utf16 path '$.a'));
select * from json_table(x, '$' columns (a text format json encoding utf7));
select * from json_table(x, '$' columns (a int without wrapper));
select * from json_table(x, '$' columns (a int without array wrapper));
select * from json_table(x, '$' columns (a int with wrapper));
select * from json_table(x, '$' columns (a int with array wrapper));
select * from json_table(x, '$' columns (a int with conditional wrapper));
select * from json_table(x, '$' columns (a int with unconditional array wrapper));
select * from json_table(x, '$' columns (a int path '$' with conditional array wrapper));
select * from json_table(x, '$' columns (a int keep quotes));
select * from json_table(x, '$' columns (a int keep quotes on scalar string));
select * from json_table(x, '$' columns (a int omit quotes));
select * from json_table(x, '$' columns (a int omit quotes on scalar string));
select * from json_table(x, '$' columns (a int with wrapper omit quotes));
select * from json_table(x, '$' columns (a int error on error));
select * from json_table(x, '$' columns (a int error on empty));
select * from json_table(x, '$' columns (a int null on empty error on error));
select * from json_table(x, '$' columns (a int default 1 on empty default 2 on error));
select * from json_table(x, '$' columns (a int empty array on empty empty object on error));
select * from json_table(x, '$' columns (a int unknown on empty true on error));
select * from json_table(x, '$' columns (a int path '$' with wrapper keep quotes default 1 on empty error on error));
select * from json_table(x, '$' columns (a int format json path '$' with wrapper omit quotes default 1 on empty error on error));
select * from json_table(x, '$' columns (a int format json with wrapper));
select * from json_table(x, '$' columns (a int exists));
select * from json_table(x, '$' columns (a int exists path '$.a'));
select * from json_table(x, '$' columns (a int exists path '$.a' true on error));
select * from json_table(x, '$' columns (a int exists path '$.a' false on error));
select * from json_table(x, '$' columns (a int exists path '$.a' unknown on error));
select * from json_table(x, '$' columns (a int exists path '$.a' error on error));
select * from json_table(x, '$' columns (a int exists path '$.a' null on error));
select * from json_table(x, '$' columns (a int exists path '$.a' empty on error));
select * from json_table(x, '$' columns (a int exists path '$.a' default 1 on error));
select * from json_table(x, '$' columns (a int exists error on error));
select * from json_table(x, '$' columns (a int exists path '$.a' error on empty));
select * from json_table(x, '$' columns (a int exists with wrapper));
select * from json_table(x, '$' columns (a int exists format json));
select * from json_table(x, '$' columns (a int path '$.a' exists));
select * from json_table(x, '$' columns (a timestamp with time zone path '$.a'));
select * from json_table(x, '$' columns (a timestamp with time zone with wrapper));
select * from json_table(x, '$' columns (a timestamp with wrapper));
select * from json_table(x, '$' columns (a varchar(5), b numeric(5, 2) path '$.b', c int[] path '$.c', d setof int));
select * from json_table(x, '$' columns (a jsonb, b json format json, c "my type", d pg_catalog.int4));
select * from json_table(x, '$' columns (a int path 'x' || 'y'));
select * from json_table(x, '$' columns (a int path y));
select * from json_table(x, '$' columns (a int path ('x')));
select * from json_table(x, '$' columns ("from" int, "a b" text path 'p'));
select * from json_table(x, '$' columns (a int, ));
select * from json_table(x, '$' columns ());
select * from json_table(x, '$' columns (a));
select * from json_table(x, '$' columns (a for));
select * from json_table(x, '$' columns (for ordinality));
select * from json_table(x, '$' columns (a int path));
select * from json_table(x, '$' columns a int);
select * from json_table(x, '$' (a int));
select * from json_table(x columns (a int));
select * from json_table(x, '$');
select * from json_table(x, '$' columns (a int), b int);
-- NESTED
select * from json_table(x, '$' columns (nested path '$.n' columns (a int)));
select * from json_table(x, '$' columns (nested '$.n' columns (a int)));
select * from json_table(x, '$' columns (nested path '$.n' as p columns (a int)));
select * from json_table(x, '$' columns (nested '$.n' as p columns (a int)));
select * from json_table(x, '$' columns (nested path '$.n' as "P q" columns (a int)));
select * from json_table(x, '$' columns (nested path '$.n' columns (a int, b text path '$.b', id for ordinality)));
select * from json_table(x, '$' columns (a int, nested path '$.n' columns (b int), c int));
select * from json_table(x, '$' columns (nested path '$.n' columns (a int), nested path '$.m' columns (b int)));
select * from json_table(x, '$' columns (nested path '$.n' columns (nested path '$.m' columns (a int))));
select * from json_table(x, '$' columns (nested path '$.n' columns (nested '$.m' as q columns (a int format json with wrapper))));
select * from json_table(x, '$' columns (nested path '$.n' columns (a int exists path '$.a' true on error)));
select * from json_table(x, '$' columns (nested path '$.n'));
select * from json_table(x, '$' columns (nested path '$.n' columns ()));
select * from json_table(x, '$' columns (nested path y columns (a int)));
select * from json_table(x, '$' columns (nested path '$.n' || '$.m' columns (a int)));
select * from json_table(x, '$' columns (nested path ('$.n') columns (a int)));
select * from json_table(x, '$' columns (nested int));
select * from json_table(x, '$' columns (nested int path '$.n'));
select * from json_table(x, '$' columns (nested path int));
select * from json_table(x, '$' columns (nested for ordinality));
select * from json_table(x, '$' columns (nested path text path '$.n'));
select * from json_table(x, '$' columns (path int));
select * from json_table(x, '$' columns (path int path '$'));
select * from json_table(x, '$' columns (nested path '$' columns (a int)) nested path '$' columns (b int));
-- ON ERROR of the table
select * from json_table(x, '$' columns (a int) error on error);
select * from json_table(x, '$' columns (a int) empty on error);
select * from json_table(x, '$' columns (a int) empty array on error);
select * from json_table(x, '$' columns (a int) empty object on error);
select * from json_table(x, '$' columns (a int) null on error);
select * from json_table(x, '$' columns (a int) true on error);
select * from json_table(x, '$' columns (a int) false on error);
select * from json_table(x, '$' columns (a int) unknown on error);
select * from json_table(x, '$' columns (a int) default 1 on error);
select * from json_table(x, '$' columns (a int) error on empty);
select * from json_table(x, '$' columns (a int) error on error error on error);
select * from json_table(x, '$' passing 1 as v columns (a int) error on error) as t;
select * from json_table(x, '$' as p passing 1 as v columns (a int) default 1 + 2 on error) as t(a);
-- names that are keywords
select * from json_table(x, '$' columns (value int, name text, path text path '$', columns int, wrapper int, keys int, quotes int));
select * from json_table(x, '$' columns (nested int, error int, empty text, scalar text, ordinality int));
select * from json_table(x, '$' columns (format int));
select * from json_table(x, '$' columns (a format));
select * from json_table(x, '$' columns (a int format));
select json_table.* from json_table(x, '$' columns (a int));
select * from json_table(x, '$' columns (a int)) json_table;
select * from json_table(x, '$' columns (a int)) as json_table(a);
