-- JSON_OBJECTAGG
select json_objectagg(k : v);
select json_objectagg(k value v);
select json_objectagg(k : v format json);
select json_objectagg(k : v format json encoding utf8);
select json_objectagg(k : v null on null);
select json_objectagg(k : v absent on null);
select json_objectagg(k : v with unique);
select json_objectagg(k : v with unique keys);
select json_objectagg(k : v without unique);
select json_objectagg(k : v without unique keys);
select json_objectagg(k : v returning jsonb);
select json_objectagg(k : v returning text format json);
select json_objectagg(k : v absent on null with unique keys returning jsonb);
select json_objectagg(k : v null on null without unique keys returning json format json encoding utf8);
select json_objectagg(k : v) filter (where x);
select json_objectagg(k : v) over ();
select json_objectagg(k : v) over w;
select json_objectagg(k : v) over (partition by y order by z);
select json_objectagg(k : v) over (w);
select json_objectagg(k : v) over (rows between unbounded preceding and current row);
select json_objectagg(k : v) filter (where x) over ();
select json_objectagg(k : v) filter (where x) over w;
select json_objectagg(k : v absent on null returning jsonb) filter (where x > 1) over (partition by y);
select json_objectagg(k : v returning jsonb) filter (where x);
select json_objectagg(k : v) from t group by z having true;
select json_objectagg(k : v), json_objectagg(a value b) from t;
select json_objectagg(distinct k : v);
select json_objectagg(k : v order by k);
select json_objectagg(k, v);
select json_objectagg();
select json_objectagg(k);
select json_objectagg(k : v) filter (x);
select json_objectagg(k : v) within group (order by k);
select json_objectagg(a + 1 value b);
select json_objectagg(a + 1 : b + 1);
select json_objectagg('a' : 1 null on null null on null);
-- JSON_ARRAYAGG
select json_arrayagg(v);
select json_arrayagg(v format json);
select json_arrayagg(v format json encoding utf8);
select json_arrayagg(v order by k);
select json_arrayagg(v order by k desc, l nulls first);
select json_arrayagg(v order by k using <);
select json_arrayagg(v null on null);
select json_arrayagg(v absent on null);
select json_arrayagg(v order by k null on null);
select json_arrayagg(v order by k absent on null returning jsonb);
select json_arrayagg(v returning text format json);
select json_arrayagg(v format json order by k absent on null returning text format json encoding utf8);
select json_arrayagg(v) filter (where x);
select json_arrayagg(v) over ();
select json_arrayagg(v) over w;
select json_arrayagg(v order by k) filter (where x) over (partition by y);
select json_arrayagg(v order by k desc returning jsonb) over (order by z rows 1 preceding);
select json_arrayagg(v) from t;
select json_arrayagg(v), json_arrayagg(w) from t group by x;
select json_arrayagg(distinct v);
select json_arrayagg(v, w);
select json_arrayagg();
select json_arrayagg(v with unique);
select json_arrayagg(v) filter (where x) filter (where y);
select json_arrayagg(v) over () over ();
select json_arrayagg(v) within group (order by v);
select json_arrayagg(a order by b order by c);
select json_arrayagg(v returning int null on null);
-- the aggregates in FROM (func_expr_windowless: no FILTER and OVER)
select * from json_arrayagg(v);
select * from json_objectagg(k : v);
select * from json_arrayagg(v) filter (where x);
select * from json_arrayagg(v) over ();
select * from json_arrayagg(v) as t;
select * from json_arrayagg(v) as t(a);
select * from lateral json_objectagg(k : v) t;
select * from json_arrayagg(v) with ordinality;
select * from json_arrayagg(v), json_objectagg(k : v);
select * from json_arrayagg(sum(v) over ());
select * from json_objectagg(k : sum(v) over ());
-- IS JSON
select a is json;
select a is not json;
select a is json value;
select a is not json value;
select a is json array;
select a is json object;
select a is json scalar;
select a is not json array;
select a is not json object;
select a is not json scalar;
select a is json with unique;
select a is json with unique keys;
select a is json without unique;
select a is json without unique keys;
select a is json value with unique keys;
select a is json array with unique keys;
select a is json object with unique;
select a is json scalar without unique keys;
select a is not json value with unique;
select a is not json object with unique keys;
select a is not json array without unique;
select a is not json scalar without unique keys;
select a is json, b is not json;
select a is json is null;
select a is json is not null;
select a is not json is true;
select a is json is json;
select a is json object is not json array;
select a is json array is null is not null;
select a is json and b;
select a is json or b is json;
select not a is json;
select a + b is json;
select a || b is json scalar;
select (a || b) is not json;
select a::text is json;
select a between b and c is json;
select a between b is json and c;
select a between b and c is json array with unique keys;
select a like b is json;
select a in (1, 2) is json;
select a = b is json;
select a = b is not json object;
select a is json = b;
select a is json + 1;
select a is json null on null;
select a is json format json;
select a is json encoding utf8;
select a format json is json;
select a is json unique;
select a is json with keys;
select a is json keys;
select a is json value array;
select a is json array object;
select a is json value value;
select a is not not json;
select a is json (b);
select a is json, b;
select a is json as c from t;
select a is json array as c from t;
select a is json object c from t;
select a is json value v from t;
select a is json scalar s from t;
select a is json with unique keys k from t;
select a is json without unique keys k from t;
select a is json keys from t;
select * from t where a is json;
select * from t where a is not json object with unique keys and b is json scalar;
select * from t where (a is json) is true;
select * from t where a is json array is false;
select * from t where not (a is json);
select case when a is json then 1 end;
select case a is json when true then 1 end;
select coalesce(a is json, false);
select a is json from t order by a is json;
select a is json from t group by a is json having a is json;
-- IS NORMALIZED
select a is normalized;
select a is nfc normalized;
select a is nfd normalized;
select a is nfkc normalized;
select a is nfkd normalized;
select a is NFC NORMALIZED;
select a is not normalized;
select a is not nfc normalized;
select a is not nfd normalized;
select a is not nfkc normalized;
select a is not nfkd normalized;
select a is normalized is null;
select a is normalized is not true;
select a is not normalized and b is nfc normalized;
select not a is normalized;
select a || b is normalized;
select (a || b) is nfkd normalized;
select a between b and c is normalized;
select a between b is normalized and c;
select a is nfc;
select a is nfc not normalized;
select a is not nfx normalized;
select a is normalized nfc;
select a is normalized as c from t;
select a is normalized from t;
select a is nfc normalized c from t;
select normalize(a), normalize(a, nfc), a is normalized;
select * from t where a is normalized;
select * from t where a is not nfkc normalized and b is nfd normalized or c is normalized;
