-- JSON_QUERY
select json_query(a, 'x');
select json_query(a format json, 'x');
select json_query(a format json encoding utf8, 'x');
select json_query(a, 'x' || y);
select json_query(a, 'x'::jsonpath);
select json_query(a, 'x' passing 1 as v);
select json_query(a, 'x' passing 1 as v, b format json as w);
select json_query(a, 'x' passing 1 + 2 as v);
select json_query(a, 'x' passing 1 as "v w");
select json_query(a, 'x' passing 1 as select);
select json_query(a, 'x' passing 1);
select json_query(a, 'x' passing);
select json_query(a, 'x' returning int);
select json_query(a, 'x' returning int format json);
select json_query(a, 'x' returning text format json encoding utf8);
select json_query(a, 'x' returning jsonb);
select json_query(a, 'x' without wrapper);
select json_query(a, 'x' without array wrapper);
select json_query(a, 'x' with wrapper);
select json_query(a, 'x' with array wrapper);
select json_query(a, 'x' with conditional wrapper);
select json_query(a, 'x' with conditional array wrapper);
select json_query(a, 'x' with unconditional wrapper);
select json_query(a, 'x' with unconditional array wrapper);
select json_query(a, 'x' with conditional);
select json_query(a, 'x' with array);
select json_query(a, 'x' without conditional wrapper);
select json_query(a, 'x' keep quotes);
select json_query(a, 'x' keep quotes on scalar string);
select json_query(a, 'x' omit quotes);
select json_query(a, 'x' omit quotes on scalar string);
select json_query(a, 'x' omit quotes on scalar);
select json_query(a, 'x' keep);
select json_query(a, 'x' error on error);
select json_query(a, 'x' null on error);
select json_query(a, 'x' true on error);
select json_query(a, 'x' false on error);
select json_query(a, 'x' unknown on error);
select json_query(a, 'x' empty on error);
select json_query(a, 'x' empty array on error);
select json_query(a, 'x' empty object on error);
select json_query(a, 'x' default 1 on error);
select json_query(a, 'x' default 1 + 2 on error);
select json_query(a, 'x' default 'x'::text on error);
select json_query(a, 'x' error on empty);
select json_query(a, 'x' null on empty);
select json_query(a, 'x' true on empty);
select json_query(a, 'x' false on empty);
select json_query(a, 'x' unknown on empty);
select json_query(a, 'x' empty on empty);
select json_query(a, 'x' empty array on empty);
select json_query(a, 'x' empty object on empty);
select json_query(a, 'x' default 1 on empty);
select json_query(a, 'x' error on empty error on error);
select json_query(a, 'x' null on empty default 1 on error);
select json_query(a, 'x' empty array on empty empty object on error);
select json_query(a, 'x' default 1 on empty default 2 on error);
select json_query(a, 'x' error on error error on empty);
select json_query(a, 'x' error on empty error on empty);
select json_query(a, 'x' error on error error on error);
select json_query(a, 'x' error on);
select json_query(a, 'x' on error);
select json_query(a, 'x' passing 1 as v returning int format json with wrapper omit quotes empty on empty error on error);
select json_query(a, 'x' passing 1 as v returning jsonb with conditional array wrapper keep quotes on scalar string default 1 on empty null on error);
select json_query(a, 'x' returning timestamp with time zone with wrapper);
select json_query(a, 'x' returning timestamp without time zone without wrapper);
select json_query(a, 'x' returning timestamp with wrapper);
select json_query(a, 'x' returning interval year to month keep quotes);
select json_query(a, 'x' wrapper);
select json_query(a, 'x' quotes);
select json_query(a, 'x' omit quotes with wrapper);
select json_query(a, 'x' keep quotes returning int);
select json_query(a, 'x' error on error with wrapper);
select json_query(a, 'x' with wrapper returning int);
select json_query(a);
select json_query(a,);
select json_query(a 'x');
select json_query();
-- JSON_EXISTS
select json_exists(a, 'x');
select json_exists(a format json, 'x');
select json_exists(a, 'x' passing 1 as v);
select json_exists(a, 'x' passing 1 as v, 2 as w);
select json_exists(a, 'x' error on error);
select json_exists(a, 'x' true on error);
select json_exists(a, 'x' false on error);
select json_exists(a, 'x' unknown on error);
select json_exists(a, 'x' null on error);
select json_exists(a, 'x' empty on error);
select json_exists(a, 'x' default 1 on error);
select json_exists(a, 'x' passing 1 as v error on error);
select json_exists(a, 'x' error on empty);
select json_exists(a, 'x' returning int);
select json_exists(a, 'x' with wrapper);
select json_exists(a, 'x' error on error true on error);
select json_exists(a, 'x') is json;
select * from t where json_exists(a, 'x' passing b as v);
-- JSON_VALUE
select json_value(a, 'x');
select json_value(a format json, 'x');
select json_value(a, 'x' passing 1 as v);
select json_value(a, 'x' returning int);
select json_value(a, 'x' returning text format json);
select json_value(a, 'x' error on error);
select json_value(a, 'x' error on empty);
select json_value(a, 'x' default 1 on empty);
select json_value(a, 'x' default 1 on empty default 2 on error);
select json_value(a, 'x' null on empty null on error);
select json_value(a, 'x' passing 1 as v returning int true on empty false on error);
select json_value(a, 'x' returning int default 1 on error);
select json_value(a, 'x' with wrapper);
select json_value(a, 'x' omit quotes);
select json_value(a, 'x' without wrapper);
select json_value(a, 'x' returning int omit quotes);
select json_value(a, 'x' empty array on error);
select json_value(a, 'x' empty object on empty);
select json_value(a, 'x' unknown on empty);
select json_value(json_query(a, 'x'), 'y');
select json_value(a, 'x') + 1;
select json_value(a, 'x' returning int) between 1 and 2;
select json_value(a, 'x')::int;
select json_value(a, 'x').y;
select (json_value(a, 'x')).y;
select json_value(a, 'x')[1];
select json_value(a, 'x') collate "C";
select json_value(a, 'x') over ();
select json_value(a, 'x') filter (where true);
-- the keywords as names
select json, json_array, json_scalar from t;
select a.json, a.json_object, a.json_query from t a;
select json as json from t;
select value, name, path, columns, nested, wrapper, quotes, keys, omit, keep, scalar, empty, error, unknown from t;
select format, encoding, absent, passing, ordinality, version, standalone, yes, no, strip, preserve, indent, document, content from t;
select xmltable, xmlelement from t;
select t.xmlattributes from t;
select 1 as json_table;
