name: Test Go targets

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goarch: [amd64, '386']
    env:
      GOARCH: ${{ matrix.goarch }}
      CGO_ENABLED: '0'
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
      - run: npm install --global typescript@5.9.3
      - run: sh ci/test.sh -count=1 -p=1 -timeout=30m
